### ISSUE TITLE
Windows Phone Support

### ISSUE THREAD

**Issue by ilhanyumer** [mauron85/cordova-plugin-background-geolocation#10]
http://cordova.apache.org/plugins/?q=geolocation says that the plugin supports only Android and iOS http://i.imgur.com/4joWSwr.png but this repository includes also [Windows Phone](https://github.com/mauron85/cordova-plugin-background-geolocation/tree/master/src/wp8) code. What does it mean? That in Windows Phone it is not working or you have forget to mention it?

**Comment by mauron85** [comment]
Yes, it seems I've forgotten somehow. Sorry for that. But I don't have resources to fully support WP8. So maybe it's better to not officially announce support for it.
