### ISSUE TITLE
Question: Http location posting

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#101]
1. Are all locations stored in local database sent to server on http post?

1. Are locations stored in database deleted when response status code is 200?

2. Is there a way to control http post intervals?

Thanks in advance.

**Comment by mauron85** [comment]
1. not yet, but you can workaround with `backgroundGeolocation.getAllLocations` to retrieve stored location and send them via some XHR on app start (also delete them when ajax was successful)

2. related to 1.
3. related to 1.

**Comment by shyamal890** [comment]
Eagerly awaiting.

**Comment by mauron85** [comment]
Closing this one. There is already ongoing discussion in #100 related to this
