### ISSUE TITLE
not working interval

### ISSUE THREAD

**Issue by manzajaro** [mauron85/cordova-plugin-background-geolocation#102]
The interval parameter does not work as I put for a location to run every 2 minutes does not work.

only it works once

regards

```
var bgOptions = {
      desiredAccuracy: 10,
    notificationIconColor: '#4CAF50',
    notificationTitle: 'Background tracking',
    notificationText: 'ENABLED',
    notificationIconLarge: 'icon_large', //filename without extension
    notificationIconSmall: 'icon_small', //filename without extension
    debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
    stopOnTerminate: false, // <-- enable this to clear background location settings when the app terminates
    locationProvider: backgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
    interval: 60000, // <!-- poll for position every minute
    fastestInterval: 120000,
      url: 'http://find-myfriends.com/api/backgroundPositionNuevo'
    };
```

**Comment by mauron85** [comment]
You should set `interval: 120000` not fastestInterval. Also set `stopOnStillActivity: true` if you want to locations every 2 minutes no matter device is still (no motion detected).

**Comment by mauron85** [comment]
Any updates?

**Comment by juanmlf** [comment]
I have the same problem, but with these options

backgroundGeolocation.configure(callbackFn, failureFn, {
        desiredAccuracy: 10,
        stationaryRadius: 20,
        distanceFilter: 10,
        interval: 10000,
        debug: true
    });

The app calls one time the true callback and then stops. I dont know if the finish() method that is in the callback is killing it. It seems that the finish() is working like the stop()
