### ISSUE TITLE
Detect authorisation status in iOS

### ISSUE THREAD

**Issue by ibcomputing** [mauron85/cordova-plugin-background-geolocation#103]
iOS 8> has two levels of authorisation status for location services:

kCLAuthorizationStatusAuthorizedWhenInUse

and

kCLAuthorizationStatusAuthorizedAlways

It would be nice if there was a method for detecting which level of authorisation has been given to the app. If the user has changed the authorisation level to kCLAuthorizationStatusAuthorizedWhenInUse, the watchLocationMode callback is not triggered because location services are still technically enabled. However background tracking won't work unless authorisation level is kCLAuthorizationStatusAuthorizedAlways.

Maybe the plugin could detect this situation and request dialog for change of permission.

The reason I am raising this as an issue is because we have an app which used foreground location services. This requested the kCLAuthorizationStatusAuthorizedWhenInUse permission. When the user upgrades the app to a new version that uses this plugin, the app does not request change of permission to kCLAuthorizationStatusAuthorizedAlways and the plugin gives no way to detect this situation. Hence background tracking does not work and there is no way of informing the user.

**Comment by mauron85** [comment]
Hi, plugin is always asking only for `requestAlwaysAuthorization` in [start method](https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/ios/CDVBackgroundGeolocation/BackgroundGeolocationDelegate.m#L186). I believe user cannot change authorization status.

**Comment by ibcomputing** [comment]
User can change authorisation level in iOS settings for the app. The plugin does not seem to detect this.

On 1 Jul 2016 9:48 am, Marián Hello <notifications@github.com> wrote:

Hi, plugin is always asking only for requestAlwaysAuthorization in start method<https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/ios/CDVBackgroundGeolocation/BackgroundGeolocationDelegate.m#L186>. I believe user cannot change authorization status.

**Comment by mauron85** [comment]
Ok, anyway this plugin is meant to be used primarily in background (as name suggest) so currently I've no plans to change this. However I'm taking note here, as I'm working on universal plugin, where this can be implemented.

**Comment by mauron85** [comment]
Actually I've just checked setting screen. And didn't found option WhenInUse there. Only Never and Always. So plugin is working as expected. There is no setting  WhenInUse to confuse user or anything like that.

**Comment by ibcomputing** [comment]
This is interesting. I think it may be to do with having the standard cordova plugin installed. I will look into that.

**Comment by mauron85** [comment]
Yes, that makes sense. However it is up to you to handle this situation with two plugins.

**Comment by ibcomputing** [comment]
The solution is to remove the "NSLocationWhenInUseUsageDescription" key from the app's info.plist. This stops the Cordova-plugin-location plugin from requesting "only when in use" location permission. Hopefully this thread might help someone else in the future...
