### ISSUE TITLE
old locations within the callbackFn

### ISSUE THREAD

**Issue by jvwelzen** [mauron85/cordova-plugin-background-geolocation#104]
Hi,

I have the feeling that I get old locations within my calbackFn.

example if I am already home my google maps marker is still standing in Brussels.

if I set saveBatteryOnBackground: false It is working better but ios kills my app

any idea ??

**Comment by jvwelzen** [comment]
did some testing and I really receive old locations within the callbackFn

`[js] BackgroundGeoLocation callback:  51.97718148590249,5.103602875028833
Object
accuracy: 5
altitude: 3.31159240262452
altitudeAccuracy: 6
heading: 29.8828125
id: 166
latitude: 51.97718148590249
location_type: "current"
longitude: 5.103602875028833
speed: 31.48999977111816
time: 1468615059000.072
__proto__: —
LOCATIONS LOAD
Object
LOADGPS
[
Object
]
[{"speed":0,"time":1468617404999.983,"id":236,"longitude":5.269632954155345,"service_provider":0,"latitude":52.29738829196644,"accuracy":10,"heading":-1,"altitude":1.766384124755859}]
`

**Comment by mauron85** [comment]
Those locations are not same. They don't have same `time`.

**Comment by jvwelzen** [comment]
Yes I know, the last recorded record in de database had id 236, thats the current location, so why do I receive an older location within the callback Fn ?

**Comment by mauron85** [comment]
They can have same lat lon, but they are not same, because `time` attr is differrent. This perfectly normal for situations where location is determined from network/wifi.

Also don't use `id` is primary key/unique key. Now it is unique, but this in upcoming version it will not be.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
