### ISSUE TITLE
Empty post and callbackFn not triggered

### ISSUE THREAD

**Issue by rafatol** [mauron85/cordova-plugin-background-geolocation#105]
Hi, i'm trying to use this plugin in my app. I've created this js file (called in every page of app):

[geolocation.txt](https://github.com/mauron85/cordova-plugin-background-geolocation/files/351447/geolocation.txt)

The background service is running (With notification in Android), and calling my backend PHP (it sends an e-mail with serialized values of post, get, request and server variables), but POST / GET / REQUEST is empty :-\ Also, callbackFn (with a jquery ajax) doesn't execute.

Thanks.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
