### ISSUE TITLE
Activity Provider not recording speed

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#106]
For some reason all locations updates have 0.00000 speed.

**Comment by mauron85** [comment]
Seems like following issue: http://stackoverflow.com/questions/19858588/getting-speed-using-google-play-location-api

**Comment by mauron85** [comment]
You have multiple android devices right? Can you try at least few of them? I would guess, that some of them will be ok. Also make sure you set `option.accuracy` to at least 10m. Then only GPS will be used. If you specify anything higher, cell and wifi provider might be used. Those don't report speed (how can they?).

**Comment by shyamal890** [comment]
I tried 4, all having same issue. I have set accuracy to 100m would that be the issue?

**Comment by mauron85** [comment]
Potentially yes. With that accuracy network and wifi provider can be used. Those don't report speed.

**Comment by shyamal890** [comment]
Ok, the recorded locations are of accuracy 30-50m.

**Comment by mauron85** [comment]
>Moreover, is there a way to know whether the location is from Cell network, Wifi or GPS?

I wish so, but android Fusion API doesn't has such a feature.

**Comment by shyamal890** [comment]
Ah! May be we can put in a request to google guys. Moreover, do consider including accelerometer readings. It helps

**Comment by mauron85** [comment]
Already check code, didn't found any potential bug candidate. Basically location handling is same for both providers. Please try another test with accuracy: 10.

**Comment by shyamal890** [comment]
Will do.

**Comment by shyamal890** [comment]
@mauron85 Did some comprehensive testing with desired accuracy set to 10. However, locations updates which are recorded don't have speed info and most are of accuracy between 0-50m. This needs to be looked into, was not an issue in Distance provider.

Now, let me tell you my the use case for speed. Will give a better idea why this is necessary:
As you know from https://github.com/mauron85/cordova-plugin-background-geolocation/issues/90 . It is important that we don't plot such locations. Morever, I would like to record for how many minutes a particular mobile was stationary at a particular location.

To be able to discern this, speed information plays a very vital role. So, either we find a way to get speed on each location update or we expose the activity as we discussed in https://github.com/mauron85/cordova-plugin-background-geolocation/issues/108  .

Would appreciate your input on this issue.

**Comment by kristfal** [comment]
@shyamal890 Just a heads up, some android devices will not return speed regardless of location service type or accuracy. I recommend you create a fallback javascript method which calculates the speed between the current and last GPS position. Also keep in mind that when transitioning from background to foreground location services, you may receive older locations after new ones.

This fallback could be handled by the plugin, but I think it should be up to each developer for how to handle this.

Here is my implementation:

```js

  /**
   * _estimatedSpeed calculates speed based on the current and previous GPS readout.
   * It is used as a fallback for devices that don't provide speed through the GPS position object.
   * @param  {Object} location  provided by either background or foreground location services
   * @return {Number}           estimatedSpeed
   */

  _estimatedSpeed: function(location) {
    var last = this.lastSpeedLocation,
        estimatedSpeed,
        point1,
        point2,
        latitude,
        longitude,
        timestamp,
        accuracy,
        distance,
        dt;

    latitude = location.latitude;
    longitude = location.latitude;
    timestamp = location.timestamp;
    accuracy = location.accuracy;

    // Ignore low accuracy locations
    if (accuracy > 30) {
      return 0;
    }

    // If this is the first location to be estimated
    if (last === undefined) {
      this._lastSpeedLocation = {
        latitude: latitude,
        longitude: longitude,
        timestamp: timestamp
      };
      return 0;
    }

    // Only accept new entries
    if (timestamp < last.timestamp) {
      return 0;
    }

    point1 = window.turf.helpers.point([longitude, latitude]);
    point2 = window.turf.helpers.point([last.longitude, last.latitude]);

    distance = window.turf.distance(point1, point2, 'kilometers'); // km
    dt = timestamp - last.timestamp; // ms
    estimatedSpeed = distance * 1000 / (dt / 1000); // m/s

    // Update last speed location
    this._lastSpeedLocation = {
      latitude: latitude,
      longitude: longitude,
      timestamp: timestamp
    };

    // Only return a significant estimated speed
    if (estimatedSpeed > 1) {
      return estimatedSpeed;
    } else {
      return 0;
    }

  }

```

This depends on turf.js to calculate the distance using the Haversine formula, but you can skip that for convenience.

**Comment by mauron85** [comment]
I was thinking about plugin calculating speed when not returned by android API, but ended up with conclusion that is not good idea as there would many edge cases, when it can get totally wrong.

**Comment by shyamal890** [comment]
@mauron85 any time-frame for https://github.com/mauron85/cordova-plugin-background-geolocation/issues/108 ?

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Comment by mauron85** [comment]
Closing. Use @kristfal solution.
