### ISSUE TITLE
Android: Seems like if GPS is switched off, no location callbacks occur

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#107]
Recently, I have been noticing that sometimes no locations are being recorded for Activity Provider even if stopOnStillActivity is false.

I investigated and found that it may be due to person switching off GPS and internet. Can you shed some light on this @mauron85 ? Shouldn't location updates be received from cell tower?

**Comment by shyamal890** [comment]
I guess if GPS and wifi are not available there would be no callbacks if cell tower location is not good enough. In that case, just like `backgroundGeolocation.watchLocationMode(success, fail)` plugin would also have to include `backgroundGeolocation.watchGPSMode(success, fail)`

**Comment by mauron85** [comment]
In vanilla android you cannot switch GPS separately. Only locations can disabled/enabled.

**Comment by shyamal890** [comment]
I don't think so, do check: 

http://stackoverflow.com/questions/15778807/how-to-detect-when-user-turn-on-off-gps-state
http://stackoverflow.com/questions/18259039/gpsstatus-listener-works-only-if-gps-is-on
http://stackoverflow.com/questions/20611824/event-for-gps-on-off-state-change

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
