### ISSUE TITLE
Feature Req: Do include accelerometer readings

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#108]
@mauron85 It would be great if on each location callback we can know whether the user is stationary/ walking or in vehicle. This would enable us to detect inaccurate location if user is in stationary condition (https://github.com/mauron85/cordova-plugin-background-geolocation/issues/90) 

Adds more context. Hope you would consider it.

**Comment by mauron85** [comment]
Expose detected activity for ANDROID_ACTITIVY_PROVIDER is doable, as it already uses activity recognition. But you're mentioning stationary condition, which is only used in ANDROID_DISTANCE_FILTER_PROVIDER. Unfortunately this provider doesn't use activity recognition, so it is not possible.

**Comment by shyamal890** [comment]
> Expose detected activity for ANDROID_ACTITIVY_PROVIDER is doable

That would be great.

**Comment by shyamal890** [comment]
@mauron85 Any updates on this? Really need this to filter gps locations.

**Comment by mauron85** [comment]
Implemented in 3.0.0-alpha.8
