### ISSUE TITLE
Android: clicking the notification starts the app new

### ISSUE THREAD

**Issue by bastian-meier** [mauron85/cordova-plugin-background-geolocation#11]
I found a problem with the notification on android.

In the original Version of the plugin a click on the "background-notification" has no effect.
In your Version a click opens my app, but the app starts new.
A click on my app in app-drawer just brings the app from the background to the foreground.
But a "notification-click" starts my app completely new, wich needs a few seconds.

Is this fixable? Or is there a way to disable the click functionality on the notification on android?

Thanks for your answer
Bastian

**Comment by mauron85** [comment]
Yes, I can confirm that. Not sure if we can do something about it. Need to do some investigation first.

**Comment by mauron85** [comment]
Seems fixed. Please reopen, if you still have issues.

**Comment by bastian-meier** [comment]
It is working perfect now, thanks a lot
