### ISSUE TITLE
Receiving 2 locations with same data

### ISSUE THREAD

**Issue by mahmed-ntd** [mauron85/cordova-plugin-background-geolocation#111]
## My Environment

* Plugin version: 2.1.2
* Platform: Android
* Device manufacturer and model: Oppo R7plus
* Cordova version (`cordova -v`): 6.2.0
* Cordova platform version (`cordova platform ls`): 5.1
* Plugin configuration options: 
{name: 'url', defaultValue: 'some url'},
      {name: 'stopOnTerminate',  defaultValue: 'false'},
      {name: 'startOnBoot', defaultValue: 'true'},
      {name: 'debug', defaultValue: 'true'},
      {name: 'stopOnStillActivity', defaultValue: 'true'},
      {name: 'startForeground', defaultValue: 'true'}
      {name: 'stationaryRadius', defaultValue: 50},
      {name: 'distanceFilter', defaultValue: 50},
      {name: 'desiredAccuracy', defaultValue: 10},
      {name: 'notificationIconColor', defaultValue: '#4CAF50'},
      {name: 'notificationTitle', defaultValue: 'Asset Management System'},
      {name: 'notificationText', defaultValue: ''},
      //{name: 'notificationIconLarge', defaultValue: 'icon_large'},
      //{name: 'notificationIconSmall', defaultValue: 'icon_large'},
      {name: 'locationProvider', defaultValue: 0},        //backgroundGeolocation.provider.ANDROID_DISTANCE_FILTER_PROVIDER,
      {name: 'interval', defaultValue: 10000},
      {name: 'fastestInterval', defaultValue: 50000},
      {name: 'activitiesInterval', defaultValue: 10000},
      {name: 'locationProvider', defaultValue: 0},
      {name: 'locationProvider', defaultValue: 0},
      {name: 'locationProvider', defaultValue: 0},
      // {name: 'activityType', defaultValue: 'AutomotiveNavigation'},
      {name: 'saveBatteryOnBackground', defaultValue: 'false'}
* Link to your project:

## Context
why we are receiving 2 same location with only the difference of debug true and debug false, i can assume that one of the location was generated due the debug is true but do we need the 2nd same location just with deference of debug?

## Possible Fix
we can set debug to either true or false depending on the value which we set in configuration

**Comment by mauron85** [comment]
Sure. This will change in upcoming version.

>All locations updates are recorded in local db. Number of location stored in db is limited by option.maxLocations and never exceeds this number. Instead old locations are replaced by newer ones.

>When App is in foreground or background in addition to storing location in local db, location callback function is triggered.

>When option.url is defined. Location updates are also stored in local db. Each location is also immediately posted to server url defined by option.url. If post is successful, the location is marked as deleted in local db. All failed to post locations will be coalesced and send in some time later in one single batch. Batch sync takes place only when number of fail to post location exceeds number defined by option.syncThreshold.

Already implemented for ios in next-ios branch.

**Comment by mahmed-ntd** [comment]
mean while i was thinking if there is any configuration that plugin should store data for how many days?

**Comment by mauron85** [comment]
Sure it will be. There is ongoing discussion in https://github.com/mauron85/cordova-plugin-background-geolocation/issues/100.

**Comment by mauron85** [comment]
Implemented in 2.2.0.alfa.1
