### ISSUE TITLE
New name for plugin

### ISSUE THREAD

**Issue by mauron85** [mauron85/cordova-plugin-background-geolocation#113]
I think it's about the time to give plugin new name, because it is not background only geolocation plugin anymore. It works both foreground and background since 0.9.x. So its' current name is confusing. 

Also I believe it's not just another fork. And I know from stackoverflow, that people tend to be reserved to use this plugin, because of it's fork label.

Please post here you name suggestion or vote for existing. Many thanks.

**Comment by TheKiller666** [comment]
bg-geolocation

**Comment by shyamal890** [comment]
cordova-plugin-geolocation

**Comment by phius** [comment]
constant-geolocation or cordova-constant-geolocation

covers both background and foreground geolocation.

**Comment by klidifia** [comment]
Or continuous instead of constant.
