### ISSUE TITLE
Functions "isLocationEnabled" & "showLocationSettings" returning "Can't find variable: backgroundGeolocation"

### ISSUE THREAD

**Issue by winknudge-tomm** [mauron85/cordova-plugin-background-geolocation#114]
Functions "isLocationEnabled" & "showLocationSettings" along with a few others returning "Can't find variable: backgroundGeolocation". I can Successfully log out "backgroundGeolocation" before calling the function but still get the error " Can't find variable: backgroundGeolocation"

backgroundGeolocation.start() & backgroundGeolocation.stop() work fine.

## Your Environment

* Plugin version: 0.9.6
* Platform: iOS
* Device manufacturer and model: 6plus
* Cordova version 5.4.1 (ionic 1.7.14)
* Cordova platform version Installed platforms: android 4.1.1, ios 3.9.2

## Context
Cannot access functions provided 

## Expected Behavior
Should return success or error if "isLocationEnabled()" is called

trying to call:

            backgroundGeolocation.isLocationEnabled(
            function() {
              console.log("success");
            }, function() {
              console.log("fail");
            })

![image](https://cloud.githubusercontent.com/assets/8375666/16800171/d8b6a7d4-48eb-11e6-9773-58928c8a6de9.png)

**Comment by mauron85** [comment]
Can you share more code, where are you calling isLocationEnabled?
