### ISSUE TITLE
Receive location by distance and interval max time

### ISSUE THREAD

**Issue by redrain87** [mauron85/cordova-plugin-background-geolocation#119]
- Plugin version: 2.1.2
- Platform: Android
- Cordova version: 6.2.0
- Cordova platform version: android 5.1.1
- Plugin configuration options: 
  {desiredAccuracy: 10, stationaryRadius: 20, distanceFilter: 30, interval: 30 \* 60 \* 1000, url: 'http://xxxx.com'}

I'm trying to use the plugin for get user location every 30 minutes and every time that he moves 30 meters, Is that possible? Because with that config that i try i receive locations every minute if the user move 30 meteres...

Thanks in advance

**Comment by mauron85** [comment]
For timed locations there is ANDROID_ACTIVITY_PROVIDER. For distance locations there is ANDROID_DISTANCE_FILTER_PROVIDER. But you cannot mix these two.

**Comment by redrain87** [comment]
I'm yet a newbie in Android development ... so the option of implement it by my self is difficult...

I need to find the way to get the position of the user for know if he still on the place that I received the last location update or to know if he have the plugin working yet.
