### ISSUE TITLE
Config option to turn off Android drawer notification

### ISSUE THREAD

**Issue by JWesorick** [mauron85/cordova-plugin-background-geolocation#12]
> On Android devices it is required to have a notification in the drawer because it's a "foreground service". This gives it high priority, decreasing probability of OS killing it. 

This isn't really an option for my app. Is there an option to not have a notification in the drawer? What are the ramifications of not being a "foreground service"? How likely is it to be killed by the OS?

**Comment by mauron85** [comment]
Yes, background service is actually foreground service started in drawer. You can probably create foreground service in main activity (as separate thread). But I cannot tell you, what are the drawbacks as I never tried this approach. As you already quoted android docs foreground service in the drawer has high priority so is preferred by this plugin. If you find something interesting, please write here so we can make this plugin better.

**Comment by mauron85** [comment]
There is ```option.startForeground``` to achieve this already in next branch. Will be implemented in version 1.0.0

**Comment by alejandromagnorsky** [comment]
I agree. I also need to hide that notification because users might uninstall the app just because of it.

**Comment by mauron85** [comment]
@alejandromagnorsky try next branch

**Comment by alejandromagnorsky** [comment]
@mauron85 I tried to use the @next branch but I get this error:
```
Failed to install 'cordova-plugin-mauron85-background-geolocation':CordovaError: Uh oh!
"/projects/app/plugins/cordova-plugin-mauron85-background-geolocation/src/android/Constant.java" not found!
```
I'm using cordova v6.1.0, cordova-android v.5.1.1 and cordova-ios v4.1.0.
Thanks.

**Comment by uzumakinaruto123** [comment]
Its funny but adding 3 notification properties to config removes that drawer notification completely ! and backgroud geolocation was still working as usual even when terminated. since these properties are supported above 5.0 ,i want to test how it works on lollipop.

**Comment by alejandromagnorsky** [comment]
@uzumakinaruto123 can you put a particular example? dattebayo

**Comment by uzumakinaruto123** [comment]
the config i added was ..

```
backgroundGeoLocation.configure(callbackFn,failureFn, {
          desiredAccuracy: 0,
          stationaryRadius: 5,
          notificationTitle: 'App Name',
          notificationText: 'Notification Service Running !',
          notificationIcon: 'icon',
          distanceFilter: 5,
          debug: true,
          stopOnTerminate: false,
          locationService: backgroundGeoLocation.service.ANDROID_FUSED_LOCATION,
          interval: 30000,
          fastestInterval: 30000
      });
```

i was expecting that  notificationIcon to take icon.png from drawable ! but later i discovered it was only for lollipop above. 

but notification disappeared and i was still getting updates even after app termination.

**Comment by alejandromagnorsky** [comment]
@uzumakinaruto123  tried with your configuration (in Android Marshmallow) and it's true, the location icon doesn't display. However, if you pull down the notification tray you can see an element saying:
```
AppName is running
Touch for more information or to stop the app.
```
So, still is not a perfect solution :(

**Comment by uzumakinaruto123** [comment]
@alejandromagnorsky  ya its not a solution at all ! i was just reporting what i experienced ! And for Android jellybean nothing appears ! no notification in the notification drawer.

**Comment by ombalakumar** [comment]
Hi guys, Is there any solution for disabling the notification of this library

**Comment by l3wi** [comment]
Also would like this function.

**Comment by mauron85** [comment]
Can I ask you guys why're actually need this? Is it that, you just don't like the drawer notification or are you trying hide something from user? Keep in mind, if you remove notification, plugin will be much less reliable and can be killed any time by the system.

**Comment by alejandromagnorsky** [comment]
Hi @mauron85 
Users are most of the times very picky and extra careful and untrustful. If they see an icon in the toolbar with the drawer notification they might go as far as uninstalling the app.

**Comment by mauron85** [comment]
Implented in 2.0.0. Option startForeground false
