### ISSUE TITLE
Very small notification icon

### ISSUE THREAD

**Issue by tux240** [mauron85/cordova-plugin-background-geolocation#121]
Hi, I'm using master and it work well.
But, on Android devices, I can see a very small notification icon instead of a normal "big" icon like the others apps.

I have copied the 2 icon pictures on the drawable folder.

Thanks for your help.

**Comment by eakkew** [comment]
If you want to have only one icon the large area, setting the small icon option and assign the large icon as null like following options

```
  notificationIconLarge: null, 
  notificationIconSmall: 'your_icon',
```

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
