### ISSUE TITLE
Should I use options.maxLocations or maxLocations in configure()?

### ISSUE THREAD

**Issue by coyu1314** [mauron85/cordova-plugin-background-geolocation#126]
In configure options of your documentation, you have the following for maxLocation. did you really mean  to use options.maxLocations or just maxLocation in configure option? Please clarify. Thanks

options.maxLocations    Number  iOS Limit maximum number of locations stored into db (default: 10000)

```
backgroundGeoLocation.configure(callbackFn, failureFn, {
            .....
            maxLocations:                        1
}
```

OR 

```
backgroundGeoLocation.configure(callbackFn, failureFn, {
            ....
            options:                        {maxLocations:                        1},
}
```

**Comment by mauron85** [comment]
Check https://github.com/mauron85/cordova-plugin-background-geolocation#real-world-example

Any suggestion how to reduce confusion in doc?

**Comment by coyu1314** [comment]
Thanks. This real world example is very helpful. 

I think it's better to include an example with all the possible options/parameters would highly reduce the confusion n documentation. Just my 2 cents.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
