### ISSUE TITLE
Feature Request: Http call on service close/killed

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#128]
It would be great if a http call back can be made when a user kills/stops the app from RAM.

This stackoverflow question may give some idea: http://stackoverflow.com/a/33078782/3955513

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Comment by shyamal890** [comment]
How do I reopen this? Also would like to get your feedback on this.
