### ISSUE TITLE
Background service gets killed arbitrarily 

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#129]
Have been using this plugin since long now with following relevant configuration:

- stopOnTerminate: false

- startOnBoot: true

- startForeground: true

I have noticed that sometimes the app gets completely killed from background. And this happens arbitrarily.

I went through this resource: https://developer.android.com/guide/components/services.html as per which it is possible that OS kills a background service in certain cases like low memory.

@mauron85 can you please see into this issue and share your insights? Whether if plugin service restarts after being killed in background?

**Comment by mauron85** [comment]
Any debug logs? Service stability was improved in 2.2.0. Now it should survive user termination without restart. At least on Marshmallow.

**Comment by shyamal890** [comment]
Sorry don't have any debug logs for this.

> Now it should survive user termination without restart.

Can you elaborate on this? 

1. What happens when the app service is killed by user?
2. What happens when the app service is killed by OS?

**Comment by mauron85** [comment]
Hmm, don't quote me on this, but as I far I remember (not very far though).

It depends if option stopOnTerminate is used or not. But behaviour should be pretty much same in both cases. In the latest version 2.2.0.alfa.1 the only difference would be, if `stopOnTerminate: true` is used, service will continue to run without restart if killed by user (tested on CM13) and if killed by OS, it should be restarted after some time (when condition like available memory are met).

**Comment by mauron85** [comment]
Please reopen if you have logs from adb logcat. There should mention why service was killed (due memory...).
