### ISSUE TITLE
Could not compile sample app

### ISSUE THREAD

**Issue by tolu360** [mauron85/cordova-plugin-background-geolocation#13]
Hello,

This is more or less a question, I was able to compile the sample app for iOS but not for android, perhaps I am missing something. The build on android throws this error - `Could not resolve all dependencies for configuration ':_debugCompile'.
Could not find any version that matches com.google.android.gms:play-services-location:+.`

Please what do you think?

**Comment by tolu360** [comment]
Update: Solved my own problems by installing/updating Google Play services and Google Repository via SDK Manager. Thanks

**Comment by mauron85** [comment]
@tolu360 That's actually good remark. I'll add it into README.md. Thanks

**Comment by tolu360** [comment]
@mauron85 Thank you for sharing your plugin.
