### ISSUE TITLE
Sync notification in 2.2.0

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#130]
It seems that the sync locations notification stays on the notification list for a long time. I hope it doesn't represent the http connection. 

Moreover, sync done notification too stays on for a long time. Is there a reason for this?

**Comment by mauron85** [comment]
> I hope it doesn't represent the http connection.
no it doesn't. Not sure why is this happening yet. But I'm aware of this.

**Comment by mauron85** [comment]
For reference stackoverflow thread http://stackoverflow.com/questions/38880330/notificationmanager-updating-hiding-notification-from-syncadapter-outside-ui-th/38880665?noredirect=1#comment65123698_38880665

**Comment by mauron85** [comment]
Fixed in 2.2.0-alpha.5
