### ISSUE TITLE
ios cordova_bg_geolocation.db in documents folder

### ISSUE THREAD

**Issue by bastian-meier** [mauron85/cordova-plugin-background-geolocation#132]
The plugin stores its database in the apps documents folder. My app publish request is rejected because of it, because the documents folder should only files that are intended for user access.

* Plugin version: 2.1.2
* Platform: iOS
* OS version: 9.3.3
* Device manufacturer and model: phone 5
* Cordova version (`cordova -v`): cli-9.3.0
* Cordova platform version (`cordova platform ls`): 5.1.1

could you please change the database location to another folder.

https://developer.apple.com/library/ios/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW2

**Comment by mauron85** [comment]
Ok. So `Library/*` seems to be right place

**Comment by bastian-meier** [comment]
Yes, library is the right place for databases, i am using my fork for now with library as db-location, i could create a PR if you want ...

**Comment by mauron85** [comment]
fixed with your PR. many thanks
