### ISSUE TITLE
Android 6.0.1 - location tracking app issue

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#134]
* Plugin version: 2.0.0
* Platform: Android
* OS version: 6.0.1
* Device manufacturer and model: Samsung Galaxy S7 edge
* Plugin configuration options: Activity Provider
* Link to your project:  Any app with your plugin installed would do

## Context

- When application asks for permission to track device's location, system's location settings is opened but the application is not included in list of applications allowed to access location. 

- When you navigate to Location permissions from App permissions in settings. App is not even visible in the list. 

## Steps to Reproduce
1. Try installing this plugin in Samsung Galaxy S7 edge

**Comment by uzumakinaruto123** [comment]
For me  , on One Plus 3 Android : 6.0.1 everything works fine , with location updates etc. In , app info it even shows that its allowed to access location.

**Comment by shyamal890** [comment]
Hmm, I wonder if there is some permission that the user has to give while installing the app? I just tried installing the app in Moto G3 Turbo (6.0.1) and it is working perfectly.

**Comment by uzumakinaruto123** [comment]
I dont know if samsung will have it , bu try going in settings --> apps -->your app --> persmissions. In here , you can toggle location permission.

**Comment by shyamal890** [comment]
So, I had a look at the issue once again. The issue seems to be `screen overlay detected`. To be exact this is what happens when you try to give location access permission:

> - [New Window]Screen overlay detected
>  > To change this settings u first have to turn off the screen overlay settings > Apps 
> 
> - [New Window]Apps that that can appear on the top
> > Select apps to allow their buttons, pop ups, or other elements to appear over other apps you are using (Location tracking may or may not found be here) 

Going through different websites, it seems that some other app has modified the system settings in a way that is interfering with our location tracking app. 

@mauron85 Feel free to close this issue

**Comment by mauron85** [comment]
Cool. Thanks for investigation.
