### ISSUE TITLE
Starting backgroundGeolocation just after configure failed

### ISSUE THREAD

**Issue by sekiroh** [mauron85/cordova-plugin-background-geolocation#139]
## Your Environment

* Plugin version: ~2.2.0-alpha.1
* Platform: Android
* OS version: 4.4.2
* Device manufacturer and model: Huawei Y540
* Cordova version (`cordova -v`): 6.3.0
* Cordova platform version (`cordova platform ls`): 5.2.1
* Link to your project: https://github.com/sekiroh/background-geolocation-test/tree/failedconfigure

## Context
Fail to do backgroundGeolocation.start just after backgroundGeolocation.configure. Log results are:

```text
[2016/08/10 12:34:25] BackgroundGeolocationPlugin:Attempt to start unconfigured service
[2016/08/10 12:34:25] BackgroundGeolocationPlugin:Location services enabled check
[2016/08/10 12:34:25] BackgroundGeolocationPlugin:initializing plugin
```

I have to call backgroundGeolocation.start after a timeout.

**Comment by mauron85** [comment]
Fixed in 2.2.0.alfa.3
