### ISSUE TITLE
Is this possible to know if all locations have been queue to callback function?

### ISSUE THREAD

**Issue by sekiroh** [mauron85/cordova-plugin-background-geolocation#140]
In issue #135, you said that callbacks are called when application in foregroud. I have two questions.
1. Suppose backgroundGeolocation is running in background, have recorded some locations. When coming back to foreground, we stop backgroundGeolocation. Will location be queue to callback function after having stop backgroundGeolocation?
2. If so, how to know when all locations have been queued?

**Comment by mauron85** [comment]
1. I've quickly checked the code and answer is probably not. Currently you need to have at least one location update since app is foreground to queue be processed. It would make sense to change this behaviour to always send all queued locations no matter if service is stopped/started.

**Comment by mauron85** [comment]
Any logs would be helpful. https://github.com/mauron85/cordova-plugin-background-geolocation#debugging
