### ISSUE TITLE
Android permissions - all necessary?

### ISSUE THREAD

**Issue by tverilytt** [mauron85/cordova-plugin-background-geolocation#143]
Hi!

The plugin seems to work great on Android (have not tested on IOS yet).
I just wonder if the Android "Contacts" permission is necessary?
The permission is not enabled for the installed app, but shows up under "App permissions".

This is added to config.xml when I install the plugin (with the --save option):

    <plugin name="cordova-plugin-mauron85-background-geolocation" spec="~2.2.0-alpha.2">
        <variable name="ACCOUNT_TYPE" value="$PACKAGE_NAME.account" />
        <variable name="CONTENT_AUTHORITY" value="$PACKAGE_NAME" />
    </plugin>

Cheers
-jo2

**Comment by mauron85** [comment]
No Contacts permission are not used nor necessary.

Here is the actual list from plugin.xml
```
            <uses-permission android:name="android.permission.AUTHENTICATE_ACCOUNTS" />
            <uses-permission android:name="android.permission.GET_ACCOUNTS" />
            <uses-permission android:name="android.permission.READ_SYNC_SETTINGS" />
            <uses-permission android:name="android.permission.WRITE_SYNC_SETTINGS" />
            <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
            <uses-permission android:name="com.google.android.gms.permission.ACTIVITY_RECOGNITION" />
            <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
            <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
            <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
            <uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
            <uses-permission android:name="android.permission.INTERNET" />
            <uses-permission android:name="android.permission.WAKE_LOCK" />
```

**Comment by tverilytt** [comment]
Cool, thanks :+1:

**Comment by tverilytt** [comment]
Hi again!

I removed these permissions, and then the Android "Contacts" permission for app permission is gone...



Is the ACCOUNT permissions for storing of geopositions in database?

cheers
-jo

**Comment by mauron85** [comment]
When you remove those "ACCOUNTS" permission, plugin will not sync locations!!!

**Comment by tverilytt** [comment]
Ok...in my use case I only want to get updated geolocations, which seems to work very well. I have no need to store or save the locations. So then I might do without the ACCOUNT permissions?!

Cheers
-jo

**Comment by Shane98c** [comment]
@mauron85 If we don't use the syncing features is there a simple way to remove the request for the account permissions?  I'd prefer not to publish my app with unnecessary permissions.

**Comment by tverilytt** [comment]
@Shane98c I commented out these lines:
LocationService.java:
//        syncAccount = AccountHelper.CreateSyncAccount(this,
//                AuthenticatorService.getAccount(getStringResource(Config.ACCOUNT_TYPE_RESOURCE)));

//                SyncService.sync(syncAccount, getStringResource(Config.CONTENT_AUTHORITY_RESOURCE));

And from the plugin.xml:



Cheers
-jo2

**Comment by mauron85** [comment]
@Shane98c remove all accounts permissions from plugin.xml and don't use option `url` or `syncUrl`! That's it. No code commenting is necessary.

**Comment by Shane98c** [comment]
@tverilytt Thanks much!
