### ISSUE TITLE
ANDROID_ACTIVITY_PROVIDER vs ANDROID_DISTANCE_FILTER_PROVIDER

### ISSUE THREAD

**Issue by jeffgsharps** [mauron85/cordova-plugin-background-geolocation#145]
## Your Environment

- Plugin version: 2.1.2
- Platform: Android
- OS version: 4.4.4
- Device manufacturer and model: Samsung (cheap something)
- Cordova version (`cordova -v`): 6.3.0
- Cordova platform version (`cordova platform ls`): android 5.2.1
- Plugin configuration options: 
  backgroundGeolocation.configure(geolocationSuccessFn, geolocationFailureFn, {
      desiredAccuracy: 10,
      stationaryRadius: 20,
      notificationIconColor: '#c4e25f',
      notificationTitle: 'geolocation',
      notificationText: 'ENABLED',
      notificationIconLarge: 'gps_icon_large', //filename without extension 
      notificationIconSmall: 'gps_icon_small', //filename without extension 
      startOnBoot: false,
      startForeground: false,
      stopOnStillActivity: false,
      activityType: 'AutomotiveNavigation',
      saveBatteryOnBackground: false,
      debug: false, // <-- enable this hear sounds for background-geolocation life-cycle. 
      stopOnTerminate: false, // <-- enable this to clear background location settings when the app terminates 
      locationProvider: backgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
      interval: 120000, // <!-- poll for position every 2 minute 
      fastestInterval: 120000,
      url: null
  });
- Link to your project:
## Context

ANDROID_ACTIVITY_PROVIDER works on marhsmallow phone testing, but does not appear to work on 4.4.4 phone.
## Expected Behavior

Expected success or fail function to fire, with log to console some data
## Actual Behavior

Works as expected on marshmallow phone but neighter success nor fail function fires on 4.4.4 phone.
Switching provider to ANDROID_DISTANCE_FILTER_PROVIDE works, success function fires
## Possible Fix

Provide some error if ANDROID_ACTIVITY_PROVIDER 
does not work/is unavailable, to allow to use ANDROID_DISTANCE_FILTER_PROVIDER
## Steps to Reproduce

I do not know. I only have this two phones, developed on marshmallow and when trying out on 4.4.4 phone it does not work and I can not find a way to get an error log
## Context

Was testing the app out on an older phone to see if there were problems.
Current solution is to simply use the other provider until I can find a method of detecting when/why this happens.

**Comment by mauron85** [comment]
Log please

**Comment by jeffgsharps** [comment]
I will try to test and collect a log for this. Unfortunately the 4.4.4 phone is not even mine so it is hard to get long enough to test. But when I do I will capture a logcat.

I am going to have the app field tested using ANDROID_DISTANCE_FILTER_PROVIDER next week. It may actually work better for my purpose. I was collecting and sending to the server every two minutes with the other provider, but I see that this ANDROID_DISTANCE_FILTER_PROVIDER does not do that and does something based on change in GPS. If it isn't firing too often when in a vehicle it may be a better use. I wouldn't want to send location to the server every 10 seconds from traveling 20 meters in a speeding vehicle.. In testing it just worked great like clockwork every two minutes on the newer phone using the ANDROID_ACTIVITY_PROVIDER.

**Comment by mauron85** [comment]
Closing. If you have the data reopen. Thanks for understanding.
