### ISSUE TITLE
Background Geolocation Success callback issue

### ISSUE THREAD

**Issue by msviswanath** [mauron85/cordova-plugin-background-geolocation#146]
When the app is in closed state the following script is not working.

var loptions: {
      desiredAccuracy: 7, //In Meters
      stationaryRadius: 1, //In Meters
      distanceFilter: 1,
      locationTimeout: 10,
      interval: 10,
      fastestInterval: 8,
      activitiesInterval: 10,
      debug: true,
      notificationTitle: 'tracking',
      notificationText: 'enabled',
      notificationIconColor: '#FEDD1E',
      notificationIconLarge: 'mappointer_large',
      notificationIconSmall: 'mappointer_small',
      locationProvider: 'ANDROID_ACTIVITY_PROVIDER', 
      stopOnTerminate: false,
      startOnBoot: false,
      startForeground: true,
      stopOnStillActivity: true,
      activityType: 'AutomotiveNavigation',
      //url:'https://example.com/locations',
     // httpHeaders: { 'X-FOO': 'bar' },
      saveBatteryOnBackground: false
    },

backgroundGeolocation.configure(function (obj) {
        $.post('https://example.com/locations', JSON.stringify(obj));   **//This post call is not executing in background thread**
        backgroundGeolocation.finish();
      }, function (reason) {
         alert('Unable to get location ' + reason);
      }, opt);

backgroundGeolocation.start();

Is there any specific problem in the configurations ? If yes, how do we resolve?

**Comment by klidifia** [comment]
Hey you need to include more information. You haven't even mentioned Android / iOS / both? Please advise.

**Comment by viswanathms** [comment]
Hi Hayden,

We tried on android. But our intension is both. Please help us fix this ...

**Comment by mauron85** [comment]
Hi, this report is not following issue template. I cannot guess, platform you are on and etc... And asking everytime very basic question, because template was not used, is super exhausting.
