### ISSUE TITLE
Hiding status notifications

### ISSUE THREAD

**Issue by shmuel-krakower** [mauron85/cordova-plugin-background-geolocation#149]
While using the plugin - some notifications are showing up even while the application is in the background (android only).
Could we disable any of the notifications which are shown below?
![bb8b1a1c-66fc-4777-a1e5-e6df405a128a](https://cloud.githubusercontent.com/assets/1592972/17949404/cd93d1d6-6a5d-11e6-98b3-21aab37e90be.jpg)
![0ca8b236-3bd1-42b4-88ce-bb5df3ee9f9e](https://cloud.githubusercontent.com/assets/1592972/17949406/cd952950-6a5d-11e6-9b5a-53a1576dfcd9.jpg)
![8fc6077f-aa67-4cc7-8777-d121b21a2c54](https://cloud.githubusercontent.com/assets/1592972/17949405/cd946b32-6a5d-11e6-8c78-a3507ca25749.jpg)

We don't want to notify the user with every sync issue, as we count on the next retry to succeed.

**Comment by shmuel-krakower** [comment]
We also don't want the sync notification to show up.

**Comment by mauron85** [comment]
I'm sorry I don't like your attitude. No please or thank you, just asking for something and expecting I'll do. Keep in mind, i'm not your mule. I'm working in my spare time. Also there is source available. If `we` means company, then hire somebody to change that, or kindly ask me next time.
