### ISSUE TITLE
Question: callbackFn called in Android but not in iOS (Simulator)

### ISSUE THREAD

**Issue by tolu360** [mauron85/cordova-plugin-background-geolocation#15]
Hello,

Please I have a question, how can I make my app call the callbackFn on iOS even while developing in the simulator, I changed the location to `Freeway drive` but still `callbackFn` isn't called and `failureFn` isn't either so I know my config is fine. The `callbackFn` is called just fine on Android by the way.

I see `CDVBackgroundGeoLocation start (background? 0)` and `CDVBackgroundGeoLocation didChangeAuthorizationStatus 4` logged in the console on XCode, please what do these mean?

Thanks

**Comment by tolu360** [comment]
Update: it seems my app wasn't calling the `callbackFn` because it had only obtained the `While Using the App` location permission rather than obtaining the `Always` permission. I wonder if it's possible to auto-detect this?

**Comment by mauron85** [comment]
With current implementation, no way. But I'll add this on my todo list.

**Comment by mauron85** [comment]
Starting version 0.9.3 there is only Always permission. For While Using the App add cordova-plugin-geolocation plugin. It should work nicely with this one. Also now error callback from configure method is called in case user declined to grant permission or location services are disabled.

All those changes should help you resolve your issue. If not reopen issue. I consider this one as fixed.

**Comment by tolu360** [comment]
Thanks @mauron85 I'd update my app and revert.
