### ISSUE TITLE
Doc error between 

### ISSUE THREAD

**Issue by anymos** [mauron85/cordova-plugin-background-geolocation#151]
in the doc 👍 
HTTP locations posting

All locations updates are recorded in local db at all times. When App is in foreground or background in addition to storing location in local db, location callback function is triggered. Number of location stored in db is limited by option.maxLocations a never exceeds this number. Instead old locations are replaced by new ones.

When option.url is defined, each location is also immediately posted to url defined by option.url. If post is successful, the location is marked as deleted in local db. All failed to post locations will be coalesced and send in some time later in one single batch. Batch sync takes place only when number of failed to post locations reaches **option.syncTreshold.**

But the real one to use is **syncThreshold**

Took me me a bit of time to find it out why the positions saved in db was not sent to the backend, so it will be usefull I guess ;-)

**Comment by mauron85** [comment]
Where exactly do you see problem?

**Comment by anymos** [comment]
a h was missing :-)
