### ISSUE TITLE
ANDROID_DISTANCE_FILTER_PROVIDER only got one location,must switch off and on geolocation to be normal

### ISSUE THREAD

**Issue by guanchaonj** [mauron85/cordova-plugin-background-geolocation#153]
## Your Environment

- Plugin version:2.2.0.alfa.6
- Platform: Android
- OS version:5.1
- Device manufacturer and model:
- Cordova version (`cordova -v`):6.3
- Cordova platform version (`cordova platform ls`):android 5.2.1
- Plugin configuration options: {
              'desiredAccuracy': 100,
              'stationaryRadius': 1,
              'distanceFilter': 1,
  
  ```
          'locationProvider':window['backgroundGeolocation']['provider']['ANDROID_DISTANCE_FILTER_PROVIDER'],
          'interval':1500,
          'fastestInterval':300,
          'activitiesInterval':500,
          'stopOnStillActivity':false,
          'debug': true, // <-- enable this hear sounds for background-geolocation life-cycle.
          'stopOnTerminate': true // <-- enable this to clear background location settings when the app terminates
      }
  ```
- Link to your project:
## Actual Behavior

only got once location callback 
## Possible Fix

must switch off and then switch on geolocation ,then location callback become normal
## Steps to Reproduce

1.
2.
3.
4.

**Comment by xiaofanwu** [comment]
what do you mean switch off and then switch on geolocation? Do you mean that the user has to do that themselves on their phone? Thank you!

**Comment by guanchaonj** [comment]
yes.i found locationManager.requestSingleUpdate doesn't return any result,it is the reason.thanks.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
