### ISSUE TITLE
Feature Req: Kalman filter location updates

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#157]
Here is something interesting: https://github.com/villoren/KalmanLocationManager

**Comment by mauron85** [comment]
There was nice article about this. 
https://blog.hypertrack.io/2016/09/11/our-framework-for-real-time-filtering-of-location-streams/

Those guys do all the filtering on a server. Maybe that's the right approach. Do not do any client side filtering, do in server.

**Comment by shyamal890** [comment]
Hmm, makes sense. Thanks @mauron85 but please do consider https://github.com/mauron85/cordova-plugin-background-geolocation/issues/108 as it would help with server side filtering

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
