### ISSUE TITLE
deleteAllLocations does nothing?

### ISSUE THREAD

**Issue by brucejo75** [mauron85/cordova-plugin-background-geolocation#158]
Hello,

I am a new user of cordova-plugin-background-geolocation.  I have been experimenting with it a bit.

In my success callback to the configure command, I make a call to `getLocations`.  In the success callback for `getLocations` I immediately call `deleteAllLocations`.  This returns in the success callback implying that it worked.

But my callback is later called with all of the original locations still available.

Am I doing something wrong?  Does this work at all now?

Also, this message is sent to the console:
> [Warning]: deleteAllLocations is deprecated and will be removed in future versions.

Then I looked at this [issue #100](https://github.com/mauron85/cordova-plugin-background-geolocation/issues/100) and I became concerned.

I am using Meteor.  I can upload all the locations via the socket interface that Meteor provides.  I could use the HTTP post requests, but it is inconvenient (more packages/code) and wasteful (the meteor socket channel works great).

I would like to suggest that `getLocations` and `deleteAllLocations` are very useful in a context where you are not using http post calls.  And that both should remain in the package.

**Comment by mauron85** [comment]
When you deleteAllLocations, they will be marked invalid (not actually deleted). So you need to use getValidLocations instead. Invalid locations are either manually deleted or already sent to server (synced).

**Comment by brucejo75** [comment]
Thanks for the clarification!

What did you think about keeping deleteAllLocations for this scenario?

**Comment by mauron85** [comment]
There is another request to keep those methods. So rather I'll not remove them.

**Comment by brucejo75** [comment]
Great, thanks
