### ISSUE TITLE
Feature Req: Http Post for change in location service settings

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#159]
Sometimes a user may unintentionally switch off location service. 

In such cases it would be great if this plugin 
1. Could either start the parent app if it not in the background already.
2. Http Post update about the change to a custom url.
3. Add another column in present local sql storage table, this column would contain change in location service setting. If there is no change, this column would be null.

Hope this makes sense.

**Comment by shyamal890** [comment]
@mauron85 Can you please share your opinion on this?

I think the following makes much more sense:
1. Log changes in location service or GPS turned on or off in a separate column/parameter in the callback. Other parameters or columns would be null.
2. Whenever a change occurs, try to send immediate update to server. If network's not available or sending fails, store the update in local database.

**Comment by shyamal890** [comment]
@mauron85 I am trying to find `watchLocationMode` implementation in the code. Currently this function is only triggered when the app is active or in background. No way to log users changes in location settings when the app is closed. Looking forward to know what you think.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Comment by shyamal890** [comment]
Can you please reopen this issue.
