### ISSUE TITLE
Phonegap Build Error

### ISSUE THREAD

**Issue by gustter** [mauron85/cordova-plugin-background-geolocation#160]
I've included in my Config.xml the following line:

<plugin name="cordova-plugin-mauron85-background-geolocation" spec="^2.2.0"/>

Result:

Error - Plugin (or a specific plugin version) not found in external repo: cordova-plugin-mauron85-background-geolocation - You can fix this here

Could you help me?

Thanks.

**Comment by anymos** [comment]
the line you speak about is missing, could you add it ?

**Comment by klidifia** [comment]
Yeah, include the line, but whatever you do have; this is probably more like what you want:
`<plugin name="cordova-plugin-mauron85-background-geolocation" spec="2.2.0-alpha.6" source="npm" />`
Although it looks like the latest version 2.2.0 now, so maybe use that instead of alpha.

**Comment by mauron85** [comment]
@klidifia answer is correct
