### ISSUE TITLE
How disable notifications in Android?

### ISSUE THREAD

**Issue by adrieldubemarante** [mauron85/cordova-plugin-background-geolocation#161]
We need to disable background-geolocation notification message.
Can the API provide a configuration variable to disable notification?

##  Environment
* Platform: Android

## Expected Behavior

 Disable notification message

**Comment by eakkew** [comment]
I think you cannot as described in document https://github.com/mauron85/cordova-plugin-background-geolocation/wiki/Android-implementation

**Comment by mauron85** [comment]
You can disable with option `startForeground`: false

**Comment by mauron85** [comment]
Duplicate of https://github.com/mauron85/cordova-plugin-background-geolocation/issues/74

**Comment by smchae** [comment]
@mauron85 Thank you for this amazing plugin. I understood I could remove notification bar using `startForeground: false`. However, according to doc, `If false **location service will not be started in foreground** and no notification will be shown.` Does this mean tracking GPS stops while the user is in foreground? Or does it just means that notification bar does not start? I would like to track the user's location both in foreground and in background.
