### ISSUE TITLE
Passive mode?!

### ISSUE THREAD

**Issue by tverilytt** [mauron85/cordova-plugin-background-geolocation#162]
Hi!
It could be handy to be able to specify passive mode, both for foreground, but especially background.

Looking at this, desiredAccuracy 10000 might seem like "passive", but that is only for foreground mode?

One use case I have where this would be very helpful, is that the user can chhose both "auto location" and "auto data update". So if user only wants automatic update of (some) data, that will not require geolocation update.

Cheers
-jo

**Comment by mauron85** [comment]
If we're talking about android implementation, then ANDROID_ACTIVITY_PROVIDER with desiredAccuracy 10000 should be completely passive.

**Comment by tverilytt** [comment]
Coll! I was thinking IOS as well...! Not possible?
