### ISSUE TITLE
Change Provider dynamically 

### ISSUE THREAD

**Issue by Jinjos** [mauron85/cordova-plugin-background-geolocation#165]
switch between ANDROID_DISTANCE_FILTER_PROVIDER and ANDROID_ACTIVITY_PROVIDER when app is going to background.
## Your Environment

* Plugin version: 2.1.2
* Platform: Android
* Cordova version (`cordova -v`): 6.3.0
* Cordova platform version (`cordova platform ls`): Android 5.2.2
* Plugin configuration options: 

## Context

Hello,
Since I would like to get the best location provider in each status of the app, I will need to use 2 different providers.
the first is for the background ANDROID_DISTANCE_FILTER_PROVIDER
The second is for the foreground: ANDROID_ACTIVITY_PROVIDER or html geo (w3c, and I really don't want to manage 2 different GPS services)

Just searching to know if possible to do it and how.

Thank you,
Tomer
## Expected Behavior

When APP is going to the background (onPause), change provider ANDROID_ACTIVITY_PROVIDER
When APP is in foreground (onResume/Active) change to ANDROID_DISTANCE_FILTER_PROVIDER

**Comment by mauron85** [comment]
You can do this with device events:

https://cordova.apache.org/docs/en/latest/cordova/events/events.html

**Comment by mauron85** [comment]
Since 3.0.0-alpha.8 this should be possible without start/stop. Now you can call configure with only props you want to change and changes will be applied immediately
