### ISSUE TITLE
No background geoloc when locked device

### ISSUE THREAD

**Issue by tux240** [mauron85/cordova-plugin-background-geolocation#166]
Hi,

I'm still using the 1.0 version. I do some tests on android 4 and android 6.
On Android 4, no problem with it.
But, with Android 6 (device recently updated) the callback isn't called when I lock the device.
This is my config code:

`backgroundGeoLocation.configure(onGeolocationSuccess, onGeolocationFailure, {
              desiredAccuracy: 0,
              stationaryRadius: 20, //meters
              distanceFilter: 500, //meters
              stopOnTerminate: true,
              activityType: 'AutomotiveNavigation',
              locationService: backgroundGeoLocation.service.ANDROID_DISTANCE_FILTER,
              notificationIconColor: '#166DAC',
              notificationTitle: 'In progress',
              notificationText: 'Do not close',
              notificationIcon: 'geoloc_icon',
            });`

What did I do wrong ? Is it the stopOnTerminate option on true ? 

Thanks.

**Comment by mauron85** [comment]
Does it immediately stop working after lock or is it working for some time and it stops?

**Comment by tux240** [comment]
I did some tests on multiple devices.
In a device, it work like a charm and on another, it doesn't work in background. I have to let the screen on.
In addition, I have some repeating network errors. 
Usually it used to work after 1 or 2 times after have locked device.

**Comment by mauron85** [comment]
If it's working on Android 4.4 then it may be either connectivity issues or the doze mode.
Can you try following:

http://www.ibtimes.co.uk/how-disable-doze-mode-certain-apps-android-6-0-marshmallow-1525840

**Comment by tux240** [comment]
Thanks. I'm testing it and will give you the result.

**Comment by tux240** [comment]
It works, thanks !
It's strange, Doze doesn't like on each device
