### ISSUE TITLE
a way to do permission request manually

### ISSUE THREAD

**Issue by cordovapolymer** [mauron85/cordova-plugin-background-geolocation#169]
When a application using the background-geolocation plugin starts for a first time it requests geolocation permission. This behavior doesn't let app explain to the user  a reason why it's being requested and it blocks other permission requests issued with the help of https://github.com/NeoLSN/cordova-plugin-android-permission .
Can you add an option to disable permission request, so it could be requested manually?

**Comment by mauron85** [comment]
Why you can just display prompt before calling configure method?

**Comment by cordovapolymer** [comment]
you are right
