### ISSUE TITLE
UnimplementedBackgroundGeoLocation.start error

### ISSUE THREAD

**Issue by srikanthreddyn143** [mauron85/cordova-plugin-background-geolocation#17]
Hi,

I have added below piece of code in ondeviceReady event. When I try to execute, I get 'Unimplemented API Emulation: BackgroundGeoLocation.start' in emulator. Can you please help me out.

  /**
        * This would be your own callback for Ajax-requests after POSTing background geolocation to your server.
        */
        var yourAjaxCallback = function(response) {
            backgroundGeoLocation.finish();
        };

        /**
        * This callback will be executed every time a geolocation is recorded in the background.
        */
        var callbackFn = function(location) {
           
            console.log('[js] BackgroundGeoLocation callback:  ' + location.latitude + ',' + location.longitude);

           
               
            
                yourAjaxCallback.call(this);
           
        };

        var failureFn = function() {
             console.log('BackgroundGeoLocation err');
        };

        // Only ios emits this stationary event
        backgroundGeoLocation.onStationary(function(location) {
          console.log('onStationary');
        });

        // BackgroundGeoLocation is highly configurable.
        backgroundGeoLocation.configure(callbackFn, failureFn, {
            desiredAccuracy: 10,
            stationaryRadius: 50,
            distanceFilter: 50,
            locationTimeout: 30,
            activityType: 'AutomotiveNavigation',
            debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
            stopOnTerminate: false, // <-- enable this to clear background location settings when the app terminates
            locationService: backgroundGeoLocation.service['ANDROID_DISTANCE_FILTER'],
            fastestInterval: 5000
        });

      backgroundGeoLocation.start();

Thanks
Sri

**Comment by mauron85** [comment]
Please write down:
1. platform (android, ios...)
2. cordova version: cordova -v

In meantime check if plugin is actually loaded. You can use chrome **about:inspect** and check sources tab in developer tools.

**Comment by srikanthreddyn143** [comment]
Thank you mauron85 for your reply.

I am actually using intel xdk for app development. I tested on both android and ios and it has thrown the same error. I am using 5.1.1 version of cordova.

I actually tried to check if the backgroundGeoLocation  object is loaded. I was able to see the functions and everything in the object. 

I will try reloading the plugin.

Thanks
Sri

**Comment by rcurvello** [comment]
I try the same, but unsuccessful...

**Comment by mauron85** [comment]
Are you testing on real device or some kind of XDK emulator?

**Comment by rcurvello** [comment]
I try Build app for Android and test in my Moto X2... but fail during the compilation

**Comment by srikanthreddyn143** [comment]
Hi Mauron85,

It didn't work on XDK emulator but it worked like charm on android device(s5).. AWESOME!! But, when I close the app holding the home button and closing all apps, how can I track the location?

Thanks
Sri

**Comment by mauron85** [comment]
@srikanthreddyn143 glad to hear that.
There is related issue https://github.com/mauron85/cordova-plugin-background-geolocation/issues/9 regarding your question (short answer: need to be implemented yet)

**Comment by rcurvello** [comment]
srikanthreddyn143 you can provide your project/source?

**Comment by srikanthreddyn143** [comment]
Added cordova-plugin-mauron85-background-geolocation plug in to XDK project. Try using pluginid if it doesn't work with git repository link. OnDeviceReady event exists in init-dev.js in xdk folder.

https://gist.github.com/srikanthreddyn143/817e2aff50c8756cca44

**Comment by rcurvello** [comment]
Thanks! I will test.

**Comment by mauron85** [comment]
@rcurvello can I close this one?

**Comment by mauron85** [comment]
Closing, reopen when necessary.
