### ISSUE TITLE
question about switchMode

### ISSUE THREAD

**Issue by culland** [mauron85/cordova-plugin-background-geolocation#170]
This isn't an issue per say as I think it me being wrong in either implementation or expectation of switchMode, but not sure if there are forums for the plugin outside of this so sorry if this is in the wrong spot.
## Your Environment

Using most recent version of the plugin, using phonegap build to compile my apps, working on app for iOS device. Testing with iOS 4s running 9.3.5.

My settings:
        desiredAccuracy: 100,
        stationaryRadius: 50,
        distanceFilter: 100,
        stopOnTerminate: true,
        debug: true,
        activityType: 'OtherNavigation',   
## Context

The plugin seems to work fine in the foreground, but not in the background. I need to avoid relying on a tower switch for the background mode to function, so I was told in earlier discussion that changePace would help, which is now done with switchMode in the newer versions of the plugin.  Is this true, is my expectation of switchMode will do correct?
## Expected Behavior

I expect that when I set switchMode to foreground that when it is in background mode it will work as if it is in foreground?
## Actual Behavior

Stops recording records in background mode, starts up again when I make app live.
## Other

The way my app works is that background mode is only needed if they are recording a 'trip', so there is a button to start and end the trip. When they press start/end I do backgroundGeolocation.start(); and backgroundGeolocation.stop();.

In my  onDeviceready() function I have my success function, my fail function, my config settings and then I follow it up with switchMode:

backgroundGeolocation.switchMode(backgroundGeolocation.mode.FOREGROUND);

Ultimately I want it to work in the background like the foreground, what am I doing wrong? 

Thanks!

**Comment by mauron85** [comment]
You don't have to fiddle with switchMode. Just use option saveBatteryOnBackground = false.

**Comment by culland** [comment]
Ok thanks
