### ISSUE TITLE
"android.hardware.location.gps" uses-feature

### ISSUE THREAD

**Issue by dennisuhlemann** [mauron85/cordova-plugin-background-geolocation#171]
Up on the new GPS Usage Requirements of Google in the following Line
    <uses-feature android:name="android.hardware.location.gps" android:required="true" />
is missing in cordova-plugin-mauron85-background-geolocation/android/plugin/src/main/AndroidManifest.xml.

Could you please add this?

Here the original Text from Google:

> If your app requires GPS to function properly and you do not include android.hardware.location.gps in your manifest declaration, your users may have a poor app experience.
> 
> Also, if you’re using the fused location provider and wish to receive the most accurate location samples from GPS (i.e. with PRIORITY_HIGH_ACCURACY), you must include the "android.hardware.location.gps" feature in your app’s manifest to ensure that Google Play only distributes your app to devices with GPS sensors.

**Comment by mauron85** [comment]
Will add this. Thanks.

**Comment by mauron85** [comment]
Added in 2.2.2
