### ISSUE TITLE
Check if geolocation is turn on

### ISSUE THREAD

**Issue by langowskiadam** [mauron85/cordova-plugin-background-geolocation#172]
Hello,
how can I check if geolocation service (not location in settings) is still turn on? For example: geolocation service is stopped after terminate the app. When I start app again I want to show if geolocation service is on or off.

Kind regards

**Comment by mauron85** [comment]
Currently you can't. You should assume service is not running, which is fine with one exception - option.stopOnTerminate = false.

**Comment by langowskiadam** [comment]
Are there any plans to add such feature in future release?

**Comment by mauron85** [comment]
Don't know yet, because it's kinda hard on Android, as there is no official Android API to get service status.

anyway, since version 2.2.3 you can stop service on app start (see issue #173 for more details),
so you'll get consistent behaviour for both cases (stopOnTerminate true and false).

```
backgroundGeolocation.stop();
backgroundGeolocation.configure();
backgroundGeolocation.start();
```

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
