### ISSUE TITLE
Geolocation does not stop after closing and reopening the app

### ISSUE THREAD

**Issue by mihkelv2in** [mauron85/cordova-plugin-background-geolocation#173]
* Plugin version: 2.2.1
* Platform: Android
* OS version: 6.0.1
* Device manufacturer and model: LG Nexus 5, same problem with Nexus 5x
* Cordova version: built with phonegap build v cli-6.3.0
* Cordova platform version: 5.2.1

* Plugin configuration options: 
desiredAccuracy: 1
stationaryRadius: 1
debug: false
distanceFilter: 10
stopOnTerminate: false
interval: 1 * 60 * 1000
url: 'http://xxx:9101/geo'
httpHeaders: { key: val }

* Context
Tracking starts normally and all locations are sent to the server,
even if the app is closed by the user.
The problem is that when the app is started again, stoping tracking
does not work - the background service does not close. 
If I try to close the app afterwards android crashes.

* Cases:
1.
backgroundGeolocation.start();
Leave app running or pause it and resume it.
backgroundGeolocation.stop();
Tracking terminates normally.

2.
backgroundGeolocation.start();
Close app and open it again.
backgroundGeolocation.stop();
Tracking does not terminate and there is a android error after closing the app.

3.
backgroundGeolocation.start();
Close app and open it again.
backgroundGeolocation.stop();
Tracking does not terminate.
backgroundGeolocation.start();
backgroundGeolocation.stop();
Tracking terminates and no errors after closing app.

* Log for the java error

09-22 22:38:59.745 20459 20459 I com.tenforwardconsulting.cordova.BackgroundGeolocationPlugin: Destroying plugin
09-22 22:38:59.783 20459 20459 D AndroidRuntime: Shutting down VM
09-22 22:38:59.784 20459 20459 E AndroidRuntime: FATAL EXCEPTION: main
09-22 22:38:59.784 20459 20459 E AndroidRuntime: Process: net.zazler.sahko_ukko, PID: 20459
09-22 22:38:59.784 20459 20459 E AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {net.zazler.sahko_ukko/net.zazler.sahko_ukko.S_hk__Ukko}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Boolean com.marianhello.bgloc.Config.getStopOnTerminate()' on a null object reference
09-22 22:38:59.784 20459 20459 E AndroidRuntime:        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3831)
09-22 22:38:59.784 20459 20459 E AndroidRuntime:        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)
09-22 22:38:59.784 20459 20459 E AndroidRuntime:        at android.app.ActivityThread.-wrap5(ActivityThread.java)
09-22 22:38:59.784 20459 20459 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
09-22 22:38:59.784 20459 20459 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
09-22 22:38:59.784 20459 20459 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
09-22 22:38:59.784 20459 20459 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
09-22 22:38:59.784 20459 20459 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-22 22:38:59.784 20459 20459 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-22 22:38:59.784 20459 20459 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
09-22 22:38:59.784 20459 20459 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Boolean com.marianhello.bgloc.Config.getStopOnTerminate()' on a null object reference
09-22 22:38:59.784 20459 20459 E AndroidRuntime:        at com.tenforwardconsulting.cordova.BackgroundGeolocationPlugin.onDestroy(BackgroundGeolocationPlugin.java:476)
09-22 22:38:59.784 20459 20459 E AndroidRuntime:        at org.apache.cordova.PluginManager.onDestroy(PluginManager.java:298)
09-22 22:38:59.784 20459 20459 E AndroidRuntime:        at org.apache.cordova.CordovaWebViewImpl.handleDestroy(CordovaWebViewImpl.java:481)
09-22 22:38:59.784 20459 20459 E AndroidRuntime:        at org.apache.cordova.CordovaActivity.onDestroy(CordovaActivity.java:305)
09-22 22:38:59.784 20459 20459 E AndroidRuntime:        at android.app.Activity.performDestroy(Activity.java:6422)
09-22 22:38:59.784 20459 20459 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1142)
09-22 22:38:59.784 20459 20459 E AndroidRuntime:        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3818)
09-22 22:38:59.784 20459 20459 E AndroidRuntime:        ... 9 more

Is there a way to prevent this from happening or am I just using the plugin wrong?

**Comment by mauron85** [comment]
Regarding 2. and 3.

You should actually start service and then stop (recommended)
```
backgroundGeolocation.start();
Close app and open it again.
backgroundGeolocation.start();
backgroundGeolocation.stop();
Tracking does not terminate and there is a android error after closing the app.
```

Or at least call configure (not tested by myself, but seems the main reason of the crash):
```
backgroundGeolocation.start();
Close app and open it again.
backgroundGeolocation.configure({});
backgroundGeolocation.stop();
Tracking does not terminate and there is a android error after closing the app.
```

The reason is that activity is binding to service only after start is called. So right now, you're trying to stop **unconfigured** and **unbound**  service.
I will take look at this and fix at least the crash.

**Comment by mihkelv2in** [comment]
Calling configure again before start and stop after reopening the app worked. Thanks alot!

**Comment by mauron85** [comment]
Ok. I've fixed both issues (2. and 3.) in 2.2.3 

You don't need to call configure anymore to stop. And service should stop even it was not started in the same app session.
