### ISSUE TITLE
Feature Request: No notification

### ISSUE THREAD

**Issue by GrimGX** [mauron85/cordova-plugin-background-geolocation#174]
Is it possible to not show the notification when tracking is happening in the background? In the case of the app I am working on I am displaying a custom notification already that is passing back data that i need when the user clicks on the notification in order to take the user to a different section of the app.

Thanks a lot for the plugin, it works a treat.

**Comment by GrimGX** [comment]
I apologise, i found a way to do this. looked somewhere else.

**Comment by GeoTob** [comment]
@GrimGX chance you could let us know how you achieved that? interested in same thing
