### ISSUE TITLE
Plugin updates location every minute irrespective of distance filter and stationary radius

### ISSUE THREAD

**Issue by sajangurung2015** [mauron85/cordova-plugin-background-geolocation#175]
## Your Environment

- Plugin version: recent one
- Platform: iOS 
- OS version: iOS9
- Cordova version (`cordova -v`): 6.2.1
## Context

Plugin updates location every minute irrespective of distance filter and stationary radius.
## Expected Behavior

Plugin needs to update location once the user exceeds distance filter limit or stationary radius limit
## Actual Behavior

<Plugin updates location every minute irrespective of distance filter and stationary radius.

**Comment by cordovapolymer** [comment]
Strange behavior, of course this could be filtered using comparison function

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
