### ISSUE TITLE
Will this plugin able to track accurate GPS coordinates in case of user uses Spoof GPS APP

### ISSUE THREAD

**Issue by akhileshm1993** [mauron85/cordova-plugin-background-geolocation#176]
## Your Environment

- Plugin version: 2.2+\* Platform:  Android
- OS version:  6.0
- Device manufacturer and model: lenevo
- Cordova version (`cordova -v`):6.2.0
- Cordova platform version (`cordova platform ls`):5.1.1
- Plugin configuration options: 
  $cordovaBackgroundGeolocation.configure(callbackFn, failureFn, {
  desiredAccuracy: 20,
  stationaryRadius: 20,
  distanceFilter: 20,
  startOnBoot:true,
  saveBatteryOnBackground:false,
  startForeground:true,
  interval:5000,
  fastestInterval:5000,
  locationService: 'ANDROID_FUSED_LOCATION',
  locationProvider: backgroundGeolocation.provider.ANDROID_DISTANCE_FILTER_PROVIDER,
  activitiesInterval: 10000,
  debug: false,
  url: 'http://192.1680.101:8000/demoTrackingCollectionApi',
  syncUrl: 'http://192.1680.101:8000/demoTrackingCollectionApi,
  syncThreshold:50,
  stopOnTerminate: false
  });
- Link to your project:
## Context

As there are "Spoof GPS"  APPs are available on play-store which returns the fake GPS coordinates ,  so will this plugin will able to track users current location even if we use such spoofing APPS.  
## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
Simple answer. If user install any app that is mocking location, then location will be just fake/mock.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
