### ISSUE TITLE
Use plugin without location UIBackgroundMode

### ISSUE THREAD

**Issue by drew-r** [mauron85/cordova-plugin-background-geolocation#177]
Is it possible to use this plugin on IOS without location UIBackgroundMode enabled? 
Apple are rejecting our app with the mode enabled and if I disable it the app will crash with an error:

> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: !stayUp || CLClientIsBackgroundable(internal->fClient)'

cordova-plugin-background-geolocation-lt has a `useSignificantChangesOnly` option that seems to be missing here that @christocracy indicated would solve this in https://github.com/christocracy/cordova-plugin-background-geolocation/issues/132 .

Thanks

**Comment by christocracy** [comment]
@drew-r If you like mine, why don't *use* mine?

**Comment by drew-r** [comment]
@christocracy let's go with 'budgetary constraints' :P

**Comment by mauron85** [comment]
Correct me if I'm wrong `useSignificantChangesOnly` still needs UIBackgroundMode.

I can check that crash. However without background mode, this plugin does make very little sense. For foreground only geolocation you can use html5 or official cordova geolocation plugin.

Chris lt version is also alternative, and it's free for ios.

**Comment by drew-r** [comment]
@mauron85 I'm led to believe that UIBackgroundMode is required only for background GPS geolocation and that the significant changes API can provide background cell tower geolocation without this mode enabled.

Further to quote @christocracy directly in https://github.com/transistorsoft/react-native-background-geolocation/issues/67

> Make sure you disable the UIBackgroundMode "location" when booting the app with useSignificantChangesOnly.

If you can check the crash that would be great. 
I can't use Chris' lt version as I need Android support.

**Comment by drew-r** [comment]
https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/52

**Comment by christocracy** [comment]
@drew-r What you want @mauron85 to do for is worth about 10-20 hours of his time.  I'd be offering him a [nice donation](https://www.paypal.com/sk/cgi-bin/webscr?cmd=_flow&SESSION=74MjMl8TcxKwTIrT_B6OZHuN8fIjaMrzFsNEO-NHiRrvyDE8kkQ6GafBwmK&dispatch=5885d80a13c0db1f8e263663d3faee8d4fe1dd75ca3bd4f11d72275b28239088), were I you.

**Comment by drew-r** [comment]
@christocracy it's not going to take 10 - 20 hours and wouldn't be 'for me' as much as for the benefit of his fork of your (formerly free?) plugin

**Comment by christocracy** [comment]
So you're going to implement it yourself and give him a PR?

**Comment by drew-r** [comment]
@christocracy Maybe, maybe not.
Don't be sad that I don't want to pay for your plugin.

**Comment by christocracy** [comment]
It's not that I'm sad about a single sale it's about expectations of free labour.

**Comment by mauron85** [comment]
I don't mind spending time on features I'll use myself as I'm heavy user of this and react-native fork of this plugin. In this case I'm not convinced if it's worth spending time on it. Maybe in the future.

**Comment by drew-r** [comment]
@christocracy no expectations of free labour here just an issue report

Thanks @mauron85 I will look out for any future developments. 
Would be great to get your thoughts having read https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/52

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
