### ISSUE TITLE
activitiesInterval parameter makes no difference on battery consumption

### ISSUE THREAD

**Issue by gsustalo** [mauron85/cordova-plugin-background-geolocation#179]
I've been testing ANDROID_ACTIVITY_PROVIDER changing the activitiesInterval parameter but it have not made great differences in the results of battery consumption.
## Your Environment

- Plugin version: 2.2.4
- Platform: Android
- OS version: 4.0.3
- Device manufacturer and model: HUAWEI Ascend G 300 NFC
- Cordova version: 6.3.1
- Cordova platform version: 5.1.1
- Plugin configuration options: 
  **1:**
  {
      desiredAccuracy: 10,
      debug: false,
      stopOnTerminate: true, 
      locationProvider: backgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
      interval: 30 \* 60000, // poll for position every 30 minute 
      fastestInterval: 30 \* 120000,
      stopOnStillActivity: false
  }
  **2:**
  
  {
      desiredAccuracy: 10,
      debug: false,
      stopOnTerminate: true, 
      locationProvider: backgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
      interval: 30 \* 60000, // poll for position every 30 minute 
      fastestInterval: 30 \* 120000,  
      activitiesInterval: 10 \* 60000,
      stopOnStillActivity: false
  }
## Context

I've been getting the same results of battery consumption when activitiesInterval parameter is set than when is not set. 
When it is not set by default takes the value of 10000?
## Expected Behavior

Expect changing parameter (config 2) battery consumption would be lower, but what I have observed remain the same.

**Comment by gsustalo** [comment]
Doing a fast research on code I've seen this:

(ActivityRecognitionLocationProvider class)

```
private void attachRecorder() {
        if (googleApiClient == null) {
            connectToPlayAPI();
        } else if (googleApiClient.isConnected()) {
            if (isWatchingActivity) { return; }
            startTracking();
            if (config.getStopOnStillActivity()) {
                ActivityRecognition.ActivityRecognitionApi.requestActivityUpdates(
                    googleApiClient,
                    config.getActivitiesInterval(),
                    detectedActivitiesPI
                );
                isWatchingActivity = true;
            }
        } else {
            googleApiClient.connect();
        }
    }
```

Maybe, _activitiesInterval_ only applies when _stopOnStillActivity_ is true?

**Comment by mauron85** [comment]
You can always check defaults here:
https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/android/plugin/src/main/java/com/marianhello/bgloc/Config.java#L49

And yes 10000 is the default value. Setting up proper value depends on your use case,  but 10000 is IMHO good default.

**Comment by mauron85** [comment]
>Maybe, activitiesInterval only applies when stopOnStillActivity is true?

yes,

**Comment by gsustalo** [comment]
My concern now is about battery drain. 

On STILL status drain will be higher in stopOnStillActivity=TRUE than stopOnStillActivity=FALSE?

When device will be moving battery usage will be higher in stopOnStillActivity=FALSE than stopOnStillActivity=TRUE?

Thank you.
