### ISSUE TITLE
PhonegapBuild gives build error

### ISSUE THREAD

**Issue by renevaessen** [mauron85/cordova-plugin-background-geolocation#18]
The -phonegapbuild version of the plugin, does not build with cradle,
maybe some incompatibility with one of the other plugins?

My configured plug-ins:

  &lt;gap:plugin name="cordova-plugin-battery-status" version="1.1.0" source="npm" /&gt;
  &lt;gap:plugin name="cordova-plugin-camera" version="1.2.0" source="npm" /&gt;
  &lt;gap:plugin name="cordova-plugin-file" version="3.0.0" source="npm" /&gt;
  &lt;gap:plugin name="cordova-plugin-device" version="1.0.1" source="npm" /&gt;
  &lt;gap:plugin name="cordova-plugin-geolocation" version="1.0.1" source="npm" /&gt;

  &lt;gap:plugin name="cordova-plugin-inappbrowser" version="1.0.1" source="npm"/&gt;
  &lt;gap:plugin name="cordova-plugin-splashscreen" version="2.1.0" source="npm" /&gt;
  &lt;gap:plugin name="cordova-plugin-media" version="1.0.1" source="npm" /&gt;
  &lt;gap:plugin name="cordova-plugin-network-information" version="1.0.1" source="npm" /&gt;
  
  &lt;gap:plugin name="phonegap-plugin-barcodescanner" version="4.1.0" source="npm" /&gt;

  &lt;!--Temperary only iOS, see issue: http://community.phonegap.com/nitobi/topics/cordova-plugin-push-notification-failed-with-gradle-android?rfm=1 --&gt;
  &lt;gap:plugin name="cordova-plugin-push-notification" version="2.5.2" source="npm" gap:platform="ios" /&gt;
  &lt;gap:plugin name="cordova-plugin-statusbar" version="1.0.1" source="npm" /&gt;

  &lt;gap:plugin name="cordova-plugin-powermanagement" version="1.0.1" source="npm" /&gt;
  &lt;gap:plugin name="cordova-plugin-whitelist" version="1.0.0" source="npm" /&gt;
  &lt;gap:plugin name="cordova-plugin-mauron85-background-geolocation-phonegapbuild" version="0.7.3" source="npm" /&gt;
  &lt;gap:plugin name="cordova-plugin-keyboard" version="1.1.2" source="npm" /&gt;

My other settings:
  &lt;gap:platform name="android" /&gt;
  &lt;preference name="webviewbounce" value="false" /&gt;
  &lt;preference name="phonegap-version" value="cli-5.2.0" /&gt;
  &lt;preference name="detect-data-types" value="false" /&gt;
  &lt;preference name="stay-in-webview" value="false" /&gt;
  &lt;preference name="exit-on-suspend" value="false" /&gt;
  &lt;preference name="KeepRunning" value="true" /&gt;
  &lt;preference name="android-windowSoftInputMode" value="adjustPan" /&gt;
  &lt;preference name="KeyboardShrinksView" value="false" /&gt;
  &lt;preference name="orientation" value="both" /&gt;
  &lt;preference name="show-splash-screen-spinner" value="false" /&gt;
  &lt;preference name="auto-hide-splash-screen" value="false" /&gt;
  &lt;preference name="splash-screen-duration" value="2500" /&gt;
  &lt;preference name="fullscreen" value="true" /&gt;
  &lt;preference name="prerendered-icon" value="true" /&gt;
  &lt;preference name="load-url-timeout" value="75000" /&gt;
  &lt;preference name="android-build-tool" value="gradle" /&gt;
  &lt;preference name="StatusBarOverlaysWebView" value="false" /&gt;
  &lt;preference name="BackupWebStorage" value="cloud"/&gt;
  &lt;preference name="KeyboardDisplayRequiresUserAction" value="false"/&gt;
  &lt;preference name="SuppressesIncrementalRendering" value="true"/&gt;
  &lt;gap:config-file platform="android" parent="/manifest/application"&gt;
    &lt;activity android:launchMode="singleTop" /&gt;
  &lt;/gap:config-file&gt;
  

Phonegap build log:

Build Date: 2015-11-26 14:46:14 +0000
----------------------------------------------
Running: /project/gradlew cdvBuildRelease -b /project/build.gradle -Dorg.gradle.daemon=true -x lintVitalRelease
:preBuild
:compileReleaseNdk
:preReleaseBuild
:checkReleaseManifest
:CordovaLib:compileLint
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:preBuild
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar
:CordovaLib:compileReleaseNdk
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease
:prepareProjectCordovaLibUnspecifiedReleaseLibrary
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources
:processReleaseManifest
:processReleaseResourceswarning: string 'menu_settings' has no default translation.

:generateReleaseSources
:compileReleaseJava/project/src/com/tenforwardconsulting/cordova/bgloc/AbstractLocationService.java:14: error: package android.support.v4.app does not exist
import android.support.v4.app.NotificationCompat;
                             ^
/project/src/com/tenforwardconsulting/cordova/bgloc/AbstractLocationService.java:120: error: package NotificationCompat does not exist
    protected NotificationCompat.Builder setClickEvent (NotificationCompat.Builder builder) {
                                                                          ^
/project/src/com/tenforwardconsulting/cordova/bgloc/AbstractLocationService.java:120: error: package NotificationCompat does not exist
    protected NotificationCompat.Builder setClickEvent (NotificationCompat.Builder builder) {
                                ^
/project/src/com/tenforwardconsulting/cordova/bgloc/AbstractLocationService.java:88: error: package NotificationCompat does not exist
            NotificationCompat.Builder builder = new NotificationCompat.Builder(this);
                              ^
/project/src/com/tenforwardconsulting/cordova/bgloc/AbstractLocationService.java:88: error: package NotificationCompat does not exist
            NotificationCompat.Builder builder = new NotificationCompat.Builder(this);
                                                                       ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /project/src/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJava'.
&gt; Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.219 secs

/project/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /project/gradlew with args: cdvBuildRelease,-b,/project/build.gradle,-Dorg.gradle.daemon=true,-x,lintVitalRelease

**Comment by mauron85** [comment]
Moving issue to cordova-plugin-mauron85-background-geolocation-phonegapbuild project

https://github.com/mauron85/cordova-plugin-mauron85-background-geolocation-phonegapbuild/issues/1

**Comment by mauron85** [comment]
@renevaessen: You're probably missing Android Support Library. Check Android SDK Manager.
Please don't reply here, but mauron85/cordova-plugin-mauron85-background-geolocation-phonegapbuild#1
