### ISSUE TITLE
Not working on Android versions prior to 6

### ISSUE THREAD

**Issue by hermandinho** [mauron85/cordova-plugin-background-geolocation#180]
Hello, great job for this plugin. Helps me alot. :). My background mode woks like charm for Android versions >= 6. But nothing works neigther in foreground nor background for older versions of Android. Is that normal? 

Regards

**Comment by anymos** [comment]
Hi there, please post a way to reproduce the issue, from my testing it works real good on any android > 4.4 and ios >8 without any problem
