### ISSUE TITLE
PhoneGap Build Gradle Error

### ISSUE THREAD

**Issue by culland** [mauron85/cordova-plugin-background-geolocation#181]
When I build my app, which is working great for iOS, for android I get an error:  "One of your plugins required the gradle android build tool to build" preventing the app from building. I double checked to make sure it was this plugin causing the issue.

I have: preference name="android-build-tool" value="gradle"    added to my config file.

I looked through the older issues and found one that indicated using an older spec would solve the problem, but that didn't work.  Are there any specific spec's that I should try that might work? Other suggestions/thoughts?
## Your Environment
- Platform: Android
- PhoneGap Build 3.7

**Comment by mauron85** [comment]
I don't use PG Build anymore. But can you try older version, for example 2.1.2?

**Comment by culland** [comment]
No difference with spec="2.1.2"

**Comment by klaus-donnert** [comment]
PhoneGap Build >= 4.0 uses Gradle by default.

**Comment by srsarcasmo** [comment]
COULD NOT INSTALL THE PLUG-IN Telerik SHOW ME TO INSTALL ERROR

**Comment by aveliks** [comment]
culland , You can try use fork 
https://www.npmjs.com/package/cordova-plugin-navis-background-geolocation

I use this in IntelXDK and don't get message about gradle

**Comment by mauron85** [comment]
@aveliks so you mixed my old 1.x branch (which is fork of cordova-background-geolocation) with another old cordova-background-geolocation-lt? I don't see any reason why your version is any different from this one regarding phonegap build. Did you done any special PG adjustments? Can you send PR so I can also benefit from your work?

**Comment by aveliks** [comment]
m-m-m? I simply try build my app with Your plugin in IntelXDK and get build error dur gradle needed for build.
After I find fork https://github.com/ivent/cordova-plugin-background-geolocation from Your plugin w/o problem with using gradle.

**Comment by mauron85** [comment]
Ach now I get. So you just published ivent repo to the npm.

**Comment by aveliks** [comment]
No problem :)

But, can You provide support PG in this site like in navis plugin to avoid problem with gradle?

And can You clear using navigator.geolocation object in first time of using and possibility to change on another geolocation object from another plugin(s)?

Thanks for answer

**Comment by mauron85** [comment]
Actually I don't see any real difference, he just used my 1.x branch. Can you test version 1.x in PG, so I can check what was changed.

**Comment by culland** [comment]
I tried versions 1.0.2 and 0.96 both with the same gradle error.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
