### ISSUE TITLE
callback on still activity

### ISSUE THREAD

**Issue by cordovapolymer** [mauron85/cordova-plugin-background-geolocation#182]
Is it possible to have a callback when a still activity is detected?
It would be very usefull as the plugin does it very well and there would be no need in another plugin.

**Comment by srsarcasmo** [comment]
COULD NOT INSTALL THE PLUG-IN Telerik SHOW ME TO INSTALL ERROR

**Comment by cordovapolymer** [comment]
Mauron85, any feedback on this question?

**Comment by mauron85** [comment]
will be added in the next version

**Comment by cordovapolymer** [comment]
> will be added in the next version
Thank you!

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
