### ISSUE TITLE
deleteAllLocations(success, fail) method not deleting all locations

### ISSUE THREAD

**Issue by RNavaneethKumar** [mauron85/cordova-plugin-background-geolocation#183]
Following is the order in which the methods are called in my code

1. backgroundGeolocation.getLocations(success, fail);
2. backgroundGeolocation.deleteAllLocations(success, fail);
3. backgroundGeolocation.getLocations(success, fail);

Following is the result

1. Success method gets executed. location.length is 123
2. Success method gets executed. status is SUCCESS
3. Success method gets executed. location.length is STILL 123. I expected the result will be 0.

Is this the expected behavior of the plugin?

**Comment by mauron85** [comment]
Read docs. You will find explanation there. Just give you hint:

```
    backgroundGeolocation.getValidLocations(success, fail);
    backgroundGeolocation.deleteAllLocations(success, fail);
    backgroundGeolocation.getValidLocations(success, fail);

```

**Comment by RNavaneethKumar** [comment]
Thanks dear friend. But here is all that I can find from the docs.

deleteAllLocations(success, fail)
Note: You don't need to delete all locations. Plugin manages number of locations automatically and location count never exceeds number as defined by option.maxLocations.
Platform: iOS, Android
Delete all stored locations.

So based on the above description, I expected the result of the final method call to ZERO. But the result is > 0. It would be kind of you, if you can explain or point me directly to the section of the docs if I have missed anything.

**Comment by RNavaneethKumar** [comment]
@mauron85 - Can you please help me with this? I'd be very thankful.

**Comment by RNavaneethKumar** [comment]
Well. Thank you very much.
