### ISSUE TITLE
Problem with using navigator.geolocation object ....

### ISSUE THREAD

**Issue by aveliks** [mauron85/cordova-plugin-background-geolocation#184]
In Android with all webkit based app You can meet this bug/trouble 
http://stackoverflow.com/questions/23383750/phonegap-geolocation-sometimes-not-working-on-android/39173044#39173044

I have this bug on my  HUAWEI P8 Lite Android 6 (API 23)
and don't have on SAMSUNG S3 NEO Android 4.4.4

where is problem?

I create simple test app in IntelXDK with your plugin ( precisely with fork from Your plugin cordova-plugin-navis-background-geolocation , tjis plugin don't have problem with gradle)

When navigator.geolocation don't work I can get only 2 or 3 messages mv:false ....
and every 2-3 minutes long tt signal

When navigator.geolocation  work I get regulary short tt signals

For geolocation need I use plugin cordova-plugin-locationservices-fix that uses Google Play Services Location API 

This plugin work fine in all cases .
## Your Environment

- Plugin version:
  cordova-plugin-navis-background-geolocation
- Platform: iOS or Android
  Android 6 , 5, 4
- OS version:
  6, 5 4
- Device manufacturer and model:
- Cordova version (`cordova -v`): latest
- Cordova platform version (`cordova platform ls`):
- Plugin configuration options: 
  as in example in readme
- Link to your project:
## Expected Behavior

Is it strictly needed use navigator.geolocation in first time  or I can change on another plugin objects? 
## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
Please send debug logs and I will take a look on it.

**Comment by aveliks** [comment]
I don't see any log entries about plugin in logcat  
I try it ...

but can I t change using navigator.geolocation in common ?

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
