### ISSUE TITLE
Android : open app when clicking on notification

### ISSUE THREAD

**Issue by GitBalou** [mauron85/cordova-plugin-background-geolocation#188]
Click on notification open the app manager. See [this link](http://images.google.fr/imgres?imgurl=http%3A%2F%2Fimages.frandroid.com%2Fwp-content%2Fuploads%2F2015%2F07%2FGoogle-play-service.jpg&imgrefurl=http%3A%2F%2Fwww.frandroid.com%2Fcomment-faire%2Ftutoriaux%2Ftrucs-et-astuces%2F296334_tuto-economiser-de-batterie-android&h=1405&w=1440&tbnid=16DPcHbRi-Xk5M%3A&docid=yAZlhZZdMcQLGM&ei=_dQIWMy4KsutaZSdibgP&tbm=isch&client=firefox-b&iact=rc&uact=3&dur=240&page=0&start=0&ndsp=16&ved=0ahUKEwiMq_CfzOnPAhXLVhoKHZROAvcQMwglKAkwCQ&bih=633&biw=1366) for an exemple.

Is this the expected behaviour ? Is there a way to open the app using the notification ?

Thanks
Gabriel
- Plugin version 2.2.4
- Android 5.1.1
- Samsung galaxy J5
- Cordova 6.2.0
- Cordova platform version (`cordova platform ls`):
- Plugin configuration options:

**Comment by GitBalou** [comment]
Problem solved.
This behavior (clicking on notification open app parameter instead of app itself) is due to an error during configuration. I don't know the exact error, as I changed lots of thing in code during theses 3 days.
Thanks for your amazing plug-in
Gabriel

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
