### ISSUE TITLE
iOS 9.1 Location Error

### ISSUE THREAD

**Issue by SaphiraT** [mauron85/cordova-plugin-background-geolocation#19]
Background service of the plugin does not work correctly on iOS 9.1 (ipad 3). 

Pressing the "btn-home" in footer, shows the current location on map. Location privileges to app are granted "always":   

When the app is closed and running in background, there are no notifications and the map "jumps" to the current location, when its reopened.

I have also tried iOS emulator with iOS 9.0 and its working fine.

**Comment by mauron85** [comment]
Can somebody else confirm this?

**Comment by mauron85** [comment]
@SaphiraT I cannot reproduce your issue on ios simulator. Just checked both ios 9.2 and 9.0 with SampleApp and everything run fine.

Can you test SampleApp from example dir? 
See doc https://github.com/mauron85/cordova-plugin-background-geolocation/tree/master/example/SampleApp

**Comment by mauron85** [comment]
@SaphiraT is this still relevant?

**Comment by freezyfridge** [comment]
i'm tested in real devices ios 9.2 with the SampleApp. It is not working. Do we need another plugin to works in ios?

**Comment by mauron85** [comment]
Seems like duplicate of #26 Need to investigate on this one

**Comment by mauron85** [comment]
Hi, can plz try 0.9.2 if it resolve your issue? It's already in npm.

**Comment by mauron85** [comment]
Can you confirm still having issues with 0.9.3 version of the plugin?

**Comment by mauron85** [comment]
Closing for no response.
