### ISSUE TITLE
Android activity provider doesn't get any position.

### ISSUE THREAD

**Issue by nschurmann** [mauron85/cordova-plugin-background-geolocation#191]
## Your Environment

- Plugin version: 2.2
- Platform: Android
- OS version: 5
- Device manufacturer and model: ZTE Blade
- Cordova version (`cordova -v`):6.3.1
- Cordova platform version (`cordova platform ls`):
  Installed platforms:
  android 5.2.2
  ios 4.2.1
- Plugin configuration options:

``` javascript
window.backgroundGeolocation.configure(callbackFn, failureFn, {
            desiredAccuracy: 10,
            stationaryRadius: 10,
            distanceFilter: 1,
            interval: 10,
            startOnBoot: true,
            activitiesInterval: 10,
            locationProvider: 1,
            fastestInterval: 3,
            notificationTitle: 'Tracking',
            notificationText: 'Active',
            pauseLocationUpdates: false,
            stopOnTerminate: false,
        })
```
## Context

The option 1 for location provider should get the location based on an amount of time, in this case interval 10 should get the location every 10 ms so i can get a more detailed position of the user.
## Expected Behavior

The app should execute the callback every 10 ms.
## Actual Behavior

Does not execute the callback ever. This happens with the option locationProvider: 1, with 0 executes the callback but not every X amount of time

**Comment by mauron85** [comment]
First I don't recommend using numbers for locationProvider. You should be using enums (eg. backgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER). It's not only easier to read, but numbering may change while enum will not.

Regarding your problem. ANDROID_ACTIVITY_PROVIDER executes callback only when motion is detected. When idle no callback will be called (this can be changed by option stopOnStillActivity).

ANDROID_DISTANCE_FILTER_PROVIDER is using elastic distance filter to achieve optimal battery and data usage, so callbacks interval will depend on how fast you're moving. Also read issue #185

**Comment by nschurmann** [comment]
@mauron85 ANDROID_ACTIVITY_PROVIDER executes callback only when motion is detected. <-- this means motion as detected by the accelerometer?, because i'm using now `Lockito`, an app to simulate gps movement, so it's like using the tools from the iOS emulator to simulate, IE, a walk.

**Comment by nschurmann** [comment]
Confirmed, ANDROID_ACTIVITY_PROVIDER  doesn't work at all with this configuration, only works ANDROID_DISTANCE_FILTER_PROVIDER. Where is this filter on the code so i can delete this filter?

**Comment by mauron85** [comment]
>Confirmed, ANDROID_ACTIVITY_PROVIDER doesn't work

Have you tried option `stopOnStillActivity: false` ?

**Comment by nschurmann** [comment]
yes!, this is the new config
```javascript
{
  desiredAccuracy: 10,
  stationaryRadius: 10,
  distanceFilter: 1,
  interval: 10,
  startOnBoot: true,
  activitiesInterval: 10,
  locationProvider: backgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
  fastestInterval: 3,
  notificationTitle: 'Tracking',
  notificationText: 'Active',
  pauseLocationUpdates: false,
  stopOnTerminate: false,
  stopOnStillActivity: false,
}
```

**Comment by mauron85** [comment]
will try replicate that with `Lockito`. Maybe tomorrow. No false promises though. Also check 'adb logcat` or even better [pidcat](https://github.com/JakeWharton/pidcat) for errors

**Comment by nschurmann** [comment]
@mauron85 thanks!, i also managed to disable the elasticity on iOS by returning the value without making any calculation. But i cannot find this on android, it would be awesome so i can get a more precise gps position because i need something based on time instead of velocity or position.

**Comment by mauron85** [comment]
Should be easy. I would start here:

https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/android/plugin/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java#L287

(but beware it might be more than one line to change).

I never though people will use this plugin also as pure cordova-geolocation-plugin replacement, so never made distanceFilter configurable. But more and more people are asking for this. I wish I has more time (which I don't).

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
