### ISSUE TITLE
Open the app from the android notification

### ISSUE THREAD

**Issue by JsanchezMGit** [mauron85/cordova-plugin-background-geolocation#192]
Hello, first of all congrats, it is a great plugin. I'm trying the example, it is perfectly running, and also I'm developing my own application, but when is in background and the user tap the notification it opens the app details and the example opens the app. ¿Some one know if it is a configuration? I was serching in the code, but I couldnt found it.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
