### ISSUE TITLE
Plugin does not work in Genymotion Android 6 emulator

### ISSUE THREAD

**Issue by pdrosos** [mauron85/cordova-plugin-background-geolocation#193]
Hi,

When I use the plugin on a physical Android 5 device, it works as expected. But when I use it in a Genymotion emulator with Android 6, it asks for location permissions, but the plug-in does not work after that. I don't receive the location in the configure method and there's no console.log output from it. It's the same for both Android providers - ANDROID_DISTANCE_FILTER_PROVIDER and ANDROID_ACTIVITY_PROVIDER

Could this be fixed somehow? Any idea how to test it in emulator? I don't have a physical Android 6 device.

Thanks!

**Comment by mauron85** [comment]
genymotion doesn't implement all required providers like net ... That's why is not supported by me.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
