### ISSUE TITLE
[Android] Callback is not being executed if the app is closed and with stopOnTerminate: false

### ISSUE THREAD

**Issue by nschurmann** [mauron85/cordova-plugin-background-geolocation#194]
## Your Environment

* Plugin version: 2.2
* Platform: Android
* OS version: 5
* Device manufacturer and model: ZTE Blade
* Cordova version (`cordova -v`):6.3.1
* Cordova platform version (`cordova platform ls`):
Installed platforms:
  android 5.2.2
  ios 4.2.1
* Plugin configuration options:
```javascript
window.backgroundGeolocation.configure(callbackFn, failureFn, {
            desiredAccuracy: 10,
            stationaryRadius: 10,
            distanceFilter: 1,
            interval: 10,
            startOnBoot: true,
            activitiesInterval: 10,
            locationProvider: backgroundGeolocation.provider.ANDROID_DISTANCE_FILTER_PROVIDER,
            fastestInterval: 3,
            notificationTitle: 'Yu-Track',
            notificationText: 'Tracking en progreso',
            pauseLocationUpdates: false,
            stopOnTerminate: false,
            stopOnStillActivity: false,
            debug: true,
            startForeground:true,
            url: 'http://localhost:3000/locations'
        })
```
## Context

`callbackFn` should be called when the app has been closed. (open apps drawer, swipe left and close it)
## Expected Behavior

Callback should be executed
## Actual Behavior

Callback is not being executed on Android, o iOS it's working.

It's very important to mention that the locations are being sent to the specified url `http://localhost:3000/locations`

**Comment by mauron85** [comment]
This IMHO not possible. Activity is dead and with it callback reciever.

**Comment by nschurmann** [comment]
Thanks!, closing!
