### ISSUE TITLE
Question about different behaviour between iOS and Android

### ISSUE THREAD

**Issue by zulhfreelancer** [mauron85/cordova-plugin-background-geolocation#196]
Hi,

I tested your [example app](https://github.com/mauron85/cordova-plugin-background-geolocation-example) and I noticed some different behaviours between iOS and Android which I want clarification from you.
## My Environment
- Plugin version: ^2.2.0
- Platform: iOS and Android
- OS version: iOS 10.1 and Android 4.1.2
- Device manufacturer and model: iPhone 5 and Nokia XL (Android)
- Cordova version (`cordova -v`): 6.3.0
- Cordova platform version (`cordova platform ls`): ios 4.2.1 and android 5.2.2
- Plugin configuration options: not touched - I used your configuration options
- App settings: see screenshots below
- Link to project: https://github.com/mauron85/cordova-plugin-background-geolocation-example

![img_2016-10-30 05 36 26](https://cloud.githubusercontent.com/assets/3416976/19832900/e173b82c-9e62-11e6-913e-bee19c1dfac9.jpg)

![img_2016-10-30 05 36 38](https://cloud.githubusercontent.com/assets/3416976/19832902/eceffd82-9e62-11e6-988a-dc80c3a2051e.jpg)

![img_2016-10-30 05 36 44](https://cloud.githubusercontent.com/assets/3416976/19832904/f67c290c-9e62-11e6-9d11-fc6eebc631ee.jpg)
## Context & Actual Behavior

| App state | iOS send HTTP POST? | Android send HTTP POST? |
| --- | :-: | --: |
| Foreground | Yes | Yes |
| Right after goes background | Yes | Yes |
| Backround | No | Yes |
| Screen locked/switch-off (phone in stand-by mode) | No | Yes |
## Expected Behavior

Why iOS can't send the location data when the app is in background and when the screen locked? Or, do I missed something important?

**Note**

The way I test the HTTP POST is by running my `rails server` and see the incoming requests from the app. Example params that I saw:

```
Started POST "/pages/index" for 192.168.1.64 at 2016-10-30 05:02:28 +0800
Processing by PagesController#index as */*
  Parameters: {"_json"=>[{"latitude"=>3.123006159667078, "longitude"=>101.6054567579111, "altitude"=>37.42809677124023, "location_type"=>"current", "speed"=>-1, "time"=>1477774946370.314, "accuracy"=>65, "altitudeAccuracy"=>10, "heading"=>-1, "bearing"=>-1}], "page"=>{"_json"=>[{"latitude"=>3.123006159667078, "longitude"=>101.6054567579111, "altitude"=>37.42809677124023, "location_type"=>"current", "speed"=>-1, "time"=>1477774946370.314, "accuracy"=>65, "altitudeAccuracy"=>10, "heading"=>-1, "bearing"=>-1}]}}
  Rendered pages/index.html.erb within layouts/application (0.1ms)
Completed 200 OK in 194ms (Views: 193.1ms | ActiveRecord: 0.0ms)
```

**Comment by mauron85** [comment]
Hmm. You're not first one asking these. But I like your description and table. Can you post plugin debug logs? Check docs for instructions.

**Comment by stephenedwards** [comment]
bump
