### ISSUE TITLE
PLUGIN NOT WORK WHEN THE MOBILE SCREEN IS OFF

### ISSUE THREAD

**Issue by mherrerar** [mauron85/cordova-plugin-background-geolocation#197]
We have a serious problems with the plugin. this work well when the screen is on, but when the screen is off the geolocation no work.

this is our configuration:

backgroundGeolocation.configure(callbackFn, failureFn, {
desiredAccuracy: 10,
stationaryRadius: 20,
distanceFilter: 30,
startOnBoot: false,
stopOnTerminate: false,
debug: true,
notificationTitle: 'Title',
notificationText: 'Text...',
//ANDROID
locationProvider: 1,
interval: 60000,
fastestInterval: 30000,
activitiesInterval: 10000
});
backgroundGeolocation.start();

**Comment by mherrerar** [comment]
this is our configuration:

backgroundGeolocation.configure(callbackFn, failureFn, {
                desiredAccuracy: 10,
                stationaryRadius: 20,
                distanceFilter: 30,
                startOnBoot: false,
                stopOnTerminate: false,
                debug: true,
                notificationTitle: 'Title',
                notificationText: 'Text...',
                //ANDROID
                locationProvider: 1,
                interval: 60000,
                fastestInterval: 30000,
                activitiesInterval: 10000
            });
            backgroundGeolocation.start();

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
