### ISSUE TITLE
[Documentation Request] Please documentation for callback for start() and stop()

### ISSUE THREAD

**Issue by scarabdesign** [mauron85/cordova-plugin-background-geolocation#199]
I noticed there is a callback that gets called when I supply it for stop(), which I didn't see reference to in the documentation. There is also success and failure callback in start() that are demonstrated in your "Real world example" that are not in the documentation for that function.

**Comment by mauron85** [comment]
good point. doc should be updated

**Comment by apptum** [comment]
oh yeah, btw:
Are the callbacks from `.start(successFn, failureFn)` the same that are set in `.configure(successFn, failureFn, options)`?

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Comment by mauron85** [comment]
This is not valid for 3.0.0. There are `on` events: start, stop, configure.
