### ISSUE TITLE
configure options

### ISSUE THREAD

**Issue by m4shiro** [mauron85/cordova-plugin-background-geolocation#200]
hi, I'm new. Is it possible to use a variable instead of a number when configuring options?

e.g.

var interval_setting = 5000;
backgroundGeolocation.configure( success, fail, {
       ....
       interval : interval_setting;
      ....
});

if so, can I also reuse backgroundGeolocation.configure elsewhere in my code to change a specific option?
Thanks in advance!

**Comment by mauron85** [comment]
you can pass your own variable as configure option, however plugin options will not change if you change it. And there're two reason why not.

1. `interval_setting` is primitive value, so when you pass it to function, that function will hold own independent copy of that value. So changing interval_settings will have no effect.
2. if you use configuration object (which is passed by reference), you can change its properties and it will be changed also in function. Try yourself:
```
var opts = { 
  interval: 5000
};
function myFunc(opts) {
  console.log(opts); 
}
myFunc(opts);
opts.interval = 9999; // now change interval
myFunc(opts);
```

However this cordova doesn't works that way. Cordova plugin is bridge between javascript and native code (java, objectivec...). So function arguments are serialized and deserialized when you call function, but they don't share same memory. In short it is not possible to change config options as in example above without calling `backgroundGeolocation.configure`

**Comment by m4shiro** [comment]
ok great, thanks! I managed to change the interval. However, a kill and restart of the app is required
