### ISSUE TITLE
force location update after stopOnStillActivity?

### ISSUE THREAD

**Issue by apptum** [mauron85/cordova-plugin-background-geolocation#201]
I got the problem that a still activity can stop location updates (and therefore stop refining accuracy) even when accuracy is bigger then desired accuracy. 

I tried this:
`function onStationaryUpdate (cb) {`
`  if (cb.accuracy > 30) {`
`  backgroundGeolocation.start();`
`  }`
`}`

but that results in an immediate still-activity again...
Is there a way to force location updates after `stopOnStillActivity`?

[I know I could set `stopOnStillActivity: true` after I reached my desired accuracy but that wouldn't preempt the case completely, as an update with accuracy > desired accuracy could occur after activation, but before still activity...]

Any ideas?

**Comment by mauron85** [comment]
Not sure I understand, what are u trying to achieve.

**Comment by apptum** [comment]
Hey @mauron85 thanks for coming back on this. Let me try to explain better:
My app needs an accuracy as precise as possible. As the app is supposed to be long running, I use stopOnStillActivity - which works great.
But: mostly on app start (f.e. at home, not moving) it's possible that the plugin recognizes a still activity and stops watching for locations while still having very rough accuracy.
Optimal would be an option to say that stopOnStillActivity should only stop when accuracy < X. As long as that threshold X is not reached, it should keep watching for location updates.
Now I work around like this:
```
backgroundGeolocation.onStationary(onStationaryUpdate, errorFn);
function onStationaryUpdate (onStat) {
  if (onStat.accuracy > 30) {
    console.log("onSTATIONARY with low accuracy (" + onStat.accuracy + "), restarting.");
    backgroundGeolocation.stop();
    backgroundGeolocation.start();
  } else {
    console.log("onSTATIONARY with good accuracy , calling locationWatchUpdate()");
    locationWatchUpdate(onStat);
  }
};
```
- __Is there a better way of restarting the location watch after an onStationary event with low accuracy?__

This `.stop();` then `.start();` again works, but it seems to me not optimal: a loophole like this is possible:
```
start()           <––––––––––––––––––––––––––\
↳ location update (stationary event)         |
↳stop()                                      |
↳ onStationary Fn (accuracy low) ->––––––––––⁄
```
... on and on

Any suggestion to make this more fail proof highly appreciated!
[and btw: thank you for your effort on this plugin!]

**Comment by apptum** [comment]
I added the following to ActivityRecognitionLocationProvider.java and a new config value `stopOnStillMinAccuracy` to handle a minimum accuracy before it calls `handleStationary();` and `stop();`on stationary event. Are you interested in adding?

ActivityRecognitionLocationProvider.java (line 65)
```
public void onLocationChanged(Location location) {
        log.debug("Location change: {}", location.toString());

        if ((lastActivity.getType() == DetectedActivity.STILL) && (location.getAccuracy() > config.getStopOnStillMinAccuracy())) {
            if (config.isDebugging()) {
                Toast.makeText(locationService, "STILL" + ", acc: " + location.getAccuracy() +  " > " + config.getStopOnStillMinAccuracy()+ ", ignoreStationary", Toast.LENGTH_SHORT).show();
            }
            return;
        } else if (lastActivity.getType() == DetectedActivity.STILL) {
            if (config.isDebugging()) {
                Toast.makeText(locationService, "STILL" + ", acc: " + location.getAccuracy(), Toast.LENGTH_SHORT).show();
            }
            handleStationary(location);
            stopTracking();
            return;
        }

        if (config.isDebugging()) {
            Toast.makeText(locationService, "acy:" + location.getAccuracy() + ",v:" + location.getSpeed() + ",df:" + config.getDistanceFilter(), Toast.LENGTH_LONG).show();
        }

        // if (lastLocation != null && location.distanceTo(lastLocation) < config.getDistanceFilter()) {
        //     return;
        // }

        if (config.isDebugging()) {
            startTone(Tone.BEEP);
        }

        lastLocation = location;
        handleLocation(location);
    }
```
and in Config.java
```
public class Config implements Parcelable
{
...
private Integer stopOnStillMinAccuracy = 100;
...
```
```
public void writeToParcel(Parcel out, int flags) {
...
out.writeInt(getStopOnStillMinAccuracy());
...
```
```
private Config(Parcel in) {
...
setStopOnStillMinAccuracy(in.readInt());
...
```
```
public Integer getStopOnStillMinAccuracy() {
    return stopOnStillMinAccuracy;
}

public void setStopOnStillMinAccuracy(Integer stopOnStillMinAccuracy) {
    this.stopOnStillMinAccuracy = stopOnStillMinAccuracy;
}
```
```
public String toString () {
...
.append(" stopOnStillMinAccuracy=").append(getStopOnStillMinAccuracy())
...
```
```
public static Config fromJSONObject (JSONObject jObject) throws JSONException {
...
config.setStopOnStillMinAccuracy(jObject.optInt("stopOnStillMinAccuracy", config.getStopOnStillMinAccuracy()));
...
```
```
public JSONObject toJSONObject() throws JSONException {
...
json.put("stopOnStillMinAccuracy", getStopOnStillMinAccuracy());
...
```

**Comment by mauron85** [comment]
ok, I roughly read your comment. It makes sense. And I will accept PR for this, but don't have time to implement it myself.

**Comment by apptum** [comment]
cool! PR #218 is out.
