### ISSUE TITLE
Intel XDK

### ISSUE THREAD

**Issue by egyprotech** [mauron85/cordova-plugin-background-geolocation#205]
The only version that works with intel XDK is 2.1.2 all the new version causes an error while building the app with intel xdk
The error says the plugin uses a gradle code

**Comment by mauron85** [comment]
Sorry I don't have resources to support XDK fully.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Comment by mauron85** [comment]
Closing as I cannot support intel xdk. The question still might get answered by others.
