### ISSUE TITLE
build fails on iOS in xCode with Parse issues on LocationManager.h

### ISSUE THREAD

**Issue by IamAdamJowett** [mauron85/cordova-plugin-background-geolocation#207]
## Your Environment

* Plugin version: 2.2.5
* Platform: iOS
* OS version: iOS 10.10.5
* Device manufacturer and model:
* Cordova version (`cordova -v`): 5.0.0
* Cordova platform version (`cordova platform ls`): ios
* Plugin configuration options: 
* Link to your project:

## Context
When compiling in xCode, the following Parse errors are thrown (all builds fine for Android). Apologies for the resolution of the image, I had to screenshot a remote desktop session.

![2016-11-16_0-53-01](https://cloud.githubusercontent.com/assets/294948/20310467/ccc01050-ab97-11e6-803f-901aac66e7c8.png)

## Expected Behavior
Build without Parse errors

## Actual Behavior
Parse errors thrown on build for iPhone 5 in xCode

## Steps to Reproduce

1. Install plugin 
2. Try to build for iPhone 5 in xCode

## Context
Trying to build for store submission

**Comment by mauron85** [comment]
You probably didn't setup Xcode properly. Is your app building with cordova cmd?

**Comment by IamAdamJowett** [comment]
You were right, it appeared to be a mis-configured xcode environment, unfortunately amongst the other things I was fixing I don't know which change solved this one.
