### ISSUE TITLE
ionic build iOS ERROR

### ISSUE THREAD

**Issue by iamsamuelfraga** [mauron85/cordova-plugin-background-geolocation#209]
I can't build my ionic 2 - angular 2 - typescript mobile aplication because when I try to generate de Xcode project, ionic build ios command returns me some errors on headers: 
`
'Cordova/CDVViewController.h' file not found
#import <Cordova/CDVViewController.h>
`

`
fatal error: 'Cordova/CDVViewController.h' file not found
#import <Cordova/CDVViewController.h>
`

`
fatal error: 'Cordova/CDV.h' file not found
#import <Cordova/CDV.h>
`

## Environment
* Plugin version: 2.2.5
* Platform: iOS
* OS version: 10.2
* Device manufacturer and model: iPhone 6s Plus
* Cordova version: 6.4.0
* Cordova platform version: 4.3.0

## Expected Behavior
Build success

## Actual Behavior
3 comands failed and Error: Error code 65 for command

**Comment by mauron85** [comment]
Anybody having this issue?

**Comment by gustavo-iniguez-goya** [comment]
Hi all,

Yes, I have also run into this problem (with ionic 1). But in my experience, removing and adding the platform again solves it.

The error code 65 also appears when xcode fails to link against libsqlite3.dylib:
https://stackoverflow.com/questions/31420166/libsqlite3-dylib-and-libz-dylib-missing-in-xcode-7-how-do-i-use-parse

**Comment by mauron85** [comment]
upgrade plugin version. Should be fixed in 2.3.5 or 3.x branch
