### ISSUE TITLE
 protected applications

### ISSUE THREAD

**Issue by frontendDuall** [mauron85/cordova-plugin-background-geolocation#210]
good morning

I am using the plugin and it works perfect, but I have a detail and is that in android 6.0 or higher the application needs a protected applications permission to prevent the process from killing in the background.

What can I do to install the application and be protected?

thank you very much

**Comment by klaus-donnert** [comment]
It seems to just work on my Android 6+ without being killed without me adding any code to set protected mode. I suspect that protected mode is built in.

**Comment by mauron85** [comment]
Not sure if i know, what is this about?
