### ISSUE TITLE
Post Json body

### ISSUE THREAD

**Issue by pareta2** [mauron85/cordova-plugin-background-geolocation#213]
I am building a post service in wcf......could you please tell me the Json body which this plugin sends on post so that i can design my parameters accordingly.

**Comment by RezaRahmati** [comment]
Yeah, it would be great if there were a sample json object which is post to server

**Comment by gchokeen** [comment]
Below one is the sample post data. you can test it using http://requestb.in/

`[{"provider":"network","time":1492603750557,"latitude":12.9253897,"longitude":77.6313731,"accuracy":25.075000762939453,"speed":0,"altitude":0,"bearing":0,"locationProvider":0}]
`

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
