### ISSUE TITLE
Question/Enhancement : Does the http post object include device info( ex. uuid ) ? 

### ISSUE THREAD

**Issue by uzumakinaruto123** [mauron85/cordova-plugin-background-geolocation#217]
What is the structure of http post object . that is sent to the server ? I went through the documentation , but it seems like it does not send anything except location details.

It would make sense if it sends device details like device model and device `uuid (universally unique identifier)`
. I am moving my logic from client ( i had my own async task with custom logic , so i don't know how does the object look like )  to server side , so sending only location object does not help.  I am sure people are using some sort of hacks to do so :p

Am i missing something ? Currently , any config parameter to post data like device info ? Thanks.

**Comment by kristfal** [comment]
The HTTP body is location data only. You can add your own HTTP headers, ex a `x-uuid-token` or any other token you'd like to identify your users with the `httpHeaders` options. Headers are set as keys and values on the `httpHeaders` object. Content type is automatically set to `application/json`.

**Comment by uzumakinaruto123** [comment]
Yeah ! I know , it can be passed in header. But , headers don't seem to be the right place to do so. Currently , I am using headers though. Passing as body parameter seems better.

**Comment by mauron85** [comment]
Another option is request url. In fact I'm using it for matching location with user in db.

**Comment by uzumakinaruto123** [comment]
Oh yes , I  never thought of that. I will try. can be closed.

**Comment by smchae** [comment]
@mauron85 Is it possible to change Content-Type? It seems that `httpHeaders: {'Content-Type': 'application/x-www-form-urlencoded'}` does not work.

**Comment by luigi37** [comment]
May I ask @smchae with which device type and iOS version? I noticed that ajax requests got problems since iOS 10.3.1 on REAL devices only...

**Comment by mauron85** [comment]
@smchae no content-type is hardcoded to json. Even if it would be possible to change content-type, body would be json string and not urlencoded.

https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/ios/CDVBackgroundGeolocation/Location.m#L218

**Comment by smchae** [comment]
@mauron85 Thank you!

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
