### ISSUE TITLE
Depricated API?

### ISSUE THREAD

**Issue by netomia** [mauron85/cordova-plugin-background-geolocation#219]
When I try to build my Cordova 6 app for Android with this plugin, I get this error:

"Note: Some input files use or override a deprecated API."

This happens only when I add this plugin.

My Android SDKs are all up to date.

Plugin version: 2.2.5
Platform: Android
OS version: 6
Device manufacturer / model: Several
Cordova version (cordova -v): 6.4.0
Cordova platform version (cordova platform ls): 6.0.0

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
