### ISSUE TITLE
Regular updates

### ISSUE THREAD

**Issue by scgrant327** [mauron85/cordova-plugin-background-geolocation#22]
Let's say I want to record the users location once every second...how can I do this with your plugin?

And, can we only record location while moving? Say the user is stationary for 5 seconds, then stop recording, but restart once they move...but have the move threshold be really low, like 1 meter?

--Sam

**Comment by mauron85** [comment]
On Android just use ANDROID_FUSED_LOCATION and set option.interval = 1000

>And, can we only record location while moving?
That is exactly what ANDROID_FUSED_LOCATION provider is doing. You can adjust ```option.activitiesInterval```. However it's in seconds not in meters.

**Comment by scgrant327** [comment]
What about on iOS?

**Comment by mauron85** [comment]
On iOS there is only original christocracy's distance filter implementation. And currently I don't have free resources to do serious iOS development (ps. PRs are very welcome :-)

Also check christocracy's free iOS only cordova-background-geolocation-lt https://github.com/transistorsoft/cordova-background-geolocation-lt or his premium version http://shop.transistorsoft.com/pages/cordova-background-geolocation-premium

**Comment by mauron85** [comment]
Did you try option.stationaryRadius?
