### ISSUE TITLE
pulign not working when iOS app is killed?

### ISSUE THREAD

**Issue by ShahnawazAli93** [mauron85/cordova-plugin-background-geolocation#220]
## Your Environment
iOS
* Plugin version:
* Platform: iOS
* OS version: latest

## Context
pulign still works when android app is killed (due to background service) but not working when iOS app is killed? no background service when iOS app is killed.

Is this feature not available with this plugin?

**Comment by marvi14** [comment]
I'm having the same issue...my console throw this

LocationManager#flushQueue has to kill an out-standing background-task!

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
