### ISSUE TITLE
phone permission being added on Android

### ISSUE THREAD

**Issue by Shane98c** [mauron85/cordova-plugin-background-geolocation#221]
Phone permission being added on Android as `READ_PHONE_STATE`.  The same behavior described below is happening with the 'storage' permission.  

## Your Environment

* Plugin version: 2.2.5
* Platform: Android
* OS version: 7.1.1
* Device manufacturer and model: nexus 6p
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`): 6.0.0

## Context
The plugin is requesting 'phone' permission on android.  It shows up in AndroidManifest.xml as `read_phone_state` and is added each time during building no matter my edits to plugin.xml or other areas that I can see referencing permissions.  The problem goes away upon removing this plugin, so it must be somehow caused by it.  

I'm on windows and my coworkers do not experience the same issue on their Mac with the same plugin/repo/etc.  This makes literally no sense to me so other explanations are welcome!

## Expected Behavior
This should not request phone permissions, or at least should be configurable to not request them.  This does not happen after running `cordova plugin rm cordova-plugin-background-geolocation`

## Actual Behavior
Requested phone permission. 

## Reproduce 
1.  Install plugin, build android.  Phone permission requested
2. remove plugin, build android.  phone permission not requested.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
