### ISSUE TITLE
Execution failed for task ':processDebugGoogleServices'.

### ISSUE THREAD

**Issue by Shakti-Sharma** [mauron85/cordova-plugin-background-geolocation#222]
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.2.0.

* Plugin version: cordova-plugin-mauron85-background-geolocation 2.2.5 "CDVBackgroundGeolocation"
* Platform: issue is generated in  Android build, but i also want to build for ios.
* OS version: OS X -10.11.6 Mac
* Device manufacturer and model:
* Cordova version (`cordova -v`):  6.3.1
* Cordova platform version (`cordova platform ls`): android and ios
* Plugin configuration options: 
* Link to your project:

## Steps to Reproduce

1. add your plugin
2. generate the build in ionic 1 using terminal following are the output.

## Context

I am not able to generate the build

## Debug logs

Following are the crash logs of the android

UP-TO-DATE
:processDebugGoogleServices

Found com.google.android.gms:play-services-location:+, but version 9.2.0 is needed for the google-services plugin.

:processDebugGoogleServices 
FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 9.2.0.

* Try:
Run with --stacktrace option to get the stack trace. Run with 
--info or --debug option to get more log output.

BUILD FAILED

Total time: 10.321 secs

####################################################
Following are the crash logs for the ios in the terminal 

2016-12-08 12:15:32.781 xcodebuild[1300:35514] CoreSimulator is attempting to unload a stale CoreSimulatorService job.  Detected Xcode.app relocation or CoreSimulatorService version change.  Framework path (/Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework) and version (209.19) does not match existing job path (/Applications/Xcode 2.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc/Contents/MacOS/com.apple.CoreSimulator.CoreSimulatorService) and version (303.8).

2016-12-08 12:15:33.045 xcodebuild[1300:35514] Failed to locate a valid instance of CoreSimulatorService in the bootstrap.  Adding it now.

2016-12-08 12:15:33.058 xcodebuild[1300:35514] *** Assertion failure in -[SimServiceContext reloadServiceIfMovedOrAbortIfWeAreInvalid], /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreSimulator/CoreSimulator-209.19/CoreSimulator/SimServiceContext.m:536

** INTERNAL ERROR: Uncaught exception **

Uncaught Exception: The loaded com.apple.CoreSimulator.CoreSimulatorService job does not match our expectations: pathOfLoadedJob: /Applications/Xcode 2.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc/Contents/MacOS/com.apple.CoreSimulator.CoreSimulatorService, our frameworkPath: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework
Stack:

  0   __exceptionPreprocess (in CoreFoundation)
  1   objc_exception_throw (in libobjc.A.dylib)
  2   +[NSException raise:format:arguments:] (in CoreFoundation)
  3   -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] (in Foundation)
  4   -[SimServiceContext reloadServiceIfMovedOrAbortIfWeAreInvalid] (in CoreSimulator)
  5   -[SimServiceContext connect] (in CoreSimulator)
  6   -[SimServiceContext initWithDeveloperDir:connectionType:] (in CoreSimulator)
  7   __63+[SimServiceContext sharedServiceContextForDeveloperDir:error:]_block_invoke_2 (in CoreSimulator)
  8   _dispatch_client_callout (in libdispatch.dylib)
  9   _dispatch_barrier_sync_f_invoke (in libdispatch.dylib)
 10   +[SimServiceContext sharedServiceContextForDeveloperDir:error:] (in CoreSimulator)
 11   __60+[SimServiceContext(DVTAdditions) dvt_sharedServiceContext:]_block_invoke (in DVTiPhoneSimulatorRemoteClient)
 12   _dispatch_client_callout (in libdispatch.dylib)
 13   dispatch_once_f (in libdispatch.dylib)
 14   +[SimServiceContext(DVTAdditions) dvt_sharedServiceContext:] (in DVTiPhoneSimulatorRemoteClient)
 15   __42-[DVTiPhoneSimulatorLocator startLocating]_block_invoke (in IDEiOSSupportCore)
 16   __DVTDispatchAsync_block_invoke (in DVTFoundation)
 17   _dispatch_call_block_and_release (in libdispatch.dylib)
 18   _dispatch_client_callout (in libdispatch.dylib)
 19   _dispatch_root_queue_drain (in libdispatch.dylib)
 20   _dispatch_worker_thread3 (in libdispatch.dylib)
 21   _pthread_wqthread (in libsystem_pthread.dylib)
 22   start_wqthread (in libsystem_pthread.dylib)

How do i change the version  from as reported below again.

Found com.google.android.gms:play-services-location:+, but version 9.2.0 is needed for the google-services plugin.

Solution i found is not so good but by strictily going to the android platform folder and change the 

From
play-services-location:+  

play-services-location:9.2.0 

But that manual solution is not the proper and actual solution for it.
Kindly please help.
Regard
Shakti

**Comment by Shakti-Sharma** [comment]
Ohh !!!!


I finally found solution for it in Ionic platform.


Here is the link which provide me the solution for it.

https://github.com/fechanique/cordova-plugin-fcm/issues/90



Actually i want to change google play service location From
play-services-location:+

play-services-location:9.2.0

in the gradel file but gradle will updated on run the ionic build command.

To fix it permanently.
Go to your Ionic project -> Platforms -> android ->project.properties

open the file change the version  like below

from 
cordova.system.library.5=com.google.android.gms:play-services-location:+

to
cordova.system.library.5=com.google.android.gms:play-services-location:9.2.0

So on building code in the terminal will not over ride version.
If you guyes have any other option to work this out.
Kindly update us.

Regard
Shakti

**Comment by EightSQ** [comment]
@Shakti-Sharma 's solution results in another bug for me.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/common/internal/zzab;

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
