### ISSUE TITLE
Option to hide syncing notification status

### ISSUE THREAD

**Issue by nabinkumarn** [mauron85/cordova-plugin-background-geolocation#223]
@mauron85  Is there any way I can hide the notification showing syncing location and syncing failed message.

**Comment by mauron85** [comment]
Sorry currently no. You'll need to fork project and edit source code. It should be easy.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
