### ISSUE TITLE
is it possible to set the condition?

### ISSUE THREAD

**Issue by AI111** [mauron85/cordova-plugin-background-geolocation#224]
is it possible to establish the location and radius where the plugin will not send data

**Comment by apptum** [comment]
So you want only the position (with accuracy)? If I understand you correct: yes! Just ignore these `.config` settings:
```
backgroundGeolocationOptions = {
      //pauseLocationUpdates: true, //Pauses location updates when app is paused (default: true),
      // Android & iOS HTTP locations posting,
      //url: 'http://192.168.81.15:3000/locations',
      //httpHeaders: { 'X-FOO': 'bar' },
      //maxLocations: 1000 //Limit maximum number of locations stored into db (default: 10000)
}
```

**Comment by AI111** [comment]
I mean that i need to define a point on the map (for example, my house) and the radius. In this round plugin should not send the coordinates to the server.

**Comment by konstantinkrassmann** [comment]
The feature, your are lookiing for is geofencing. No the plugin doens't provide this.

You can do it by yourself. Pick up the geofences from your server (houseposition + radius) and check, if the delivered coordinate is within the radius.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
