### ISSUE TITLE
Record Geo Data Locally?

### ISSUE THREAD

**Issue by Ethan-Hooker** [mauron85/cordova-plugin-background-geolocation#226]
## Your Environment

* Plugin version:2.2.0
* Platform: iOS
* OS version: 10.2
* Device manufacturer and model: iPhone 5s
* Cordova version (`cordova -v`): 6.3.1
* Cordova platform version (`cordova platform ls`): 4.3.1
* Plugin configuration options: 
    backgroundGeolocation.configure(callbackFn, failureFn, {
        stationaryRadius: 0,
        distanceFilter: 0,
        desiredAccuracy: 0,
        debug: true,
        notificationTitle: 'Background tracking',
        notificationText: 'enabled',
        notificationIconColor: '#FEDD1E',
        notificationIconLarge: 'mappointer_large',
        notificationIconSmall: 'mappointer_small',
        //locationProvider: 0,//backgroundGeolocation.provider.ANDROID_DISTANCE_FILTER_PROVIDER,
        interval: 10,
        fastestInterval: 5,
        activitiesInterval: 10,
        stopOnTerminate: true,
        startOnBoot: false,
        startForeground: true,
        stopOnStillActivity: true,
        activityType: 'AutomotiveNavigation',
        syncThreshold: 100,
        url: "http://10.0.20.103:3000", // My local server for testing
        httpHeaders: {
          'X-FOO': 'bar'
        },
        pauseLocationUpdates: false,
        saveBatteryOnBackground: false,
        maxLocations: 100
    });

* Link to your project:

## Context
When sleeping the app or locking the screen, it will not fire the callbackFn. It will display a notification saying "Monitoring Region". However after driving around for awhile it never leaves this state. 

The ideal scenario would be to store this data in the apps local session storage, then send it when POSTing the rest of the data (Other form inputs).

Android is firing the function, so it is storing it in local storage just perfectly.

## Expected Behavior
On a new location it will fire the callbackFn which will store the data in local session storage 

## Actual Behavior
callbackFn is never executed

## Possible Fix
Another way around which I tried looking through the doco for was to get the data out of the local db for the plugin.  I see you say its stored in a local db but I couldn't find anywhere on how to access it.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
