### ISSUE TITLE
No resource found that matches the given name (at 'smallIcon' with value '@mipmap/icon')

### ISSUE THREAD

**Issue by abunour22** [mauron85/cordova-plugin-background-geolocation#227]
## Your Environment
* Plugin version: Latest
* Platform: Android
* Cordova version (`cordova -v`): Cordova android v6.1.0

## Context
I'm using cocoon compiler and installed all plugins successfully, but when i trying to build my app after adding your plugin its fails.

## Expected Behavior
Build successfully 

## Actual Behavior
Build failed

## Debug logs
:processArmv7ReleaseManifest
:processArmv7ReleaseResources/workspace/platforms/android/res/xml/authenticator.xml:5:19-31 : AAPT: No resource found that matches the given name (at 'icon' with value '@mipmap/icon').

/workspace/platforms/android/res/xml/authenticator.xml:6:24-36 : AAPT: No resource found that matches the given name (at 'smallIcon' with value '@mipmap/icon').

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processArmv7ReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/opt/cocoon_compiler/workspace/production/data/sdks/android-sdks-linux/build-tools/25.0.0/aapt'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
 FAILED

BUILD FAILED

Total time: 26.58 secs

**Comment by aamir1995** [comment]
getting same error :(

**Comment by aamir1995** [comment]
Nevermind solved it by https://github.com/mauron85/cordova-plugin-background-geolocation/issues/206 :)

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
