### ISSUE TITLE
option to check background service is running or not

### ISSUE THREAD

**Issue by gchokeen** [mauron85/cordova-plugin-background-geolocation#228]
Hi,

When background service started (BackgroundGeolocation.start()). I am showing  the button in UI, which says. background is running do you wanna stop it?

Is there any status options which tells background is enabled or stopped ?

```
if( BackgroundGeolocation.status()){
//enabled
}
else{
//disabled
}
```

After killing app and re opening the app. I am getting service is enabled or disbaled. Let me know please?

**Comment by mauron85** [comment]
Currently no. You have to track status yourself. However I agree, it's kind of bummer, when you use `stopOnTerminate: false`. I've working implementation of checkStatus in react-native version of this plugin.

https://github.com/mauron85/react-native-background-geolocation/blob/android/android/lib/src/main/java/com/marianhello/bgloc/LocationService.java#L508

**Comment by gchokeen** [comment]
Can you add this feature in this plugin too?

**Comment by shyamal890** [comment]
+1

**Comment by gchokeen** [comment]
Anyone update on this ticket, This is very useful feature

**Comment by jackdaniel9** [comment]
+1

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Comment by shyamal890** [comment]
Can you please reopen this issue

**Comment by mauron85** [comment]
This is already implemented in v3 - method checkStatus. No need to reopen.

**Comment by leandroz** [comment]
@mauron85 checkStatus returns isRunning as false if you terminate the application.

**Comment by mauron85** [comment]
@leandroz I guess you mean on iOS. I already answered you in another issue.
