### ISSUE TITLE
accuracy issues with points

### ISSUE THREAD

**Issue by culland** [mauron85/cordova-plugin-background-geolocation#229]
Not necessarily an issue, but wanted to see if other folks are experiencing this kind of thing. May app uses the standard geolocation tools with Phonegap as well as this plugin for the background geolocations.  Everything is working reasonably well on android/iphone, except I have these random points with terrible accuracy, 20km+ out.

Is this normal? Is there something I can do with the settings to limit this?  My initial thought it to use location.accuracy to discard any bad points, but wanted to see if this is an issue I have with my setup overall.  Thanks!

## Your Environment

* Plugin version: most recent
* Platform: iOS or Android
* OS version: varies
* Phonegap Build 5.2

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
