### ISSUE TITLE
navigator.geolocation vs Fused Location ?

### ISSUE THREAD

**Issue by Gp2mv3** [mauron85/cordova-plugin-background-geolocation#23]
Hi,
I'm currently switching from navigator.geolocation.watchPosition() to this plugin. But I'm noticing a very big difference in accuracy. 
With the plugin, I've an accuracy of approximately 2km and with watchPosition I've something really close of my actual position. I notice this difference inside of my house so I presume the navigator.geolocation.watchPosition() uses my Wifi and the plugin tries to use the Cell tower.

My question is: What's the actual difference between the two implementations ? I thought the navigator uses the Fused provider ?
Is there a list of parameters I can use to refine the location given by the Fused Provider ?

Thanks !

PS: Google Maps also seems to locate me really fine.

**Comment by mauron85** [comment]
Try to set option.desiredAccuracy = 10. 

```
My question is: What's the actual difference between the two implementations ? I thought the navigator uses the Fused provider ?
```
With navigator, you can only set enableHighAccuracy: true. With this plugin you can control accuracy with option.desiredAccuracy and also interval of detection (options interval and fastInterval). See docs.
Also Fused provider uses activity recognition, so when device is still, location detection is off (saving battery).

**Comment by mahmed-ntd** [comment]
i was wondering that if i can use  enableHighAccuracy: true?

i tried to use but no luck can you help me?

**Comment by mauron85** [comment]
@mahmed-ntd this plugin has no such a option as enableHighAccuracy. Instead you specify desired accuracy with option ***desiredAccuracy***

From docs
>
desiredAccuracy:
Desired accuracy in meters. Possible values [0, 10, 100, 1000]. The lower the number, the more power devoted to GeoLocation resulting in higher accuracy readings. 1000 results in lowest power drain and least accurate readings

**Comment by Gp2mv3** [comment]
I found a plausible explanation for the difference: By default the first source used for the geolocation is the cell tower. 

If I don't unlock my SIM card, the phone only relies on Wifi and thus is a lot more accurate (the plugin in Fused mode is comparable with navigator.geolocation). If the SIM card is present however, the plugin seems to rely more on the cell tower than the navigator.

Finally, after some time (maybe 10 minutes), the plugin also uses the Wifi. So it can be traited as a side effect when the plugin is started.
