### ISSUE TITLE
background tracking not working

### ISSUE THREAD

**Issue by guestisp** [mauron85/cordova-plugin-background-geolocation#230]
i'm trying to use the background tracking.
I don't have any errors, but the javascript callback is not called (probably this is normale when app is in background) but also the http post request is not called.

i've configured it like this:
```
window.backgroundGeolocation.configure(
   watchPositionSuccessCallback,
   watchPositionErrorCallback,
   {
       desiredAccuracy: 0,
       interval: 10,
       activityType: 'AutomotiveNavigation',

       notificationTitle: 'My App',
       notificationText: 'My Text',

       url: api_domain+'/orders/'+order_uuid+'/route',
       httpHeaders: {
           'Authorization': sessionStorage.getItem('http_auth')
       },

       pauseLocationUpdates: false,
   }
);
$scope.startBackgroundGeolocation();
```

at least I should receive an HTTP POST on my server, but this doesn't happen.

**Comment by marvi14** [comment]
are you doing somewhere window.backgroundGeolocation.start()?

**Comment by guestisp** [comment]
Yes, inside `$scope.startBackgroundGeolocation()`

geolocation works for a couple of seconds immediatly after starting it up, then it stop but I can see a very small and light pointer icon in notification bar

Seems that I have to move for many chilometers or many many many minutes before it start to track.
The app that i'm developing needs a very fast position tracking and this is no good.

**Comment by guestisp** [comment]
I have the same issue with both , javascript callback and native http POST request.

Both stop to work at the same time.

**Comment by guestisp** [comment]
bump

**Comment by guestisp** [comment]
Bump

**Comment by thorvx** [comment]
same issue

backgroundGeolocation.configure(callbackFn, failureFn, {
                desiredAccuracy: 10,
                stationaryRadius: 1, //1 for test
                distanceFilter: 1, //1 for test
                interval: 30000,
                notificationTitle: 'Title',
                notificationText: 'Background Service',
                stopOnTerminate: false,
                pauseLocationUpdates: false,
                ...
            });

**Comment by guestisp** [comment]
Yes, this plugin is unusable.

**Comment by aliexalter** [comment]
@guestisp The function you are trying to achieve can be done by calling changePace inside your callback function like this
var callbackFn = function(location, taskId)
{
//store location
....
setTimeout(function() {
              bgGeo.changePace(true);
            }, 60000); // I call it after 1 minute because it take 10 second to satire my data on 4G so i give it some time before another call sometime it calls twice but it will keep background geolocation on all time.

setTimeout(function() {
            bgGeo.finish(taskId); // <-- execute #finish when your work in callbackFn is complete
          }, 20000);
}

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
