### ISSUE TITLE
showLocationSettings() fails to open settings in iOS 10.2

### ISSUE THREAD

**Issue by coderroggie** [mauron85/cordova-plugin-background-geolocation#231]
## Your Environment

* Plugin version: 2.2.5
* Platform: iOS, Android works
* OS version: 10.2
* Device manufacturer and model: Apple iPhone 6s Plus
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`):
  android 6.1.0
  ios 4.3.1
* Plugin configuration options: 
```
backgroundGeolocation.configure(postLocationCallback, failureCallback, {
                    desiredAccuracy: 10,
                    stationaryRadius: 20,
                    distanceFilter: 30,
                    interval: 60000
                });
```
* Link to your project:
N/A

## Context

backgroundGeolocation.showLocationSettings() does nothing on iOS.
backgroundGeolocation.showAppSettings() works properly.

## Expected Behavior

backgroundGeolocation.showLocationSettings() should open the Settings > Privacy > Location Services Preferences panel, similar to how it opens in Android.

## Actual Behavior

Nothing.  App Settings are not opened.

## Steps to Reproduce

1.  Open my App. 
2.  Hit the following code section in my app.
```
backgroundGeolocation.isLocationEnabled(function (enabled) {
                    if (enabled) {
                            $log.info('backgroundLocationService: Location is enabled, success with collection.');
                    } else {
                        // Location services are disabled
                        if (window.confirm('Location is disabled. Would you like to open location settings?')) {
                            backgroundGeolocation.showLocationSettings();
                        }
                    }
                });
```
3.  Nothing happens.
4.  Sadness ensues. 

## Context

I've become sad.

## Debug logs

None.  There is no output in the iOS logging nor in the console as a result of this call, only undefined.

**Comment by mauron85** [comment]
Yes, I stopped worked since iOS v10. There is nothing I can do about it.

**Comment by coderroggie** [comment]
@mauron85 My workaround is to just use the ```backgroundGeolocation.showAppSettings()``` call instead on iOS, that seems to give you access to what you need.  Maybe we could just update the docs?

**Comment by coderroggie** [comment]
https://github.com/mauron85/cordova-plugin-background-geolocation/pull/232

**Comment by mauron85** [comment]
merged. thank you
