### ISSUE TITLE
Build 2.2.5 fails on PhoneGap build (v2.1.2 built ok)

### ISSUE THREAD

**Issue by blukis** [mauron85/cordova-plugin-background-geolocation#233]
## Your Environment
* Plugin version: 2.2.5
* Platform: Android

## Context
Android build fails in PhoneGap build.  (iOS version builds ok.)  Using:
	`<plugin name="cordova-plugin-mauron85-background-geolocation" version="2.2.5"/>`
Older version built ok*:
	`<plugin name="cordova-plugin-mauron85-background-geolocation" version="2.1.2"/>`
*UPDATE (actually, 2.1.2 doesn't build either with latest version of phonegap build (cli-6.3.0), but 2.1.2 worked on the last PG-build version I was using when I last built.  i.e. the following builds (and functions) ok:
	`<preference name="phonegap-version" value="cli-5.2.0" />`
	`<plugin name="cordova-plugin-mauron85-background-geolocation" version="2.1.2"/>`
UPDATE 2: I'm seeing various notes in the readme, this might be because of a missing icon I need to place in locales/android/drawable somewhere, but I'm unclear what files I need to add, per PhoneGap build instruction in readme.  Trying a few variations - haven't found one that works yet...

## Steps to Reproduce
Build log file attached.  I can include a config.xml that fails if needed.

## Debug logs
Build log file attached.
[build2.txt](https://github.com/mauron85/cordova-plugin-background-geolocation/files/676433/build2.txt)

**Comment by barrylachapelle** [comment]
+1

**Comment by klaus-donnert** [comment]
I get ios to build with cli-6.3.0 - cli-6.4.0 has another ios issue not related to this plugin
I get Android to build with cli-6.4.0

**Comment by mauron85** [comment]
Seems like duplicate of https://github.com/mauron85/cordova-plugin-background-geolocation/issues/206. There is suggestion to use latest cli as @klaus-donnert is suggesting. Also you can safely use 2.2.4, there is no benefit to use 2.2.5.

**Comment by blukis** [comment]
2.2.5/cli-6.4.0 did not build for me (same issue in the attached log above), but 2.2.4/cli-6.3.0 looks like it's building OK.  Thanks for your help.
