### ISSUE TITLE
Android permission GET_ACCOUNTS required?

### ISSUE THREAD

**Issue by blukis** [mauron85/cordova-plugin-background-geolocation#234]
## Your Environment
* Plugin version: 2.2.4
* Platform: Android

## Context
I'm upgrading geolocation plugin version in my Android app from 2.1.2 to 2.2.4.  App upgrade/install in Android requires a new permission that user must accept, "find accounts on the device".  I believe this is related to the following in plugin.xml
`<uses-permission android:name="android.permission.GET_ACCOUNTS" />`

I'm wondering, is this necessary for current plugin functionality?  This added permission might be surprising to my users (who are probably cautious about sharing their location, particularly when paired with their personal info like their accounts).  I fear it might be too surprising for my particular use-case.  Is it possible to remove permission requirement from the plugin?

**Comment by mauron85** [comment]
Sure, it's needed for background sync. Not sure why android team decided this will be the good idea. For latest android it should not be displayed in list of required permissions, but for older android it will. Anyhow I agree with you and in the future I would like to remove that permission. Background sync when app is not launched will not be possible, but who needs this anyway?

**Comment by blukis** [comment]
OK, if I understand correctly, I don't use background sync (I'm posting to server in JS callback function).  I removed the permission request with the following (works in PhoneGap build):
`<config-file platform="android" parent="/manifest" mode="delete">
	<uses-permission android:name="android.permission.GET_ACCOUNTS" />
</config-file>`

If background-sync isn't used (i.e. url & syncUrl parameters are not used in configure() call), this should have no obvious ill effects?  I can confirm it builds & installs, but haven't tested app much.  Thanks!
