### ISSUE TITLE
Add a cordova plugin variable to automatically set NSLocationAlwaysUsageDescription value in the Info.plist 

### ISSUE THREAD

**Issue by anymos** [mauron85/cordova-plugin-background-geolocation#235]
## Your Environment

* Plugin version: 2.2.4
* Platform: iOS
* OS version: 8 and more 
* Device manufacturer and model: iphone
* Cordova version (`cordova -v`): not relevant
* Cordova platform version (`cordova platform ls`):not relevant
* Plugin configuration options: not relevant
* Link to your project:not relevant

## Context

Apple has been rejecting the application for the following reason 

Your app uses background location services but does not clarify the purpose of its use in the location modal alert as required in the iOS Human Interface Guidelines.

We've attached screenshot(s) for your reference.

Next Steps

Please revise the NSLocationAlwaysUsageDescription value in the Info.plist to specify the intended purpose of using the user's location while the app is in the background.

Resources

For additional information and instructions on configuring and presenting an alert, see the Requesting Permission section of the iOS Human Interface Guidelines and the Information Property List Key Reference.

![image](https://cloud.githubusercontent.com/assets/7828003/21558750/b36d05ac-ce71-11e6-8f0e-e92451fc78f0.png)

How to fix the issue by modifying the info.plist manually : http://matthewfecher.com/app-developement/getting-gps-location-using-core-location-in-ios-8-vs-ios-7/

## Expected Behavior
To have apple accepting the app :)
More seriously, to have the possibility to set the message, ideally dynamically (probably not possible), or using cordova variable in a similar fashion than the cordova-plug-camera :
https://github.com/apache/cordova-plugin-camera#ios-quirks 

as per 

> cordova plugin add cordova-plugin-camera --variable CAMERA_USAGE_DESCRIPTION="My App would like to access your camera, to take photos of your documents."

## Actual Behavior
The msg is not correct from Apple testing perspective

## Possible Fix
Use a similar method than for cordova-plugin-camera  to add a variable to set this message and avoid the manual step of modifying the plist outside of the plugin

## Steps to Reproduce
Submit and app to Apple without the msg :-)
More seriously, run on a ios device virgin of any same version of the app to trigger the message.

## Context
Trying to get Apple approval 

## Debug logs
Not relevant

## Others

Thank you so much in advance fro your help on that matter :-)

**Comment by mauron85** [comment]
This plugin have it too. However it's currently only in git. Checkout https://github.com/mauron85/cordova-plugin-background-geolocation/issues/206 for more info.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
