### ISSUE TITLE
Plugin crashing onResume Android

### ISSUE THREAD

**Issue by andrewbriggs** [mauron85/cordova-plugin-background-geolocation#236]
Using PhoneGap Build. When I open the app the first time, it works fine. When I minimize the app and then reopen it, it that's when it crashes.

		<preference name="phonegap-version" value="cli-6.3.0" />
		<preference name="orientation" value="default" />
		<preference name="fullscreen" value="false" />
		<preference name="target-device" value="handset" />
		<preference name="webviewbounce" value="false" />
		<preference name="prerendered-icon" value="true" />
		<preference name="stay-in-webview" value="true" />
		<preference name="ios-statusbarstyle" value="default" />
		<preference name="detect-data-types" value="true" />
		<preference name="exit-on-suspend" value="true" />
		<preference name="show-splash-screen-spinner" value="false" />
		<preference name="ShowSplashScreenSpinner" value="false" />
		<preference name="auto-hide-splash-screen" value="false" />
		<preference name="EnableViewportScale" value="true" />
		<preference name="MediaPlaybackRequiresUserAction" value="false" />
		<preference name="AllowInlineMediaPlayback" value="false" />
		<preference name="BackupWebStorage" value="local" />
		<preference name="TopActivityIndicator" value="gray" />
		<preference name="KeyboardDisplayRequiresUserAction" value="false" />
		<preference name="HideKeyboardFormAccessoryBar" value="false" />
		<preference name="SuppressesIncrementalRendering" value="false" />
		<preference name="android-minSdkVersion" value="18" />
		<preference name="android-targetSdkVersion" value="23" />
		<preference name="android-installLocation" value="auto" />
		<preference name="android-windowSoftInputMode" value="stateHidden|adjustPan" />
		<preference name="SplashScreenDelay" value="5000" />
		<preference name="FadeSplashScreen" value="false" />
		<preference name="ErrorUrl" value=""/>
		<preference name="BackgroundColor" value="0xffffffff"/>
		<preference name="KeepRunning" value="true" />
		<preference name="DisallowOverscroll" value="false"/>
		
 		<preference name="LoadUrlTimeoutValue" value="20000" />
		<preference name="disable-cursor" value="false" />
		<preference name="AndroidLaunchMode" value="singleTask" />

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
