### ISSUE TITLE
How to hide Notification Bar?

### ISSUE THREAD

**Issue by RezaRahmati** [mauron85/cordova-plugin-background-geolocation#238]
Hi

Thanks for great plugin, 

I know that notification bar is for keeping app alive and reporting the location, but it will have negative effect on user minds, for example if I myself install an app and 24*7 I see it on notification bar I will uninstall the app, 

I was wondering if is there any option to hide the Notification bar (maybe with accepting the risk of loosing some location data)?

**Comment by nishantpant** [comment]
The red notification bar only shows when you turn debug on. If you are talking about the blue bar which briefly shows "XXX is using your location" when you close your app, there is no way around that.

**Comment by konstantinkrassmann** [comment]
From what i can see in the code LocationService.java: 238, it will automatically start if in background mode and can't be disabled.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
