### ISSUE TITLE
Ios Battery consumption is insane

### ISSUE THREAD

**Issue by umarriaz9018** [mauron85/cordova-plugin-background-geolocation#239]
## Your Environment

* Plugin version:
* Platform: iOS 
* OS version:10.1
* Device manufacturer and model: Iphone
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by umarriaz9018** [comment]
I am using this plugin for my Ios App and its battery consumption is very bad, It is consuming 98% of battery in Iphone which is impossible to deploy, anyone please help configuring this plugin to consume battery efficiently. Thanks

**Comment by gustavo-iniguez-goya** [comment]
Hi umarriaz9018,

What config values are you using? A user has also reported me this, but in my case I'm requesting locations every 5s or less (besides other network operations), so I guess it's normal. In any case I'll investigate it further, at least to try to minimize the impact on iOS if such is the case.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
