### ISSUE TITLE
Background App did not killed

### ISSUE THREAD

**Issue by freezyfridge** [mauron85/cordova-plugin-background-geolocation#24]
Hi, 

I am testing this plugin using the SampleApp. I am trying to kill/stop the app(by swipe away the app from the running list ,in android samsung S5). I noticed that the older version of the plugin  version="0.7.3" is able to kill the app through this action but the newer version version="0.8.1" is not able to kill. Can help to verify if this is the bug in the newer or there's something i am missing? Thank you.

**Comment by Gp2mv3** [comment]
Hi,
Do you have stopOnTerminate: true ?
Otherwise the plugin will keep the service running I think.

**Comment by freezyfridge** [comment]
Hi, 

Thanks for reply. Ya, tested the stopOnTerminate: true, it seems like is working ;) Thank you!

**Comment by mauron85** [comment]
@Gp2mv3 already answered this one. 
Not terminate on swipe away was the most requested feature.
