### ISSUE TITLE
start() needs parameters in readme.md

### ISSUE THREAD

**Issue by blukis** [mauron85/cordova-plugin-background-geolocation#241]
I got hung up for a while time trying to debug an issue.  It turned out my iOS device was blocking location service in system settings, and I wasn't handling properly, because I didn't realize start() took parameters.

I think "start()" heading in README.md should read "start(success, fail)".

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
