### ISSUE TITLE
Null time in http post

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#243]
Null time in response

## Your Environment
* Plugin version:
* Platform: Android
* OS version: 4.1.2
* Device manufacturer and model: Samsung GT-I8552
* Cordova version (`cordova -v`): 
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project: https://play.google.com/store/apps/details?id=com.smarttask.app&hl=en

## Context
The response data in post has nulled time. I wonder why that is happening.

## Expected Behavior
Nulled time should not be sent to server.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
