### ISSUE TITLE
Posting location service onChange 

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#244]
Currently watchLocationMode(success, fail) is only available when the app is in background or active. However, can this implementation be taken into the service and a http call be made when there is change in settings?

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
