### ISSUE TITLE
How to add button in the notification bar

### ISSUE THREAD

**Issue by gchokeen** [mauron85/cordova-plugin-background-geolocation#245]
Hi,

When we use uber app, we getting notification bar with buttons. I want similar buttons. When background location enabled we getting notification bar. I want to add there "stop tracking" button. How can I do that.

#228 - Since this plugin in not giving option for checking status of tracking. these buttons will be very useful.

![uber-notification](https://cloud.githubusercontent.com/assets/1717379/21708496/58c4bc74-d3ff-11e6-9278-6931cca361db.jpg)

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Comment by marcoandreac** [comment]
> Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

are you sure it's already fixed? I can not find anything in the documentation about button notification
