### ISSUE TITLE
Handing BadRequest:400 response from server

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#246]
The app is in production and is failing to post locations through the url. I am getting `sync failed due server error`.

I did adb log into the main app and got this info `reason: 10119  SyncResult: stats [ numIoExceptions: 1]`

On adb logging into com.marianhello.bgloc.LocationService. I am getting this result:

**When a new location is added** - `error: database is locked (code 5)`

**Posting json to url**: 
`https://api.smarttask.io/api/Location/AddMauron85Locations/e2af17c3edb51253/Mi 4i headers: {Authorization=Bearer GfRwkLPixDDAPmQBCO...}
W/com.marianhello.bgloc.LocationService( 5389): Server error while posting locations responseCode: 400
`
The service should reply with response info too. We would be able to know where exactly the error occurs.

Also, what happens when say the location result has an invalid data. The ModelState check fails on server and the server responds with `BadRequest:400`. As per plugin's design I guess those locations with error are still persisted and when they are again sent to the server - `BadRequest:400`. Bad data stays in the mobile forever. We need a better way to handle this issue.

Currently am sending 200(OK) even on error, so that the service would remove bad data from storage.

Model setup in C#
```
public class Mauron85Location
    {
        public Nullable<long> locationId { get; set; }
        public string provider { get; set; }
        public string locationProvider { get; set; }
        public bool debug { get; set; }
        public Nullable<double> time { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<decimal> accuracy { get; set; }
        public Nullable<decimal> speed { get; set; }
        public Nullable<decimal> altitude { get; set; }
        public Nullable<decimal> bearing { get; set; }
    }
```

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Comment by shyamal890** [comment]
Can you please reopen this issue.
