### ISSUE TITLE
How can i use server with php code?

### ISSUE THREAD

**Issue by diogo-palma** [mauron85/cordova-plugin-background-geolocation#247]
## Your Environment

* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

## Possible Fix

**Ok, problem solved**

If anyone have a some question like this follow this steps:

## Steps to Reproduce

1. _upload  any php file to a server like 'http://www.yourserver.com/server.php'_

2. _then put the post of app in some variable_ 
example:
$value = json_decode(file_get_contents('php://input'));

3. _the post of app is json format, so you can put this on in another variable_
example:
$array = (array) $value ;

4. _to se this values, upload a blank value1.text  to server and put this code:_
file_put_contents('value1.txt', var_export($array[0]->latitude, TRUE));

**Now open value1.txt and you will see the values of latitude while the app run in the background
If you want to see all of json use this code:

file_put_contents('value1.txt', var_export($value, TRUE));
after this show all tags for usage on $array[0]->, something like 'latitude', 'longitude', 'time', ...**

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
