### ISSUE TITLE
[Android] Plugin working without google play services on device?

### ISSUE THREAD

**Issue by coredinate** [mauron85/cordova-plugin-background-geolocation#249]
Hello, 

We are developing an app for our customers outside of playstore, because having them to login every single device is a drawback. 

1.Is the plugin able to work without google play services even if they are installed on the device ?

**Comment by konstantinkrassmann** [comment]
We just tried by ourself and yes, it will work without google play services on the device

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
