### ISSUE TITLE
Factory Reset Geolocation is not working

### ISSUE THREAD

**Issue by freezyfridge** [mauron85/cordova-plugin-background-geolocation#25]
Hi,

I using the SampleApp to test on the android. I faced an issue, where i have factory reset the android s5, open the sampleApp app, click locate and start the tracking, the tracking is not working(android setting is all in default mode, without google account). 

Then i added google account to the android, the app is working. May i know why? Do users requires to setup google account on the phone then this background geolocation will only works?

**Comment by mauron85** [comment]
Did you used the ANDROID_DISTANCE_FILTER provider or ANDROID_FUSED_LOCATION?
Did you also install any software upgrades, like Android System WebView or Google Play Services?

**Comment by mauron85** [comment]
@freezyfridge Any updates?

**Comment by mauron85** [comment]
No response for 16 days. Closing, reopen if necessary.
