### ISSUE TITLE
version 2.2.5 Error compile in PhonegapBuild

### ISSUE THREAD

**Issue by ivent** [mauron85/cordova-plugin-background-geolocation#250]
Hello, mauro again, congratulations for keeping this plugin always up to date, I had some problems compiling the app on phonegapbuild that was resolved from version v2.0.0-rc.1 to 2.2.4, which pass correctly through the compilation, but I tried Update to 2.2.5 and the problem of compilation error has returned, I hope it can help to identify this error, hugs ...

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
