### ISSUE TITLE
how to continuously monitor a user location your plugin sends the location of a user on start of the application and not after that?

### ISSUE THREAD

**Issue by ddgrimmson418** [mauron85/cordova-plugin-background-geolocation#251]

**Comment by oliviercherrier** [comment]
Kind of same problem here:  I launch the application and I had to wait a long ... long ... time to get the tracking working.

Source code of my Ionic 2 application is on https://github.com/oliviercherrier/mauron85-background-geolocation-example-ionic2

Thank you for your help.

**Comment by AsimNet** [comment]
@oliviercherrier I did exactly like you did, and it didn't work :(

**Comment by oliviercherrier** [comment]
Happy to know that i'm not alone with this problem.  One of other question is: is it somedody Who maintain tais plugin ?

**Comment by AsimNet** [comment]
it seems this problem related to device's OS.
May they trying to block any app wants to drain the battery as a protection system.
I tested it in a Redmi 3, it gives me only one location after the app starts. Another device gave me locations for about 6 minutes.

**Comment by oliviercherrier** [comment]
On a Samsung galaxy s7. I have a location after about 3 minutes

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
