### ISSUE TITLE
Is this repository still active ?

### ISSUE THREAD

**Issue by oliviercherrier** [mauron85/cordova-plugin-background-geolocation#252]
Hello @mauron85 ,

Firstly, thank you for creating this fork of the free christocracy/cordova-plugin-background-geolocation plugin.  399$ to use a plugin before the GO LIVE is too expansive on my point of view.

Considering that:
- 94 issues are opened and that your last post on this repository was on December 30th,
- Only 4 commits happened last 4 month for minor bug fixes.

Can you say us if some actions are planned to take into account opened issues ? And what is the roadmap of your plugin ?

Again, I thank you for creating this fork, I just need to know if they are still somebody here ;-).

Olivier

**Comment by christocracy** [comment]
@oliviercherrier What you're paying for is active, full time support.  I generally respond to issues within a few minutes.

**Comment by shyamal890** [comment]
@mauron85 would like to know whether if this repository is still being maintained

**Comment by nschurmann** [comment]
@mauron85 i want to know that too.

**Comment by mauron85** [comment]
Hi guys. Sorry for no responding. I'm just too busy right now. There are many open issues, but most of them are questions and proposals for new functionality. But to be honest, I don't have much time now to work on any new functionality or issues. But I'm willing to accept PRs. There will be potentially some updates coming from react version of this plugin, but not giving any guarantees. If you need something with predictable development and support, consider @christocracy's proposal.

**Comment by oliviercherrier** [comment]
Hi @mauron85,

Thank you for your answer.

Well noted

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
