### ISSUE TITLE
how add more parameters to json that sended to server ?

### ISSUE THREAD

**Issue by MAntonio95** [mauron85/cordova-plugin-background-geolocation#254]
How could you do to add more parameters in json that is sent to the server
For example:
Add deviceid
...

**Comment by nakulkundaliya** [comment]
hello @MAntonio95 
You can pass deviceid into header
`httpHeaders: { 'deviceid':123123123123},`
its work for me. i hope its also work for you.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
