### ISSUE TITLE
Plugin sleep ~60 seconds

### ISSUE THREAD

**Issue by first-leon** [mauron85/cordova-plugin-background-geolocation#255]
* Plugin version: 2.2.5
* Platform: Android
* OS version: 4.1, 6.0
* Device manufacturer and model: xiaomi redmi note 4, lenovo p770
* Cordova version: 6.4.0
* Cordova platform version (`cordova platform ls`): android 6.0.0
* Plugin configuration options:
``` 
var config = {
        stationaryRadius: 10,
        distanceFilter: 20,
        desiredAccuracy: 10,
        debug: debug,
        notificationTitle: 'Background tracking',
        notificationText: 'enabled',
        notificationIconColor: '#FEDD1E',
        notificationIconLarge: 'mappointer_large',
        notificationIconSmall: 'mappointer_small',
        locationProvider: 0, 
        interval: duringCoordinateRequestTrack * 1000,
        fastestInterval: 2000,
        activitiesInterval: duringCoordinateRequestTrack * 1000,
        stopOnTerminate: false,
        startOnBoot: false,
        startForeground: true,
        stopOnStillActivity: true,
        activityType: 'AutomotiveNavigation',
        pauseLocationUpdates: false,
        saveBatteryOnBackground: false,
        maxLocations: 10
 };
```

Hello.
When i run:

```
backgroundGeolocation.configure(successBackgroundGeolocation, failureBackgroundGeolocation, config);
backgroundGeolocation.start();
```

plugin get first coordinate and sleep ~60sec. Then continues to read the coordinates.
What is the pause? How disable this pause?

**Comment by iamjoyce** [comment]
Could it be because you are not moving? Try setting

`stopOnStillActivity: false`

**Comment by first-leon** [comment]
I test with stopOnStillActivity: false. Pause remained. And when i test, i move in automobile.

**Comment by sammyspills** [comment]
I also have this issue. 
I'm so glad you pointed it out, at first I thought it just wasn't updating location, but it was because I was only testing it for ~15 seconds. After a minute or so, it starts updating regularly. 
Still would be nice if there wasn't the pause. 
My config is: 
`var bgOptions = {
                stationaryRadius: 50,
                distanceFilter: 10,
                desiredAccuracy: 0,
                debug: false,
                notificationTitle: 'SeaIce Tracking',
                notificationText: 'Your route is being tracked!',
                notificationIconColor: '#00388d',
                notificationIconLarge: 'mappointer_large',
                notificationIconSmall: 'mappointer_small',
                locationProvider: 0,//backgroundGeolocation.provider.ANDROID_DISTANCE_FILTER_PROVIDER,
                interval: 5000,
                fastestInterval: 5000,
                stopOnTerminate: true,
                startOnBoot: false,
                startForeground: true,
                activityType: 'AutomotiveNavigation',
                pauseLocationUpdates: false,
                saveBatteryOnBackground: false
            };`

**Comment by gustavo-iniguez-goya** [comment]
If I'm not wrong, this is due to use locationProvider: 0 (aka distanceFilter provider). I don't know the inner working of the method, but as far as I remember taking a quick look at the code, it needed several locations to start performing the calculations (see [distanceFilter provider](https://github.com/mauron85/cordova-plugin-background-geolocation/blob/next/ANDROID_DISTANCE_FILTER_PROVIDER.md) ).

Use  locationProvider: 1, and see if it gets locations faster.

**Comment by mauron85** [comment]
It is not just that. It is how just this provider works. You already provided link to explanation, so I'm not going to repeat it. Just read it and you'll get it.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Comment by alexandretok** [comment]
I'm having the same issue... any updates?
