### ISSUE TITLE
In which unit comes the speed that is provided in the POST?

### ISSUE THREAD

**Issue by nschurmann** [mauron85/cordova-plugin-background-geolocation#257]
In which unit comes the speed that is provided in the POST? km/h, miles per hour?

**Comment by scarabdesign** [comment]
The documentation states:
"speed ::	Number :: speed if it is available, in **meters/second** over ground."

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
