### ISSUE TITLE
Able to use your plugin as a dependency to my service?

### ISSUE THREAD

**Issue by scarabdesign** [mauron85/cordova-plugin-background-geolocation#258]
I'm building a service that grabs quite a few data points from the device and sends them to our servers for diagnostic overviews and the like. I was wondering if it's possible (or easy) to use your background location plugin as a dependency to my own service and make calls to it through Java, not needing to rely on the JavaScript portion to get the data. Which source files should I reference to for this? Let me know if you even think this is feasible.

Right now I'm developing for Android. Eventually I'll start on the iOS version as well.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
