### ISSUE TITLE
Make iOS send the complete queue instead of the last item

### ISSUE THREAD

**Issue by nschurmann** [mauron85/cordova-plugin-background-geolocation#259]
I'm using this configuration:
```javascript
{
            desiredAccuracy: 10,
            stationaryRadius: 5,
            distanceFilter: 1,
            interval: 4000,
            startOnBoot: true,
            activitiesInterval: 5000,
            locationProvider: backgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
            fastestInterval: 3000,
            notificationTitle: 'Yu-Track', 
            notificationText: 'Tracking en progreso', 
            stopOnTerminate: false,
            stopOnStillActivity: false,
            startForeground:true,
            url: URL_SERVICES + '/api/v1/users/track',
            syncThreshold: 5,
            activityType: 'Fitness',
            saveBatteryOnBackground: false,
            httpHeaders: { 
                'authorization': session.token
            }
}
```

And it's recording all the positions in the database, but it's only sending the first position recorded and then it's popped from the database. If you don't have time to change this could you point me to the function that is actually getting the locations from the database so i can change that to send a batch instead of a single element?, i don't know objective C but i can learn this little thing just to be sure that this plugins works also for iOS.

**Comment by iamjoyce** [comment]
Not sure if I understood your question correctly; do you mean that you want all positions before processing?

I think you can try setting `desiredAccuracy: 1, stationaryRadius: 5`

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
