### ISSUE TITLE
How to log into the server (passport library) before sending POST request?

### ISSUE THREAD

**Issue by iamjoyce** [mauron85/cordova-plugin-background-geolocation#261]
## Your Environment
* Plugin version: 2.2.5
* Platform: Android
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`): Android 6.1.2
* Plugin configuration options: `{url: "http://localhost/locations"}` _(Other properties does not matter)_

## Context
I am using [passport library on nodejs](http://passportjs.org/)

Is there any way to send a request to the server whereby that request can be authenticated by the passport library (e.g. `req.isAuthenticated() === true`)?

I have tried setting `httpHeaders: { 'Authorization': 'Basic <%username:password% in base64%>' }}`, but it doesn't work.

I am trying to avoid doing a `$http.post()` request by my own since this library has some pretty good features for POST.

## Actual Behavior
POST request to the server is successful, but the request is not sent by an authorised user.

## Possible Fix
Might be tough thing to fix or circumvent. Currently, every request generates a new session ID.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
