### ISSUE TITLE
Http request in Background

### ISSUE THREAD

**Issue by diegobill** [mauron85/cordova-plugin-background-geolocation#263]
Hi,

Why the call http POST request to my server (backend to save location) is not executing in background? The http request just called when the app goes back to foreground.

var callbackFn = function(location) {
        console.log('[js] BackgroundGeolocation callback:  ' + location.latitude + ',' + location.longitude);

        // Do your HTTP request here to POST location to your server.
        jQuery.post(url, JSON.stringify(location));

        backgroundGeolocation.finish();
};

Is there another option to post immediately the location in background or only the option.url?

https://github.com/mauron85/cordova-plugin-background-geolocation#http-locations-posting

Using the option.url I can not customize my request. Where I can get the responde from options.url request?

**Comment by diegobill** [comment]
Is there another option to post immediately the location in background or only the option.url?

https://github.com/mauron85/cordova-plugin-background-geolocation#http-locations-posting

Using the option.url I can not customize my request.

**Comment by diegobill** [comment]
On iOS the post immediately the location (I think because I set pauseLocationUpdates: false) in background (jQuery.post), but on android the request just called when the app goes back to foreground.

**Comment by leninr0a** [comment]
Hi diegobill. I had the same problem in Android but I decided to use the config defined in the example (https://github.com/mauron85/cordova-plugin-background-geolocation-example) and it worked for me.

**Comment by diegobill** [comment]
@leninr0a , what config? 
config.xml? 
https://github.com/mauron85/cordova-plugin-background-geolocation-example/blob/master/www/app.js#L14 ??

**Comment by leninr0a** [comment]
Nope, I mean the options you pass to config the backgroundGeolocation.

var bgOptions = {
  stationaryRadius: 50,
  distanceFilter: 50,
  desiredAccuracy: 10,
  debug: true,
  notificationTitle: 'Background tracking',
  notificationText: 'enabled',
  notificationIconColor: '#FEDD1E',
  notificationIconLarge: 'mappointer_large',
  notificationIconSmall: 'mappointer_small',
  locationProvider: 0,//backgroundGeolocation.provider.ANDROID_DISTANCE_FILTER_PROVIDER,
  interval: 10,
  fastestInterval: 5,
  activitiesInterval: 10,
  stopOnTerminate: false,
  startOnBoot: false,
  startForeground: true,
  stopOnStillActivity: true,
  activityType: 'AutomotiveNavigation',
  url: 'http://192.168.81.15:3000/locations',
  syncUrl: 'http://192.168.81.15:3000/sync',
  syncThreshold: 100,
  httpHeaders: {
    'X-FOO': 'bar'
  },
  pauseLocationUpdates: false,
  saveBatteryOnBackground: false,
  maxLocations: 100
};

For some reason I can't explain yet, using these options allow me to send the http post in background mode. I passed the data in the httpHeaders and that solved my problem.

**Comment by diegobill** [comment]
@leninr0a , this config works because you set  "url: 'http://192.168.81.15:3000/locations'", like explanation here:

https://github.com/mauron85/cordova-plugin-background-geolocation#http-locations-posting

But using this solution I can not handle the response (callback) of location send. How do you handle the response for requests to this "url: 'http://192.168.81.15:3000/locations'" url ???

**Comment by diegobill** [comment]
@mauron85 , how can I define interval to iOS, not only distanceFIlter?

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
