### ISSUE TITLE
Disabling logback (logback.db database 300+MB)

### ISSUE THREAD

**Issue by rtholmes** [mauron85/cordova-plugin-background-geolocation#265]
Is it possible to disable logback? While  the `cordova_bg_geolocation.db` stays at a reasonable size (25kb), the `logback.db` database has grown extremely large on my device:
 `310394880 2017-02-20 14:53 logback.db` (310 MB). 

## Your Environment

* Plugin version: 2.2.5
* Platform: Android
* OS version: 6.0.1
* Device manufacturer and model: Nexus 5
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`): android 6.1.2
* Plugin configuration options: 
* Link to your project:

## Context

`LoggerManager.java:55` says the log should only persist for 7 days, but it seems like 310MB should be more than 7 days worth of logging. Regardless, being able to disable this logging entirely would be helpful (e.g., a `debugLog: false` option?). 

## Expected Behavior

The log DB should not grow to be hundreds of MB. I have confirmed that the data in `logcat.db` is indeed from this plugin.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
