### ISSUE TITLE
Application Rejected by Apple with error support for location in the UIBackgroundModes

### ISSUE THREAD

**Issue by ivent** [mauron85/cordova-plugin-background-geolocation#269]
## Application Rejected by Apple

* Plugin version: 2.25
* Platform: iOS 
* OS version: 10.2
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 

----------

      ```
  
        	// Config
        	desiredAccuracy:5,
        	distanceFilter:5,
        	stationaryRadius:20,
        	locationUpdateInterval:1000,
        	fastestLocationUpdateInterval:1000,
		
		// Activity Recognition config
		activityType: 'AutomotiveNavigation',
		activityRecognitionInterval:1000,
		stopTimeout:1,
				
		// Notificações
		notificationIcon: 'icon',
		notificationTitle: 'Myapp',
		notificationIconColor: '#FC6932',
		notificationText: 'Toch to return',
		saveBatteryOnBackground:false,	
		startForeground:false,
		
		// Application config
        	debug:false,
        	stopOnTerminate:true,
        	startOnBoot: true,	

```
-------------

## Question

Hello my application was declined in the Apple Store apparently it is a problem in requesting the update in Background how do I solve this, could anyone help me?

## Apple Return

From Apple
2. 5 PERFORMANCE: SOFTWARE REQUIREMENTS

Performance - 2.5.4

Your app declares support for location in the UIBackgroundModes key in your Info.plist file but does not have any features that require persistent location. Apps that declare support for location in the UIBackgroundModes key in your Info.plist file must have features that require persistent location.

Next Steps

Please review your app to include features that require the persistent use of real-time location updates while the app is in the background.

If your app does not require persistent real-time location updates, please remove the "location" setting from the UIBackgroundModes key. You may wish to use the significant-change location service or the location monitoring service if persistent real-time location updates are not required for your app features.

Resources

For more information, please review the Starting Significant-Change Location Service and Monitoring Geographical Regions.

Request a phone call from App Review

At your request, we can arrange for an Apple Representative to call you within the next three business days to discuss your App Review issue.

To request a call and ensure we have accurate contact information, reply directly to this message with a contact name and direct phone number to reach you.

**Comment by ivent** [comment]
Any solution? My app is still being rejected by the appstore because of this problem could anyone help?

**Comment by epetre** [comment]
This is scary...

**Comment by luigi37** [comment]
The problem is not the plugin. Apple rejects everything that try to uses background modes for something different than the intended use... (Sometime even if you explain to them...)
I ensured to write in both changelog and app description that my app was supporting tracking also in background and the very same binary was accepted.
I hope this helps

**Comment by klaus-donnert** [comment]
And it varies from one Apple reviewer to another.

**Comment by ivent** [comment]
Thanks for the help, I made some adjustments in the settings and the inclusion of the information in the description as requested and was approved !!!

**Comment by victorvitalino** [comment]
@ivent  How did you get approved? What steps did you follow? I have the same problem, and have tried everything and always reject. Android as always works everything perfectly.

**Comment by ivent** [comment]
@victorvitalino Hi friend, I'm also from Brazil, I'm not sure what the solution was I used Luigi's tip37 and I informed in the description that the app uses constant location tracking in background mode, and also changed the configuration, from the app to the following, You can do some tests on startForeground true or false, which I suspect is one of the reasons this happens. I hope it really helps the review is something variable that we can not predict and can vary from app to app ..

backgroundGeoLocation.configure(callbackFn, failureFn, {
        desiredAccuracy:5,
        distanceFilter:5,
        stationaryRadius:20,
        locationUpdateInterval:1000,
        fastestLocationUpdateInterval:1000,
		
		// Activity Recognition config
		activityType: 'AutomotiveNavigation',
		activityRecognitionInterval:1000,
                stopTimeout:1,
				
		// Notifications
		notificationIcon: 'icon',
		notificationTitle: 'App Name',
		notificationIconColor: '#FC6932',
		notificationText: 'Open App Name,
		saveBatteryOnBackground:false,	
		startForeground:false,
		
		// Application config
        debug:false,
        stopOnTerminate:true,
        startOnBoot: true,	

    });
