### ISSUE TITLE
Issues with using custom ICon

### ISSUE THREAD

**Issue by netbitsolutions** [mauron85/cordova-plugin-background-geolocation#27]
Hi, when i define the custom icon notificationIcon : res://icon.png   or even in the drawable folder, the pulgin works in a very unexpected way by over writing the notificationTitle  and notificationText to the default name of the App, once you click on the notification, the takes to to RUNNING APPS program.

What is the standard way of defining and setting the custom Icon

**Comment by mauron85** [comment]
Make sure, that those icons are really available. I've had issues like yours before.

**Comment by netbitsolutions** [comment]
Ok, where are the icons expected to be ?

**Comment by mauron85** [comment]
Very good example is the SampleApp.

**Comment by pugwonk** [comment]
I have this exact same problem. If I use:

```
notificationTitle: 'MyApp',
notificationText: 'MyApp is continuing to track your location',

```
Then the notification gets that correct title and text. If I change it to:

```
notificationIcon: 'icon',
notificationTitle: 'MyApp',
notificationText: 'MyApp is continuing to track your location',

```
Then the icon appears as desired, but the text changes to what netbitsolutions mentions. The icon is definitely available (it appears fine).

**Comment by RistoNiinemets** [comment]
Same problem here. The icon is visible (although not notificationColor), but not the title and text:
Title: AppName is running
Text: Touch for more information or to stop the app.

**Comment by mauron85** [comment]
That's the default system message, that from my experience is not shown when icon is not found.
It's not exactly bug, but it's kind of my fault. The icon has to be in drawable folder, which is not created by cordova add platform by default and has to be created in cordova script or manually.

**Comment by RistoNiinemets** [comment]
Yes, that really worked. Thank you!

At the moment, if I want to change the notification titlte and/or text, it seems that I would have to stop the service, (re)configure and then start the service again. I think that the notification should be more configurable or maybe an option to disable it (and use another plugin more specified for it).

**Comment by mauron85** [comment]
@RistoNiinemets all notification related stuff is on lines 97 - 113. Probably post some more code, so I can help.

https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/src/android/AbstractLocationService.java#L97

**Comment by djereg** [comment]
The custom icon is working fine except one thing, it does not change it's color, keeps white.

Created the icon with [AndroidAssetStudio](http://romannurik.github.io/AndroidAssetStudio/icons-notification.html), used my own PNG and tried one Clipart, but same result, the icon keeps white.

The text color changed as expected.

**Comment by mauron85** [comment]
white color accent is how notifications now works on android. nothing i can do about it.
