### ISSUE TITLE
Can't stop background tracking

### ISSUE THREAD

**Issue by guestisp** [mauron85/cordova-plugin-background-geolocation#270]
I'm using the latest version and even after calling `window.backgroundGeolocation.stop();` the plugin is still tracking and sending location updates to our server.

How can I ensure that plugin stop to track when calling `window.backgroundGeolocation.stop();` ?

**Comment by mauron85** [comment]
It's probably sending locations there were not send due of lack of network connection (syncing location)

**Comment by guestisp** [comment]
How can I stop everything ?
Anyway, is still sending from 2 days.

**Comment by awoodwardskyline** [comment]
I am having the same issue.

**Comment by guestisp** [comment]
No solutions ?

**Comment by harithFED** [comment]
can i know you guys use ios or android.

**Comment by guestisp** [comment]
android

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Comment by mubi64** [comment]
I am also facing the same issue with 3.0.0-alpha.50. Is there any solution to it? Even I have terminated the app from recent list but it is starting again and again.

**Comment by mubi64** [comment]
Any solution to this? No reply from Author

**Comment by ohjeyong** [comment]
I have same issue on react-native-mauron85-background-geolocation
