### ISSUE TITLE
"cannot access AbstractSafeParcelable"

### ISSUE THREAD

**Issue by sebi-b** [mauron85/cordova-plugin-background-geolocation#271]
Hey there,

When building the app with "ionic build android" i get the error above...

* Platform: Android
* Device manufacturer and model: Nexus 5x
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`):  android 6.1.2

## Context

let config = {
      desiredAccuracy: 0,
      stationaryRadius: 20,
      distanceFilter: 10,
      debug: true,
      interval: 2000
    };

    BackgroundGeolocation.configure((location) => {

      console.log('BackgroundGeolocation:  ' + location.latitude + ',' + location.longitude);

      // Run update inside of Angular's zone
      this.zone.run(() => {
        this.lat = location.latitude;
        this.lng = location.longitude;
      });

    }, (err) => {

      console.log(err);

    }, config);

    // Turn ON the background-geolocation system.
    BackgroundGeolocation.start();

**Comment by Mossito** [comment]
I had the same problem. Just update your android platform project.properties
from
cordova.system.library.3=com.google.android.gms:play-services-location:9.8.0
to
cordova.system.library.3=com.google.android.gms:play-services-location:+

Anyone knows hoy can i define anywhere before the platform generation? i need to automate this.

Thank you very much

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
