### ISSUE TITLE
How can plugin send request to server for each 15 minutes

### ISSUE THREAD

**Issue by le1tuan** [mauron85/cordova-plugin-background-geolocation#272]
## Your Environment

* Plugin version: 2.2.0
* Platform: Android
* Device manufacturer and model: xiaomi redmi note 3 
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
        desiredAccuracy: 100,
        stationaryRadius: 1,
        distanceFilter: 1,
        locationProvider: backgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
        maxLocations: 24 * 4,
        interval: 900000,
        fastestInterval: 5000,
        activitiesInterval: 10,
        stopOnTerminate: false,
        stopOnStillActivity: false,
        startOnBoot: true,
        startForeground: true,
        url: 'http://localhost:3000/attendances/locations' 

## Context

when i open application , they send first request to server immediately , after 15 minitues, the application doesn't send request to server
## Expected Behavior

based on the configuration , i want the application sends the new location information to server for each 15 minites , but it sends  request after 2 or 3 minitues

**Comment by mcichecki** [comment]
Did you come up with any solution?

**Comment by le1tuan** [comment]
@mcichecki if you want your app send request to server every 15 minutes, you should set fastestInterval =900000

**Comment by mcichecki** [comment]
Yes, I've figured it out too. Thanks!

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
