### ISSUE TITLE
no posting on server

### ISSUE THREAD

**Issue by bigbossmaher** [mauron85/cordova-plugin-background-geolocation#273]
hi i'm a new user
i want to use this plugin to 
- get the current position of the user in background ( when the app is closed ) and check if it is close the a specific place , if yes i want to send a notification 

can someone help me 
what are the config that i should use , and where i should put the code that will check send notification and check if the user is close the some places

thanks

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
