### ISSUE TITLE
Variables on HTTP-POST

### ISSUE THREAD

**Issue by mario-berardo** [mauron85/cordova-plugin-background-geolocation#274]
What is the headers names that are posted when the HTTPPOST is called ?

**Comment by maxHus** [comment]
you can try creating your own headers
_backgroundGeolocation.configure(callbackFn, failureFn, {
    desiredAccuracy: 10,
    stationaryRadius: 20,
    distanceFilter: 30,
    url: 'http://192.168.81.15:3000/locations',
    httpHeaders: { 'X-FOO': 'bar' }
});_

**Comment by maxHus** [comment]
you can try creating your own headers
```
backgroundGeolocation.configure(callbackFn, failureFn, {
desiredAccuracy: 10,
stationaryRadius: 20,
distanceFilter: 30,
url: 'http://192.168.81.15:3000/locations',
httpHeaders: { 'X-FOO': 'bar' }
});

```

**Comment by jleal52** [comment]
You can use it to identify what device is sending you the tracking information. You can send a phone uuid, or any other user/phone identifier in you app.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
