### ISSUE TITLE
IllegalStateException: GoogleApiClient is not connected yet.

### ISSUE THREAD

**Issue by gustavo-iniguez-goya** [mauron85/cordova-plugin-background-geolocation#277]
## Your Environment

* Plugin version: 2.2.5
* Platform: Android
* OS version: Api 16
* Device manufacturer and model: GT-I8190L
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`): 6.0.0
* Plugin configuration options: 

                desiredAccuracy: 50,
                stationaryRadius: 5,
                locationProvider: 1,
                distanceFilter: 2,
                interval: 1000 * 5,
                fastestInterval: 1000 * 4,
                debug: true,
                notificationTitle: 'xxx',
                notificationText: '',
                activitiesInterval: 5,
                maxLocations:   100,
                /* iOS */
                activityType: 'Fitness',
                pauseLocationUpdates: false

## Possible Fix
catch(Exception e){} at the end of the block, below SecurityException, in.
ActivityRecognitionLocationProvider.java:113

## Debug logs

**Exception java.lang.RuntimeException: Error receiving broadcast Intent { act= com.marianhello.bgloc.DETECTED_ACTIVITY_UPDATE flg=0x10 (has extras) } in com.marianhello.bgloc.ActivityRecognitionLocationProvider$1@42bf31e0**

**Caused by java.lang.IllegalStateException: GoogleApiClient is not connected yet.**
com.google.android.gms.internal.zzrb.zzb ()
com.google.android.gms.internal.zzrf.zzb ()
com.google.android.gms.internal.zzrd.zzb ()
com.google.android.gms.location.internal.zzd.requestLocationUpdates ()
com.marianhello.bgloc.ActivityRecognitionLocationProvider.startTracking (ActivityRecognitionLocationProvider.java:113)
com.marianhello.bgloc.ActivityRecognitionLocationProvider$1.onReceive (ActivityRecognitionLocationProvider.java:278)
android.app.LoadedApk$ReceiverDispatcher$Args.run (LoadedApk.java:755)
android.os.Handler.handleCallback (Handler.java:615)
android.os.Handler.dispatchMessage (Handler.java:92)
android.os.Looper.loop (Looper.java:137)
android.os.HandlerThread.run (HandlerThread.java:60)

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
