### ISSUE TITLE
Ts ERROR 

### ISSUE THREAD

**Issue by rambey** [mauron85/cordova-plugin-background-geolocation#278]
## Windows7

* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:
* Cordova version (`cordova -v`):6.5.0
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

## Context
 when i'm testing that exemple https://www.joshmorony.com/adding-background-geolocation-to-an-ionic-2-application/ ,  i get this error in my  provider.ts : [ts] Cannot find name 'Geoposition'.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by gustavo-iniguez-goya** [comment]
Hi @rambey ,

As stated in the frontpage: "As version 2.0 platform support for Windows Phone 8 was removed."
There're no windows sources on latest version of this plugin.

The ionic documentation is outdated: http://ionicframework.com/docs/v2/native/background-geolocation/

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
