### ISSUE TITLE
Android Phone crashes after 30/40 mins of plugin usage

### ISSUE THREAD

**Issue by luigi37** [mauron85/cordova-plugin-background-geolocation#279]
## Your Environment
* Plugin version: 2.2.5 (latest as per today)
* Platform: Android
* OS version: 6
* Device manufacturer and model: Samsung A3
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

## Context
Started the background activity while driving, with Waze active and some phone calls...

## Expected Behavior
Should not crash app an phone

## Actual Behavior
At random, after 30/40 minutes the phone crashes

## Steps to Reproduce
This is my configuration file.
I save all readings in a GPX file and I don't need to use the internal position save feature.
No info is sent to server.

I suspect my configuration is too aggressive:

//         debug: true,
        desiredAccuracy: 10, //< than ...
        stationaryRadius: 50,
        distanceFilter: 50,
        startForeground: true, //android
        interval: 1000, //android
        notificationTitle: aanotificationTitle, //android
        notificationText: aanotificationText, //android
        notificationIconColor: "#b4c1d7", //android
        notificationIconLarge: "icon", //android
        notificationIconSmall: "mappointer_small", //android
        locationProvider: backgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER, //android
        activityType: "OtherNavigation", //iOS
        pauseLocationUpdates: false,  //iOS
        saveBatteryOnBackground: false, //iOS
        fastestInterval: 5,
        activitiesInterval: 10,
        stopOnStillActivity: false, //android        
        maxLocations: 100

Is my configuration too aggressive?
What would be ideal parameters for an activity similar to continuos walking/running for 2/4 hours?

Thanks a lot

Luigi

**Comment by mauron85** [comment]
Please provide some logs. Either from plugin or from adb logcat. Try to locate moment of crash.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
