### ISSUE TITLE
Parameters of posted request

### ISSUE THREAD

**Issue by maxHus** [mauron85/cordova-plugin-background-geolocation#282]
what are the names of the parameters of posted request ? that i can get on my server side ?

**Comment by kholiavko-roman** [comment]
@maxHus, are you found the solution?

**Comment by maxHus** [comment]
@kholiavko-roman as long as i remember this is the format  i got
` [
  {
    "provider": "gps",
    "time": 1491829730802,
    "latitude": 24.902657468798626,
    "longitude": 67.086751468987217,
    "accuracy": 96,
    "speed": 1.6746340990066528,
    "altitude": -1.0148536674573743,
    "bearing": 344.48202514648438,
    "locationProvider": 0
  }`

**Comment by kholiavko-roman** [comment]
@maxHus thanks for replay! Do you know how to add custom parameters in POST request ?

**Comment by maxHus** [comment]
@kholiavko-roman  you can use HTTP headers to post your custom parameters
like this:
![capture](https://user-images.githubusercontent.com/12863333/27822077-d9b5da84-60bd-11e7-967d-f89d582ed498.JPG)

**Comment by kholiavko-roman** [comment]
Yes, but this is the headers, its not POST parameters. I need send some parameters like userId, ect. And send this information in headers this is not good idea I think.

**Comment by maxHus** [comment]
@kholiavko-roman i know.. but this is how people used it .. you can also try attaching query strings in url

**Comment by kholiavko-roman** [comment]
I understand you. But use GET params is not safe too. 
But anyway, thank you for reply!
