### ISSUE TITLE
Not all locations are saved when app is close

### ISSUE THREAD

**Issue by feddu** [mauron85/cordova-plugin-background-geolocation#283]
## Your Environment
* Plugin version: 2.2.5
* Platform: Android
* OS version: 4.4.2
* Device manufacturer and model: Huawei Y635
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`): android 6.0.0
* Plugin configuration options: 
`backgroundGeolocation.configure(callbackFn, failureFn, {
                desiredAccuracy: 10,
                stationaryRadius: 20,
                distanceFilter: 30,
                debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
                notificationTitle: 'APP',
                notificationText: 'GPS',
                notificationIconColor: '#489ad0',
                locationProvider: backgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,//ANDROID_ACTIVITY_PROVIDER,//backgroundGeolocation.provider[ENV.settings.locationProvider],
                interval: 15 * 1000, // <!-- poll for position every minute
                fastestInterval: 30 * 1000,
                activitiesInterval: 30 * 1000,
                stopOnTerminate: false, // <-- enable this to clear background location settings when the app terminates
                startOnBoot: true,
                startForeground: true,
                stopOnStillActivity: false,
                pauseLocationUpdates: false,
                maxLocations: 9500
            });`

## Behavior
When app is closed completely the app stores between 111 and 113 locations when it should be more because I use maxLocations: 9500 . I'm using getValidLocations on callbackFn

## Expected Behavior
The app should store locations specify on maxLocations

**Comment by maxHus** [comment]
did you try using _syncThreshold_  ?
default value of _syncThreshold_ is 100 i guess, so while application would be saving _maxLocations_, it might only be sending around 100 failed location to the server in bulk

**Comment by feddu** [comment]
Thanks for the reply I tried with _syncThreshold_ after I post this and still no luck

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
