### ISSUE TITLE
configure 'startOnBoot' does not execute callbackFn

### ISSUE THREAD

**Issue by smchae** [mauron85/cordova-plugin-background-geolocation#284]
## Your Environment

* Plugin version: 2.2.5
* Platform: Android
* OS version: 7.0
* Device manufacturer and model: Galaxy S7
* Cordova version (`cordova -v`): 6.5
* Cordova platform version (`cordova platform ls`): android 5.2.2
* Plugin configuration options: startOnBoot
* Link to your project:

## Context

I have set configuration as below

    backgroundGeolocation.configure(callbackFn, failureFn, {
            desiredAccuracy: 10,
            stationaryRadius: 10,
            distanceFilter: 10,
            interval: 60000,
            maxLocations: 50,
            startOnBoot: true,
            stopOnTerminate: false
        });

 And callbackFn as below
   
        var callbackFn = function(location) {
            var link = API_URL;

            $http.defaults.headers.post["Content-Type"] = "application/x-www-form-urlencoded";

            $http({
                method: 'POST',
                url: link,
                headers: {'Content-Type': 'application/x-www-form-urlencoded'},
                transformRequest: function(obj) {
                    var str = [];
                    for(var p in obj)
                    str.push(encodeURIComponent(p) + "=" + encodeURIComponent(obj[p]));
                    return str.join("&");
                },
                params: {
                    'device': 'android',
                },
                data: {
                    lat:location.latitude,
                    lng:location.longitude,
                }
            }).success(function(data){
                console.log(data);
            }).error(function(data){
                console.log(data);
            });

            backgroundGeolocation.finish();
        };

## Expected Behavior

After rebooting the device, the app still sends its location to server through http request.

## Actual Behavior

It seems that the app does not send its location to server through http request. The location information on my DB does not get updated.

It works perfectly fine once app is opened(before and after reboot). However, after reboot, if I do not execute app at all, even though it says background location working on alarm center on top of the device, it does not do http request.

**Comment by maxHus** [comment]
did you try using url and syncurl options ?

i guess the activity might be killed after reboot, so does the callback function.
you should be using plugins _url_ and _syncurl_ option to send data to your server, because the service might survive after the reboot.

**Comment by smchae** [comment]
@maxHus Yes. I was able to get location after boot using _url_ option. However, I had to change backend structure accordingly :( . 
Thank you!

**Comment by beritsistemas** [comment]
I have the same problem with ionic 3 and the native wrapper.

The app finish and the background service also finish with the app. 

I have tested with these config parameters also

         startOnBoot:true
         pauseLocationUpdates:false

**Comment by maxHus** [comment]
if you are using callbackbk function to fetch location and send it to the server, i am afraid you might not get location after the app is killed.. i have used _url_ option of the plugin and it keeps sending me updates even if the app is killed.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
