### ISSUE TITLE
"startOnBoot: true" doesnt stop after calling stop function

### ISSUE THREAD

**Issue by maxHus** [mauron85/cordova-plugin-background-geolocation#286]
* Platform:   Android
* OS version: 5.0.1
* Device  : Samsung S4
* Cordova version : 6.4.0

I have set the plugin configuration option "  startOnBoot: true"  

if the phone is restarted .. the plugin works fine and application reboots and start doing its work.

But I have created a button inside the Application For exiting the app and stopping the background tracking, where i call _" backgroundGeolocation.stop(); "_
 _"backgroundGeolocation.stop();"_ Also works fine as it stops the background tracking.
but as soon as i restarts the app after calling  _"backgroundGeolocation.stop();"_  , the application start working again (even thought i stopped it, before restarting)

-- is it a expected behavior or am I missing something ?
Thanks

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
