### ISSUE TITLE
How can I detect if my app is in background mode?

### ISSUE THREAD

**Issue by klaus-donnert** [mauron85/cordova-plugin-background-geolocation#287]
I'm using phonegap build 
This issue is on Android - I haven't tested it on iOS
I have an ajax request inside of setInterval which updates table data in the ui, however it does not need to be updated while in background mode. 

Any workarounds?

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
