### ISSUE TITLE
Improvement request - Foreground tracking

### ISSUE THREAD

**Issue by luigi37** [mauron85/cordova-plugin-background-geolocation#288]
Hi,
following some of the conversation here I could obtain the result I needed: 
foreground tracking working properly and at maximum frequency with both Android and iOS.
I forked the code here
https://github.com/luigi37/cordova-plugin-background-geolocation

It would be great if this code could merged and in a more structured way.

The logic would be in my opionion the following:
1- Developer desires maximum accuracy. He/she assigns 

    desiredAccuracy=0 
    distanceFilter=0

In this case the code to be executed will be

    locationManager.distanceFilter = kCLDistanceFilterNone;
    locationManager.desiredAccuracy = kCLLocationAccuracyBestForNavigation;

Instead of the std:

    locationManager.distanceFilter = _config.distanceFilter; // meters
    locationManager.desiredAccuracy = [_config decodeDesiredAccuracy];

2- For foreground tracking another parameter should be added which is like:
foregroundTracking=true (default to false)

which will trigger:

    bgloc.type = @"raw";
    if (self.delegate && [self.delegate respondsToSelector:@selector(onLocationChanged:)]) {
              [self.delegate onLocationChanged:[bgloc toDictionary]];
    }

Does it makes sense?

Thanks!

Luigi

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
