### ISSUE TITLE
iOS: stopOnTerminate not working

### ISSUE THREAD

**Issue by cofetti** [mauron85/cordova-plugin-background-geolocation#29]
I'm testing on a real device with iOS 9.2.1. I have set `stopOnTerminate` to true, but when I close my app (double tap on home and swipe it away), I keep seeing the GPS icon on the statusbar. It persists through phone reboot. I am sure that the icon belongs to my app, because uninstalling the app or disabling Location Services for this specific app immediately removes the icon.

**Comment by mauron85** [comment]
Thanks, will check it out on sampleApp.

**Comment by mauron85** [comment]
Hmm strange, just checked it out and it works just as it should on iOS 9.2.
Can you run your cordova app from terminal:
```
$ cordova run ios --device
```

And observe output while terminating app. You should see 'CDVBackgroundGeoLocation stoping on terminate' meaning your app will listen to location updates in the background.

```
2016-01-25 16:41:31.615 Cordova Background GeoLocation[1184:562473] - CDVBackgroundGeoLocation appTerminate
2016-01-25 16:41:31.617 Cordova Background GeoLocation[1184:562473] - CDVBackgroundGeoLocation stoping on terminate
```

**Comment by cofetti** [comment]
I tested this some more and I see now that this doesn't happen every time. After an uninstall it took me maybe 10-20 tries to get it stuck again (I was debugging another issue). But when it does get stuck, it stays there through all app updates via Xcode and reboots, that's why I thought at first that it was always there.

Right now I quit the app maybe 3 hours ago and I'm getting occasional "MOVING" notifications while sitting at the dinner table :)

I will try to monitor the console for this message, when I debug again tomorrow.

**Comment by cofetti** [comment]
I think this was some kind of a glitch. Luckily it stopped reproducing on both of my phones after complete wipe.
