### ISSUE TITLE
Doubts about API (Development of APP in Brasil )

### ISSUE THREAD

**Issue by AdelioMoura** [mauron85/cordova-plugin-background-geolocation#290]
First of all thank you for developing this API, it has helped me a lot, thank you very much.

## Your Environment
* Plugin version: 2.2.0
* Platform: Android
* OS version: 5.1
* Device manufacturer and model:  MOTO G
* Cordova version (`cordova -v`):  6.2.0
* Cordova platform version (`cordova platform ls`): 5.1.1

* Plugin configuration options: 

backgroundGeolocation.configure(f_sucesso, f_erro, {
    desiredAccuracy: 10,
    stationaryRadius: 20,
    distanceFilter: 30,
    url: '******************************',
    httpHeaders: { 'X-FOO': 'bar' },
    maxLocations: 1000,
    locationProvider: backgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
    interval: 120000,
    fastestInterval: 120000,
    activitiesInterval: 10000,
    notificationTitle: ' Coordenadas ',
    notificationText: 'enabled',
    notificationIconColor: '#FEDD1E',
    notificationIconLarge: 'mappointer_large',
    notificationIconSmall: 'mappointer_small'
});

* Link to your project:  https://play.google.com/store/apps/details?id=com.mid_eos

## Context ( Doubts )
    ( 1 ) How to delete this information (image) from my APP when the API is running.
    ( 2 ) How to identify if the background Geolocation.start () is active

## Image
![img_01_eos](https://cloud.githubusercontent.com/assets/16105979/25447049/00095892-2a8a-11e7-8679-c2f0349072a6.jpg)

![img_02_eos](https://cloud.githubusercontent.com/assets/16105979/25447062/0ea15922-2a8a-11e7-9c4b-a19eadd202b2.jpg)

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
