### ISSUE TITLE
Crash on IOS after 1 hours

### ISSUE THREAD

**Issue by jackdaniel9** [mauron85/cordova-plugin-background-geolocation#291]
Hi,

My IOS App with background geolocation crash after 1 hour.

Do you have the same problem ?

## Your Environment
* Platform: iOS 
* OS version: 5 or 6
* Cordova version (`cordova -v`): 6.4.0
* Plugin configuration options: mauron85/cordova-plugin-background-geolocation

**Comment by epetre** [comment]
you mean you closed the app and it tracked everything right in ios and then it crashes after 1h?

**Comment by jackdaniel9** [comment]
i set "stopOnTerminate" to false and i will see if my application work.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
