### ISSUE TITLE
iOS seems to stop tracking when app is closed.

### ISSUE THREAD

**Issue by epetre** [mauron85/cordova-plugin-background-geolocation#292]
Android's service runs properly and tracks position when the app is closed, but iOS only tracks the position when the app is in the background and not when it's closed.

## Environment
Plugin version 2.2.5
Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v4.4.3
Xcode version: Xcode 8.3.2 Build version 8E2002

## Context
In iOS, when closing the app, all tracking stops. Most of the time, I am in stationary mode, but even if I go in the emulator and fake movement, it's not tracked if the app is closed. However, it works as expected when the app is in background.

### Config
`    const config: BackgroundGeolocationConfig = {
            desiredAccuracy: 0,
            stationaryRadius: 4,
            distanceFilter: 4,
            syncThreshold: 1,
            maxLocations: 25,
            startOnBoot: true,
            saveBatteryOnBackground: false, //ios
            startForeground: true,
            debug: true, //  enable this hear sounds for background-geolocation life-cycle.
            pauseLocationUpdates: false, //Pauses location updates when app is paused (default: true)
            stopOnTerminate: false, // enable this to clear background location settings when the app terminates
            httpHeaders: { 'Authorization': this.config.getApiKey() },
            url: this.config.url + '/positions'
    }`

## Expected Behavior
Like Android, I was thinking that it would send position updates when moving or changing position. But it doesn't seem to work at all when the app is closed.

## Actual Behavior
Nothing seems to be happening in the background, so I'm wondering if this is just because the service is killed and will never come back or if it will come back on it's own later... not sure how it works yet.

## Possible Fix
Unsure yet since I don't understand if this is normal behavior or not.

## Steps to Reproduce

1. Install on iOS
2. Start app (position gets tracked)
3. Double tap home
4. Emulator Debug City Run (position gets tracked)
5. Close app
6. Emulator Debug City Run (position doesn't get tracked)
7. Emulator Debug Freeway Drive (position doesn't get tracked)
8. Whatever I do, no more updates from that point on...

## Context
We are using this plugin in order to match people and we don't want to force users to come back in the app regularly just to update their position so we take very inaccurate regular positions in order to know if they are still available to match in their respective radius.

**Comment by epetre** [comment]
@mauron85 if you can tell me if this is supposed to work, I would really appreciate that since I am unable to tell from the doc and past issues if this is normal behaviour or not. 

It seems to me that in iOS it should still update the position from time to time when we move far enough even if the app is closed right? 

Just knowing that it should work will help me know if I should investigate more.

**Comment by klaus-donnert** [comment]
I am having the same issue with v2.2.4 of the plugin

**Comment by epetre** [comment]
When I close the app it does an interrupted sound... this is the log:
```
2017-05-01 20:58:38.730420-0400 App[943:182231] Disconnected from FCM
[DEBUG] Did enter background
[DEBUG] Did close IPv6 listening socket 13
[DEBUG] Did close IPv4 listening socket 12
[INFO] GCDWebServer stopped
2017-05-01 20:58:38:737 App[943:182231] CDVBackgroundGeoLocation paused
2017-05-01 20:58:38.759637-0400 App[943:182695] LocationManager switchMode 0
2017-05-01 20:58:38:737 App[943:182231] LocationManager switchMode 0
2017-05-01 20:58:38.779273-0400 App[943:182555] CDVBackgroundGeoLocation appTerminate
2017-05-01 20:58:38:778 App[943:182231] CDVBackgroundGeoLocation appTerminate
2017-05-01 20:58:38.793068-0400 App[943:182689] LocationManager switchMode 0
2017-05-01 20:58:38:778 App[943:182231] LocationManager switchMode 0
```

**Comment by epetre** [comment]
It seems like it just isn't possible in iOS.. it looks like when it's killed it just does switchMode 0 and dies and we never hear from it again...

**Comment by epetre** [comment]
Ok so I tried [cordova-background-geolocation-lt](https://github.com/transistorsoft/cordova-background-geolocation-lt) and it works fine with the same configs... so to answer my own question, yes it's supposed to work...

**Comment by epetre** [comment]
basically this plugin doesn't work on ios when the app closes it just silently crashes, no logs no notification... Impossible for me to debug, so I'm moving on. [Cordova-background-geolocation-lt](https://github.com/transistorsoft/cordova-background-geolocation-lt) works from the first try with the same configurations.

**Comment by iBasit** [comment]
Me too. gonna move to ` Cordova-background-geolocation-lt` — no support here.
