### ISSUE TITLE
deleteAllLocations is deprecated and will be removed in future versions

### ISSUE THREAD

**Issue by jackdaniel9** [mauron85/cordova-plugin-background-geolocation#293]
Hi,

If "deleteAllLocations" is deprecated, how i can delete all location in database ?

Thanks

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
