### ISSUE TITLE
In IOS when app is killed it not update to server

### ISSUE THREAD

**Issue by beritsistemas** [mauron85/cordova-plugin-background-geolocation#294]
## Your Environment

* Plugin version: 2.2.5
* Platform: iOS
* OS version: 10.3.1
* Device manufacturer and model: Iphone 5S
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`): ios 4.3.1
* Plugin configuration options: 

      var config = {
  stationaryRadius: 10,
  distanceFilter: 10,
  desiredAccuracy: 10,
  debug: true,
  notificationTitle: 'Background tracking',
  notificationText: 'enabled',
  notificationIconColor: '#FEDD1E',
  notificationIconLarge: 'mappointer_large',
  notificationIconSmall: 'mappointer_small',
  locationProvider: 0,//backgroundGeolocation.provider.ANDROID_DISTANCE_FILTER_PROVIDER,
  interval: 10,
  fastestInterval: 5,
  activitiesInterval: 10,
  stopOnTerminate: false,
  startOnBoot: true,
  startForeground: true,
  stopOnStillActivity: true,
  activityType: 'Fitness',
     url: 'http://192.168.81.15:3000/geolocationpush',
      //  syncUrl: 'http://192.168.81.15:3000/sync',//for batch update (multiple locations at same time)
        syncThreshold: 10,
        httpHeaders: {
                  "userid": "x"
        },
  pauseLocationUpdates: false,
  saveBatteryOnBackground: false,
  maxLocations: 100
};

* Link to your project:

## Context
I open the app and I received updates to server

## Expected Behavior
Receive updates to server in background mode (when app is close or when I reset my phone and never open the app)
This behaviour works ok in android. 

## Actual Behavior
The server does't get updates

## Steps to Reproduce
1. Open the app
2. Close it
3. Or restart the iphone
4.

## Context
My app needs to get notification about location of the user even if the app is close

**Comment by nakulkundaliya** [comment]
I am fetching same issue in the iPhone.
It's Working fine in the Simulator.

And when my device is locked at time plugin not send any updated location to the server.
When open device lock at time plugin send all location to server (rather than latest location)

Any solution for it?

**Comment by iBasit** [comment]
+1

**Comment by nabinkumarn** [comment]
@nakulkundaliya @beritsistemas  I am facing the same issue in ios device. Have you found any solution to it? Is there any workaround?

**Comment by beritsistemas** [comment]
No workaround for me.. seems that the IOS code need a review.

**Comment by AdamKraif** [comment]
Any updates?

**Comment by ihuseynoff** [comment]
I also face the same problem. When I terminate application it stops working in background in real device it works fine in simulator.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
