### ISSUE TITLE
interval option dosen't respected

### ISSUE THREAD

**Issue by MaximilienFaure** [mauron85/cordova-plugin-background-geolocation#298]
## Your Environment

* Plugin version: 2.2.5
* Platform: Android (I didn't test on iOS)
* OS version: 6.0.1
* Device manufacturer and model: asus zenfone selfie
* Cordova version (`cordova -v`): 6.4.0
* Cordova platform version (`cordova platform ls`):android 6.1.2
* Plugin configuration options: 
<plugin name="cordova-plugin-mauron85-background-geolocation" spec="~2.2.5">
        <variable name="ACCOUNT_TYPE" value="$PACKAGE_NAME.account" />
        <variable name="CONTENT_AUTHORITY" value="$PACKAGE_NAME" />
        <variable name="ALWAYS_USAGE_DESCRIPTION" value="This app requires background tracking enabled" />
</plugin>

## Context
when I set an interval option, it not respected, I get location before the and of interval.
I try with 60000, 6000000, 600000000 but I get the same result... 
I think the interval option is not use.

## Expected Behavior
I would get location every 60000ms

## Actual Behavior
I get location based on the distance traveled. If I not move, I don't get location but I move I get location between 0 and 5 minutes while my configuration is : 
backgroundGeolocation.configure(callbackEnregistrementBackground, failureFn, {
                desiredAccuracy: backgroundGeolocation.accuracy.MEDIUM,
                stationaryRadius: 20,
                distanceFilter: 20,
                interval: 60000
            });
            backgroundGeolocation.start();

## Possible Fix
before 2.0.0 version we should use locationTimeout (it is here yet : https://github.com/mauron85/cordova-plugin-background-geolocation/blob/next/ANDROID_DISTANCE_FILTER_PROVIDER.md )
Interval can be use with ANDROID_DISTANCE_FILTER_PROVIDER ? 

## Steps to Reproduce
backgroundGeolocation.configure(callbackEnregistrementBackground, failureFn, {
                desiredAccuracy: backgroundGeolocation.accuracy.MEDIUM,
                stationaryRadius: 20,
                distanceFilter: 20,
                interval: 60000
});
backgroundGeolocation.start();

var callbackEnregistrementBackground = function(location) 
    console.log("location.lat = " + location.latitude + ", loc.lng = " + location.longitude);
}
and see the time on console.

## Context
If I get so much location my power battery's users  decreased so fast !

## Debug logs
the times where I get location : (almost always inferior to 60000ms)
06-06 14:10:43
06-06 14:10:58
06-06 14:11:32
06-06 14:11:37
06-06 14:12:11
06-06 14:12:13
06-06 14:14:58
06-06 14:16:03
06-06 14:16:34
06-06 14:16:37

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
