### ISSUE TITLE
Error on Samsung Galaxy S4 Mini at setColor

### ISSUE THREAD

**Issue by schlomm** [mauron85/cordova-plugin-background-geolocation#3]
Firstly: Great plugin!
Unfortunately I have a problem using the plugin (**version 0.4.3**) with a Samsung Galaxy S4 mini running **Android 4.4.4**.

Once I start the background geolocation service, the app chrashes with the following error:

    java.lang.NoSuchMethodError: android.app.Notification$Builder.setColor
    	at com.marianhello.cordova.bgloc.LocationUpdateService.onStartCommand(LocationUpdateService.java:232)
    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2989)
    	at android.app.ActivityThread.access$2200(ActivityThread.java:174)
    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1404)
    	at android.os.Handler.dispatchMessage(Handler.java:102)
    	at android.os.Looper.loop(Looper.java:146)
    	at android.app.ActivityThread.main(ActivityThread.java:5593)
    	at java.lang.reflect.Method.invokeNative(Native Method)
    	at java.lang.reflect.Method.invoke(Method.java:515)
    	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
    	at dalvik.system.NativeStart.main(Native Method)

After some research, I think the problem is caused by the following line [<-click me->](https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/src/android/AbstractLocationService.java#L92)

As the setColor-function was introduced in API level 21, this might not be available for devices running on Android 4.4.4, which is API level 19 and 20.

Is this issue known? Or maybe it is just a problem with my device?
Thans a lot!

**Comment by mauron85** [comment]
Thank you for your report. I'll check this out. I'll try to release version 0.5.1 with the proper fix and new FusedGeolocation provider, which is currently experimental in 0.5.0

In the meantime you can pin cordova to use version 0.4.2

```
cordova plugin add cordova-plugin-mauron85-background-geolocation@0.4.2
```

or for phonegap build. edit config.xml

```
<gap:plugin name="cordova-plugin-mauron85-background-geolocation" source="npm" version="0.4.2"/>
```

**Comment by schlomm** [comment]
Mauron,
It is absolutely fantastic that you've answered to my issue in this short time. Thanks <3
As I've implemented a GeoFencing App for my master thesis, where the user study will start on Tuesday. For this reason it would be awesome to get a fix from your side.....Then I would be able to get testers owning a smartphone running Android 4.4.

In the mean time, I've flashed my Nexus 5 back to 4.4.2, where the same problem occurs.
I will also flash 4.4.3 and 4.4.4 to see what will happen on those versions...I'll report back in the next couple of minutes

A fix for this issue would be awesome and a donation would be on your way. Also without a proper fix, but as you can imagine: A fix would help me a lot!!!

Thanks so much,
Dominik

**Comment by schlomm** [comment]
Dear Mauron,
Just for verification: I've also flashed Android 4.4.3 and 4.4.4 on my Nexus 5 and I've faced the same problem.
After flashing my device to Android Lollipop 5.0.2 (API Level 21) I am able to use the plugin without any problems.

If I can assist you regarding testing, you can contact me anytime!

All the best
Dominik

**Comment by mauron85** [comment]
Version 0.5.1 with fix is already on npm.

I've made some changes how notifications are build. Basically now it should work on all versions of Android. I've tested on My Nexus4 with 5.1.1 and also on 4.4.4 using genymotion. 

Please let me know if it is fixed for you. You can also test it on SampleApp from example folder, which has been updated recently and now it can send positions to https://background-geolocation-console.herokuapp.com/. You can find more info README.md in SampleApp folder.

Last more thing. It would be great, if you can contribute with geofencing functionality to make plugin better.

**Comment by christocracy** [comment]
I see you've found my [background-geolocation-console](https://github.com/transistorsoft/background-geolocation-console)
