### ISSUE TITLE
No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

### ISSUE THREAD

**Issue by mapolonio** [mauron85/cordova-plugin-background-geolocation#30]
I'm getting this error when trying to run my app. I simply install the plugin and try to run the app, without any change in my code. 

If I remove the plugin and run the app, everything works. So, something wrong is happening with the plugin. The only difference between one case and the other is the presence of the plugin.

Help please.

**Comment by mauron85** [comment]
Do you have google play services installed in Android SDK Manager?

![screenshot 2016-01-26 10 14 12](https://cloud.githubusercontent.com/assets/359450/12576703/d804c22c-c415-11e5-9354-870c808b80c0.png)

**Comment by mapolonio** [comment]
Yes, it is installed. I'm trying in my phone. I'ts a Samsung Galaxy S6, Android 5.1.1, API 22

**Comment by mapolonio** [comment]
Could you post indications for an environment where the plugin works?
(Required packages in SDK, Android version, API, etc..)

Thanks

**Comment by jpuua** [comment]
I was experiencing the same issue. To bypass the issue I had to install Android Support Library, Android Support Repository and Google Repository.
![image](https://cloud.githubusercontent.com/assets/2513370/12615392/175bf398-c50e-11e5-8acd-f572cef8cef4.png)

One out of three mentioned fixed the issue.. Not sure which one :)

**Comment by mapolonio** [comment]
Yes, they are installed.

I managed to make it work. Here is what needed to be done:

-Use Android SDK Build Tools 22.0.1 
-Install the above mentioned

It was imposible to make it work with Android SDK Build Tools 23.0.2. I think it is necesary to clarify the requirements of the plugin in the Readme

**Comment by mauron85** [comment]
@mapolonio I agree that some more information about setup is needed. But you should also realise that in time of writing this plugin build tools were at 22 or less. And I can predict future to see that plugin will not work with future version of build tools.

**Comment by mauron85** [comment]
I'm posting android requirements here before I put them into README.

Android SDK Tools (24.4.1)
Android SDK Platform-tools (23.1)
Android SDK Build-tools (23.0.1)
Android Support Repository (25)
Android Support Library (23.1.1)
Google Play Services (29)
Google Repository (24)

And cordova compatible Android API. Cordova 5.4.1 it is Android API level >14

**Comment by mapolonio** [comment]
Yes, I realise about what you say. That's why this kind of issues is useful: to identify what problems start to appear as dependencies evolve ;)

**Comment by mauron85** [comment]
Agree on that :-) I've added section Compilation with list of deps for Android. Closing this one.
