### ISSUE TITLE
Background tracking stops after some point on Android 7.0 +

### ISSUE THREAD

**Issue by smchae** [mauron85/cordova-plugin-background-geolocation#301]
I am using this plugin to track all the user's location, however, I discovered that some users' locations were not updating. And I observed that users with Android Version of 7.0+ were the ones who could not be tracked.

## Your Environment

* Plugin version:  2.2.5
* Platform: Android
* OS version: 7.0
* Device manufacturer and model: Samsung Galaxy S7
* Cordova version (`cordova -v`):  6.5.0
* Cordova platform version (`cordova platform ls`):  android 6.1.2
* Plugin configuration options: 
```
const config: BackgroundGeolocationConfig = {
            locationProvider: this.backgroundGeolocation.LocationProvider.ANDROID_ACTIVITY_PROVIDER,
            url: some API URL,
            desiredAccuracy: 10,
            stationaryRadius: 1,
            distanceFilter: 1,
            interval: 60000,
            maxLocations: 2,
            syncThreshold: 1,
            startOnBoot: true,
            startForeground: false,
            stopOnTerminate: false,
            stopOnStillActivity: false,
            activitiesInterval: 60000,
            fastestInterval: 60000
        };
```
* Link to your project:

## Context

Looking at Android 7.0 documentation, I was able to discover `Project Svelte: Background Optimizations` which basically minimize the background process. So I am guessing not being able to update some users' locations is because of this added feature.

## Expected Behavior

I want to be able to track users' location regardless of their OS version and their activity (I want their locations to be updated even in still activity)

## Actual Behavior

Users with Android Version of 7.0 + do not update their locations after certain point if they do not launch/use an app.

## Possible Fix

Android documentation suggests to use `JobScheduler` or `GcmNetworkManager` for background process.

## Steps to Reproduce

1. Install an app with configuration above on android phone with OS version of 7.0 +.
2. Observe the location that app is sending.
3. Wait until the app stops sending its location
4. Make sure GPS is enabled and app is not uninstalled

**Comment by diey** [comment]
I'm also experiencing this issue.

**Comment by maxHus** [comment]
did you try setting Doze off for your devices.. try putting your Application in "Not Optimized" list

**Comment by nimeso** [comment]
Same issue here. It runs in the background fine but after about 40secs the phone goes in sleep mode and stops tracking, I've installed insomnia and that works great with everything else but not background geolocation. This is holding back a release and people are getting pissed off. Please help :)

**Comment by maxHus** [comment]
@nimeso try putting your Application to Not Optimized

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
