### ISSUE TITLE
Track geolocation with shutdown screen on Android Devices

### ISSUE THREAD

**Issue by tux240** [mauron85/cordova-plugin-background-geolocation#303]
Hello,

Is it possible to track some positions with a shutdown Android device screen ?
Is there a special option to enable ?

Thanks

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
