### ISSUE TITLE
Bakground Location Fetching not working

### ISSUE THREAD

**Issue by anusree-mmlab** [mauron85/cordova-plugin-background-geolocation#304]
Background location fetching ends after 1 or 2 minutes. It does not turn the GPs on, or the tracking unless i go to the app screen again and again. It showing the 'Exit message' toas in 1- 2 minutes.

## Your Environment

* Plugin version: 2.2.5
* Platform: Android
* OS version: 6.01
* Device manufacturer and model: XIOMI Redmi Note 3
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`):Installed platforms:
  android 6.2.3
  ios 4.4.0

* Plugin configuration options: 

desiredAccuracy: 0,
            stationaryRadius: 1,
            distanceFilter: 1, 
            debug: true,
            interval: 10000 ,
            stopOnTerminate: false,
* Link to your project: It is in development mode

## Expected Behavior

It should continue work in the background, even if i turned off the screen, until i stops background tracking.

## Actual Behavior

It shows the background tracking info even though the app is in foreground. It continue to show the toast messages after 1 minute till i exit from the app screen. After that most of the time it says stationary exit. The GPS signal is no longer in the navbar of my device.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by arapocket** [comment]
Many others are having the same problem as well. This really sucks.

**Comment by jleal52** [comment]
Try to put you app in "Protected Mode" for Huawei Devices, or as "Not Optimized" in other manufacturers. This says to Android not to close your App when then screen shuts down.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Comment by ruben82** [comment]
HI @mauron85  any news about this issue? Thanks' in advance

**Comment by mauron85** [comment]
Have you tried any other provider than DISTANCE_FILTER? Try new RAW_PROVIDER, so we can isolate it to specific provider or plugin as issue.
