### ISSUE TITLE
Saving locations to storage offline

### ISSUE THREAD

**Issue by ittesla** [mauron85/cordova-plugin-background-geolocation#305]
The whole idea is to save all locations on device , either local storage, or saving it directly to file. but problem is that when I close app (either move it to the background or close it completely) App will not save any locations. I have tried with pure js local storage which will work if i move it in background but will not work if i close the app.I can still do getValid locations , and delete them after, but that is not proper fix for me.
Here are is my setup
this.logEvery = 10
  const config: BackgroundGeolocationConfig = {
        desiredAccuracy: 0,
        stationaryRadius: 1,
        distanceFilter: 1,
        debug: false,
        stopOnTerminate: false, 
        stopOnStillActivity: false,
        interval: this.logEvery * 1000,
        fastestInterval: this.logEvery * 1000,
        activitiesInterval: this.logEvery * 1000,
        locationProvider: 1
      };
 this.backgroundGeolocation.Mode = 0

  this.backgroundGeolocation.configure(config)
        .subscribe((location: BackgroundGeolocationResponse) => {
   
         var locationData: any = localStorage.getItem('test');
         locationData = JSON.parse(locationData)
         locationData.push(location)
         localStorage.setItem('test', JSON.stringify(locationData))
         this.backgroundGeolocation.finish();
 
});

Is there any other way to save locations locally while app is in background or closed

**Comment by Jeet0027** [comment]
You can not store it in local storage when the app is closed as plugin runs its own pure native code even when the application is closed. 
Solution.  send the locations to the server using **url**  config setting and fetch from db (Server) on the time of login in app

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
