### ISSUE TITLE
Plugin causes issue with websql and sqlite

### ISSUE THREAD

**Issue by netbitsolutions** [mauron85/cordova-plugin-background-geolocation#31]
Hi, i implemented the plugin on my project. On doing this, i observed some sql inconsitency, quries  now return zero results sometimes but once remove the call to the plugin in my project, everthing works just fine.

**Comment by mauron85** [comment]
Which platform?

**Comment by netbitsolutions** [comment]
Oh , sorry for the false alarm i was actually doing something wrong.But its ok now
