### ISSUE TITLE
How to know if the user stops ?

### ISSUE THREAD

**Issue by TraceDeTrail** [mauron85/cordova-plugin-background-geolocation#311]
Hello,

Is there a way to be notified when the user stops (speed=0) ?
I want to display the speed on the screen and for the moment, I can't know when the speed is null...

Thanks in adavance !

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
