### ISSUE TITLE
How enable provider GPS  in ionic 2?

### ISSUE THREAD

**Issue by maykelrodrigues** [mauron85/cordova-plugin-background-geolocation#312]
The device is capturing the same location, possibly because it is using the network.
I wish he would start using GPS to capture the location.

`let config = {
        desiredAccuracy: 10, // desired accuracy in meters. Possible values [0, 10, 100, 1000]
        stationaryRadius: 20, // 20
        distanceFilter: 10, // the minimum distance
        debug: false, //  enable this hear sounds for background-geolocation life-cycle.
        stopOnTerminate: true, // enable this to clear background location settings when the app terminates
        interval: 2000
      };`

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
