### ISSUE TITLE
missing body when request on POST url

### ISSUE THREAD

**Issue by usama-ayub** [mauron85/cordova-plugin-background-geolocation#314]
client side code:
let config: BackgroundGeolocationConfig = {
      desiredAccuracy: 10,
      stationaryRadius: 1,
      distanceFilter: 1,
      debug: true,
      stopOnTerminate: false,
      url: 'https://classified-app-server.herokuapp.com/api/tracker'
    };

server side code:
 function tracker(req, res, next) {
    let body = req.body;
    return console.log('tracker work' + body.longitude + body.latitude);
   }

response of api is undefined.

**Comment by bharat-saralweb** [comment]
Your server side code should look like this:
function tracker(req, res, next) {
    let body = req.body;
    resp.send('tracker work' + body.longitude + body.latitude);
}

**Comment by bharat-saralweb** [comment]
Your server side code should look like this:
function tracker(req, res, next) {
    let body = req.body;
    res.send('tracker work' + body.longitude + body.latitude);
}

**Comment by usama-ayub** [comment]
i change code with this:
function tracker(req, res, next) {
    let body = req.body;
    console.log('Body:',body.longitude,body.latitude)
    res.send('tracker work' + body.longitude + body.latitude);
}
and the response is this : Body: undefined undefined

**Comment by bharat-saralweb** [comment]
Hi @usama-ayub It might have too late to reply, but may be helpful for others,
**req.body** is array of location objects, so you have to loop through to get each location object:
`res.send('tracker work' + body[0].longitude + body[0].latitude);
`
You can loop through all the location objects like below:
```
body.forEach(function(location) {
    console.log('longitude: ' + location.longitude + ' latitude: ' + location.latitude);
})
```
Above block of code will show you all the lat long values from body.

**Comment by bharat-saralweb** [comment]
Hi @usama-ayub It might have been too late to reply, but may be helpful for others,
**req.body** is array of location objects, so you have to loop through to get each location object:
`res.send('tracker work' + body[0].longitude + body[0].latitude);
`
You can loop through all the location objects like below:
```
body.forEach(function(location) {
    console.log('longitude: ' + location.longitude + ' latitude: ' + location.latitude);
})
```
Above block of code will show you all the lat long values from body.

**Comment by usama-ayub** [comment]
i will try later no problem for late reply may be it help in future thanks for your reply

**Comment by mauron85** [comment]
as @bharat-saralweb wrote. Locations are always sent in array. Closing.
