### ISSUE TITLE
License validation is failure. Background is running in evolution mode IONIC 2

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [mauron85/cordova-plugin-background-geolocation#315]
## Your Environment
IONIC 2
Android
## Context
 I am using sample application for cordova-plugin-background-geolocation
but on configuring method. I keep getting error
License validation is failure. Background is running in evolution mode

https://ionicframework.com/docs/native/background-geolocation/

**Comment by mauron85** [comment]
This plugin is completely free and doesn't require any license. Probably you're using https://www.transistorsoft.com/shop/products/cordova-background-geolocation

**Comment by Gurjit-ONEBCG** [comment]
Yes, I noticed .

Thanks
