### ISSUE TITLE
[Question] Schedule geolocation in background mode - track only certain timeframe

### ISSUE THREAD

**Issue by matheusdavidson** [mauron85/cordova-plugin-background-geolocation#316]
## Information

Hi there, i have an app to track parents on the way to grab their children in school, so the school is notified when they get near. I'm using this plugin very successfully for this job.

The problem is that the app needs to track people only in certain timeframes, but currently i`m tracking them all day and i have the fixed notification showing all the time(i know this is needed for accuracy). So to fix this problem, i need some way to start this plugins in background mode/app killed, as the app just need to be installed for tracking purposes and its not very likely to be used in foreground.

I tried many ways to deal with this using other cordova plugins to start this one, but i didn`t find a good solution because javascript won`t run in background mode or when app is killed. 

Yesterday i found Cordova Geofence Plugin, that execute a callback when user gets inside/outside a geofence(around the school in my case) and it triggers a callback, i could start your plugin from this callback in background mode, but when app is killed, geofence plugin won`t run the javascript code, instead is gives me an event inside java(https://github.com/cowbell/cordova-plugin-geofence#listening-for-geofence-transitions-in-native-code), so thought i could remove all the javascript/callback code and use only java to start background geolocation even with the app in background or killed.

## Questions

**So my questions are:** 
How can i start your plugin from java(is it possible/i have limited java knowledge)? (https://github.com/cowbell/cordova-plugin-geofence#listening-for-geofence-transitions-in-native-code)

Is there a way i can schedule background geolocation to start/stop in certain timeframes? So it would be off when outside the timeframe(i mean, no tracking, no fixed notification) and turn on inside the timeframe?

Sorry for the long text, needed to explain what my use case is. Thank you.

## Environment

plugin version:

    cordova-plugin-mauron85-background-geolocation : 2.2.5 "CDVBackgroundGeolocation"

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.2.0

System:

    Node       : v6.10.2
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.1 Build version 8E1000a 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    npm        : 3.10.10

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
