### ISSUE TITLE
Can not build iOS (Salesforce Plugin + cordova-plugin-background-geolocation) - Error code 65

### ISSUE THREAD

**Issue by Caballer0** [mauron85/cordova-plugin-background-geolocation#317]
## Your Environment

* Plugin version: 2.2.5
* Platform: iOS
* OS version: macOS Sierra
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`): iOS@4.4.0 (needed by Salesforce plugin)

## Context

I am trying to build an hybrid iOS application that need to have Salesforce SDK plugin (https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin) and Background geolocation integrated. When I try to build the project it fails always with the following trace:

![image](https://user-images.githubusercontent.com/30310618/28404412-79bb862e-6d29-11e7-92d7-f035ff44d099.png)

I have removed all the others plugin installed in my project and I exclusively left these two plugins. If I remove one of this two plugins I can build and run well my application. So the incompatibility is between this plugins.

Can you try to reproduce my error following this steps? 

## Steps to Reproduce

1. Add iOS@4.4.0 platform
2. Add mauron85/cordova-plugin-background-geolocation plugin.
3. Add Salesforce plugin (v 5.2.0) with: _cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin --force_ (it has to be the last plugin inserted)
4. In Xcode Go to project -> Capabilities -> Active "KeyChain Sharing"
5. Build iOS: _cordova build ios_

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
