### ISSUE TITLE
this plugin sending location on server only once in background

### ISSUE THREAD

**Issue by vipulgit77** [mauron85/cordova-plugin-background-geolocation#318]
i want to send gps location on server  every 5 second please help me .. 
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="msapplication-tap-highlight" content="no" />
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width" />
    
    <meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline'; style-src 'self' 'unsafe-inline'; media-src *" />
    
    

     <script type="text/javascript" src="cordova.js"></script>
     <script type="text/javascript" src="lib/jquery.js"></script>
    <title>Hello World</title>
    <script>
document.addEventListener('deviceready', onDeviceReady, false);
//onDeviceReady ();
function onDeviceReady () {

    /**
    * This callback will be executed every time a geolocation is recorded in the background.
    */
    var callbackFn = function(location) {

       // console.log('[js] BackgroundGeolocation callback:  ' + location.latitude + ',' + location.longitude);
//alert('[js] BackgroundGeolocation callback:  ' + location.latitude + ',' + location.longitude)
        // Do your HTTP request here to POST location to your server.
        // jQuery.post(url, JSON.stringify(location));

        /*
        IMPORTANT:  You must execute the finish method here to inform the native plugin that you're finished,
        and the background-task may be completed.  You must do this regardless if your HTTP request is successful or not.
        IF YOU DON'T, ios will CRASH YOUR APP for spending too much time in the background.
        */
       // backgroundGeolocation.finish();
       var lati=location.latitude;
       var longi=location.longitude;
       //alert(longi);
        //ajaxlat(lati,longi);

 var id=6;
//alert(lati);
  //navigator.geolocation.getCurrentPosition(function(position) {  
    
    $.ajax({
    type       : 'get',
    url        : 'url',
    //data       :  myKeyVals,
     crossDomain: true,
     data       : { tutor_id:id,route_latitude:lati,route_longitude:longi },
    dataType   : 'json',
    async : false,
     
    success : function(data) {
      //window.localStorage.setItem("loggedIn", 1);

       
    });
     // backgroundGeolocation.start();

}, 
 error : function() {

  //alert('error');
            }

     
}); 

    };

    var failureFn = function(error) {
        console.log('BackgroundGeolocation error');
        alert('BackgroundGeolocation error')
    };

    // BackgroundGeolocation is highly configurable. See platform specific configuration options
    backgroundGeolocation.configure(callbackFn, failureFn, {
        desiredAccuracy: 10,
        stationaryRadius: 20,
        distanceFilter: 30,
        debug:true,
        interval: 5000
       
    });

    // Turn ON the background-geolocation system.  The user will be tracked whenever they suspend the app.
    backgroundGeolocation.start();

    // If you wish to turn OFF background-tracking, call the #stop method.
    // backgroundGeolocation.stop();
//backgroundGeolocation.finish();
   // setTimeout(callbackFn,5000);
}

/*
        function ajaxlat(lati,longi){
    var id="6";
//alert(lati);
  //navigator.geolocation.getCurrentPosition(function(position) {  
    
    $.ajax({
    type       : 'get',
    url        : 'https://www.tutago.com/api/accounts/latlong_update',
    //data       :  myKeyVals,
     crossDomain: true,
     data       : { tutor_id:id,route_latitude:lati,route_longitude:longi },
    dataType   : 'json',
    async : false,
     
    success : function(data) {
      //window.localStorage.setItem("loggedIn", 1);

alert(JSON.stringify(data));
       
      

}, 
 error : function() {

  //alert('error');
            }

     
}); 

    //return lat;
//setTimeout(callbackFn, 5000);  

}

*/
//callbackFn();

</script>
</head>

<body>

    
    
</body>

</html>

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
