### ISSUE TITLE
Is there an easy way to force the user to enable the GPS ?

### ISSUE THREAD

**Issue by jgauna** [mauron85/cordova-plugin-background-geolocation#319]
## Your Environment

* Plugin version: Latest
* Platform: Android
* OS version: 6.0.0
* Device manufacturer and model: All
* Cordova version (`cordova -v`): 6
* Cordova platform version (`cordova platform ls`): Android 6.0.0
* Plugin configuration options:  The simplest one
* Link to your project: -

## Context
I'm trying to find an easy way to force the user to enable the GPS and if not, close the app.

## Expected Behavior
There should be an easy way to detect whether the user is not enabling the location services after the ```showAppSettings()``` method.

## Actual Behavior
I think a good option would be that the ```showAppSettings()``` returns an ```enabled``` option.

## Possible Fix
Maybe ```showAppSettings()``` could return an ```isEnable``` option.

## Steps to Reproduce

- The app starts and you show an modal saying "Enable the location services"
- The user taps on "Ok" and the app shows the location settings
- The user tap on "back" without enabling the location services
- You can know if the user have enabled the location services using the callback from ```showAppSettings()```

## Context
Trying to force the user to have the location services (gps) enable

**Comment by emc2spider** [comment]
Hi @jgauna,
I use this plugin for the permission settings: https://github.com/dpa99c/cordova-diagnostic-plugin
My app requires other services besides the GPS tracking so I find it useful to have permission settings centralised.

**Comment by jgauna** [comment]
Nice solution! Thanks.
