### ISSUE TITLE
2.16 - Multitasking Apps may only use background services for their intended purposes: VoIP, audio playback, location, task completion, local notifications, etc.

### ISSUE THREAD

**Issue by jjgarciadev** [mauron85/cordova-plugin-background-geolocation#32]
Our app has been rejected by Apple due to 2.16 - Multitasking Apps may only use background services for their intended purposes: VoIP, audio playback, location, task completion, local notifications, etc.

We have enabled Location Updates, Background Fetch and Remote notifications in Xcode's Background Modes.

We don't know why Apple has been rejected out app.
Our app needs to send locations to server when is in background.

Could you help us to solve this problem?

Regards

**Comment by mauron85** [comment]
Hi @jjgarciadev. I'm about to send my own iOS application, that is using bg services to the app store. Yes they're very cautious when apps are doing location tracking in the background, so I'm expecting problems too. But to raise my chances to be approved, I'll create application walkthrough, where I'll explain what for I need background updates and hopefully the apple team will understand, that's for good thing. But that's pretty much you can do about it.

**Comment by jjgarciadev** [comment]
Thans for your reply.

I understand that Location updates must be enabled in Xcode's Background modes and otherwise background geolocation doesn't work properly.

We have Location updates, Background Fetch and Remote notifications enabled in Xcode´s Background modes. Do we need to enabled Background Fetch?

**Comment by jjgarciadev** [comment]
Your app declares support for location in the UIBackgroundModes key in your Info.plist file but does not declare any features that require persistent location. Apps that declare support for location in the UIBackgroundModes key in your Info.plist file must have features that require persistent location.

**Comment by mauron85** [comment]
Background Fetch and Remote notifications are not necessary.

**Comment by mauron85** [comment]
Also check http://stackoverflow.com/questions/29406588/apple-binary-rejected-2-16

**Comment by jjgarciadev** [comment]
We use remote notifications with OneSignal plugin but we are not sure about background fetch.

We don't know what to do with this problem because our app works properly but Apple ... 

Thanks a lot for your reply.

**Comment by jjgarciadev** [comment]
Our app also need geolocation when app is in foreground.

**Comment by jjgarciadev** [comment]
Hi @mauron85 Do I use useSignificantChangesOnly: true or this is enabled by default?
My bgGeo.configure section is like that:
bgGeo.configure(callbackFn, failureFn, {
          desiredAccuracy: 10,
          stationaryRadius: 15,
          distanceFilter: 25,
          useSignificantChangesOnly: true,
          debug: true,
          stopOnTerminate: false       
});

Thanks in advance

**Comment by jjgarciadev** [comment]
Hi @mauron85 
Apple has answered to our claim:

Thank you for your reply. Please note that upon further review with the information provided we found your app to be out of compliance with Guideline 2.16 as it does not contain a feature that requires persistent location tracking.

You may wish to use the significant-change location service or the region monitoring location service if persistent real-time location updates are not required for your app features.

Resources

For more information, please review the Starting the Significant-Change Location Service and Monitoring Shape-Based Regions. 

I don't know what to do about that !!!

If we disabled Location updates our app doesn't work how we expected..

**Comment by mauron85** [comment]
@jjgarciadev 
There is no such option useSignificantChangesOnly in my version. Maybe you're using cordova-background-geolocation-lt? And yes, significant cache location in current implementation is not usable for real time tracking. Not sure if it can be improved.

**Comment by jjgarciadev** [comment]
Hi @mauron85,
we are using your plugin but we don't know if useSignificantChangesOnly was implemented on it.
We don't understand when Apple says "... it does not contain a feature that requires persistent location tracking."
It would be interesting to improved significant change location to avoid problems with Apple, when publishing the application.

**Comment by mauron85** [comment]
@jjgarciadev I think you can disable background locations capability and get accepted by apple. I'm not 100% sure yet, but this plugin does not use background locations anyway. It uses significant changes and those does not require background locations to work.

EDIT: you have to edit package.json of this plugin and remove lines:
```
        <config-file target="*-Info.plist" parent="UIBackgroundModes">
            <array>
                <string>location</string>
            </array>
        </config-file>
```

Of course try it first on your dev iphone.

**Comment by jjgarciadev** [comment]
Hi,
If I disable Location updates Xcode shows me the following message and position is not send to server.

exeption nativeEvalAndFetch : TypeError: undefined is not an object (evaluating 'bgGeo.start')

Thanks for your time and information.

**Comment by mauron85** [comment]
Ok, I must admit I was wrong about not using background updates. They're used. But they can be replaced with significant changes only, that's actually what is implemented in recent version of cordova-background-geolocation-lt options [useSignificantChangesOnly](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/api.md#param-boolean-usesignificantchangesonly-false).

Bu there is another reason, why your app was rejected. I mentioned it already in [here](https://github.com/mauron85/cordova-plugin-background-geolocation/issues/26#issuecomment-172496547). I'll quote apple docs.
>
in iOS 9 and later, regardless of deployment target, you must also set the allowsBackgroundLocationUpdates property of the location manager object to YES in order to receive background location updates. By default, this property is NO, and it should remain this way until a time when your app actively requires background location updates.

And this plugin was not upgraded for iOS 9.x, so it's missing that option. I'm working on it. But you can add it yourself and try build your app and resend for review. Fingers crossed

**Comment by jjgarciadev** [comment]
I have been reading information about cordova-plugin-geolocation-ios9-fix but I have doubts about the use of this plug-in. Do I have to install this plugin and remove cordoba-plugin-geolocation?

**Comment by jjgarciadev** [comment]
Thank you so much for your time and information
We have decided to remove background geolocation until we have under control new Apple’s requirements for iOS 9.2

We hope Apple publish our app removing Location updates.

After that we are going to implement background geolocation without be in a hurry!!

Best regards,

José J. GARCIA

**Comment by mauron85** [comment]
Make sense, good luck with your app. Reopen if needed.
