### ISSUE TITLE
Can we Set interval variable for IOS devices if not ... how to achieve to capture location every 15 min

### ISSUE THREAD

**Issue by sudhakar77** [mauron85/cordova-plugin-background-geolocation#320]
## Your Environment

* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
