### ISSUE TITLE
Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.0.1.

### ISSUE THREAD

**Issue by shahdeep1989** [mauron85/cordova-plugin-background-geolocation#323]
## Your Environment

* Plugin version: latest on git
* Platform: Android
* OS version: 
* Device manufacturer and model:
* Cordova version (`cordova -v`): 7.0.1
* Cordova platform version (`cordova platform ls`): android and ios (but issue in cordova build android )
* Plugin configuration options: 
* Link to your project:

## Context

When I am trying to prepare android build via "cordova build android" getting build failed:

## Expected Behavior

It should build android successfully.

## Actual Behavior

BUILD FAILED

Total time: 12.582 secs
Error: /Users/Shivank/Build/agentapp/limolushagentapp/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.0.1.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

## Possible Fix

When I am using this plugin and push plugin(https://github.com/phonegap/phonegap-plugin-push) together I am getting this error.

## Steps to Reproduce

1. install https://github.com/phonegap/phonegap-plugin-push and https://github.com/mauron85/cordova-plugin-background-geolocation plugin together.
2. If we use single plugin it will work well
3.
4.

**Comment by markdegrootnl** [comment]
+1

**Comment by shahdeep1989** [comment]
What do you mean by +1? Where should I add +1?

**Comment by agil-NUBBA** [comment]
https://github.com/YosuaZ/cordova-plugin-background-geolocation/commit/020eaa537e4a7a3b0b965295dacee764eda736a5

**Comment by markdegrootnl** [comment]
Sorry. +1 means I also experience this issue. The fix from @agil-NUBBA looks good!

**Comment by ArielMorningstar** [comment]
How can I use the fix of @agil-NUBBA ?

**Comment by mauron85** [comment]
Sorry guys, but I don't think updating version number every time is sustainable for me in a long run. It might work for you combination of plugins, but will not run with other.

**Comment by shahdeep1989** [comment]
@markdegrootnl still getting the same issue.

**Comment by markdegrootnl** [comment]
What other plugins do you use that might be using google services?

**Comment by shahdeep1989** [comment]
Push plugin (FCM - Firebase)
https://github.com/phonegap/phonegap-plugin-push

**Comment by shahdeep1989** [comment]
Getting below issue while preparing iOS build (cordova build ios). Android build is working well.

ld: 117 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld build/emulator/RR\ Operator.app/RR\ Operator normal x86_64
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Applications/app/platforms/ios/cordova/build-debug.xcconfig,-workspace,RR Operator.xcworkspace,-scheme,RR Operator,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone SE,build,CONFIGURATION_BUILD_DIR=/Applications/app/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Applications/app/platforms/ios/build/sharedpch

**Comment by emc2spider** [comment]
Hello, I'm also experiencing this issue. Is this going to be fixed soon? or is the only available solution to use @agil-NUBBA's plugin fork?

**Comment by emastyle** [comment]
Hello, same issue here:
Plugin I'm using:
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
**cordova-plugin-fcm 2.1.2 "FCMPlugin"**
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"

Seems conflits with FCMPlugin and seems not fixed yet.

**Comment by mauron85** [comment]
Once again. Do you guys realise that you want to me to hardcode dependency version just to make this plugin compatible with other. I can exactly say, that go and fill issue in phonegap-plugin-push to make it compatible with this plugin.

That's not way to go. Sorry. Won't fix./

**Comment by mauron85** [comment]
After some investigation I think we can however get some compatibility.

Starting version 2.3.3 you can override google play version to match your other plugin (cordova-plugin-fcm).

Read updated section [Installing plugin](https://github.com/mauron85/cordova-plugin-background-geolocation#installing-the-plugin) for more information.

**Comment by christocracy** [comment]
We plugin developers are going to need to settle on a common name for this.

I use `GOOGLE_API_VERSION` (to be common to both firebase as well as play-services, which must both be aligned to the same version).

I've seen `FCM_VERSION` and `GMS_VERSION` as well.

**Comment by christocracy** [comment]
@mauron85 Cordova `>=7.1.0` / `cordova-android >=6.3.0` are required for evaluating a `<preference />` in a `<framework />` tag.

@See [this commit](https://github.com/phonegap/phonegap-plugin-push/commit/468f6001c24a0e4889f64ad384f86585ff22ba9b) at `phonegap-plugin-push` (who instigated this feature with Cordova).

**Comment by mauron85** [comment]
Thank you for mentioning that. In Docs it's already required. But need to update plugin.xml.

As there is no better way, old cordova version from this momemt not supported.

**Comment by christocracy** [comment]
I feel that providing a mechanism to solve the infamous gradle conflicts between plugins far outweighs the issues created forcing developers to upgrade to cordova `>=7.1.0`.

**Comment by mauron85** [comment]
So what is your suggestion?

**Comment by christocracy** [comment]
> old cordova version from this momemt not supported.

That *is* my suggestion

**Comment by mauron85** [comment]
Ok. Got you. Didn't read your response properly at first time, thinking you are against it.
