### ISSUE TITLE
Build Error after installation

### ISSUE THREAD

**Issue by ReemaBegum** [mauron85/cordova-plugin-background-geolocation#326]
Hi,

I have installed this  plugin after build its showing error 
 My Cordova Version :6.1.1

Error		.....\platforms\android\res\xml\authenticator.xml:6:24-43 : AAPT: No resource found that matches the given name (at 'Icon' with value '@mipmap/ic_launcher')
Error		.....\platforms\android\res\xml\authenticator.xml:6:24-43 : AAPT: No resource found that matches the given name (at 'smallIcon' with value '@mipmap/ic_launcher')

Severity	Code	Description	Project	File	Line	Suppression State
Error		Execution failed for task ':processDebugResources'.	SS_V2_15		1

Can you plz help ?

**Comment by ArielMorningstar** [comment]
I have the same error :(

**Comment by Snowbunny** [comment]
Me too. Phonegap 6.3.0

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
