### ISSUE TITLE
iOS infrequent location updates

### ISSUE THREAD

**Issue by cofetti** [mauron85/cordova-plugin-background-geolocation#33]
Hi

I have some trouble with iOS. I've been testing with two iPhones (5 and 6, both 9.2) and also runnig SportsTracker on one of them to compare the results.

If I test my app with a simulator and select "city run" or similar, I get constant location updates and everything seems fine.

However with a real phone in my city (Helsinki, Finland) it works really strange. I ride the bus and monitor the app's log. The log might say "engaging agressive mode" and then nothing happends for several minutes (up to 7 minutes in my testing). Plugin gets no location for 7 minutes.

I also had issues with stationaryRadius. The plugin might output "continue stationary" even though the bus's been going for a minute. On the ohter hand it might suddenly exist the stationaryRegion while the bus is still at a bus stop. I tried using changePace to keep it always moving, but the problem describes above still prevents me from getting accurate results.

In the end if I follow a straight road total distance is fine with infrequent location updates. But if the bus turns a lot in a small block area the result can be half of the real distance.

Do you know what could be causing this issue? I get no explanation from the plugin's console output. As if it just stopped doing anything for several minutes.

**Comment by mauron85** [comment]
Hi @cofetti That's the actually the point of existence the whole plugin :-). To save battery by polling sensors efficiently, based on speed you're moving. If you need regular intervals, than use cordova-geolocation plugin (does work only in foreground). Or for ios only there is [cordova-background-geolocation-lt](https://github.com/transistorsoft/cordova-background-geolocation-lt), which has option disableElasticity, which should behave as you want.

**Comment by cofetti** [comment]
You're saying it's normal to not get any location update for 7 minutes _while moving 30-40 km/h_?

**Comment by mauron85** [comment]
I start reading, when the issue comment was empty. So I didn't have all informations. I'll get back to this later.

**Comment by cofetti** [comment]
Yes, sorry, I misclicked while creating the issue.

**Comment by mauron85** [comment]
Hi, can plz try 0.9.2 if it resolve your issue? It's already in npm.

**Comment by cofetti** [comment]
Thanks, I'll try it over the weekend.
Can you please explain, what does using `changePace(true)` give me? Does it disable the `stationaryRadius` functionality? Will it still use the Significant Changes API? I don't really believe Significat Changes API is good for Finnish countryside :(

**Comment by mauron85** [comment]
Maybe give a try to new version 0.9.3. Many thing was fixed. Check CHANGES.md

**Comment by mauron85** [comment]
@cofetti any news? is it working for you now?

**Comment by cofetti** [comment]
Hi! I made a test today morning with an Android and two iPhones, one of which was set to permanent moving mode with setPace. The scenario wasn't exactly like before, because I was in a car, not a bus, and I barely had to stop at all.

The permanent moving mode iPhone got 10.9 km which I think is exactly right (yay). The Android got 10.7 km, which is just fine. The second iPhone got 10.1 however, which isn't good because we wan't to an error margin of no more than 5%. I also believe that the error will be bigger when I stop more often. It's also worth noting that I was following a fairly straight road, so the error will be bigger in the city.

I will perform the same test in a bus in a traffic jam next week. I will be able to monitor the phone and see if it stops getting updates for periods of time.

**Comment by cofetti** [comment]
Yeah, the stationary functionality doesn't work well. And my app is supposed to work everywhere in Finland, not just Helsinki...

Today it took the phone up to 2km to exit stationary radius in a bus at about 50 km/h. 2km with no location updates is not good.

**Comment by cofetti** [comment]
Our tester tried driving in the countryside and said that her phone failed to get location for 6.7 km. That's with constant moving mode on. Any ideas?

**Comment by mauron85** [comment]
This is strange. Last time I checked it was working perfectly fine. What is your configuration settings?

**Comment by cofetti** [comment]
desiredAccuracy: 1
distanceFilter: 5
stationaryRadius: 10
locationService: 0
locationTimeout: 5
fastestInterval: 5
stopOnTerminate: true
activityType: 'AutomotiveNavigation'

I also do a bgGeo.changePace(true)

**Comment by mauron85** [comment]
Try upcoming version 2.0. And reopen when necessary.
