### ISSUE TITLE
Ability to customize "dummy" account name.

### ISSUE THREAD

**Issue by unixmonkey** [mauron85/cordova-plugin-background-geolocation#331]
https://github.com/mauron85/cordova-plugin-background-geolocation/blob/e9022591a78eeda9fb059c9c5e3b5fa9ac81e129/android/plugin/src/main/java/com/marianhello/bgloc/sync/AuthenticatorService.java#L9

Is there a way to customize this value from an app that uses this plugin?

It is visible in some versions of Android, when browsing to "Settings -> Accounts -> My App", and I feel that seeing the word "dummy" associated with apps that use this plugin to be undesirable.

Ideally, I think I'd like to be able to set a `<variable name="ACCOUNT_NAME" value="myAppName" />` in __config.xml__, and have "myAppName" be used in place of "dummy".

## Environment
* Plugin version: 2.2.5
* Platform: Android
* OS version: macOS High Sierra (10.13), Android 7.0
* Device manufacturer and model: Motorola G4
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`): android 6.2.3
* Plugin configuration options: 
```xml
<plugin name="cordova-plugin-mauron85-background-geolocation" spec="~2.2.5">
    <variable name="ACCOUNT_TYPE" value="$PACKAGE_NAME.account" />
    <variable name="CONTENT_AUTHORITY" value="$PACKAGE_NAME" />
    <variable name="ALWAYS_USAGE_DESCRIPTION" value="This app requires background location tracking" />
</plugin>
```

**Comment by mauron85** [comment]
PR merged in 2.3.0. Thank you.
