### ISSUE TITLE
Is there any way of scheduling the background geolocation plugin to run for a specific period of time ?

### ISSUE THREAD

**Issue by swa06** [mauron85/cordova-plugin-background-geolocation#333]
Is there any possible way to stop the plugin after eight hours or schedule it for specific period of time. Below is my ionic info,

**cli packages:**
```
@ionic/cli-plugin-proxy : 1.4.13
@ionic/cli-utils        : 1.13.1
ionic (Ionic CLI)       : 3.13.1
```
global packages:

**cordova (Cordova CLI) :** 7.1.0
**local packages:**
```
@ionic/app-scripts : 3.0.0
Cordova Platforms  : android 6.3.0
Ionic Framework    : ionic-angular 3.7.1
```
**System:**
**Android SDK Tools :** 26.0.2
Node              : v6.10.2
npm               : 5.5.1

Stackoverflow link:
[https://stackoverflow.com/questions/46950830/i-am-trying-to-schedule-an-ionic-cordova-background-geolocation-plugin-is-it-pos](url)

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
