### ISSUE TITLE
#Not working in ios 11.1, and device in motion

### ISSUE THREAD

**Issue by Ravi448** [mauron85/cordova-plugin-background-geolocation#336]
<H2>OS Version 11.1</h2>
The app works well in Android and iOS 10 in both background and foreground. But in OS11.1 it do not send current location if the device is in motion(During travel and speed goes up). If I slow down, it send the location. But if speed goes up, It sends the location when I was in slow motion. I'm not getting why this happens. It continuously sends location, but the location of stationary position, not of current.

**Comment by juancafe4** [comment]
Hi, I have a question do you location is set up while using the app or always. My case is in 11.1 it only get location while using the app

**Comment by Ravi448** [comment]
I've set location to always
Background as well as foreground

**Comment by juancafe4** [comment]
How you set up to always ?

**Comment by juancafe4** [comment]
BTW people are saying this repo is dead. We should use this one https://github.com/transistorsoft/cordova-background-geolocation-lt

**Comment by christocracy** [comment]
I'm the author of `cordova-background-geolocation-lt`.  You'll find @mauron85 providing some [new code soon](https://github.com/mauron85/cordova-plugin-background-geolocation/commits/ios).

I'm sure it'll be fine soon for a wide variety of tracking use-cases.

If you need more advanced features, use mine:
- iOS `preventSuspend` feature
- Scheduling
- Periodic `heartbeat` event
- Advanced geofencing
- Configurable HTTP JSON templates
- A variety of other config options for advanced use-cases.

**Comment by mauron85** [comment]
Hey @christocracy. Thank you for pointing out. :-). Yes I'm working on unifying API and code base with react-native variant. It will allow cordova variant to move faster. Currently it's little bit behind.

My priorities are bit different, than cordova-background-geolocation-lt. So if you like all those features, go ahead and give cordova-background-geolocation-lt shot. And also support chris by buying his android version. I don't have any ambition to sell this product, but you can also support me by donation of course. ;-)

**Comment by Ravi448** [comment]
@juancafe4 I set that in Xcode to location always. This will ask the user for permission to always.

**Comment by juancafe4** [comment]
where do you do that ?

**Comment by christocracy** [comment]
![](https://dl.dropboxusercontent.com/s/js3apodqrc26ct8/Screenshot%202017-11-13%2011.22.21.png?dl=1)

**Comment by juancafe4** [comment]
Thanks!

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.
