### ISSUE TITLE
Sending a Http request to background location service

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#337]
Sending a Http request from server to background location service to get current location or to know status of the service. I guess we can also trigger an event with silent notification from server.

**Usecase:**
Sometimes the mobile kills the background service. In such cases its difficult for the developer/administrator to know whether background service is running or not.

**Comment by assunluis80** [comment]
This feature would be very usel.

**Comment by mauron85** [comment]
This cannot be implemented by the plugin. You have to implement this via push notifications by yourself.

**Comment by mauron85** [comment]
@shyamal890 No. But maybe it could listen on some intent.
