### ISSUE TITLE
callbackFn called several times on iOS

### ISSUE THREAD

**Issue by matbeard** [mauron85/cordova-plugin-background-geolocation#34]
I've integrated background tracking into my Phonegap app (based on the Sample App).

On my Android device it seems to work perfectly. It's posting location updates to my sever nicely: infrequently when stationary and more often when moving.

I don't have an iOS device to test, but in the simulator with Location set to Freeway Drive, I'm getting the exact same position logged several times (anything up to 10 times) in my database - all with exactly the same timestamp.

Is this a problem with the plugin; the behaviour of the iOS simulator; or my code (which works in every other respect).

Any advice is much appreciated. Thanks

**Comment by mauron85** [comment]
check your success callback when configuring plugin if you use closure.

For example http://stackoverflow.com/questions/750486/javascript-closure-inside-loops-simple-practical-example

**Comment by matbeard** [comment]
Is this likely to behave any differently in Android and iOS?

My success callback looks like:

        var callbackFn = function(location) {
            console.log('Background GeoLocation:  ' + location.latitude + ',' + location.longitude);

            try {
                app.setCurrentLocation(location);
            } catch (e) {
                console.error('[ERROR]: setting location', e.message);
            }

            // add location to database (or offline store) then stop background process
            mobileTrackingData.add({
                lat: location.latitude,
                lng: location.longitude,
                accuracy: location.accuracy,
                speed: location.speed,
                deviceId: device.uuid,
                platform: device.platform
            });
            backgroundGeoLocation.finish();
        };

I'm integrating this with a Kendo Mobile app (which has it's own facilities for handling offline data). The ```mobileTrackingData.add()``` function handles the POSTing of location data to the server (or localStorage when offline).

This is working perfectly on Android, but on iOS, each location is being POSTed multiple times. I can't figure out if this is a problem with the geolocation plugin or the Kendo datasource?

**Comment by mauron85** [comment]
I've just checked my db and it seems that it happens quite often also on Android. Not sure why, but maybe those duplicates are coming from sensors.

**Comment by matbeard** [comment]
Some of that makes sense... I'll do some more digging next week.

Strange thing is, though, the ```console.log('Background GeoLocation:  ' + location.latitude + ',' + location.longitude);``` runs the "correct" number of times and not for every time data is posted to the sever?

**Comment by mauron85** [comment]
>and not for every time data is posted to the sever?

not sure if I completely understand the very last part of your question

**Comment by matbeard** [comment]
Well, the console.log and the post to the server are both in the callback, but I get around 10 database entries for each log message. That's what I can't understand. Doesn't happen in Android. I need to dig a little more.

**Comment by mauron85** [comment]
I understand now. Seems to be different problem than I wrote about. My experience from db logs was max 3. duplicates for same timestamp and very occasionally.

**Comment by mauron85** [comment]
Hey @matbeard. Did you found the problem?

**Comment by matbeard** [comment]
Not really. I just made a simple workaround that compares the last timestamp with the current one. If they are the same, then I don't send the data to the server.

I'll maybe try to figure out what's causing the problem when I get time, but this workaround fixes the issue for the time being.

Thanks

**Comment by mauron85** [comment]
I have some news about it. The problem actually can arrise when stopOnTerminate is true on Android, which was the default option. Service was sometimes started multiple times in that case. Did you use stopOnTerminate?
