### ISSUE TITLE
Firebase report a error

### ISSUE THREAD

**Issue by humbertocruz** [mauron85/cordova-plugin-background-geolocation#340]
Hello, I received this message from firebase:

java.lang.RuntimeException: Unable to start service com.marianhello.bgloc.LocationService@642eb6d with Intent { flg=0x4 cmp=[REDACTED_DOMAIN_NAME]/com.marianhello.bgloc.LocationService (has extras) }: java.lang.IllegalStateException: GoogleApiClient is not connected yet. at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3335)

## Your Environment
* Plugin version: 2.2.5
* Platform: Android

**Comment by mauron85** [comment]
Hmm. Without more info I doubt I can help. Please use ISSUE template
