### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#343]
Readme says the plugin is updated significantly since v2 to v3. However, the changelog doesn't reflect the same. Also, which is the latest plugin version number? 2.3.2 or 3.0.0?

**Comment by mauron85** [comment]
changelog needs to updates. but you can read MIGRATIONS.md.

**Comment by shyamal890** [comment]
I tried downloading the alpha release of v3 but couldn't make it work.

`ionic cordova plugin add cordova-plugin-mauron85-background-geolocation@3.0.0-alpha.7 --save`

**Comment by mauron85** [comment]
You mean you cannot install it?

**Comment by shyamal890** [comment]
Yes. gives invalid error

**Comment by mauron85** [comment]
Your are probably using older ionic or cordova, because just installed plugin with ionic cordova plugin add.

**Comment by shyamal890** [comment]
![i](https://user-images.githubusercontent.com/6606965/33267339-1df23b58-d39f-11e7-899f-97f6c710f0d8.JPG)

**Comment by mauron85** [comment]
I'm not sure why you get this error. Try to nuke all plugins, platforms and start fresh.

**Comment by mauron85** [comment]
is this still relevant?
