### ISSUE TITLE
startOnBoot functionality

### ISSUE THREAD

**Issue by robertolocal** [mauron85/cordova-plugin-background-geolocation#344]
* Plugin version: Latest
* Platform: Android

## Expected Behavior
If `startOnBoot: true` but the plugin is stoped. Then do not start after restart device.

## Actual Behavior
If `startOnBoot: true`  always start plugin on restart device, ignoring last state(started or stoped)

## Question
Should I call `configure({startOnBoot: false})` always when stop plugin?

**Comment by mauron85** [comment]
Good question. Yes, u need to call configure to achieve what you want to achieve.
