### ISSUE TITLE
checkStatus should also inform about GPS status

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#346]
Currently `checkStatus` functions informs whether the service is running or not, whether the app has needed permission for location tracking and whether the syncUrl has authenticated header.

It is also important to know whether GPS is turned ON or OFF, as when `desiredAccuracy` is set to around 20, GPS has to be ON.

**Comment by mauron85** [comment]
>and whether the syncUrl has authenticated header.
no. authenticated means location services are enabled/disabled.

There is no explicait check if GPS is turned ON or OFF, rather location services as whole (it could be gps, network ...).
