### ISSUE TITLE
What is authorization in checkStatus?

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#349]
Hey @mauron85 can you please explain the difference between `authorization` and `hasPermissions` in `checkStatus` function.

Also the options in `authorization` is not visible in the ReadMe section.

**Comment by mauron85** [comment]
Authorization means that location services are enabled and hasPermissions means user granted  permissions android.permission.ACCESS_COARSE_LOCATION and android.permission.ACCESS_FINE_LOCATION
