### ISSUE TITLE
ios build failed when added this plugin  

### ISSUE THREAD

**Issue by labolado** [mauron85/cordova-plugin-background-geolocation#35]
** BUILD FAILED **

The following build commands failed:
	CompileC build/QianDao.build/Debug-iphonesimulator/QianDao.build/Objects-normal/i386/CDVLocation-220F4D50F87A2F61.o QianDao/Plugins/cordova-plugin-geolocation-ios9-fix/CDVLocation.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/zengyanli/Documents/dev/prj/app/svn/szyd/tongfu/qiaodao/client/platforms/ios/cordova/build-debug.xcconfig,-project,QianDao.xcodeproj,ARCHS=i386,-target,QianDao,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/zengyanli/Documents//client/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/dev/prj/app/svn/szyd/tongfu/qiaodao/client/platforms/ios/build/sharedpch

**Comment by mauron85** [comment]
Please look couple lines above, there will be real error message. BTW. I've just released 0.9.3, try that one if it fix your problem.

**Comment by mauron85** [comment]
closing, please reopen with more info
