### ISSUE TITLE
Question: What will happen if I start the service without stopping the previous instance?

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#350]
Do I need to do the following in case the service is already running to avoid having 2 instance of the service?

```
-> Stop Service
-> Configure settings
-> Start Service
```

Does the following step killing the previous instance of the service?

```
-> Configure settings
-> Start Service
```

**Comment by mauron85** [comment]
There is only single instance of service running.

**Comment by shyamal890** [comment]
Will configuration change on restarting the service without stopping the service?
