### ISSUE TITLE
Bug: on('authorization') triggered twice

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#351]
## Your Environment

* Plugin version: 3.0.0.alpha7
* Platform: Android
* OS version: 6.0.1
* Device manufacturer and model: Moto G Turbo
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): 6.4.0

## Context
When Location services settings is switched back on in mobile. on('authorization') event is triggered twice. While on turning off the location service settings, the event is triggered only once.

## Expected Behavior
'authorization' should only be triggered once.

**Comment by mauron85** [comment]
Make sure you don't register listeners twice. In react it's quite easy to do so, eg. if you forgot to remove listener in `componentDidUnmount`.

**Comment by mauron85** [comment]
I can't reproduce your issue. I've used very basic skeleton:

index.js
```
var app = {
    // Application Constructor
    initialize: function() {
        document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
    },

    // deviceready Event Handler
    //
    // Bind any cordova events here. Common events are:
    // 'pause', 'resume', etc.
    onDeviceReady: function() {
          BackgroundGeolocation.on('authorization', function(status) {
            console.log('on authorization', status);
            BackgroundGeolocation.checkStatus(function(status) {
              console.log('[INFO] BackgroundGeolocation service is running: ' + status.isRunning);
              console.log('[INFO] BackgroundGeolocation services enabled: ' + status.locationServicesEnabled);
              console.log('[INFO] BackgroundGeolocation auth status: ' + status.authorization); 
            });
          });
      
          BackgroundGeolocation.start();
    }
};

app.initialize();
```
When enable location service in Chrome console log (chrome://inspect/#devices):

```
on authorization 1
index.js:15 [INFO] BackgroundGeolocation service is running: true
index.js:16 [INFO] BackgroundGeolocation services enabled: true
index.js:17 [INFO] BackgroundGeolocation auth status: 1
```

Same when I disable location services. Clearly it's not called multiple times.

Please try this example and report

**Comment by mauron85** [comment]
Closing as no response received.
