### ISSUE TITLE
Question - Reduce wait for the first location callback

### ISSUE THREAD

**Issue by Jahrenski** [mauron85/cordova-plugin-background-geolocation#352]
I would like to know what are the best settings to get the first location quickly even if it's inaccurate.

I currently use : 
```
{
    desiredAccuracy: 100,
    stationaryRadius: 1,
    distanceFilter: 1,
    debug: false,
    interval: 10
  };
```

But this still takes 20 seconds to yield a location coordinates on android device.

**Comment by mauron85** [comment]
You can use RAW_PROVIDER and switch to DISTANCE_FILTER_PROVIDER later. In upcoming version that would be possible even without stopping first.
