### ISSUE TITLE
Just a question: it's possible to append more data to send to server?

### ISSUE THREAD

**Issue by assunluis80** [mauron85/cordova-plugin-background-geolocation#355]
Just a question: it's possible to append more data to send to server? Or it's possible to add a callback for every request to server?

**Comment by mauron85** [comment]
Yes it is. Put them into url.

http://server:port/path?param1=value1&param2=value2

**Comment by mauron85** [comment]
Just added another option in 3.0.0-alpha.8 via customizable `postTemplate` config option.

More info https://github.com/mauron85/cordova-plugin-background-geolocation#custom-post-template
