### ISSUE TITLE
Not working for Android 5.0

### ISSUE THREAD

**Issue by iamjoyce** [mauron85/cordova-plugin-background-geolocation#356]
No coordinates received for Android 5.0.

## Your Environment
* Plugin version: 2.3.3 and 3.0.0-alpha.7
* Platform: Android
* OS version: 5.0
* Device manufacturer and model: Lenovo Vibe S1
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): 6.4.0
* Plugin configuration options: 
```js
backgroundGeolocation: {
    maxLocations: 0, // I don't need storage
    desiredAccuracy: 10,
    stationaryRadius: 1,
    distanceFilter: 1,
    interval: 3000,
    // Android
    fastestInterval: 3000,
    activitiesInterval: 2000,
    stopOnStillActivity: false,
    locationProvider: 1 // ACTIVITY_PROVIDER
}
```

## Context
I am not receiving any geolocation coordinates for Android 5.0. The same codes for both v2 and v3 works fine on a device running on Android 7.0

The notification does appear correctly, but no coordinates are sent to the callback/event.

## Expected Behavior
Geolocation coordinates should be received, either by callback or event, depending on the version.

## Actual Behavior
Callback and event `location` is never called.

## Steps to Reproduce
Run any project with the simplest code.

## Context
Android 5.0 is the most common Android used by my users.

**Comment by mauron85** [comment]
>The same codes for both v2 and v3 works fine on a device running on Android 7.0

What do you mean by that? Do you have any logs?

**Comment by iamjoyce** [comment]
Hi @mauron85, I meant that given the same piece of code, it works on Android 7.0 but not Android 5.0. I understand v2 and v3 are different, so I have two pieces of codes, and tested them on both Android OS. My point was that the problem is unlikely to be caused by incorrect implementation.

I don't have any logs, but I can get them ASAP. I assumed you meant [debugging logs](https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/DEBUGGING.md)

**Comment by iamjoyce** [comment]
Ok, I found the issue behind this. The Google Play Services version on the phone was outdated. Another application forced me to download the latest, that's how I realised that's the issue.
