### ISSUE TITLE
Using the plugin without React

### ISSUE THREAD

**Issue by josegrad** [mauron85/cordova-plugin-background-geolocation#358]
Sorry for not filling properly the issue report. I don't believe this is a bug report. Maybe a request for extra documentation.

There is a example for React, which I can't follow because I'm on a "pure" Phonegap app for Android.

I install this plugin with:

`phonegap plugin add cordova-plugin-mauron85-background-geolocation`

The plugin files show up in the project and the config.xml has the line including it:

`<plugin name="cordova-plugin-mauron85-background-geolocation"/>`

## Environment

* Plugin version: 2.3.3
* Platform: Android
* OS version: 7.0
* Device manufacturer and model: Huawei Honor 8 Lite
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`):

Installed platforms:
  browser 5.0.1
Available platforms: 
  android ~6.3.0
  blackberry10 ~3.8.0 (deprecated)
  ios ~4.5.1
  osx ~4.0.1
  ubuntu ~4.3.4 (deprecated)
  webos ~3.7.0
  windows ~5.0.0
  www ^3.12.0

phonegap plugin list:
cordova-plugin-console 1.0.7 "Console"
cordova-plugin-mauron85-background-geolocation 2.3.3 "CDVBackgroundGeolocation"
cordova-plugin-statusbar 1.0.1 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
phonegap-plugin-push 2.1.2 "PushPlugin"

* Plugin configuration options: Can't get to that point as described below.

## Context

Since I'm using the plugin without React, I can't follow the example. However just adding the plugin and calling the methods directly I can't get it working. Probably missing something.

```
function setupGeolocation() {
    
    var callbackFn = function(location) {
      console.log('BackgroundGeoLocation callback:  ' + location.latitude + ',' + location.longitude);
    };
 
    var failureFn = function(error) {
      console.log('BackgroundGeoLocation error');
    };
 
    console.log("Before configure")
    backgroundGeoLocation.configure(callbackFn, failureFn, {
        desiredAccuracy: 10,
        stationaryRadius: 20,
        distanceFilter: 30,
        debug: true
    });
    console.log("After configure")
 
    backgroundGeoLocation.start();
 
}


// Handle Cordova Device Ready Event
$$(document).on('deviceready', function() {
    setupGeolocation();
});
```

## Expected Behavior

Configuration should take place and both logs lines should show up.

## Actual Behavior

The only console line written is:
`console.log("Before configure")`

Any hints why the plugin is not available? 

I have tried with the Phonegap Developer app, as well as installing the application with its own package. I've also tried installing it over the most basic Phonegap application with the same result.

**Comment by mauron85** [comment]
But your problem is you don't specify version and by default version 3 will be installed. 

Do instead
```
phonegap plugin add cordova-plugin-mauron85-background-geolocation@2.3.3
```

Also you can use plugin version 3 without react:

```
BackgroundGeolocation.configure({...});
BackgroundGeolocation.on('start', function(){});
BackgroundGeolocation.start();
...
```

**Comment by josegrad** [comment]
Thanks for the reply.

Version 2.3.3 is then one I've had installed all the time.
I however removed and added it again. Now the config.xml has version again (I guess I took it away at some point)

`<plugin name="cordova-plugin-mauron85-background-geolocation" spec="~2.3.3" />`

Also tried:

   
```
    console.log("Before configure")
    backgroundGeolocation.configure({
        desiredAccuracy: 10,
        stationaryRadius: 20,
        distanceFilter: 30,
        debug: true
    });
    console.log("After configure")
```

Also in the form:

```
backgroundGeolocation.configure(callbackFn, failureFn, {
        desiredAccuracy: 10,
        stationaryRadius: 20,
        distanceFilter: 30,
        debug: true
});
```

Still the second log line is never reached. I used backgroundGeolocation and also BackgroundGeolocation as you indicated.


Just in case I also tried with version 2.2.5 and 2.3.0 but the result is the same.

Running our of ideas.


```
phonegap plugin add cordova-plugin-mauron85-background-geolocation@2.2.5
Installing "cordova-plugin-mauron85-background-geolocation" for browser

Saved plugin info for "cordova-plugin-mauron85-background-geolocation" to config.xml
```

I guess that "for browser" is not relevant right?

**Comment by mauron85** [comment]
If `console.log("After configure")` is never reached, it means plugin is not installed properly.
However in that case you should see console errors: `backgroundGeolocation is not defined`.

You can try to connect your phone and in Chrome browser open page: `chrome://inspect` to debug your cordova app. In console you should be able to call plugin methods (eg. backgroundGeolocation.configure({})

**Comment by mauron85** [comment]
Documentation was rewritten without using react.
