### ISSUE TITLE
Error: Plugin Geolocation failed to install, Intel XDK

### ISSUE THREAD

**Issue by lalogrosz** [mauron85/cordova-plugin-background-geolocation#36]
I've removed the plugin and added again with Intel XDK and the build fails with the message **Error: Plugin Geolocation failed to install**.

I try to know why, but I couldn't find the solution. Then, I sow that recently you release a new tag (0.9.3) and the Geolocation Plugin Dependency was with the suffix ios-fix. So I suppose the error was in that new dependency.
When I specify the 0.9.1 tag, that builds OK.

Thank you

**Comment by mauron85** [comment]
Actually in 0.9.3 dependency on cordova-plugin-geolocation was removed completely

**Comment by lalogrosz** [comment]
Yeah, but it depends to another plugin, cordova-plugin-geolocation-ios9-fix and that was the build failed cause. I don't test building with local cordova command line. The error was in XDK.

Thanks.

**Comment by mauron85** [comment]
No it does not in 0.9.3. Nuke everything and start fresh. Not sure how can be that done on intel XDK.
On pure cordova:
```
rm -rf platforms/ plugins/
cordova platform add android
cordova build android
```

**Comment by lalogrosz** [comment]
Ok, I will try that way.
Thanks

**Comment by mauron85** [comment]
Any news?

**Comment by lalogrosz** [comment]
Sorry. I didn't try again. I'm using the 0.9.2 version without problem.
Later I will try becouse my timeline is to close, so I must to complete the first version.

Thanks!

**Comment by mauron85** [comment]
Ok, no problem. Thank you for the update. Closing for now. You can reopen if needed.
