### ISSUE TITLE
Partial reconfiguration

### ISSUE THREAD

**Issue by pcrombach** [mauron85/cordova-plugin-background-geolocation#360]
## Your Environment

* Plugin version: 2.3.2
* Platform: iOS and Android
* OS version: macOS HighSierra
* Device manufacturer and model: Samsung S7
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: all
* Link to your project: na

## Context

IMHO partial reconfiguration doesn't work as described. If I try debug: true object as a parameter debug is not started.

example
BackgroundGeolocation.configure({
     debug: true
});

## Expected Behavior

Partial reconfigure should work

## Actual Behavior

IMHO partial reconfiguration doesn't work as described. If I try debug: true object as a parameter debug is not started.

example
BackgroundGeolocation.configure({
     debug: true
});

## Possible Fix

I hope there is a fix or I am doing it wrong.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
Just tested in on android and works as advertised. What are your expectations about toggle debug? Plugin must be started to see difference

**Comment by mauron85** [comment]
Just realized your problem is plugin version 2.3.2. This feature is 3.0.0 only.

**Comment by pcrombach** [comment]
You are right. My version of the plugin is 2.3.3

Where is version 3.0 If I reinstall the plugin it is still 2.2.2

**Comment by pcrombach** [comment]
Hi,

I found the 3.0.0 version of the plugin: 3.0.0-alpha.12 right?

If I remove the 2.3.2 version and install 3.0.0 my app doesn’t build anymore. Here the log of build proces:

(node:64674) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: /Users/pietcrombach/Development/Projecten/trinl/trinlfirebase/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/pietcrombach/Development/Projecten/trinl/trinlfirebase/platforms/android/src/com/zencity/cordova/bgloc/LocationUpdateService.java:6: error: package org.apache.http does not exist
import org.apache.http.HttpResponse;
                      ^
/Users/pietcrombach/Development/Projecten/trinl/trinlfirebase/platforms/android/src/com/zencity/cordova/bgloc/LocationUpdateService.java:7: error: package org.apache.http.client.methods does not exist
import org.apache.http.client.methods.HttpPost;
                                     ^
/Users/pietcrombach/Development/Projecten/trinl/trinlfirebase/platforms/android/src/com/zencity/cordova/bgloc/LocationUpdateService.java:8: error: package org.apache.http.entity does not exist
import org.apache.http.entity.StringEntity;
                             ^
/Users/pietcrombach/Development/Projecten/trinl/trinlfirebase/platforms/android/src/com/zencity/cordova/bgloc/LocationUpdateService.java:9: error: package org.apache.http.impl.client does not exist
import org.apache.http.impl.client.DefaultHttpClient;
                                  ^
/Users/pietcrombach/Development/Projecten/trinl/trinlfirebase/platforms/android/src/com/zencity/cordova/bgloc/LocationUpdateService.java:662: error: cannot find symbol
            DefaultHttpClient httpClient = new DefaultHttpClient();
            ^
  symbol:   class DefaultHttpClient
  location: class LocationUpdateService
/Users/pietcrombach/Development/Projecten/trinl/trinlfirebase/platforms/android/src/com/zencity/cordova/bgloc/LocationUpdateService.java:662: error: cannot find symbol
            DefaultHttpClient httpClient = new DefaultHttpClient();
                                               ^
  symbol:   class DefaultHttpClient
  location: class LocationUpdateService
/Users/pietcrombach/Development/Projecten/trinl/trinlfirebase/platforms/android/src/com/zencity/cordova/bgloc/LocationUpdateService.java:663: error: cannot find symbol
            HttpPost request = new HttpPost(url);
            ^
  symbol:   class HttpPost
  location: class LocationUpdateService
/Users/pietcrombach/Development/Projecten/trinl/trinlfirebase/platforms/android/src/com/zencity/cordova/bgloc/LocationUpdateService.java:663: error: cannot find symbol
            HttpPost request = new HttpPost(url);
                                   ^
  symbol:   class HttpPost
  location: class LocationUpdateService
/Users/pietcrombach/Development/Projecten/trinl/trinlfirebase/platforms/android/src/com/zencity/cordova/bgloc/LocationUpdateService.java:677: error: cannot find symbol
            StringEntity se = new StringEntity(params.toString());
            ^
  symbol:   class StringEntity
  location: class LocationUpdateService
/Users/pietcrombach/Development/Projecten/trinl/trinlfirebase/platforms/android/src/com/zencity/cordova/bgloc/LocationUpdateService.java:677: error: cannot find symbol
            StringEntity se = new StringEntity(params.toString());
                                  ^
  symbol:   class StringEntity
  location: class LocationUpdateService
/Users/pietcrombach/Development/Projecten/trinl/trinlfirebase/platforms/android/src/com/zencity/cordova/bgloc/LocationUpdateService.java:691: error: cannot find symbol
            HttpResponse response = httpClient.execute(request);
            ^
  symbol:   class HttpResponse
  location: class LocationUpdateService
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
11 errors

After reinstalling 2.00 version of the plugin these errors stay now. So what to do now?????

**Comment by mauron85** [comment]
You've installed wrong plugin. Probably this one https://www.npmjs.com/package/cordova-plugin-background-geolocation

I can tell because com/zencity/cordova/bg is not package name I'm using, but it exactly matches this one

https://github.com/ZenCity/cordova-plugin-background-geolocation/blob/master/src/android/LocationUpdateService.java#L1
