### ISSUE TITLE
Android takes long to get location

### ISSUE THREAD

**Issue by juancafe4** [mauron85/cordova-plugin-background-geolocation#361]
When i start background geolocation it takes a while to get lat lng even when I am calling the stationary. event  
Is this a normal behavior of the plugin ?

Thanks

**Comment by kschultz1986** [comment]
Define "a while". Several hours? Several minutes? Several seconds?

**Comment by juancafe4** [comment]
Minutes

**Comment by mauron85** [comment]
You didn't mentioned which provider are you using. DISTANCE_FILTER_PROVIDER is doing sampling to get accurate location when switching between foreground/background. You can try using different one, like ACTIVITY_PROVIDER or RAW_PROVIDER.

**Comment by juancafe4** [comment]
This my configuration     
   let config = {
          desiredAccuracy: window.BackgroundGeolocation.HIGH_ACCURACY,
          stationaryRadius: 50,
          distanceFilter: 50,
          notificationTitle: 'Background tracking',
          notificationText: 'enabled',
          debug: true,
          startOnBoot: false,
          stopOnTerminate: false,
          locationProvider: window.BackgroundGeolocation.ACTIVITY_PROVIDER,
          interval: 10000,
          fastestInterval: 5000,
          activitiesInterval: 10000,
          startForeground: true
        };

**Comment by Amit025** [comment]
Hi i'am trying to use this plugin into my application,Get location method in plugin is always returning an array of length zero, I've the same config in my code as mentioned above.
