### ISSUE TITLE
BackgroundGeolocationResponse.locationId is not available

### ISSUE THREAD

**Issue by rguntha** [mauron85/cordova-plugin-background-geolocation#365]
## Your Environment

* Plugin version: 2.3.3
* Platform: iOS or Android: Android
* OS version: Window 10
* Device manufacturer and model: One Plus 3
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 7.0.0
* Plugin configuration options: 
desiredAccuracy: 0,/*High*/
      stationaryRadius: 0,
      distanceFilter: 0.001,
      fastestInterval:5000,
      activitiesInterval:1000,
      locationProvider:1,
      debug: false,
      interval: 5000,
      // stopOnTerminate: false,
      stopOnStillActivity:false
* Link to your project:
private repository

## Context

The locationId is missing from the BackgroundGeolocationResponse object. But when called getLocations(), it's returning a lot of locations and their number continuously increases. 

## Expected Behavior

locationId should be provided

## Actual Behavior

locationId is missing
## Steps to Reproduce

1. Please see my code. You can try it yourself..
2.
3.
4.
----Start---
let config = {
      desiredAccuracy: 0,/*High*/
      stationaryRadius: 0,
      distanceFilter: 0.001,
      fastestInterval:5000,
      activitiesInterval:1000,
      locationProvider:1,
      debug: false,
      interval: 5000,
      // stopOnTerminate: false,
      stopOnStillActivity:false
    };
    this.backgroundGeolocation.configure(config).subscribe((location:BackgroundGeolocationResponse) => {
      this.processLocationData(location,location.time);
    }, (err) => {
      console.log(err);
    });
----End---
## Context

locationId is needed for deleting the locations from getLocations() result, which are transmitted to the server successfully, right now I am unable to delete the transmitted locations. Because the locationId is not present, I am unable to use the stopOnTerminate:false flag. Because when the app comes back, I would not know which locations are transmitted and which are not.

Also calling deleteAllLocations() has no effect on the getLocation() return value.

**Comment by mauron85** [comment]
You don't need to manually delete locations. It's max limit is determined by `maxLocations`.

Read https://github.com/mauron85/react-native-background-geolocation#http-locations-posting for detailed information.

**Comment by rguntha** [comment]
I have my own mechanism to stream the locations "in real time" to my server and I do not want to double stream them. 
Right now I am using my own location cache to store until confirmation from server and deleting it. 
But I want to use the location cache you have, because then I can take advantage of tracking when the app is closed also. For that I want to use getLocations() and deleteLocation() method.
Right now the deleteLocation does not work because there is no locationId in the Location.
