### ISSUE TITLE
background-geolocation is active after reboot, even after it is stopped

### ISSUE THREAD

**Issue by akaope** [mauron85/cordova-plugin-background-geolocation#366]
## Your Environment

* Plugin version: 2.3.3
* Platform: Android
* OS version: Android 5.1
* Device manufacturer and model: Meizu m3 note and several different devices
* Cordova version (`cordova -v`): 6.5.0
* Cordova platform version (`cordova platform ls`): android 6.3.0
* Plugin configuration options: 
```
backgroundGeolocation.configure(callbackFn, failureFn, {
        notificationTitle: backgroundTitle,
        notificationText: 'enabled',
        locationProvider: backgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
        stopOnTerminate: false,
        startOnBoot: true,
        startForeground: true,        
        desiredAccuracy: 10,
        stationaryRadius: 0,
        distanceFilter: 20,   
        stopOnStillActivity: false,
        fastestInterval: 10000, 
        activitiesInterval: 10000,
        interval: 1000,
        url: approu.getServerHost() + '/Uplcoord',
        httpHeaders: {
            'UCDKRY': approu.loginUcodeUser
        }
    });
```
* Link to your project:

## Context

1. I start background-geolocation using `backgroundGeolocation.start()`
2. then I stop using `backgroundGeolocation.stop()`
3. when my device reboots, there is a notification that background-geolocation is active

and this happens in some other different devices

## Expected Behavior

background-geolocation should be inactive because it has been stopped before the device reboots

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
That is not how `startOnBoot: true` works. It starts service no matter if it was stopped or not.
