### ISSUE TITLE
GET_ACCOUNTS permission under Android reqiured?

### ISSUE THREAD

**Issue by mihristov** [mauron85/cordova-plugin-background-geolocation#367]
## Your Environment

* Plugin version: any
* Platform: Android
* OS version: -
* Device manufacturer and model: an
* Cordova version (`cordova -v`): -
* Cordova platform version (`cordova platform ls`): -
* Plugin configuration options: -
* Link to your project: -

## Context

Hi there. I'm currently trying to deploy my app in google play store and they tell me that I need to include in my privacy policy that I'm using GET_ACCOUNTS permission. I started searching who's using it and it turned out it was this plugin. My guess was that it's because of GCM, but it seem that google account is not needed anymore for it (https://stackoverflow.com/a/18444343). So can you please tell me if it is actually used and needed?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
True. That permission was not actually necessary. Dropped in latest alpha.
