### ISSUE TITLE
Not getting location data when the user is riding a bike or in a car

### ISSUE THREAD

**Issue by swa06** [mauron85/cordova-plugin-background-geolocation#369]
##  Environment

* Plugin version: 2.2.0 
* Platform: Android

 ionic (Ionic CLI)       : 3.13.1

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.1.6-201712271536
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.1-201711081842

System:

    Android SDK Tools : 26.0.2
    Node              : v6.10.2
    npm               : 5.5.1
    OS                : Windows 7

I am using cordova background geolocation plugin for my ionic app(android). Below is my configuration,
const config: BackgroundGeolocationConfig = {
        desiredAccuracy: 0,
        stationaryRadius: 5,
        distanceFilter: 5,
        interval: 10000,
        fastestInterval: 5000,
        url: "https://1*.**.**.**1:8200/geo_api/saveBackgroundGeoLocation",
        syncUrl: "https://1*.**.**.**1:8200/geo_api/saveBackgroundGeoLocation",
        httpHeaders: { "User": user },
        maxLocations: 8,
        syncThreshold: 4,
        startForeground: false,
        startOnBoot: true,
        debug: true,
        stopOnTerminate: false,
        stopOnStillActivity: false
      };

      this.backgroundGeolocation.configure(config).subscribe(
        (location: BackgroundGeolocationResponse) => {
          console.log(location);
          this.backgroundGeolocation.finish(); // FOR IOS ONLY
        },
        err => {
          console.log(err);
        }
      );

This configuration is working fine when the user is walking or at a slow speed. 
But whenever the user is on a bike or in a car location is not being sent to url.

Could, anyone please explain what should be the optimized configuration for getting location data from a fast moving user.

**Comment by landryjeanluc** [comment]
Have you had any luck with this at all?

Problem seems to only start after a few minutes for me. Users can restart the app when they get to their destination and it starts recording again but for some reason when they drive the updates stop as well as onStationary stops getting called so i lose track of people.

if you found out anything any help would be great i have been digging for a couple of days already at this.

**Comment by swa06** [comment]
When the user is going at a faster speed, it becomes difficult to articulate the location.In my case, I increased the values of "desiredAccuracy" and "stationaryRadius" parameters. I put desiredAccuracy at 100 which made sure the device uses "A-GPS".
Also a higher stationaryRadius helps the device to fetch the location.
