### ISSUE TITLE
CDVBackgroundGeoLocation locatinManager failed

### ISSUE THREAD

**Issue by roninJoseph** [mauron85/cordova-plugin-background-geolocation#37]
More often than not I keep getting this error thrown the Xcode logs:

CDVBackgroundGeoLocation locationManager failed: Error Domain=kCLEerrorDomain Code=0 "(null)"

This happens when the app is in the background and when it happens it failed to send the geolocation. I'm very new iOS dev and any help would be much appreciated. I am testing on an iPad mini running 9.2.1

**Comment by mauron85** [comment]
Yes, that is ugly. Need to take look at it.

**Comment by mauron85** [comment]
Just turn debug notifications with debug:false option. You should do it anyway in production
