### ISSUE TITLE
onStationary never called, tracker stop after some minutes

### ISSUE THREAD

**Issue by rafwell** [mauron85/cordova-plugin-background-geolocation#371]
* Plugin version: ^2.3.3
* Platform: Android
* OS version: Ubuntu 16.04LTS
* Device manufacturer and model: Motorola Moto G3
* Cordova version: 8.0.0
* Cordova platform version:
Installed platforms:
  android 6.3.0
Available platforms: 
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0

* Plugin configuration options: 
```
desiredAccuracy: 10,
      stationaryRadius: 20,
      distanceFilter: 30,
      interval: 60000,
      debug: true, //  enable this hear sounds for background-geolocation life-cycle.
      stopOnTerminate: false, // enable this to clear background location settings when the app terminates
      startOnBoot: true,
      stopOnStillActivity: false
````
* Link to your project: not yet

## Context
I need track the smartphone position at most realtime as possible. I leave the app opened, that capture 2 times my location and stop work. I think it because i'm stopped on escritory obviously. But, i've tried hear the onStationary event and that is never called.
``` 
this.backgroundGeolocation.onStationary().then(res=>{
      console.log('here', res);  //never called
      alert('here '); //never called
    });
```

## Expected Behavior
I expected get location always, with a timeout average 5 minutes for example, for realtime track. Even if device is stationary.

## Actual Behavior
onStationary never called and the tracker stop work after 2 minutes average.

**Comment by landryjeanluc** [comment]
Have you gotten anywhere with this?

Problem does seem worst when the user is riding in a car for me, does this seem to be the case for you?

I for example can walk down the street and i have never had a problem this way. But if i have users that drive down the street, after a few minutes of updates that work perfectly, i stop getting them.

**Comment by rafwell** [comment]
No news yet. I'll try use the other provider, the ACTIVITY_PROVIDER. Maybe there give me best results.

**Comment by mauron85** [comment]
What provider did you used? You don't have any in your config option. Keep in mind if you don't specify one, one from previous session will be used or default. So it might be different than you think it is.

**Comment by mauron85** [comment]
Also sorry to say but 2.x branch will not get any fixes, even if your issue is actual bug. I just don't have resources to maintain two branches.

**Comment by rafwell** [comment]
I understand you. But, the branch alpha is not working on IONIC aplications. The console say me "the plugin is not available or required" I dont remember now. Really i wanna try use the branch 3 in my application, because the 2 is bringing me a lot of problems.
