### ISSUE TITLE
build failed using Xcode 8

### ISSUE THREAD

**Issue by iwan-uschka** [mauron85/cordova-plugin-background-geolocation#372]
## Your Environment

* Plugin version: 3.0.0-alpha-12
* Platform: iOS
* OS version: -
* Device manufacturer and model: -
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): ios 4.5.4
* Plugin configuration options: default
* Link to your project: -

## Context
Please define requirements for building iOS apps.

## Actual Behavior
- build failed using Xcode 8.2.1 on Mac OS X 10.11.6.
- build proceed successfully using Xcode 9

## Debug logs
    /some-project-path/production/platforms/ios/SomeProject/Plugins/cordova-plugin-mauron85-background-geolocation/BackgroundGeolocationFacade.m:283:13: warning: local declaration of 'locationProvider' hides instance variable [-Wshadow-ivar]
                locationProvider = [[DistanceFilterLocationProvider alloc] init];
                ^
    /some-project-path/production/platforms/ios/SomeProject/Plugins/cordova-plugin-mauron85-background-geolocation/BackgroundGeolocationFacade.m:286:13: warning: local declaration of 'locationProvider' hides instance variable [-Wshadow-ivar]
                locationProvider = [[ActivityLocationProvider alloc] init];
                ^
    /some-project-path/production/platforms/ios/SomeProject/Plugins/cordova-plugin-mauron85-background-geolocation/BackgroundGeolocationFacade.m:289:13: warning: local declaration of 'locationProvider' hides instance variable [-Wshadow-ivar]
                locationProvider = [[RawLocationProvider alloc] init];
                ^
    /some-project-path/production/platforms/ios/SomeProject/Plugins/cordova-plugin-mauron85-background-geolocation/BackgroundGeolocationFacade.m:300:6: warning: local declaration of 'locationProvider' hides instance variable [-Wshadow-ivar]
        [locationProvider onCreate];
         ^
    /some-project-path/production/platforms/ios/SomeProject/Plugins/cordova-plugin-mauron85-background-geolocation/BackgroundGeolocationFacade.m:301:12: warning: local declaration of 'locationProvider' hides instance variable [-Wshadow-ivar]
        return locationProvider;
               ^
    /some-project-path/production/platforms/ios/SomeProject/Plugins/cordova-plugin-mauron85-background-geolocation/BackgroundGeolocationFacade.m:314:9: error: unexpected '@' in program
        if (@available(iOS 10, *)) {
            ^
    5 warnings and 1 error generated.

    ** BUILD FAILED **

    The following build commands failed:

        CompileC /Users/some-user/Library/Developer/Xcode/DerivedData/SomeProject-cmqrawdtbrrcvufstsowdeskyxti/Build/Intermediates/SomeProject.build/Debug-iphonesimulator/SomeProject.build/Objects-normal/x86_64/BackgroundGeolocationFacade.o SomeProject/Plugins/cordova-plugin-mauron85-background-geolocation/BackgroundGeolocationFacade.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    (1 failure)

    Error: Error code 65 for command: xcodebuild with args: -xcconfig,/some-project-path/production/platforms/ios/cordova/build-debug.xcconfig,-workspace,SomeProject.xcworkspace,-scheme,SomeProject,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone SE,build,CONFIGURATION_BUILD_DIR=/some-project-path/production/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/some-project-path/production/platforms/ios/build/sharedpch

thx

**Comment by mauron85** [comment]
Please upgrade to latest alpha. Should be fixed.
