### ISSUE TITLE
Project errors after adding the plugin

### ISSUE THREAD

**Issue by wolvesworld** [mauron85/cordova-plugin-background-geolocation#373]
Trouble in adding pluing

## Your Environment

* Plugin version:2.3.2
* Platform: Android
* OS version:windows 10
* Device manufacturer and model:
* Cordova version (`cordova -v`):6.5.0
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

## Context
I have added the PLugin to my project but a lot of unknown libraries such as 
import org.apache.cordova.CallbackContext;
import org.apache.cordova.CordovaPlugin;
import org.apache.cordova.PluginResult; 
IN BackgroundGeolocationPlugin 

import com.google.android.gms.common.ConnectionResult;
import com.google.android.gms.common.api.GoogleApiClient;
import com.google.android.gms.location.ActivityRecognition;
import com.google.android.gms.location.ActivityRecognitionResult;
import com.google.android.gms.location.DetectedActivity;
import com.google.android.gms.location.LocationListener;
import com.google.android.gms.location.LocationRequest;
import com.google.android.gms.location.LocationServices;
IN ActivityRecognitionLocationProvider

private org.slf4j.Logger log;
IN LocationService

import org.apache.cordova.CordovaInterface;
import org.apache.cordova.CordovaPlugin;
import org.apache.cordova.LOG;
IN PermissionHelper

and So ON

## Expected Behavior

So I was expected that all of my setup are fine since I have update my cordova version 
## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
Version 2.3.2 is tool old. Please try 2.3.5.
