### ISSUE TITLE
Is there plans to support cordova-android 6.3.0+?

### ISSUE THREAD

**Issue by ftunholm** [mauron85/cordova-plugin-background-geolocation#374]
Great library really enjoy it! This is just a simple question, I hope it was alright to write it here. Are there any future plans to support cordova-android 6.3.0+? Support for new 7.0.0 would be awesome.

Thanks, keep up the good work!

**Comment by mauron85** [comment]
Yes. Didn't test it myself, but Maybe it's already working on 7.0.0.

**Comment by ftunholm** [comment]
@mauron85 Thanks for the fast answer, great will definitely keep an eye out for it.
