### ISSUE TITLE
plugin doesn't work on Android Studio Emulator

### ISSUE THREAD

**Issue by mihristov** [mauron85/cordova-plugin-background-geolocation#375]
## Your Environment

* Plugin version: 2.2.5
* Platform: Android Studio Emulator
* OS version: win10
* Device manufacturer and model: nexus 5
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options:  
          desiredAccuracy: 10, // meters
          stationaryRadius: 50, // meters
          distanceFilter: 30, // meters
          startForeground: true,

          locationProvider: backgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
          interval: 1000, // millis
          fastestInterval: 900, // millis
          activitiesInterval: 1000, // millis

          stopOnStillActivity: false,
* Link to your project:

## Context

I am trying to debug my application in the Android Studio Emulator but it doesn't seem to return GPS locations as I'm changing it. It's working on a device.
## Expected Behavior

Return gps location when I enter one in the emulator.
## Actual Behavior

Nothing happens.
## Steps to Reproduce

1. 
2.
3.
4.

## Debug logs

02-25 20:19:56.023 2778-2778/? I/com.marianhello.bgloc.LocationService: Creating LocationService
02-25 20:19:56.034 2778-2778/? I/com.marianhello.bgloc.LocationService: Received start startId: 1 intent: Intent { flg=0x4 cmp=bg.luckydriver.dev/com.marianhello.bgloc.LocationService (has extras) }
02-25 20:19:56.035 2778-4665/? I/com.marianhello.bgloc.LocationService: Network condition changed hasConnectivity: true
02-25 20:19:56.040 2778-2778/? D/com.marianhello.bgloc.LocationService: Will start service with: Config[distanceFilter=30 stationaryRadius=50.0 desiredAccuracy=10 interval=1000 fastestInterval=900 activitiesInterval=1000 isDebugging=false stopOnTerminate=true stopOnStillActivity=false startOnBoot=false startForeground=true locationProvider=1 nTitle=Lucky Driver nText=Background Location Tracking Enabled nIconLarge=null nIconSmall=null nIconColor=null url= syncUrl= syncThreshold=100 httpHeaders={} maxLocations=10000]
02-25 20:19:56.062 2778-2778/? I/com.marianhello.bgloc.ActivityRecognitionLocationProvider: Creating ActivityRecognitionLocationProvider
02-25 20:19:56.077 2778-2778/? I/com.marianhello.bgloc.ActivityRecognitionLocationProvider: Start recording

**Comment by mihristov** [comment]
@mauron85  can you tell me the plugin and android version that this plugin was last tested on emulator, please?

**Comment by okandeb** [comment]
i have same problem since i have switched location provider to activity provider. i cant use emulator. plugin does not send any location.

**Comment by mihristov** [comment]
@okandeb try using Lockito instead of emulator. It suited my needs. It can help you too. You can mock locations with it.

**Comment by mauron85** [comment]
Sorry I don't use Android Studio Emulator. Only genymotion and real devices.

**Comment by antocorso** [comment]
I have the same problem, on emulator this plugin doesn't work and even with app that set mock locations
