### ISSUE TITLE
App works on ios simulator but not on device

### ISSUE THREAD

**Issue by kunjanthakkar1** [mauron85/cordova-plugin-background-geolocation#376]
## Your Environment
iOS simulator iPhone X, iPhone 6 and iPhone 6 device (ios 11.1)

* Plugin version: 2.3.3
* Platform: iOS
* OS version: 11.1
* Device manufacturer and model: iPhone 6
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): ios 4.5.4
* Plugin configuration options: 
* Link to your project:

## Context

I am trying to create a location tracking app. I started with a small example wherein I just get the current position of device and add a marker for it on map. It works perfectly on simulators (iPhoneX and iPhone6), however, I am unable to get it to work on actual device (iPhone6). I noticed that when I run the sample on simulator I get an alert asking for permission, however, on device I do not get any such alert. I have checked my plist file too and am slightly confused as to how the same code asks for permission on simulator but not on actual device.

This is my code:
```
var callbackFn = function(location) {
          console.log('[js] BackgroundGeolocation callback:  ' + location.latitude + ',' + location.longitude);
alert("BackgroundGeolocation callback");
          backgroundGeolocation.finish();
        };

        var failureFn = function(error) {
          console.log('BackgroundGeolocation error');
        };

        // BackgroundGeolocation is highly configurable. See platform specific configuration options
        backgroundGeolocation.configure(callbackFn, failureFn, {
          desiredAccuracy: 10,
          stationaryRadius: 20,
          distanceFilter: 30,
          interval: 60000
        });
        backgroundGeolocation.start();

if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function(position) {
          alert("got current position via geolocation");
        }, function() {
          alert('Could not get current location, please search for a location');
        });
      } else {
        // Browser doesn't support Geolocation
        alert('Browser does not support Geolocation. Could not get current location, please search for a location');
      }
```

## Expected Behavior

All the alerts and logs show up on simulators but none of them show up on device. What am I missing?
## Steps to Reproduce

1. Execute the above code on simulator vs on device.

**Comment by ravzski** [comment]
im having similar issue on ios 11.2 6

**Comment by mauron85** [comment]
You only get system alert on first "start" method call. Maybe you already declined that prompt. Check app permissions in settings. Or try uninstall / install app. You should get prompt on clean install

**Comment by mauron85** [comment]
Considered as answered. Please feel free to reopen, if your issue still persists.
