### ISSUE TITLE
Plugin Not Installed

### ISSUE THREAD

**Issue by SergioSuarezDev** [mauron85/cordova-plugin-background-geolocation#377]
## Your Environment

* Plugin version: Last version
* Platform: iOS 
* OS version: 10
* Device manufacturer and model: iPhone 7
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): iOS
* Plugin configuration options: 
 desiredAccuracy: 10, stationaryRadius: 1, distanceFilter: 1, debug: true, stopOnTerminate: false,
        // Solo para Android
        locationProvider: 1, startForeground: true, interval: 6000, fastestInterval: 5000, activitiesInterval: 10000,

## Context

Runtime error: Uncaught (in promise) plugin_not_installed

## Steps to Reproduce

1. Opening the app

## Context

![captura de pantalla 2018-02-23 a las 10 12 11](https://user-images.githubusercontent.com/3636232/36586431-0c97e556-1882-11e8-9f10-bc9df7366fd8.png)

## Debug logs

[10:13:04]  tslint: src/app/app.module.ts, line: 28
            'BackgroundGeolocationConfig' is declared but never used.
      L27:  import { Geolocation } from '@ionic-native/geolocation';
      L28:  import { BackgroundGeolocation, BackgroundGeolocationConfig, BackgroundGeolocationResponse } from '@ionic-na
      L29:  import { Camera /*,CameraOptions*/ } from '@ionic-native/camera';
[10:13:04]  tslint: src/app/app.module.ts, line: 28
            'BackgroundGeolocationResponse' is declared but never used.
      L27:  import { Geolocation } from '@ionic-native/geolocation';
      L28:  import { BackgroundGeolocation, BackgroundGeolocationConfig, BackgroundGeolocationResponse } from '@ionic-na
      L29:  import { Camera /*,CameraOptions*/ } from '@ionic-native/camera';
[10:13:04]  lint finished in 4.22 s
[10:13:15]  console.log: Ionic Pro initializing (app id: %cbf12280b%c) color: blue color: black
[10:13:16]  console.log: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
[10:13:16]  console.log: Ionic Native: deviceready event fired after 1264 ms
**[10:13:16]  console.warn: Native: tried calling BackgroundGeolocation.isLocationEnabled, but the BackgroundGeolocation plugin is not installed.**
**[10:13:16]  console.warn: Install the BackgroundGeolocation plugin: 'ionic cordova plugin add
            cordova-plugin-mauron85-background-geolocation'**

**Comment by leandroz** [comment]
The version on npm is wrong

**Comment by leandroz** [comment]
I installed it from master and still having the same problem!

**Comment by mauron85** [comment]
I'm not using ionic, but I guess they didn't support version 3. So probably you should install v2 with something like:

```
ionic cordova plugin add
cordova-plugin-mauron85-background-geolocation@2.3.3
```

**Comment by leandroz** [comment]
Yes, they are referencing `backgroundGeolocation` instead of `BackgroundGeolocation`

**Comment by mauron85** [comment]
Just make sure you're using v2 with ionic. V3 will not work I guess. They have to make changes to their plugin wrapper to support v3.

**Comment by SergioSuarezDev** [comment]
i installed @2.3.3 
but I have the same error :( 


![captura de pantalla 2018-03-02 a las 14 31 46](https://user-images.githubusercontent.com/3636232/36901167-77c12780-1e26-11e8-8e9b-f0bdb79c0f07.png)

**Comment by Chal131313** [comment]
@SergioSuarezDev, if you wanna use version 3.0.0 then change (like @leandroz said) in
<app-path>\node_modules\@ionic-native\background-geolocation\index.js
the value ````pluginRef: 'backgroundGeolocation'```` to ````pluginRef: 'BackgroundGeolocation'```` until it gets updated by the ionic team.

It's not the nicest solution, but for now there is nothing you can do about it.

**Comment by ismailgurler1** [comment]
@mauron85, 

This repository lists 2.3.3 as the latest stable release. I think that's why there isn't any new wrapper for Ionic. 

Currently version 2 has some issues under iOS in the background. I would like to know if maybe the next revision will be marked as stable so we can integrate it with Ionic.

**Comment by mauron85** [comment]
@ismailgurler1 yes, I was thinking about same reason as well. There still some things I would like to finish before proclaim this version as stable.

**Comment by eudgen-dev** [comment]
I have fixed the issue with the next steps:

Make sure that you init plugin AFTER platform.ready
Check plugins/cordova-plugin-mauron85-background-geolocation/www/backgroundGeolocation.js the line window.backgroundGeoLocation = backgroundGeolocation; (if you are using 2.x plugin version)
and

check node_modules/@ionic-native/background-geolocation/index.js the line pluginRef: 'backgroundGeolocation',

Change pluginRef: 'backgroundGeolocation' to pluginRef: 'backgroundGeoLocation'
I think it should depends on @ionic-native version.

Good Luck!

**Comment by franzisk** [comment]
I am having the same problem here, again, I am 100% sure I have had this problem before but I am not sure how I solved it.

Any idea how to fix this? Actually I have the plugin installed, but when I run on device (Android) is says I have not:
```
[15:28:26]  console.warn: Ionic Native: tried calling BackgroundGeolocation.configure, but the BackgroundGeolocation plugin is not installed.
[15:28:26]  console.warn: Install the BackgroundGeolocation plugin: 'ionic cordova plugin add cordova-plugin-mauron85-background-geolocation@alpha'
[15:28:26]  console.warn: Ionic Native: tried calling BackgroundGeolocation.isLocationEnabled, but the BackgroundGeolocation plugin is not installed.
[15:28:26]  console.warn: Install the BackgroundGeolocation plugin: 'ionic cordova plugin add cordova-plugin-mauron85-background-geolocation@alpha'
```

Plugins:
```
± % cordova plugin list                                                                                                                                                       !40
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-android-support-gradle-release 2.0.1 "cordova-android-support-gradle-release"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-facebook4 3.1.0 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googleplus 5.3.2 "Google SignIn"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-linkedin 1.2.1 "LinkedIn"
cordova-plugin-mauron85-background-geolocation 2.3.6 "CDVBackgroundGeolocation"
cordova-plugin-media 5.0.2 "Media"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-nativegeocoder 3.1.2 "NativeGeocoder"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-streaming-media 2.2.0 "StreamingMedia"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.1 "SocialSharing"
cordova-sqlite-storage 2.5.0 "Cordova sqlite storage plugin"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 8.0.0 "BarcodeScanner"
phonegap-plugin-push 2.1.2 "PushPlugin"
twitter-connect-plugin 0.6.0 "Twitter Connect"
```

Ionic Info:
```
± % ionic info                                                                                                                                                                !41

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 3.2.1
    Cordova Platforms  : android 6.3.0 ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 2.0.0
    ios-sim           : 6.0.0
    Node              : v8.11.3
    npm               : 5.6.0
    OS                : macOS
    Xcode             : Xcode 10.1 Build version 10B61

Environment Variables:

    ANDROID_HOME : /Users/francisco/Library/Android/sdk
```
