### ISSUE TITLE
Question about isRunning from checkStatus

### ISSUE THREAD

**Issue by leandroz** [mauron85/cordova-plugin-background-geolocation#379]
Hi @mauron85 , this is just a question and depending on the answer and will raise it as a bug.

If the user terminates the application on iOS, for example closing the app with double click on home button and swipe up, and the plugin is started, shouldn't `isRunning` from `checkStatus` return true when the app is opened back again? Or we can rely on `isRunning` only in the same "session"?

**Comment by mauron85** [comment]
Currently there is nothing like `stopOnTerminate`: false on iOS. So if you terminate app, you also stop location tracking. So yes `isRunning` on iOS is only in the same "session".

However this might change soon, as I'm planning to implement stopOnTerminate`: false  for iOS too.

**Comment by leandroz** [comment]
Ok so then I have other question: You are saying that if the app is terminated `isRunning` will be `false` and the locations will stop being recorded?
Or just `isRunning` will be false but the locations will be stored and we can access them on the next open using `getValidLocations`?

**Comment by mauron85** [comment]
>You are saying that if the app is terminated isRunning will be false and the locations will stop being recorded?

on iOS currently yes, with exception of RAW_LOCATION_PROVIDER in latest alpha.15 version and option `stopOnTerminate`: false` will continue to record locations (also option isRunning will be true if you start app back again). Other providers will follow same pattern soon (hopefully)

**Comment by leandroz** [comment]
I am on that version so I will test using RAW_LOCATION_PROVIDER, do you wan't me to test something in particular? Maybe I can help somehow. Thanks for the hard work!

**Comment by leandroz** [comment]
@mauron85 it is not working:

2018-03-01 21:02:27.168912-0300 ORIX OneView[37111:7532289] CDVBackgroundGeolocation paused
2018-03-01 21:02:27:169 ORIX OneView[37111:7532289] BgGeo #switchMode 0
2018-03-01 21:02:27.175381-0300 ORIX OneView[37111:7534463] BgGeo #switchMode 0
2018-03-01 21:02:27.318300-0300 ORIX OneView[37111:7532289] CDVBackgroundGeolocation appTerminate

Then when opened isRunning is false, something to check?

**Comment by mauron85** [comment]
Can you post plugin comfiguration?

**Comment by leandroz** [comment]
````
      desiredAccuracy: BackgroundGeolocation.MEDIUM_ACCURACY, // LOW_ACCURACY
      stationaryRadius: 100,
      distanceFilter: 50,
      notificationTitle: 'Background tracking',
      notificationText: 'enabled',
      debug: true,
      startOnBoot: false,
      stopOnTerminate: false,
      locationProvider: BackgroundGeolocation.RAW_PROVIDER, // DISTANCE_FILTER_PROVIDER
      interval: 10000,
      fastestInterval: 5000,
      activitiesInterval: 10000,
      activityType: 'AutomotiveNavigation',
      saveBatteryOnBackground: false,
````

**Comment by mauron85** [comment]
Keep it mind, you have to move significantly to restart location tracking after app was terminated. It will not happen immediately.
