### ISSUE TITLE
PhoneGap for Android buid fails

### ISSUE THREAD

**Issue by Nett** [mauron85/cordova-plugin-background-geolocation#38]
Hello, I really liked your plugin, it's awesome.

I use it for my PhoneGap application, to switch on/off tracking while app is in foreground/backgound mode. It worked just awesome. But today I needed to build new version of app, and got an error like "Error - One of your plugins required the gradle android build tool to build". I saw you added some notes regarding Android SDK version, and I used the latest one (24.4.1), but unfortunately it didn't help.

Here is by PhoneGap config file:

`<?xml version='1.0' encoding='utf-8'?>
<widget id="tracking" version="0.12.11" versionCode="1" xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0">
    < name >Tracking</name>
    < description >
        Tracking
    < /description >
    < author email="" href="" >
        Team
    < /author >
    < feature name="http://api.phonegap.com/1.0/device" />
    < preference name="permissions" value="" />
    < preference name="orientation" value="default" />
    < preference name="target-device" value="universal" />
    < preference name="fullscreen" value="false" />
    < preference name="webviewbounce" value="true" />
    < preference name="prerendered-icon" value="true" />
    < preference name="stay-in-webview" value="false" />
    < preference name="ios-statusbarstyle" value="black-opaque" />
    < preference name="detect-data-types" value="true" />
    < preference name="exit-on-suspend" value="false" />
    < preference name="show-splash-screen-spinner" value="true" />
    < preference name="auto-hide-splash-screen" value="true" />
    < preference name="disable-cursor" value="false" />
    < preference name="android-minSdkVersion" value="24.4.1" />
    < preference name="android-installLocation" value="internalOnly" />
	< preference name="phonegap-version" value="cli-5.2.0" />
	< preference name="android-maxSdkVersion" value="" />
	< preference name="android-targetSdkVersion" value="" />
	< preference name="KeepRunning" value="true" />
	< preference name="splash-screen-duration" value="5000" />
	< preference name="ErrorUrl" value="error.html" />
	< preference name="LoadingDialog" value="Please wait, the app is loading." />
	< preference name="LoadingPageDialog" value="Please wait, the data is loading." />
	< preference name="LoadUrlTimeoutValue" value="20000" />
	< preference name="AndroidPersistentFileLocation" value="Internal" />
    < icon src="icon.png" />
    < icon gap:platform="android" gap:qualifier="ldpi" src="res/icon/android/icon-36-ldpi.png" />
    < icon gap:platform="android" gap:qualifier="mdpi" src="res/icon/android/icon-48-mdpi.png" />
    < icon gap:platform="android" gap:qualifier="hdpi" src="res/icon/android/icon-72-hdpi.png" />
    < icon gap:platform="android" gap:qualifier="xhdpi" src="res/icon/android/icon-96-xhdpi.png" />
	< icon gap:platform="android" gap:qualifier="xxhdpi" src="res/icon/android/icon-144-xxhdpi.png" />

    <gap:splash gap:platform="android" gap:qualifier="port-ldpi" src="res/screen/android/screen-ldpi-portrait.png" />
    <gap:splash gap:platform="android" gap:qualifier="port-mdpi" src="res/screen/android/screen-mdpi-portrait.png" />
    <gap:splash gap:platform="android" gap:qualifier="port-hdpi" src="res/screen/android/screen-hdpi-portrait.png" />
    <gap:splash gap:platform="android" gap:qualifier="port-xhdpi" src="res/screen/android/screen-xhdpi-portrait.png" />
	<gap:splash gap:platform="android" gap:qualifier="port-xhdpi" src="res/screen/android/screen-xhdpi-n7-portrait.png" />
	<gap:splash gap:platform="android" gap:qualifier="port-xxhdpi" src="res/screen/android/screen-xxhdpi-portrait.png" />
	<gap:splash gap:platform="android" gap:qualifier="port-xxhdpi" src="res/screen/android/screen-xxhdpi-n7-portrait.png" />
	<gap:splash gap:platform="android" gap:qualifier="land-xxhdpi" src="res/screen/android/screen-xxhdpi-n7-landscape.png" width="1920" height="1200" />
	<gap:splash gap:platform="android" gap:qualifier="land-xxhdpi" src="res/screen/android/screen-xxhdpi-landscape.png" width="1920" height="1080" />
	<gap:splash gap:platform="android" gap:qualifier="land-xhdpi" src="res/screen/android/screen-xhdpi-n7-landscape.png" width="1280" height="800" />
	<gap:splash gap:platform="android" gap:qualifier="land-xhdpi" src="res/screen/android/screen-xhdpi-landscape.png" width="1280" height="720" />
	<gap:splash gap:platform="android" gap:qualifier="land-hdpi" src="res/screen/android/screen-hdpi-landscape.png" width ="800" height="480" />
	<gap:splash gap:platform="android" gap:qualifier="land-mdpi" src="res/screen/android/screen-mdpi-landscape.png" width="480" height="320" />
	<gap:splash gap:platform="android" gap:qualifier="land-ldpi" src="res/screen/android/screen-ldpi-landscape.png" width="320" height="200" />
	<gap:splash gap:platform="ios" height="1136" src="res/screen/ios/screen-iphone-portrait-568h-2x.png" width="640" />
    
	< access origin="*" />
	< gap:platform name="android" />
	< feature name="http://api.phonegap.com/1.0/camera" />
	< feature name="http://api.phonegap.com/1.0/file" />
	< feature name="http://api.phonegap.com/1.0/geolocation" />
	< feature name="http://api.phonegap.com/1.0/media" />
	< feature name="http://api.phonegap.com/1.0/notification" />
	< gap:plugin name="cordova-plugin-console" source="npm" />
	< gap:plugin name="cordova-plugin-media-capture" source="npm" />
	< gap:plugin name="cordova-plugin-device" source="npm" />
	< gap:plugin name="cordova-plugin-file" source="npm" />
	< gap:plugin name="cordova-plugin-file-transfer" source="npm" />
	< gap:plugin name="cordova-plugin-geolocation" source="npm" />
	< gap:plugin name="cordova-plugin-media" source="npm" />
	< gap:plugin name="cordova-plugin-network-information" source="npm" />
	< gap:plugin name="cordova-plugin-dialogs" source="npm" />
	< gap:plugin name="cordova-plugin-splashscreen" source="npm" />
	< gap:plugin name="com.synconset.imagepicker" source="pgb" />
	< gap:plugin name="com.phonegap.plugins.pushplugin" source="pgb" />
	< gap:plugin name="cordova-plugin-x-toast" source="npm" />
	< gap:plugin name="cordova-plugin-whitelist" source="npm" />
	< gap:plugin name="cordova-plugin-inappbrowser" source="npm" />
< gap:plugin name="cordova-plugin-mauron85-background-geolocation-phonegapbuild" source="npm"/>
	< plugin name="de.appplant.cordova.plugin.background-mode" spec="0.6.4" source="pgb" />
</widget>
`

I also followed the link, that adobe provided [http://docs.build.phonegap.com/en_US/support_failed-builds.md.html#gradle_required](url), but none of those instructions solve the issue.

Could you please advise what to do, how can I fix it. I really need to make it work.
Thank you.

**Comment by mauron85** [comment]
I'm aware of this, but don't know yet, why it's failing. If previous version was working you use that one till this issue will be fixed.

```
<plugin name="cordova-plugin-mauron85-background-geolocation-phonegapbuild" spec="0.7.3" />
```

**Comment by Nett** [comment]
Hello again! Thank you very much! It works!
And, sorry for publishing this type of issue here, I needed to contact you, and it was the fastest way.
I'll remember this link by heart <plugin name="cordova-plugin-mauron85-background-geolocation-phonegapbuild" spec="0.7.3" /> ))

Tnank you one more time!
