### ISSUE TITLE
What is PASSIVE_ACCURACY for ?

### ISSUE THREAD

**Issue by ThomasKientz** [mauron85/cordova-plugin-background-geolocation#385]
Hi

I want to track **very** significant changes, like moving outside a country. I don't need any accuracy.

I was wondering if PASSIVE_ACCURACY option would be good in my case.

How long does the location service will run in background with app totally close ? Forever ?

Thanks a lot for the great work.

**Comment by mauron85** [comment]
PASSIVE means plugin will only passively listen to location updates initiated by other apps. Will not turn any hardware sensor itself.
