### ISSUE TITLE
Why default http headers are « 'content-type': 'application/json,application/json' »

### ISSUE THREAD

**Issue by ThomasKientz** [mauron85/cordova-plugin-background-geolocation#386]
Why default http headers are : `'content-type': 'application/json,application/json'` 
 instead of : `'content-type': 'application/json'` ?

I think it is causing my firebase cloud function to not parse correctly the request.

I tried without success to override it with : 

```
BackgroundGeolocation.configure({
      httpHeaders: {
        "content-type": "application/json",
      }
    });
``` 
Plugin version: 3.0.0-alpha.18
OS : iOS 11.2.6
cordova : 8.0.0 

Thanks !

**Comment by mauron85** [comment]
Are you sure about that. Just run quick test with config option `sync` in emulator. Logged http headers in node js server were `content-type`: `application/json`.

```
Headers:
 { host: '192.168.81.15:3000',
  'content-type': 'application/json',
  connection: 'keep-alive',
  accept: '*/*',
  'user-agent': 'BG%20Example/2.0.0 CFNetwork/893.14 Darwin/17.4.0',
  'accept-language': 'en-us',
  'accept-encoding': 'gzip, deflate',
  'content-length': '60' }
```

**Comment by mauron85** [comment]
But I can replicate this with `httpHeaders` you've used. So my recommendation: Don't override `content-type` in `httpHeaders` and you'll be just fine.

**Comment by ThomasKientz** [comment]
Fixed by removing those lines in the plugin files :
`[request setValue:@"application/json" forHTTPHeaderField:@"Content-Type"];` in `Location.m`  and in `BackgroundSync.m`

**Comment by mauron85** [comment]
Sorry, but there is not need to remove those lines. But I can't stop you. :)

**Comment by ThomasKientz** [comment]
I tried without overriding it.
