### ISSUE TITLE
why is the provider giving value UNDEFINED?

### ISSUE THREAD

**Issue by dj7918** [mauron85/cordova-plugin-background-geolocation#388]
## Your Environment

* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
Sorry I'm closing the issue. Please fill issue template. Specially steps to reproduce. I can't make guesses about what platform you're using ...
