### ISSUE TITLE
No signs of life and no error either

### ISSUE THREAD

**Issue by karolszklarski** [mauron85/cordova-plugin-background-geolocation#39]
Hello,

I try to use your plugin in my cordova app on iPhone. I compile it on remote mac and install IPA on real device - iPhone 5c. I installed the plugin from git. Below is my test code. I can't get ANY response - no alert, nothing on js console, no js error, just simply nothing at all. Before and after execution of this code everything works fine. The code is triggered by a button press. It's after deviceReady. I use window.onerror = someFunction to capture js errors - nothing there too. The app has "location: always" access rights.

When I use
`gpsWatch = navigator.geolocation.watchPosition(saveGpsPoint, silentFail, geolocationOptions);`
then everything works fine, but only in foreground, and I need to receive gps location also when in background.

`    backgroundGeoLocation.getLocations(function(location) {
        alert("getLocations: " + JSON.stringify(location));
    });

    backgroundGeoLocation.watchLocationMode(function(location) {
        alert("getLocations: " + JSON.stringify(location));
    });

    backgroundGeoLocation.onStationary(function(location) {
        alert("onStationary: " + JSON.stringify(location));
    });

    backgroundGeoLocation.configure(function(location) {
        alert("configure ok: " + JSON.stringify(location));
        backgroundGeoLocation.finish();
    }, function(msg) {
        alert("configure fail: " + JSON.stringify(msg));
    }, {
        desiredAccuracy: 10,
        stationaryRadius: 15,
        distanceFilter: 20,
        stopOnTerminate: false,
        locationTimeout: 30,
        notificationTitle: 'TripTrack',
        notificationText: 'Recording trip',
        locationService: 0,
        activityType: 'AutomotiveNavigation',
        fastestInterval: 5000,
        activitiesInterval: 10000
    });

    backgroundGeoLocation.start();

    backgroundGeoLocation.isLocationEnabled(function(location) {
        alert("isLocationEnabled: " + JSON.stringify(location));
    });

    backgroundGeoLocation.changePace(true);
`

**Comment by mauron85** [comment]
Try to run in iOS Simulator and connect it to Safari remote debug and watch console logs, if there is something not right.

**Comment by karolszklarski** [comment]
I created a new cordova out-of-a-box project, installed minimal required plugins, added configure and start in onDeviceReady and then it works. So there's clearly something wrong on my side.

I also noticed that in this minimal project navigator.geolocation.watchPosition started to work in background and even setInterval() works in a background too. In my "big" project none of these work in background, but they are resumed when app goes back to foreground.

I'll write more when I'll find out what's the problem.

**Comment by neoadventist** [comment]
@karolszklarski same here, I get the notification, but no data is sent and no error.

**Comment by karolszklarski** [comment]
Currently I got it working this way:

In onDeviceReady:
```
    setInterval(function() {   // for debugging
        logInfo('tick');     // prints to js console and sends by http post to server
    }, 10000);`

    backgroundGeoLocation.configure(bgLocCallback, fail, {
        desiredAccuracy: 0,   // best
        stationaryRadius: 20,
        distanceFilter: 10,
        activityType: 'Fitness',
        stopOnTerminate: true
    });
```
Start:
```
    backgroundGeoLocation.start();
    setTimeout(function() {
      // I guess it should be executed after start, so I add delay
      // to avoid potential asynchronous execution problems
      backgroundGeoLocation.changePace(true, function() {}, function() {})
    }, 5000);
```

It still needs some cleanup and more debugging, but it looks like changePace() is crucial.

Without changePace I get one or two locations in foreground and then nothing. The 'tick' log keeps showing only in foreground.

With changePace I keep getting locations from time to time, in both foreground and background. The 'tick' log keeps showing all the time, even in background.

I suppose that without changePace I'd have to move until cell tower change to activate gps. Then whole app would resume, along with 'tick' and everything it does in other setInterval functions. I have to test it yet. Also I wonder when the plugin switches back from 'moving' to 'stationary' mode.

**Comment by mauron85** [comment]
Please try SampleApp, if it's working on your 5c. Because changePace should not be called to achieve position update.

**Comment by luposlip** [comment]
Any news on this issue? I can't get any location updates from my app at all on iOS. It works fine on Android though.

**Comment by mauron85** [comment]
Please try version 1.0.1. Reopen if necessary.
