### ISSUE TITLE
void com.marianhello.bgloc.LocationProvider.onDestroy() on a null object reference

### ISSUE THREAD

**Issue by ftunholm** [mauron85/cordova-plugin-background-geolocation#390]
## Your Environment
* Plugin version: 2.3.3
* Platform: Android
* OS version: API level 27
* Device manufacturer and model: Nexus 5X
* Cordova version: 8.0.0
* Cordova platform version: android 7.0.0
* Plugin configuration options: 

    let config: BackgroundGeolocationConfig = {
      desiredAccuracy: 10,
      stationaryRadius: 1,
      distanceFilter: 0,
      debug: false,
      stopOnTerminate: false,
      startOnBoot: false,
      startForeground: false,
      pauseLocationUpdates: false,
      url: "...",
      httpHeaders: {"Authorization": "..."},
      stopOnStillActivity: true
    };

This happened to me in --prod --release mode. I start the app fine, background geolocation starts successfully. It keeps running fine in background also. But when i kill the app (open latest and swipe it away) the app crashes, the stacktrace should give you a pretty good idea about the problem. I have not investigated it myself yet, I don't have the time this evening. I appreciate all the help i can get on the matter.

## Context
I tried to keep the location service running when app is killed

## Debug logs
Exception java.lang.RuntimeException: Unable to stop service com.marianhello.bgloc.LocationService@75d0f1c: java.lang.NullPointerException: Attempt to invoke interface method 'void com.marianhello.bgloc.LocationProvider.onDestroy()' on a null object reference
android.app.ActivityThread.handleStopService (ActivityThread.java:3522)
android.app.ActivityThread.-wrap26 ()
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1697)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:6494)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)

Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void com.marianhello.bgloc.LocationProvider.onDestroy()' on a null object reference
com.marianhello.bgloc.LocationService.onDestroy (LocationService.java:188)
android.app.ActivityThread.handleStopService (ActivityThread.java:3504)
android.app.ActivityThread.-wrap26 ()
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1697)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:6494)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)

**Comment by mauron85** [comment]
FYI: Fixed in 3.x branch

**Comment by ftunholm** [comment]
Thanks for the fast reply. Is 3.x stable? Looking forward to trying out the new stuff. Keep up the good work, this is a great plugin.

**Comment by RajanYugtia** [comment]
I am using version 3.0.0 alpha.50 still got this error.
