### ISSUE TITLE
postTemplate option not working on Android

### ISSUE THREAD

**Issue by gcivicodev** [mauron85/cordova-plugin-background-geolocation#392]
## Your Environment

* Plugin version: 2.3.3
* Platform: Android
* OS version: Windows 10
* Device manufacturer and model: Samsung S6 Edge
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`):
```
Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
```
* Plugin configuration options: 
```
let config = {
	// locationProvider: 0,
	desiredAccuracy: 0,
	// stationaryRadius: 20,
	stationaryRadius: 1,
	debug: true,
	// distanceFilter: 10,
	distanceFilter: 1,
	stopOnTerminate: true,
	/* Android */startOnBoot: false,
	/* Android */startForeground: true,
	/* Android */interval: 60000,
	/* Android */fastestInterval: 120000,
	/* Android */activitiesInterval: 10000,
	/* IOs */activityType: 'OtherNavigation',
	/* IOs */pauseLocationUpdates: false,
	/* IOs */saveBatteryOnBackground: false,
	url: 'https://myBackendServiceUrl...',
	httpHeaders: { 'Content-Type':'application/json' },
	postTemplate: {
		lat: '@latitude',
		lon: '@longitude',
		foo: 'bar' // you can also add your own properties
	}
};
```
* Link to your project: Is a private project.

## Context

I configured the postTemplate option equally to the example [here](https://github.com/mauron85/cordova-plugin-background-geolocation#custom-post-template) but when background geolocation started (on foreground or background) the post registered is this:
```
{
    "_id" : ObjectId("5abacc5ebb0cb6362ef2d11b"),
    "provider" : "gps",
    "time" : 1522191453907.0,
    "latitude" : 3.42219499821646,
    "longitude" : -76.5332469170133,
    "accuracy" : 24,
    "speed" : 0.173585832118988,
    "altitude" : 1018.49943172358,
    "bearing" : 341.454254150391,
    "locationProvider" : 0
}
```
and the `lat`, `lon `and `foo `properties never registered (or posted).

## Expected Behavior

The `lat`, `lon `and `foo` properties should be posted.

## Actual Behavior

The `lat`, `lon `and `foo` properties never posted.

## Steps to Reproduce

1. Create ionic-angular project.
2. Add the plugin following the instructions [here](https://github.com/mauron85/cordova-plugin-background-geolocation)
3. Add android platform.
4. Configure the options like above.
5. Test the app on android device. 
6. A backend is needed to process the http post call.

## Context

I am trying to store some custom properties using the postTemplate option.

## Debug logs

There is no printed bug for this in my context.

**Comment by mauron85** [comment]
Sorry postTemplate is feature of version 3.x

**Comment by gcivicodev** [comment]
Thanks. I already have a way to solve this. 
And by the way, nice plugin!
