### ISSUE TITLE
Notification do not appear after install some plugins

### ISSUE THREAD

**Issue by localdrive** [mauron85/cordova-plugin-background-geolocation#395]
## Your Environment

* Plugin version: 3.0.0-alpha.23
* Platform: Android
* OS version: 8
* Device manufacturer and model: Samsung Galaxy S8
* Cordova version (`cordova -v`): 8
* Cordova platform version (`cordova platform ls`): 7.1
* Plugin configuration options: none
* Link to your project:

## Context

The `notificationTitle` do not appear on notifications bar after install some plugins. I suspect that this problem is related to _android/project.properties_ configurations. This issue can cause android to kill background proccess?

## Expected Behavior

Show the text on `notificationTitle` at notifications bar.

## Actual Behavior

Nothing related appear on notification bar.

## Steps to Reproduce

1. Install this plugin
2. install cordova-plugin-x-socialsharing

**Comment by mauron85** [comment]
Yes, this plugin is still not Oreo compatible. Please wait

**Comment by localdrive** [comment]
Thank you for response. Is there any other version compatible?

**Comment by mauron85** [comment]
Actually, you use bit older 3.0.0-alpha.15-oreo.2

**Comment by mauron85** [comment]
Should be ok in latest alpha 24
