### ISSUE TITLE
Attempt to read from field 'double android.location.Location.mLatitude' on a null object reference

### ISSUE THREAD

**Issue by ftunholm** [mauron85/cordova-plugin-background-geolocation#398]
## Your Environment
* Plugin version: 2.3.5
* Platform: Android
* OS version: 8.0.0 Oreo
* Device manufacturer and model: Samsung Galaxy S8
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 7.0.0
* Plugin configuration options: 
      desiredAccuracy: 0,
      stationaryRadius: 10,
      distanceFilter: 20,
      interval: 30000,
      debug: false,
      stopOnTerminate: false,
      startOnBoot: true,
      startForeground: false,
      pauseLocationUpdates: false,
      url: HttpServiceProvider.getSearchForOffersUrl(),
      syncUrl: HttpServiceProvider.getSearchForOffersUrl(),
      syncThreshold: 5,
      maxLocations: 20,
      httpHeaders: {"Authorization": "Token " + token},
      stopOnStillActivity: false

## Context
When i killed the app i got the classic error message "Your app has stopped working".

## Expected Behavior
I expected the background geolocation service to run in background and send location updates to server

## Actual Behavior
The app crashed when i killed it (swiped it away)

## Debug logs
Exception java.lang.NullPointerException: Attempt to read from field 'double android.location.Location.mLatitude' on a null object reference
android.location.Location.distanceTo (Location.java:482)
com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider.onLocationChanged (DistanceFilterLocationProvider.java:310)
android.location.LocationManager$ListenerTransport._handleMessage (LocationManager.java:291)
android.location.LocationManager$ListenerTransport.-wrap0 ()
android.location.LocationManager$ListenerTransport$1.handleMessage (LocationManager.java:236)
android.os.Handler.dispatchMessage (Handler.java:105)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:6938)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)

**Comment by mauron85** [comment]
Please try latest 3.x. Version 2.x is not supported.

**Comment by ftunholm** [comment]
I had some problems with 3.x, same as #377 the "workaround" made the plugin start, but i got some other errors. Better wait for the offical release. Thanks
