### ISSUE TITLE
Request: Turn on Location Services using Google Play Services

### ISSUE THREAD

**Issue by tolu360** [mauron85/cordova-plugin-background-geolocation#40]
Hello,

This is more or less a request, since the plugin already leverages the `Google Play Services` - Would it be possible to expose an API/method that turns on the device's location services without first going to the device settings view as `showLocationSettings` currently does?

I'm working on a project where the client wants the behaviour they have seen on Google Maps app - which just uses a dialog to ask for user's permission to turn on location without opening the settings or navigation away from the app.

Thank you.

**Comment by tolu360** [comment]
#Update: You may disregard my request to keep the plugin from getting bloated. if anyone's looking for the feature I wanted, they may use - https://github.com/dpa99c/cordova-plugin-request-location-accuracy 

Cheers.

**Comment by mauron85** [comment]
Actually, this is worth to be implemented.

**Comment by tolu360** [comment]
I quite agree with you, thank you @mauron85

**Comment by mauron85** [comment]
Google in latest version of Android actually disallowed this. Not possible to implement. Sorry.
