### ISSUE TITLE
don't work with cordova-plugin-fcm

### ISSUE THREAD

**Issue by xkelxmc** [mauron85/cordova-plugin-background-geolocation#401]
## Theme
i have problem with use *cordova fcm* and *cordova background geolocation* on my ionic v3 app
I have app, this running correctly with fcm, but i add background geolocation, and then have drop and errors...

## Your Environment
* Plugin version: v2.3.5
* Platform: Android 
* OS version: 5.0.2
* Device manufacturer and model: redmi note 2
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): 
Installed platforms:
  android 7.0.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0
* Plugin configuration options: 
* Link to your project: 

## Context
My app have Building failed - google service error, i do magic witch versions and build.gradle, and i have win, my app building successful with comment (FCMPlugin.gradle)
```// apply plugin: com.google.gms.googleservices.GoogleServicesPlugin```

and change version from 11+ to 12.0.1 in (project.properies)
```cordova.system.library.2=com.google.android.gms:play-services-location:12.0.1```
BUT my app has ceased runs on my device, hi drop after start....

Who can help me?))
p.s. sry for my bad english

## Steps to Reproduce
1. create ionic app
2.  add https://github.com/fechanique/cordova-plugin-fcm
3. add cordova-plugin-background-geolocation
4. have nice day with errors, and build failed

**Comment by bastiendonjon** [comment]
+1 !
