### ISSUE TITLE
Java Crash Null Pointer Exception

### ISSUE THREAD

**Issue by DannyS121** [mauron85/cordova-plugin-background-geolocation#403]
Java crash null pointer exception while the app is running in the background.

## Your Environment
* Plugin version: 3.0.0-alpha.24
* Platform: Android
* OS version: 7.0
* Device manufacturer and model: Samsung Galaxy Xcover4 (xcover4lte), 2048MB RAM, Android 7.0
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): 7.1.0
* Plugin configuration options: 
"GOOGLE_PLAY_SERVICES_VERSION" value="11+"
 "ANDROID_SUPPORT_LIBRARY_VERSION" value="27.1.0" 

## Context
Some of our users have reported that our App is crashing while in the background. I have checked the google play store crash report tool and I have included it at the bottom. I have not been able to reproduce this issue on various devices including the one mentioned above.

## Expected Behavior
Continue tracking the GPS while the app is in the background.

## Actual Behavior
App crashed due to java exception.

## Possible Fix
Unknown

## Steps to Reproduce
Unknown

## Context
We are trying to get the app to run in the background tracking the GPS for 12+ hours.

## Debug logs
java.lang.RuntimeException: 
1. at android.app.LoadedApk$ReceiverDispatcher$Args.run (LoadedApk.java:1195)
2. at android.os.Handler.handleCallback (Handler.java:751)
3. at android.os.Handler.dispatchMessage (Handler.java:95)
4. at android.os.Looper.loop (Looper.java:154)
5. at android.os.HandlerThread.run (HandlerThread.java:61)

Caused by: java.lang.NullPointerException: 
1. at android.location.Location.distanceTo (Location.java:460)
2. at com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider.onPollStationaryLocation (DistanceFilterLocationProvider.java:427)
3. at com.tenforwardconsulting.bgloc.DistanceFilterLocationProvider$1.onReceive (DistanceFilterLocationProvider.java:453)
4. at android.app.LoadedApk$ReceiverDispatcher$Args.run (LoadedApk.java:1185)

**Comment by mauron85** [comment]
Maybe this PR will fix this https://github.com/mauron85/background-geolocation-android/pull/2/files
Do you have time and resources to try?

**Comment by DannyS121** [comment]
Hi, 

Thanks for the quick response. I can get this done for you. It will probably be sometime tomorrow before I can give some feedback on if it's working or not.

Regards,
Dan

**Comment by mauron85** [comment]
It's already merged in common module and react-native variant. Soon will be for cordova too.

**Comment by DannyS121** [comment]
Hi, 

Sorry for the late reply, I have given it a test over the weekend and it seems to have resolved the crashes to do with the Java error.

Thanks for the help! :+1: 

Regards,
Dan

**Comment by mauron85** [comment]
@DannyS121 ok thank u for the feedback. Closing then
