### ISSUE TITLE
Whats the difference between this plugin and the Transistorsoft plugin?

### ISSUE THREAD

**Issue by rwillett** [mauron85/cordova-plugin-background-geolocation#406]
Hi,

I stumbled on this plugin whilst searching for something else, I glanced at the docs and thought I recognised the configuration, looked a bit closely and it clearly is based on the plugin from Christocracy. The fact its stated as a fork of christocracy/cordova-plugin-background-geolocation does give the game away as well :)

We use Chris's plugin as a paid customer and it works well for us, we were interested in what the differences were with this plugin and the paid one. We did look around the issues and docs, but there didn't seem to be any obvious doc stating what the differences are.

Its clearly quite closely related as the mechanism for updating the plist messages appears to be the same. We're interested to see if this plugin has any significant advantages over Chris's.

Many thanks 

Rob
www.jambuster.london

**Comment by mauron85** [comment]
This project is based on older https://github.com/christocracy/cordova-plugin-background-geolocation. The API looks similar, however if you look closer there are some differences (like configure vs ready...). It currently has less features like there is no geofence support (I suggest using separate plugin for that), no support for time based scheduling for location syncing,  background and scheduled tasks.
The most significant difference is thus plugin is complete free for Android and iOS. 
But if you're happy with Transistorsoft's version then maybe stick with it. You'll support Chris and his company. He deserve it as he is also contributing to many other projects.

However I plan to add some unique features later on. So maybe keeping eye on this is good idea.

**Comment by rwillett** [comment]
Thanks for the update. Much appreciated.

We built our own geofence support as we wanted a geofence that was the size and shape of the London congestion charge. Thats a rather irregular polygon about 6 miles by 3. A simple geofence wouldn't quite have worked :)

You mention 'background', Does your plugin not work in the background? We thought it did from reading the docs. We don't use much of the other functionality to be honest.

Chris's stuff works well though and we have a perpetual license,

Thanks again and best wishes,

Rob

**Comment by mauron85** [comment]
This plugin works in background.
I mean [schedule](https://github.com/transistorsoft/cordova-background-geolocation-lt/blob/master/docs/README.md#schedule), which allows you to run arbitrary js code in defined intervals (this plugin will run your code as result of locations event only).

Just one more thing :) If you use this plugin and build your app in React then you can switch to react-native later on. Example app is doing that. It's build on react-native-web and using react native variant of the plugin.

**Comment by mauron85** [comment]
That use case is definitely out of scope of this plugin for now. ;)  Sound cool though.

Personal side note for other readers. It look like a simple fork, but keep it mind this fork is based on very different project that is now. Most of the features original project doesn't have. So I've already spent many hours on implementing them. Just for comparison, this is the state of project serving as a baseline:

https://github.com/christocracy/cordova-plugin-background-geolocation/tree/9f8f4bb40b3df4da6f7328a72f92411750db6df8
