### ISSUE TITLE
Location event time is imprecise

### ISSUE THREAD

**Issue by Tiagow** [mauron85/cordova-plugin-background-geolocation#407]
## Your Environment

* Plugin version: 3.0.0-alpha.24
* Platform: Android
* OS version: 8 
* Device manufacturer and model: Galaxy  #S8
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): Android 6.3.0
* Plugin configuration options: 
* Link to your project:

## Context
I've read all the docs and Issues in this repository hoping to find an answer to my predicament.
In my context it's ok that it sometimes takes a while before sending and syncing the data to my backend, but the correct timestamp of the location is a must for me. 
I've tried to send a new Date in the custom post template, but it doesn't refresh the Date, just gets the date of when the template was set.
This problem occured in all of devices i used to test, not just the galaxy s8, even tho they were all made by samsung but other models.
Could you please recommend a way to solve this issue or should i try to send the location manually when the event `location` is fired?
I'm trying to solve this issue for a couple of days now and already lost some hair hahahah
Thanks.

**Comment by mauron85** [comment]
There is `time` in location event, it's time recorded by gps sensor (or any other provider). That is the only value you want to use.

**Comment by Tiagow** [comment]
I'm sorry if i didnt't specify why how or when the time is imprecise.
My problem seems to be when the plugin tries to sync all the stored locations when it reaches the `syncThreshold` number.
I tested several times letting the device without any connection and then when i turn it on again, the recorded time in my db is just couple of minutes before the actual time my server commited the transaction. Usually it would be fine, but i left the device recording the locations for at least 30 minutes.
Hope i made myself clear this time.
Thanks for the reply.

**Comment by Tiagow** [comment]
> There is time in location event, it's time recorded by gps sensor (or net provider...). That is the only value you want to use.

Reading carefully what you said.. Does this could mean that if the device is in another country/timezone that is not the same as mine, the provided time could be different? 
If this is true, is it possible to get the timezone along with the time?

**Comment by Tiagow** [comment]
After using RAW_LOCATION_PROVIDER I got better results. 
Thanks.
