### ISSUE TITLE
App Crashes on Calling BackgroundGeolocation.configure Second Time

### ISSUE THREAD

**Issue by onkar0777** [mauron85/cordova-plugin-background-geolocation#409]
## Your Environment

* Plugin version: 3.0.0-alpha.24
* Platform: Android
* OS version: 6.0.1
* Device manufacturer and model: OnePlus2
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): 7.0.0
* Plugin configuration options: locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
            desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
            stationaryRadius: 1,
            distanceFilter: 2,
            stopOnTerminate: false,
            startOnBoot: true,
            startForeground:true,
            debug: false,
            notificationTitle: 'Background tracking',
            notificationText: 'Enabled for Vehicle Tracking',
            interval: 5000,
            fastestInterval: 2000,
            activitiesInterval: 100000000,
            url: serverLocationUrl+'?routeId='+routeId,
            maxLocations: 1,
            httpHeaders: {
                'authorization': $window.UTILITIES.LOCAL_STORAGE.get('auth')
            },
            // customize post properties
            postTemplate: {
                latitude: '@latitude',
                lonngitude: '@longitude',
                bearing: '@bearing',
                speed: '@speed'
            }
* Link to your project:

## Context

Due to a faulty logic i ended up calling BackgroundGeolocation.configure() second time and the app crashed as soon as it reaches the code.
## Expected Behavior

App should not crash - can give a warning in console logs or ignore the new configuration or override the old configuration
## Actual Behavior

App Crashed
## Steps to Reproduce

1. Call BackgroundGeolocation.configure
2. Call BackgroundGeolocation.start
3. Call BackgroundGeolocation.configure again

## Context

It is not affecting me as I have changed the logic and now it gets called only once. Just opening this issue to keep track of this.
## Debug logs

04-18 15:28:44.399 22117 22117 D wpa_supplicant: CTRL_IFACE monitor sent successfully to /data/misc/wifi/sockets/wpa_ctrl_1388-11\x00
  timestamp = 1524045524593276 D GpsLocationProvider: reportNmea $GPGSV,3,1,12,06,39,187,21,07,42,135,26,13,26,282,20,19,51,274,25*7D
  timestamp = 1524045524594276 D GpsLocationProvider: reportNmea $GPGSV,3,2,12,30,70,113,28,01,18,045,,02,06,206,,03,00,000,*7C
  timestamp = 1524045524594276 D GpsLocationProvider: reportNmea $GPGSV,3,3,12,09,04,161,,11,10,039,,15,00,000,,28,35,018,*7B
  timestamp = 1524045524594276 D GpsLocationProvider: reportNmea $GLGSV,2,1,07,74,50,061,19,86,45,224,,73,20,118,,75,28,350,*63
  timestamp = 1524045524595276 D GpsLocationProvider: reportNmea $GLGSV,2,2,07,84,14,021,,85,65,350,,72,01,217,*50
04-18 15:28:44.600  1388  4276 V GpsLocationProvider: reportLocation lat: 12.91288899 long: 77.60788627 timestamp: 1524045454000
  timestamp = 1524045524601276 D GpsLocationProvider: reportNmea $GPGSA,A,3,06,07,13,19,30,,,,,,,,1.6,1.3,1.0*3E
  timestamp = 1524045524601276 D GpsLocationProvider: reportNmea $GPVTG,,T,,M,0.0,N,0.0,K,D*26
  timestamp = 1524045524601276 D GpsLocationProvider: reportNmea $GPRMC,095734,A,1254.773339,N,07736.473176,E,0.0,,180418,1.1,W,D*27
  timestamp = 1524045524603276 D GpsLocationProvider: reportNmea $GPGGA,095734,1254.773339,N,07736.473176,E,2,05,1.3,910.0,M,-85.0,M,,*6F
04-18 15:28:44.652  4259 20637 W ctxmgr  : [AclManager]No 2 for (accnt=account#-1053903722#, com.google.android.gms(10012):UserLocationProducer, vrsn=12521000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 4259). Was: 2 for 1, account#-1053903722#
04-18 15:28:44.660  4259 20637 W ctxmgr  : [AclManager]No 2 for (accnt=account#-1583333941#, com.google.android.gms(10012):UserLocationProducer, vrsn=12521000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 4259). Was: 2 for 1, account#-1583333941#
04-18 15:28:44.993  3914  4201 D NetworkController.MobileSignalController(3): onSignalStrengthsChanged signalStrength=SignalStrength: 99 0 -120 -160 -120 -1 -1 18 -106 -12 62 2147483647 2147483647 3 3 gsm|lte level=3 voicelevel=3 datalevel=3
04-18 15:28:45.039  7801  7801 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
04-18 15:28:45.974 22117 22117 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
04-18 15:28:45.976 22117 22117 D wpa_supplicant: CTRL-DEBUG: global_ctrl_sock-sendto: sock=11 sndbuf=212992 outq=0 send_len=48
04-18 15:28:45.994 19762 19762 D SystemWebChromeClient: file:///android_asset/www/js/angular/controllers/map-controller.js: Line 10 : 5ad08553a5172c2e88b2e8e3
04-18 15:28:45.994 19762 19762 I chromium: [INFO:CONSOLE(10)] "5ad08553a5172c2e88b2e8e3", source: file:///android_asset/www/js/angular/controllers/map-controller.js (10)
04-18 15:28:46.006 19762 19762 D SystemWebChromeClient: file:///android_asset/www/js/angular/controllers/bus-routes-controller.js: Line 61 : app.map
04-18 15:28:46.006 19762 19762 I chromium: [INFO:CONSOLE(61)] "app.map", source: file:///android_asset/www/js/angular/controllers/bus-routes-controller.js (61)
04-18 15:28:46.007 19762 19762 D SystemWebChromeClient: file:///android_asset/www/js/angular/controllers/bus-routes-controller.js: Line 62 : app.busroutes
04-18 15:28:46.007 19762 19762 I chromium: [INFO:CONSOLE(62)] "app.busroutes", source: file:///android_asset/www/js/angular/controllers/bus-routes-controller.js (62)
04-18 15:28:46.021 19762 20952 D com.marianhello.bgloc.data.sqlite.SQLiteConfigurationDAO: Configuration persisted with rowId = 1
04-18 15:28:46.021 19762 20952 D com.marianhello.bgloc.BackgroundGeolocationFacade: Service configured with: Config[distanceFilter=20 stationaryRadius=10.0 desiredAccuracy=0 interval=5000 fastestInterval=2000 activitiesInterval=100000000 isDebugging=false stopOnTerminate=false stopOnStillActivity=true startOnBoot=true startForeground=true locationProvider=0 nTitle=Background tracking nText=Enabled for Vehicle Tracking nIconLarge= nIconSmall=resources/android/icon/drawable-xhdpi-icon.png nIconColor= url=http://192.168.1.5:3500/service/gps/saveLocationForDriver?routeId=5ad08553a5172c2e88b2e8e3 syncUrl= syncThreshold=100 httpHeaders={authorization=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiI1YWQwODRmYWE1MTcyYzJlODhiMmU4ZTIiLCJyb2xlIjoiRFJJVkVSIiwiaWF0IjoxNTIzNzM1MTQ2fQ.5m00pheFmw_c2zeGY-mPIacyJQPlj-FIqHUW6RBhuxY} maxLocations=1 postTemplate={"bear":"@bearing","lon":"@longitude","lat":"@latitude","speed":"@speed"}]
04-18 15:28:46.032 19762 19762 D com.marianhello.bgloc.LocationService: Handler received message: { what=7 when=0 target=Handler (com.marianhello.bgloc.LocationService$IncomingHandler) {1cd67f5} }
04-18 15:28:46.045 19762 19762 D AndroidRuntime: Shutting down VM
```
04-18 15:28:46.047 19762 19762 E AndroidRuntime: FATAL EXCEPTION: main
04-18 15:28:46.047 19762 19762 E AndroidRuntime: Process: com.followclass.driver, PID: 19762
04-18 15:28:46.047 19762 19762 E AndroidRuntime: java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(pri=0 contentView=com.followclass.driver/0x1090085 vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 vis=PRIVATE)
04-18 15:28:46.047 19762 19762 E AndroidRuntime: 	at android.app.NotificationManager.notify(NotificationManager.java:223)
04-18 15:28:46.047 19762 19762 E AndroidRuntime: 	at android.app.NotificationManager.notify(NotificationManager.java:195)
04-18 15:28:46.047 19762 19762 E AndroidRuntime: 	at com.marianhello.bgloc.LocationService.configure(LocationService.java:380)
04-18 15:28:46.047 19762 19762 E AndroidRuntime: 	at com.marianhello.bgloc.LocationService.configure(LocationService.java:402)
04-18 15:28:46.047 19762 19762 E AndroidRuntime: 	at com.marianhello.bgloc.LocationService.access$200(LocationService.java:64)
04-18 15:28:46.047 19762 19762 E AndroidRuntime: 	at com.marianhello.bgloc.LocationService$IncomingHandler.handleMessage(LocationService.java:172)
04-18 15:28:46.047 19762 19762 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-18 15:28:46.047 19762 19762 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:152)
04-18 15:28:46.047 19762 19762 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5497)
04-18 15:28:46.047 19762 19762 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 15:28:46.047 19762 19762 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-18 15:28:46.047 19762 19762 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-18 15:28:46.050 19762 19762 D AppTracker: App Event: crash
04-18 15:28:46.061  1388  4456 W ActivityManager:   Force finishing activity com.followclass.driver/.MainActivity
```
04-18 15:28:46.065  3914  3914 I StatusBarIconController:  appTransitionPending
04-18 15:28:46.089  1388  4456 I ActivityManager_Thumbnails: Setting thumbnail of ActivityRecord{389ad5a u0 com.followclass.driver/.MainActivity t178 f} to android.graphics.Bitmap@80b0d5c
04-18 15:28:46.093  1388 20955 D DropBoxManagerService: file :: /data/system/dropbox/data_app_crash@1524045526073.txt
04-18 15:28:46.108  1388  1669 W ActivityManager:  Dismiss app error dialog : com.followclass.driver
04-18 15:28:46.109  1388  1669 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=1464854877792 duration=9102 nesting=0
04-18 15:28:46.111 19762 19762 I Process : Sending signal. PID: 19762 SIG: 9
04-18 15:28:46.112  3914  3914 D PhoneStatusBar: setSystemUiVisibility vis=8000 mask=ffffffff oldVal=8600 newVal=8000 diff=600
04-18 15:28:46.149  7801  7801 W Settings: Setting preferred_network_mode has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
04-18 15:28:46.196  1388  4456 I WindowState: WIN DEATH: Window{827a361 u0 com.followclass.driver/com.followclass.driver.MainActivity}
04-18 15:28:46.197  1388  1663 V ActivityManager: killProcessGroupAsync took 0 ms for PID 19762 on thread 14
04-18 15:28:46.197  1388  4498 D GraphicsStats: Buffer count: 8
04-18 15:28:46.198  1388  4481 I ActivityManager: Process com.followclass.driver (pid 19762) has died
04-18 15:28:46.198  1388  4481 D ActivityManager: cleanUpApplicationRecord -- 19762
04-18 15:28:46.198  1388  4444 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=1628, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ], android.os.BinderProxy@7bc6592)
04-18 15:28:46.198  1388  4481 W ActivityManager: Service crashed 2 times, stopping: ServiceRecord{1ad8451 u0 com.followclass.driver/com.marianhello.bgloc.LocationService}
04-18 15:28:46.198  1388  3828 D ConnectivityService: releasing NetworkRequest NetworkRequest [ id=1628, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
04-18 15:28:46.199  1388  3828 D ConnectivityService: sending notification RELEASED for NetworkRequest [ id=1628, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
04-18 15:28:46.199  1388  3828 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=1628, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
04-18 15:28:46.199  1388  1548 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ id=1629, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ], android.os.BinderProxy@315eb63)
04-18 15:28:46.200  1388  3828 D ConnectivityService: releasing NetworkRequest NetworkRequest [ id=1629, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
04-18 15:28:46.200  1388  3828 D ConnectivityService: sending notification RELEASED for NetworkRequest [ id=1629, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]
04-18 15:28:46.200  1388  3828 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ id=1629, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED] ]

**Comment by mauron85** [comment]
Is there any chance you've used `notificationIconSmall` configure option?

**Comment by onkar0777** [comment]
I may have used it once and then removed it. So basically if I set it once, then the next time it expects it to be present, is that it ?

**Comment by mauron85** [comment]
just set it to null
