### ISSUE TITLE
Dude: Read GPS position only once

### ISSUE THREAD

**Issue by marcoas** [mauron85/cordova-plugin-background-geolocation#41]
(Translated by Google)

I need to read the GPS position in background , just once . No repeatedly. Only when the app , receive a push notification .

Is it possible with this plugin do that?

The idea is to show (or not), the notification to the user, depending on whether the person is close to the position reached in the notification itself.

Thanks

**Comment by mauron85** [comment]
You don't need this plugin for it. You more need phonegap-build/PushPlugin and HTML5 geolocation navigator.geolocation.getCurrentPosition (on platforms missing geolocation use cordova-geolocation as polyfill)

**Comment by marcoas** [comment]
thank
