### ISSUE TITLE
Java files are hidden

### ISSUE THREAD

**Issue by mrHassanRaza** [mauron85/cordova-plugin-background-geolocation#410]
After installing this plugin I need to update java file for more ease but there is no java file on display against different folders.. WHY ?

**Comment by mrHassanRaza** [comment]
![capturewtf](https://user-images.githubusercontent.com/30258796/39053667-033899a6-44c9-11e8-8a5d-4713ad70795f.PNG)

**Comment by mauron85** [comment]
Normally I would not respond if I see WTF, but I feel you frustration here.
What you marked yellow is actually quote from https://developer.android.com/topic/libraries/support-library/setup.html

>The support libraries are now available through Google's Maven repository. We no longer support downloading the libraries through the SDK Manager, and that functionality will be removed soon..

The requirements table now just show default support library plugin will use by default.
