### ISSUE TITLE
BackgroundGeolocation is not defined error.

### ISSUE THREAD

**Issue by mrHassanRaza** [mauron85/cordova-plugin-background-geolocation#411]
When the application runs there comes an error such that:
>BackgroundGeolocation is not defined error.

**Comment by grassick** [comment]
Yes, it appears to be in `backgroundGeolocation`, not `BackgroundGeolocation`, but even that one is incomplete, as it doesn't contain `HIGH_ACCURACY`, etc. Somethings is dreadfully wrong with the latest version?

**Comment by grassick** [comment]
I should add that I'm on cordova 8.0, adding to an Android project, building on Linux. window.BackgroundGeolocation is not defined, but the camelcase one is.

**Comment by mauron85** [comment]
@grassick if you want to install latest version from npm you need to add version:

```
cordova plugin add cordova-plugin-mauron85-background-geolocation@latest
```
or 
```
cordova plugin add cordova-plugin-mauron85-background-geolocation@3.0.0-alpha.24
```

**Comment by mauron85** [comment]
I think you've resolved your issue by now. Closing.

**Comment by mauron85** [comment]
Duplicate of https://github.com/mauron85/cordova-plugin-background-geolocation/issues/353.
