### ISSUE TITLE
ActivityLocationProvider outputting debug message on iOS

### ISSUE THREAD

**Issue by estacks** [mauron85/cordova-plugin-background-geolocation#413]
## Your Environment

* Plugin version: 3.0.0-alpha.24
* Platform: iOS

## Context

When the ActivityLocationProvider detects a new activity it incorrectly outputs a debug notification.

## Possible Fix
ios/common/BackgroundGeolocation/ActivityLocationProvider.m, Line 174
`[self notify:[NSString stringWithFormat:@"%@ activity detected: %@ activity, confidence: %d", TAG, type, confidence]];`

The notify command does not check for the debug flag.

**Comment by mauron85** [comment]
I think this one was fixed, but yet not published.
