### ISSUE TITLE
Discussion: What is a good config for consistent location updates?

### ISSUE THREAD

**Issue by ftunholm** [mauron85/cordova-plugin-background-geolocation#420]
Hello there!

I can't seem to label this with discussion, don't know where else to present this matter, I hope it's fine here.

I have been trying out some different settings for some time now, I have had more and less luck with different devices. I have a hard time on Oreo especially. Sometimes when I try the config out it seems to do exactly what I want, other times I get no locations request at all with the same config.

Some that is worth to note is that I get some requests from my app, I'm not sure where the request timeouts occur, I suspect it is geolocation. Any familiar with something like this (apache access.log)?:

m.y.i.p - - [07/May/2018:14:13:26 +0000] "-" 408 0 "-" "-" 

Does anyone have a good idea for me what I can run? My goal is to get consistent location updates while in motion (walking, car, bicycle), something like every 300-500 meters with the default provider, alternatively I want to get an update every ~3-5 min with activity provider (have not gotten this one to work out at all for me yet)

If you have any experience with a good set of config please let me know. Thanks!

This is the current config I have been running:

      desiredAccuracy: 0,
      stationaryRadius: 10,
      distanceFilter: 20,
      interval: 30000,
      stopOnTerminate: false,
      startOnBoot: true,
      startForeground: false,
      pauseLocationUpdates: false,
      syncThreshold: 5,
      maxLocations: 20,
      stopOnStillActivity: false

**Comment by ftunholm** [comment]
Good evening folks!

I just tried out some settings with ACTIVITY_PROVIDER, I must say I'm really satisfied. It might also be because I also set startForeground: true. But I really got a good result, it detects activity right on the time it should, the updates comes a clockwork. Just tried it out both in background and foreground for 1h walking. I will keep an eye on it the coming days with more mixed activity. 

      locationProvider: 1, //Activity provider
      desiredAccuracy: 0,
      stationaryRadius: 30,
      distanceFilter: 20,
      interval: 180000,
      fastestInterval: 120000,
      activitiesInterval: 20000,
      stopOnTerminate: false,
      startOnBoot: true,
      startForeground: true,
      pauseLocationUpdates: false,
      syncThreshold: 5,
      maxLocations: 20,
      stopOnStillActivity: true,

**Comment by jfbourne** [comment]
Thanks for the update! Looking forward to hearing more about your progress

**Comment by ftunholm** [comment]
@Chal131313 with that config I get a location update every 1-3 minutes, almost as expected. One thing I have noticed is that sometimes it posts 2-4 updates at the same time, I'm guessing it's the same location as well, that seems to happen when the speed is higher, like when traveling in a car or train. It does not bother me too much tho, everything has been working out fine for days now, in both foreground and background, even with long periods of passivity in between.

**Comment by andersborgabiro** [comment]
I use something similar, but need updates more often though.

            locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER // I could probably do with DISTANCE_FILTER_PROVIDER instead
            desiredAccuracy: BackgroundGeolocation.MEDIUM_ACCURACY, // controlled by an app option
            stationaryRadius: 25,
            distanceFilter: 20,
            notificationTitle: 'Tracking position in the background',
            notificationText: 'enabled',
            debug: false, // placeholder when debugging (controlled by an app option)
            interval: 10000,
            fastestInterval: 5000,
            activitiesInterval: 5000,
            stopOnTerminate: false, // true would probably suffice
            startOnBoot: false, // not interesting to me
            startForeground: true, // not sure why this is needed
            pauseLocationUpdates: false, // I need location events in the background too; isn't that the whole point with this plugin?
            stopOnStillActivity: true, // hopefully it turns on again safely when moving
            saveBatteryOnBackground: false // probably not needed as I use coarse location, but will try that as well
