### ISSUE TITLE
Plugin crashes app on iOS

### ISSUE THREAD

**Issue by pavelety** [mauron85/cordova-plugin-background-geolocation#425]
## Your Environment

* Plugin version: 3.0.0-alpha.27
* Platform: iOS
* OS version: 11.3.1, 10.2.1
* Device manufacturer and model: Apple iPhone 5, iPhone 6s+
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): ios 4.5.4
* Plugin configuration options: 
```json
{
      "desiredAccuracy": 0,
      "stationaryRadius": 0,
      "distanceFilter": 0,
      "interval": 0,
      "saveBatteryOnBackground": false,
      "debug": false,
      "stopOnTerminate": true,
      "fastestInterval": 0,
      "activitiesInterval": 0,
      "activityType": "Fitness",
      "locationProvider": 0
}
```

## Context
Plugin starts on app ready

## Expected Behavior
On version 3.0.0-alpha.14 it works fine

## Actual Behavior
App crashes on start plugin

## Steps to Reproduce
install 3.0.0-alpha.27
start plugin on real ios device

## Context
App and plugin is not working completely

## Debug logs
WARNING: Requested sleep of 82 milliseconds, but SQLite returned 1000. Maybe SQLite wasn't built with HAVE_USLEEP=1?
Unknown error calling sqlite3_step (19: UNIQUE constraint failed: __META.id) eu
DB Query: INSERT INTO __META (id,db_version,created,last_updated) VALUES (1,0,datetime(),null)
Unknown error finalizing or resetting statement (19: UNIQUE constraint failed: __META.id)
DB Query: INSERT INTO __META (id,db_version,created,last_updated) VALUES (1,0,datetime(),null)
INSERT INTO __META (id,db_version,created,last_updated) VALUES (1,0,datetime(),null) failed code: 19: message: UNIQUE constraint failed: __META.id
Current db version: 3

**Comment by mauron85** [comment]
From you log I see strange behaviour. Plugin is trying to init its internal version table (INSERT INTO __META), but it's already initialised as version 3 (Current db version: 3). This is strange, however it's not root cause of crash as those are just warnings. Can you locate actual crash log?
