### ISSUE TITLE
Start up on boot

### ISSUE THREAD

**Issue by fcamisa** [mauron85/cordova-plugin-background-geolocation#43]
In order for an app like this can be really complete, it should consider entering the geolocation service to the start up of the device in the background, without having to manually start the app.

It would be difficult to do this, remaining within cordova, ie without writing native code?

Thank you

**Comment by mauron85** [comment]
Starting service on boot is possible for Android. Checkout next branch. It will be publicly available in version 2.0

**Comment by gauravarora** [comment]
@mauron85 I came here looking for this exact feature. Thanks for this.

Do you have a planned date for v2.0?

**Comment by mauron85** [comment]
Sorry, I cannot give you any estimates.

**Comment by KinjiQaudra** [comment]
And for ios have you an idea for make the same stuff than Android ?

**Comment by mauron85** [comment]
Didn't have time to investigate for iOS it yet. PRs welcome :-)

**Comment by KinjiQaudra** [comment]
Ok thanks

**Comment by shyamal890** [comment]
+1

**Comment by mauron85** [comment]
Implemented for Android in version 2.0.0
