### ISSUE TITLE
Does getCurrentLocation utilize navigator.geolocation.getcurrentlocation ?

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#430]
## Your Environment
* Plugin version: 3.0.0aplha.30
* Platform: Android

## Context
Does `getCurrentLocation` utilize `navigator.geolocation.getcurrentlocation` underneath or does the plugin utilize the same location stream when the app service is in background?

I am asking because `navigator.geolocation.getcurrentlocation` doesnot always work as expected. There are a lot of complaints from `Ionic` as well as `ReactNative` community and that is the reason why https://github.com/Agontuk/react-native-geolocation-service plugin was created. My hope is that implementation here is very similar to this plugin.

**Comment by mauron85** [comment]
It's not using `navigator.geolocation.getcurrentlocation`, but rather own implementation.
