### ISSUE TITLE
getCurrentLocation not fired on iOS device

### ISSUE THREAD

**Issue by bastiendonjon** [mauron85/cordova-plugin-background-geolocation#432]
## Your Environment
* Plugin version: 3.0.0-alpha.35
* Platform: iOS
* OS version: iOS 11.3.1
* Device manufacturer and model: iPHone 6
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): ios ~4.5.4
* Plugin configuration options: 
* Link to your project:

## Expected Behavior
Get current location

## Actual Behavior
On click event any callback fired (success or error). However, on Android, it's work.

## Steps to Reproduce
1. call getCurrentLocation with callback or not.

**Comment by mauron85** [comment]
Did you used any options? If not it may wait indefinitely for location.
Try using (more info in docs):

```
getCurrentLocation(success, error, {maxWaitTime: 10000});
```

**Comment by bastiendonjon** [comment]
Yes i use this options 

`
{
    maximumAge: 10000,
    timeout: 10000
}
`

**Comment by mauron85** [comment]
I cannot reproduce. Tested both on iPhone 6s and Simulator. Not sure what is your problem. Maybe you can try to debug method getCurrentLocation in `MAURBackgroundGeolocationFacade.m`.

**Comment by bastiendonjon** [comment]
Don't worry, phongap build used old apha version.
I fixed version and it fixed the problem !
Thanks.
