### ISSUE TITLE
Plugin stops as application goes to background or on killing the app

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [mauron85/cordova-plugin-background-geolocation#434]
* Plugin version:3.0.0-alpha.35
* Platform: Android
* OS version:8.1
* Device manufacturer and model:nokia 6 oreo 8.1
* Cordova platform version (`cordova platform ls`):7.1.0
* Plugin configuration options:   
     const config: BackgroundGeolocationConfig = {
      desiredAccuracy: 10,
      stationaryRadius: 10,
      distanceFilter:10,
      debug: false, //  enable this hear sounds for background-geolocation life-cycle.
      stopOnTerminate: false, // enable this to clear background location settings when the app terminates
      notificationTitle: "DCI App",
      notificationText: "Route Tracking..", 
      pauseLocationUpdates: false,
      activitiesInterval: 2000,
      stopOnStillActivity: false,
      saveBatteryOnBackground: false,
      //startOnBoot: true,
      locationProvider: this.backgroundGeolocation.LocationProvider.ANDROID_ACTIVITY_PROVIDER,
      interval: 2000,
      fastestInterval: 1000,
      url:  'url',
      syncUrl:'url',
      syncThreshold: 100
    };

## Context
 I create build with SDK 27 and cordova android 7.1.0 then plugin does not work as expected  

## Expected Behavior
 It should still work as it works with v 2.3.5  

## Actual Behavior
  Plugin stopped sending location to server as application goes to background. And the gps icon disappear from the top bar of device 

 
## Steps to Reproduce 
1.Start the app and call start method
2.Go to background or put the application in background by pressing center button of device
3.Or kill the application by swiping after calling the start method

**Comment by mauron85** [comment]
```
locationProvider: this.backgroundGeolocation.LocationProvider.ANDROID_ACTIVITY_PROVIDER,
```

There is no such provider in v3. Use:
```
{
  locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER
}
```

**Comment by mauron85** [comment]
Cannot replicate your issue. Can you try to replicate your issue with example app https://github.com/mauron85/cordova-plugin-background-geolocation-example. It was just upgraded to cordova-android 7.1.0.
