### ISSUE TITLE
BackgroundGeolocation Not Defined Even After successful Build

### ISSUE THREAD

**Issue by siddmegadeth** [mauron85/cordova-plugin-background-geolocation#439]
Error Message

ReferenceError: BackgroundGeolocation is not defined
    at onDeviceReady (globalCtrl.js:173)
    at Object.<anonymous> (globalCtrl.js:34)
    at Object.invoke (angular.min.js:44)
    at S.instance (angular.min.js:94)
    at n (angular.min.js:69)
    at g (angular.min.js:61)
    at g (angular.min.js:62)
    at g (angular.min.js:62)
    at angular.min.js:61
    at angular.min.js:22
(anonymous) @ angular.min.js:123

I am using cordova 8.0.0 and has added all the dependeincies to compile this module with my code.
i am using Angular 1.6 with cordova to run. On chrome inspection i get the above error message,

## Your Environment

* Plugin version:
* Platform: Android
* OS version: using Mac 
* Device manufacturer and model: Moto E6
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`):
Installed platforms:
  android 7.0.0
Available platforms: 
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0

* Plugin configuration options: 
* Link to your project:

## Expected Behavior
Should not give error mesage.
## Possible Fix
None
## Steps to Reproduce
Add this to the cordova project and perform build
on chrome inspect get the following error
**
ReferenceError: BackgroundGeolocation is not defined
**

**Comment by Chal131313** [comment]
If you go into the console, you can check if the object is added to the window. Just start typing BackgroundGeolocation and it if it's in the window object then it will give you an autocomplete option. There is a difference between the versions 2 and the 3. in version 2 its "backgroundGeolocation" and in version 3 its BackgroundGeolocation. It could be that you are using version 2 of the plugin, in which case you probably should try "backgroundGeolocation"

**Comment by Tobiasartz** [comment]
FYI It seems "cordova plugin add cordova-plugin-mauron85-background-geolocation" installs v2.

**Comment by siddmegadeth** [comment]
i am still getting the issue for V3. but for V2 it works using camelcases.

**Comment by siddmegadeth** [comment]
```
{
    "name": "reise.com.app",
    "displayName": "reise",
    "version": "1.0.0",
    "description": "A sample Apache Cordova application that responds to the deviceready event.",
    "main": "index.js",
    "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "Apache Cordova Team",
    "license": "Apache-2.0",
    "dependencies": {
        "cordova-android": "^7.0.0",
        "cordova-plugin-mauron85-background-geolocation": "^2.3.5",
        "cordova-plugin-whitelist": "^1.3.3",
        "nedb": "^1.8.0"
    },
    "cordova": {
        "plugins": {
            "cordova-plugin-whitelist": {},
            "cordova-plugin-mauron85-background-geolocation": {
                "GOOGLE_PLAY_SERVICES_VERSION": "11+",
                "ANDROID_SUPPORT_LIBRARY_VERSION": "23+",
                "ICON": "@mipmap/icon",
                "SMALL_ICON": "@mipmap/icon",
                "ACCOUNT_NAME": "@string/app_name",
                "ACCOUNT_LABEL": "@string/app_name",
                "ACCOUNT_TYPE": "$PACKAGE_NAME.account",
                "CONTENT_AUTHORITY": "$PACKAGE_NAME"
            }
        },
        "platforms": [
            "android"
        ]
    }
}

```

**Comment by siddmegadeth** [comment]
how do i install the latest version. i am following your guide only (readme.md)

**Comment by Chal131313** [comment]
```cordova plugin add cordova-plugin-mauron85-background-geolocation``` installs only v2

@mauron85 Maybe you should update the docs for the people that really want to use v3 that they can install them like this (and everything else in the docs already is for v3): 
``` cordova plugin add cordova-plugin-mauron85-background-geolocation@3.0.0@alpha.36```
but first remove the old one:
``` cordova plugin remove cordova-plugin-mauron85-background-geolocation```

**Comment by Tobiasartz** [comment]
For the comment above it is:
```
cordova plugin add cordova-plugin-mauron85-background-geolocation@3.0.0-alpha.36
```

Side note: it seems the following is the latest:
```
cordova plugin add cordova-plugin-mauron85-background-geolocation@3.0.0-alpha.37
```

**Comment by rtholmes** [comment]
I had the same problem but upgrading the cordova android platform to v7.1 solved it for me:

```
cordova platform rm android
cordova platform add android@7.1.0
```

**Comment by apistraining** [comment]
Hi,
I have installed this version:
cordova-plugin-mauron85-background-geolocation 3.0.0-alpha.38 "CDVBackgroundGeolocation"

But still getting same error: 'ReferenceError: BackgroundGeolocation is not defined' in console.
please help.
