### ISSUE TITLE
using another cordova plugin(cordova local notification) on success callback is it possible? 

### ISSUE THREAD

**Issue by uzumakinaruto123** [mauron85/cordova-plugin-background-geolocation#44]
@mauron85  Thanks for the great plugin ! appreciate your hardwork !

i am using this plugin without any major issues ! Currently i am `scheduling local notifications on success callback` which works very well !

However , what i noticed is even if this plugin can run in background i **cant  schedule notification if the app was closed during success callback !**

`so is there a way to schedule that local notification ?`

Also i am aware about the issue about background service terminating and restarting later ! 

when the service terminates i checked currently running processes in settings (`settings-->apps-->myapp`) ,

here it seems that service is not totally terminated , the status shows of the process is always **"restarting.."** ! it gets stuck while restarting !

This post is more of a question , and am sorry for that ! help is appreciated !

**Comment by mauron85** [comment]
I personally don't have any experience with local notifications. Is your platform Android?
If so, please send me output of ```adb logcat```, and try to locate lines when service is restarting.

**Comment by uzumakinaruto123** [comment]
@mauron85 
here is the log when i kill the app...




`On line 273 (logcat) The app is killed by swiping`

**After that immediately on line 274  :**

`03-01 22:48:47.174 W/ActivityManager(  527): Scheduling restart of crashed service com.crosswalk.testgeo/com.tenforwardconsulting.cordova.bgloc.FusedLocationService in 352962ms`

it seems on app kill `com.tenforwardconsulting.cordova.bgloc.FusedLocationService` crashes and it tries scheduling it in `352962ms` ! after which it starts working again i guess..

I dont know how much this helped , but i will try getting more detailed log !


[geoadb.txt](https://github.com/mauron85/cordova-plugin-background-geolocation/files/153269/geoadb.txt)

**Comment by mauron85** [comment]
Nothing unusual here.That's how it suppose to work. So what exactly do you mean by: "i cant schedule notification if the app was closed during success callback !"

**Comment by uzumakinaruto123** [comment]
i meant that on every success callback i can make http calls ! but i cant use cordova plugin to schedule new notification ! because cordova plugins needs device to be ready for which app is suppose to run !

so i was asking whether is it possible to use any other cordova plugin in success callback when app not running !

 ############################## 

About the restart part , it created a confusion :p 
i was not relating that restart part to the notifications ! i was just wondering what happens on app kill and why service needs to be killed and restarted !

**Comment by mauron85** [comment]
Ah OK, np. I can only answer second part.

The restarts is due android bug, I've tried many other approaches to avoid service kill and restart, none work. Read my [my answer](http://stackoverflow.com/a/35107931/3896616) on stackoverflow regarding this.

**Comment by uzumakinaruto123** [comment]
Thanks for the response ! :)  will keep a watch on the issue and hope it will work well on kitkat above versions as stated in some posts ! its ok to close the issue if this is how its suppose to work :+1:

**Comment by mauron85** [comment]
> cant schedule notification if the app was closed during success callback !
if app was terminated (and you use stopOnTerminate: false), you code will not get executed anymore on android.
