### ISSUE TITLE
location interval does not work properly 

### ISSUE THREAD

**Issue by aaronharper123** [mauron85/cordova-plugin-background-geolocation#441]
I give 300000 millisecond location interval to the background geolocation plugin but plugin updates at 2-3 seconds continuously. 
My code is below....

 let config = {
         desiredAccuracy: 10,
         stationaryRadius: 30,
         distanceFilter: 50,
         notificationTitle: 'App is running',
         notificationText: 'ENABLED',
         foregroundService: true,
         debug: false,
         interval: 300000,
         url: 'http://......',
         httpHeaders: {
          "Content-Type": "application/json"
        },
        postTemplate: {
            "UserId": this.UserId, 
            "LocationData": [
            {
              "Lat": this.lat,
              "Long": this.lng,
              "Date": this.cuuDate,
              "BatteryPerc": this.batteryLevel
            }
            ]
        },
         method: 'POST',
         autoSync: true,
         stopOnTerminate: false,
         startOnBoot: true
     };

## Your Environment

* Plugin version: 2.3.5
* Platform: Android
* OS version: 7.1
* Device manufacturer and model: Moto g4
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 7.0.0
* Plugin configuration options:  
 let config = {
         desiredAccuracy: 10,
         stationaryRadius: 30,
         distanceFilter: 50,
         notificationTitle: 'App is running',
         notificationText: 'ENABLED',
         foregroundService: true,
         debug: false,
         interval: 300000,
         url: 'http://......',
         httpHeaders: {
          "Content-Type": "application/json"
        },
        postTemplate: {
            "UserId": this.UserId, 
            "LocationData": [
            {
              "Lat": this.lat,
              "Long": this.lng,
              "Date": this.cuuDate,
              "BatteryPerc": this.batteryLevel
            }
            ]
        },
         method: 'POST',
         autoSync: true,
         stopOnTerminate: false,
         startOnBoot: true
     };

* Link to your project: 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
Try fastestInterval

**Comment by aaronharper123** [comment]
should i try fastestInterval instead of interval ?

**Comment by guzmange** [comment]
mauron85 where can i contact you ? i need informatio regarding your plugin. thanks

**Comment by aaronharper123** [comment]
please give me answer

**Comment by aaronharper123** [comment]
i try fastesInterval but although get same problem.
Some times no any location updates till15-20 mins

**Comment by mauron85** [comment]
> plugin but plugin updates at 2-3 seconds continuously.

> but although get same problem. Some times no any location updates till15-20 mins

You're using default DISTANCE_FILTER_PROVIDER. If you need exact timing use RAW or ACTIVITY_PROVIDER.
https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/PROVIDERS.md

**Comment by aaronharper123** [comment]
when i gave time 300000 milliseconds with ACTIVITY_PROVIDER but location does not updates till 15-20 mins....

let config = {
         desiredAccuracy: 10,
         stationaryRadius: 30,
         distanceFilter: 50,
         notificationTitle: 'App is running',
         notificationText: 'ENABLED',
         foregroundService: true,
         debug: false,
         locationProvider:1,
         fastestInterval: 300000,
         url: 'http://.......',
         httpHeaders: {
          "Content-Type": "application/json"
        },
        postTemplate: {
            "UserId": this.UserId,    //  <-- Android ONLY:  HTTP POST params sent to your server when persisting locations.
            "LocationData": [
            {
              "Lat": this.lat,
              "Long": this.lng,
              "Date": this.cuuDate,
              "BatteryPerc": this.batteryLevel
            }
            ]
        },
         method: 'POST',
         autoSync: true,
         stopOnTerminate: false,
         startOnBoot: true
     };

**Comment by aaronharper123** [comment]
i try two cases,
1. when device is not moving , i.e. device is stay at one side => location is arrived 2-3 times at 2-3 mins but after then till 15-20 mins no one location is updates.
2. when device is moving => some time location is updates at2-3 min and some time is update at 15 -20 mins

**Comment by aaronharper123** [comment]
i want to update location and push data to server at 5 mins continuously even device is moving or not
So please give me config object or edit my config object

**Comment by aaronharper123** [comment]
please look my location updated time which are pushed to the server.
at this time i set fastestInterval = 30000 for testing ,
i test my app from 2018-06-04 : 23:55 to 2018-06-04 : 00:17 around 22 mins but i got location updates only 5 times which are below

2018-06-04 23:55:01.000
2018-06-04 23:56:43.000
2018-06-04 23:56:49.000
2018-06-05 00:06:58.000
2018-06-05 00:17:19.000

**Comment by mauron85** [comment]
You need to use both interval and fastestInterval

**Comment by aaronharper123** [comment]
If device is not moving then is it possible to get location updates at every accurate interval's seconds.

**Comment by aaronharper123** [comment]
> You need to use both interval and fastestInterval

i use both but i get one problem,
i gave time 30000 seconds and device is not moving but first 1-2 times location updates are arrived at 1-2 mins but after then till 20 min no any location updates are arrived.

**Comment by aaronharper123** [comment]
how can i fix sir

**Comment by aaronharper123** [comment]
My framework is Ionic and my plugin version is:

<plugin name="cordova-plugin-mauron85-background-geolocation" spec="^2.3.5">
        <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="11+" />
        <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="23+" />
        <variable name="ICON" value="@mipmap/icon" />
        <variable name="SMALL_ICON" value="@mipmap/icon" />
        <variable name="ACCOUNT_NAME" value="@string/app_name" />
        <variable name="ACCOUNT_LABEL" value="@string/app_name" />
        <variable name="ACCOUNT_TYPE" value="$PACKAGE_NAME.account" />
        <variable name="CONTENT_AUTHORITY" value="$PACKAGE_NAME" />
    </plugin>

**Comment by AnupNair91** [comment]
I have the same issue. where you able to fix this?

**Comment by aaronharper123** [comment]
Not fixed yet, i tried many times to contact with @mauron85  but he did not give response yet.
