### ISSUE TITLE
getCurrentLocation is caching locations

### ISSUE THREAD

**Issue by alterplataforma** [mauron85/cordova-plugin-background-geolocation#443]
## Your Environment
Plugin version: 3.0.0-alpha.7
Platform: Android
OS version: 6.0
Device manufacturer and model: Various models.
Cordova version (cordova -v): 8.0.0
Cordova platform version (cordova platform ls): 6.3.0

## Context
When i use the getCurrentLocation function in one point everythings going fine, but when i moved to another place in the city (like 12km ≈ 9 miles) still sending the same first location.

## Expected Behavior
Change the location when the user moves and ask for location.
## Possible Fix
Maybe is caching locations.

**Comment by mauron85** [comment]
Did used max age option?

**Comment by alterplataforma** [comment]
Oh i forgot the options. Let me try with max age and i told you to close this issue. Thank you!

**Comment by alterplataforma** [comment]
Yep the problem was the max age option. You can close this issue.
