### ISSUE TITLE
why getValidLocations() method gives duplicate data ?

### ISSUE THREAD

**Issue by aaronharper123** [mauron85/cordova-plugin-background-geolocation#445]
I am using getValidLocations() method for retrieved stored location and push to server.
after pushed i used deleteAllLocations() method for delete stored locations.

But many times  getValidLocations() method gives me duplicate data , i think its due to plugin updates location two times at same time. 

## Your Environment

* Plugin version: 2.3.5
* Platform: iOS
* OS version: 10.2.1
* Device manufacturer and model: iPhone 5s
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): 4.5.4
* Plugin configuration options: 
`let config = {
desiredAccuracy: 0,
stationaryRadius: 50,
distanceFilter: 200,
notificationTitle: 'XYZ',
notificationText: 'ENABLED',
foregroundService: true,
debug: true,
locationProvider: 1,
interval: 120000,
fastestInterval: 120000,
url: 'http://....',
httpHeaders: {
"Content-Type": "application/json"
},
postTemplate: {
"UserId": this.UserId,
"LocationData": [
{
"Lat": this.lat,
"Long": this.lng,
"Date": this.cuuDate,
"BatteryPerc": this.batteryLevel
}
]
},
method: 'POST',
autoSync: true,
saveBatteryOnBackground: false,
stopOnTerminate: false,
startOnBoot: true
};`

* Link to your project:

## Context

getValidLocations() method gives duplicate entry. 

## Expected Behavior
i think , its due to plugin updates two or three times at same time 

## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

My Code is Below......
` startBackgroundLocation() {

          this.UserId = 4

        let config = {
desiredAccuracy: 0,
stationaryRadius: 50,
distanceFilter: 200,
notificationTitle: 'XYZ',
notificationText: 'ENABLED',
foregroundService: true,
debug: true,
locationProvider: 1,
interval: 120000,
fastestInterval: 120000,
url: 'http://....',
httpHeaders: {
"Content-Type": "application/json"
},
postTemplate: {
"UserId": this.UserId,
"LocationData": [
{
"Lat": this.lat,
"Long": this.lng,
"Date": this.cuuDate,
"BatteryPerc": this.batteryLevel
}
]
},
method: 'POST',
autoSync: true,
saveBatteryOnBackground: false,
stopOnTerminate: false,
startOnBoot: true
};
       this.backgroundGeolocation.configure(config).subscribe((location) => {

               console.log('configuration: '+JSON.stringify(location));

               console.log('Lat: '+location.latitude + ' :: '+location.longitude );

               this.lat = location.latitude;
               this.lng = location.longitude;

               this.cuuDate = new Date();
               this.cuuDate = moment(this.cuuDate).format('YYYY-MM-DDTHH:mm:ss');
               console.log('current date and time : '+this.cuuDate);
               const subscription = this.batteryStatus.onChange().subscribe(status => {
                   console.log(status.level, status.isPlugged);
                   this.batteryLevel = status.level;
               });

               if( this.httpService.isOnline() ) {
                   this.arrLocations = [];
                   // this.arrLocations = this.dbHandlerProvider.get_location();
                   this.backgroundGeolocation.getValidLocations().then(res=> {
                        // this.arrLocations = res;
                        console.log('Background getValidLocations: '+JSON.stringify(res));
                        for(let i=0; i<res.length; i++) {
                            var millisec = new Date(res[i].time);
                            var milliInDate = moment(millisec).format('YYYY-MM-DDTHH:mm:ss');
                            if(this.arrLocations.indexOf(res[i].latitude) != -1 && this.arrLocations.indexOf(res[i].longitude) != -1 && this.arrLocations.indexOf(res[i].milliInDate) != -1 ) {
                            } else {
                                this.arrLocations.push({
                                    Lat: res[i].latitude,
                                    Long: res[i].longitude,
                                    Date: milliInDate,
                                    BatteryPerc: this.batteryLevel
                                });
                            }
                        }
                        setTimeout(()=> {
                            console.log('Back Location Data: '+JSON.stringify(this.arrLocations));
                            this.serverPush.pushPosition({
                                UserId: this.UserId,
                                LocationData: this.arrLocations
                            });
                        },2000);
                   });
           } else {
               // this.dbHandlerProvider.add_location(this.lat,this.lng,this.cuuDate,11);
           }
           this.backgroundGeolocation.finish();

       }, (err) => {
         console.log(err);
       });

       this.backgroundGeolocation.start();

 }`

**Comment by aaronharper123** [comment]
@mauron85 
And also plugin not woek after app is killed in ios...
please see my code above if i am doing any wrong .

**Comment by mauron85** [comment]
>And also plugin not woek after app is killed in ios...

documentation is wrong here. `stopOnTerminate` is currently Android only. But I'm working on iOS implementation.

**Comment by aaronharper123** [comment]
> documentation is wrong here. stopOnTerminate is currently Android only. But I'm working on iOS implementation.

now what i do to enable your plugin in background also.

**Comment by aaronharper123** [comment]
> I am using getValidLocations() method for retrieved stored location and push to server.
after pushed i used deleteAllLocations() method for delete stored locations. But many times getValidLocations() method gives me duplicate data , i think its due to plugin updates location two times at same time.

Please give me answer for my above question also

**Comment by mauron85** [comment]
>now what i do to enable your plugin in background also.
it's working in background. Terminated app is separate topic.

>getValidLocations() method gives me duplicate data
do you have any sample to show?

**Comment by aaronharper123** [comment]
`do you have any sample to show?`

![log](https://user-images.githubusercontent.com/39259380/41092177-eff4d4be-6a65-11e8-9311-aed428dfdd8c.jpg)

please see above snap, there are three duplicate entries with time
2018-06-07 11:41:48.000
2018-06-07 11:42:17.000
2018-06-07 11:42:18.000

2018-06-07 11:41:48.000
2018-06-07 11:42:17.000
2018-06-07 11:42:18.000

2018-06-07 11:41:48.000
2018-06-07 11:42:17.000
2018-06-07 11:42:18.000

i set interval 120000 seconds with distanceFilter 200 m but it catch location like above

**Comment by aaronharper123** [comment]
> it's working in background. Terminated app is separate topic.

i means terminated instead of background..
if i want to enable plugin after app is terminated then what i do sir..
please guide me.

**Comment by mauron85** [comment]
>if i want to enable plugin after app is terminated then what i do sir..

on iOS user currently need to start app manually.

**Comment by aaronharper123** [comment]
> on iOS user currently need to start app manually.

I want to track user even he is terminate the app with your plugin,
so is this possible?

**Comment by aaronharper123** [comment]
> please see above snap, there are three duplicate entries with time

??

**Comment by aaronharper123** [comment]
@mauron85 
**Hello sir, please update me , i have to complete work within tomorrow.
My both questions are above , please look..**

**Comment by aaronharper123** [comment]
How can I push url with my params like latitude, longitude, battery status and date to server?.
Please explain me, I saw your docs but I cannot understand this. 

my code is below in which I put static params and it pushed successfully but how can i send current location with my params..

`url: "http://property.zoomi.in:86/api/User/UserTracking",
        headers: {  // <-- Optional HTTP headers
            "Content-Type": "application/json"
        },
        params: {   // <-- Optional HTTP params
          "UserId": 4,
          "LocationData": [
          {
            "Lat": 'aa',
            "Long": 'bb',
            "Date": '2018-06-08T11:53',
            "BatteryPerc": 22
          }
          ]
        },`

**Comment by aaronharper123** [comment]
i am getting duplicate entries 3-4 imesin this mehtod  `this.backgroundGeolocation.getValidLocations()` 

please update me.

**Comment by mauron85** [comment]
What is `SubmitDate` ?

**Comment by mauron85** [comment]
I only see repeating SubmitDate, but with different latitude and longitude. Where is this `SubmitDate` coming from?

**Comment by aaronharper123** [comment]
i am getting all stored location in the time of interval and delete records after pushed to server.
but all time , i get duplicate entries 3-4 times.

please check my logs below

[{"provider":"fused","time":1528714195154,"latitude":23.0401284,"longitude":72.5188049,"accuracy":30.132999420166016,"locationProvider":1,"locationId":4}]

[{"provider":"fused","time":1528714195154,"latitude":23.0401284,"longitude":72.5188049,"accuracy":30.132999420166016,"locationProvider":1,"locationId":4}]

[{"provider":"fused","time":1528714195154,"latitude":23.0401284,"longitude":72.5188049,"accuracy":30.132999420166016,"locationProvider":1,"locationId":4}]

**Comment by aaronharper123** [comment]
please see my logs above, i get duplicare data yet with also same locationId

**Comment by aaronharper123** [comment]
hello I am not getting any response of my question yet

**Comment by aaronharper123** [comment]
any update?

**Comment by aaronharper123** [comment]
please check my logs above and try to resolve.
