### ISSUE TITLE
Plugin doesn't work on iOS

### ISSUE THREAD

**Issue by KolyaTsypa** [mauron85/cordova-plugin-background-geolocation#447]
I don't know why, but plugin doesn't work on iOS, in background mode. 
    let config = {
      desiredAccuracy: **10,**
      stationaryRadius: 30,
      distanceFilter: 30,
      debug: false,
      interval: 10000,
      stopOnTerminate: false,
      startOnBoot: true,
      notificationTitle: 'Collecting memories ',
      notificationText: 'Enabled',
    };

I used version 2.3.5 before, and it worked good. But I had to update plugin to newest version, because app was rejected on App Store review (problem with prefs-root).

And in XCode I got error: 

"WARN: Native: tried calling BackgroundGeolocation.configure, but the BackgroundGeolocation plugin is not installed.
2018-06-11 23:35:02.296286+0300 Wowanders[24753:370195] WARN: Install the BackgroundGeolocation plugin: 'ionic cordova plugin add cordova-plugin-mauron85-background-geolocation'
2018-06-11 23:35:02.296393+0300 Wowanders[24753:370195] WARN: Native: tried calling BackgroundGeolocation.start, but the BackgroundGeolocation plugin is not installed.
2018-06-11 23:35:02.296477+0300 Wowanders[24753:370195] WARN: Install the BackgroundGeolocation plugin: 'ionic cordova plugin add cordova-plugin-mauron85-background-geolocation'"

But, plugin installed
      "cordova-plugin-mauron85-background-geolocation": {
        "GOOGLE_PLAY_SERVICES_VERSION": "11+",
        "ANDROID_SUPPORT_LIBRARY_VERSION": "26+",
        "ICON": "@mipmap/icon",
        "SMALL_ICON": "@mipmap/icon",
        "ACCOUNT_NAME": "@string/app_name",
        "ACCOUNT_LABEL": "@string/app_name",
        "ACCOUNT_TYPE": "$PACKAGE_NAME.account",
        "CONTENT_AUTHORITY": "$PACKAGE_NAME",
        "ALWAYS_USAGE_DESCRIPTION": "This app always requires location tracking",
        "MOTION_USAGE_DESCRIPTION": "This app requires motion detection"
      }

Can anyone help?

**Comment by ghal** [comment]
I have the same issue. The app got rejected and the new version seems to not work on iOS...

**Comment by mauron85** [comment]
this is not plugin issue. just ionic is still on 2.x branch. you can't use 3.x with ionic.

**Comment by mauron85** [comment]
will close this. there is already one issue regarding ionic. please write your comments there instead.
