### ISSUE TITLE
Getting location when app is in background, just once and fast

### ISSUE THREAD

**Issue by uriva** [mauron85/cordova-plugin-background-geolocation#45]
My use case is slightly different than most, I need to get the location when the app is in background, but just once, and as fast as possible.

Doing this with these parameters takes the better part of a minute: `{desiredAccuracy: 500, stationaryRadius: 0, distanceFilter: 0, interval: 0, stopOnTerminate: true}`

when the callback is called, I stop the background service.

I can't use the regular navigator.geolocation or the other plugins because the request expires, apparently you can't get the location even once when the app is not in foreground.

This plugin works but is a bit slow.

Any ideas?

**Comment by mauron85** [comment]
>I can't use the regular navigator.geolocation or the other plugins because the request expires, apparently you can't get the location even once when the app is not in foreground.

I believe you can on Android. However not on iOS. You can try to use higher desiredAccuracy, so slow GPS will not be used.

**Comment by uriva** [comment]
Tried that too to no avail.
This doesn't work on android as well.
If I resume to the app, however, the request returns immediately.

**Comment by mauron85** [comment]
Zero accuracy is the lowest and the most accurate that almost guarantees GPS will be used. In your case try desiredAccuracy: 1000

**Comment by uriva** [comment]
21 seconds. Some improvement but not ideal yet. Thanks

**Comment by mauron85** [comment]
Should be much improved with ANDROID_FUSION_PROVIDER in version 0.9.6. Please give try.

**Comment by mauron85** [comment]
please feel free to reopen when necessary, but time to first position was improved in recent versions
