### ISSUE TITLE
BackgroundGeolocation is not defined

### ISSUE THREAD

**Issue by YeisonVelez11** [mauron85/cordova-plugin-background-geolocation#451]
* Plugin version: last
* Platform: Android
* OS version: 6.0.0
* Device manufacturer and model: Samsung Galaxy s7
* Cordova version (`cordova -v`): 8.0.0

cordova-android-play-services-gradle-release 1.4.2 "cordova-android-play-services-gradle-release"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-facebook4 2.1.0 "Facebook Connect"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.2 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-mauron85-background-geolocation 2.3.5 "CDVBackgroundGeolocation"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.8 "Diagnostic"

I am trying to use this plugin for IONIC1 and use the code provided in the "README" of this page. when I compile and tested on my galaxy s7, I am getting this error:

![captura](https://user-images.githubusercontent.com/1949889/41830213-2e37308a-7805-11e8-85b6-7a3c85abc244.PNG)

I am using this code:

app.controller('loginController', function($scope,$timeout) {
    function onDeviceReady() {
      BackgroundGeolocation.configure({
        locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
        desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
        stationaryRadius: 50,
        distanceFilter: 50,
        notificationTitle: 'Background tracking',
        notificationText: 'enabled',
        debug: true,
        interval: 10000,
        fastestInterval: 5000,
        activitiesInterval: 10000,
        url: 'http://192.168.81.15:3000/location',
        httpHeaders: {
          'X-FOO': 'bar'
        },
        // customize post properties
        postTemplate: {
          lat: '@latitude',
          lon: '@longitude',
          foo: 'bar' // you can also add your own properties
        }
      });

      BackgroundGeolocation.on('location', function(location) {
        // handle your locations here
        // to perform long running operation on iOS
        // you need to create background task
        BackgroundGeolocation.startTask(function(taskKey) {
          // execute long running task
          // eg. ajax post location
          // IMPORTANT: task has to be ended by endTask
          BackgroundGeolocation.endTask(taskKey);
        });
      });

      BackgroundGeolocation.on('stationary', function(stationaryLocation) {
        // handle stationary locations here
      });

      BackgroundGeolocation.on('error', function(error) {
        console.log('[ERROR] BackgroundGeolocation error:', error.code, error.message);
      });

      BackgroundGeolocation.on('start', function() {
        console.log('[INFO] BackgroundGeolocation service has been started');
      });

      BackgroundGeolocation.on('stop', function() {
        console.log('[INFO] BackgroundGeolocation service has been stopped');
      });

      BackgroundGeolocation.on('authorization', function(status) {
        console.log('[INFO] BackgroundGeolocation authorization status: ' + status);
        if (status !== BackgroundGeolocation.AUTHORIZED) {
          // we need to set delay or otherwise alert may not be shown
          setTimeout(function() {
            var showSettings = confirm('App requires location tracking permission. Would you like to open app settings?');
            if (showSetting) {
              return BackgroundGeolocation.showAppSettings();
            }
          }, 1000);
        }
      });

      BackgroundGeolocation.on('background', function() {
        console.log('[INFO] App is in background');
        // you can also reconfigure service (changes will be applied immediately)
        BackgroundGeolocation.configure({ debug: true });
      });

      BackgroundGeolocation.on('foreground', function() {
        console.log('[INFO] App is in foreground');
        BackgroundGeolocation.configure({ debug: false });
      });

      BackgroundGeolocation.checkStatus(function(status) {
        console.log('[INFO] BackgroundGeolocation service is running', status.isRunning);
        console.log('[INFO] BackgroundGeolocation services enabled', status.locationServicesEnabled);
        console.log('[INFO] BackgroundGeolocation auth status: ' + status.authorization);

        // you don't need to check status before start (this is just the example)
        if (!status.isRunning) {
          BackgroundGeolocation.start(); //triggers start on start event
        }
      });

      // you can also just start without checking for status
      // BackgroundGeolocation.start();

      // Don't forget to remove listeners at some point!
      // BackgroundGeolocation.events.forEach(function(event) {
      //   return BackgroundGeolocation.removeAllListeners(event);
      // });
    }

    document.addEventListener('deviceready', onDeviceReady, false);

    });

What am I missing or what am I doing wrong?
thanks

**Comment by willmero** [comment]
I believe this is because the plugin is actually listed with a lower-case "b" - backgroundGeolocation
Though, when I change all instances of "BackgroundGeolocation" to "backgroundGeolocation" in the example script, I get some XCode errors on `if (isNotNull(config[@"stationaryRadius"])) {` 

Hmm...

**Comment by YeisonVelez11** [comment]
@willmero @mauron85  Do you know how to remove this notification and the message that appears to me?

![indice](https://user-images.githubusercontent.com/1949889/41916397-92fc5036-791d-11e8-9b6d-f92dfe21fdde.jpg)
![indice2](https://user-images.githubusercontent.com/1949889/41916401-93cbd716-791d-11e8-8614-ec26be180499.jpg)

**Comment by rafwell** [comment]
Try https://github.com/mauron85/cordova-plugin-background-geolocation/issues/449

**Comment by willmero** [comment]
Any update here on the initial issue with BackgroundGeoLocation not being defined? This seems like a serious bug.

**Comment by xodock** [comment]
Have BackgroundGeolocation is undefined too. Any workaround?

**Comment by mauron85** [comment]
You're reading documentation for plugin version 3. But installed plugin version 2. There is big notice at the very top of README.md.

>Documentation has been updated to v3. Documentation for version 2.x can be found here.

**Comment by mauron85** [comment]
Also please don't use `Plugin version: last` as this can mean one version and another week later.

**Comment by HarelM** [comment]
@mauron85 When installing this plug-in using cordova-cli it installs v2.3.5, I'm curious as to why you decided to change the documentation without changing the stable version? 
I just had the same issue as described above...

**Comment by mauron85** [comment]
There is literally big disclaimer:

![image](https://user-images.githubusercontent.com/359450/44430721-d6f9a900-a59b-11e8-9a8d-a379b5ed24eb.png)

**Comment by HarelM** [comment]
I know, and I saw it, But intuitively I thought that this is intended for people using an old version and not the latest stable, i.e. I got to this repository and read this and said to myself: "hmm, this is interesting, but I'm using latest stable so this is probably not intended for me", and continued to using it and then failing and then finding this issue...

**Comment by rafwell** [comment]
In my opinion the 3.x branch is so more stable than that. And, really, is very confused and hard to install the latest 3.x branch, or I have did it on wrong way.

**Comment by mauron85** [comment]
Sorry for the confusion. Maybe it's time to make 3.x stable.

**Comment by StevenMapes** [comment]
@mauron85 I actually get this error on version 2.3.6 whilst using the example from the [v2 guide](https://github.com/mauron85/cordova-plugin-background-geolocation/tree/2.x)

`<plugin name="cordova-plugin-mauron85-background-geolocation" spec="^2.3.6">`
The error is:
` ReferenceError: backgroundGeolocation is not defined`

Cordova 8.0.0
Cordova plugins
```
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.9 "Globalization"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-mauron85-background-geolocation 2.3.6 "CDVBackgroundGeolocation"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```
