### ISSUE TITLE
Background status notification doesn't show up on Android 8

### ISSUE THREAD

**Issue by luisfrancajr** [mauron85/cordova-plugin-background-geolocation#452]
## Your Environment
* Plugin version: 2.3.5
* Platform: Android
* OS version: 8.0.0
* Device manufacturer and model: Moto Z (Br)
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): 7.0.0
* Plugin configuration options: 
```
const config: BackgroundGeolocationConfig = {
  desiredAccuracy: 100,
  stationaryRadius: 4,
  distanceFilter: 4,
  debug: true, 
  stopOnTerminate: true, 
  interval: 30000,
  notificationTitle: 'Title',
  notificationText: 'Content',
  notificationIconColor: '#ffcc00',
  pauseLocationUpdates: false
};
```
* Link to your project: Under development (local)

## Context
I’ve got an issue by running the plugin on Android 8. The notification doesn’t show up on the notification bar. There’s a fixed notification telling the user that the app is consuming battery instead.
Even though I set the title, text, icon color, and stuff it doesn’t work. I figured out that on Android 7.1 or bellow it does work fine. I could even change the targetSdkVersion to 25 or bellow so it works on Android 8 but my problem is that Google Play Store will start requiring targetSdkVersion 26 in august.
I need to know if there’s an update to solve this or even a way to remove this notification on Android 8.
Everything else works fine for me.

## Expected Behavior
The "consuming battery" notification should not appear.

## Actual Behavior
Should be a notification to tell the user that the app is running on background

## Possible Fix:
I need to know if there’s an update to solve this or even a way to remove this notification on Android 8.

## Steps to Reproduce
1. Simply run the project on Android 8

## Context
It's showing the wrong notification.

## Debug logs
There's no logs for this

**Comment by RikdeBoer** [comment]
Would this be related to this: https://developer.android.com/about/versions/oreo/background-location-limits

Does this plugin even work properly in background? According to what I've read elsewhere, in Android 8/API 26, location-based code must effectively run in the foreground for frequent position updates.

**Comment by luisfrancajr** [comment]
Yes, the plugin is fully functional in background! It does what it is supposed to do! The problem is that the notification doesn’t show up, there’s only a battery warning notification instead. If I change it to API 25 the notification works properly.

I was looking into the java files in order to try to remove this battery warning notification. I did remove it but as soon as I did it, the plugin stopped working in background. 

After taking a look at the link you sent I started looking for deprecated functions on Android 8 and I’ve found something in the Notification.Builder as you can see in the following link:
https://developer.android.com/reference/android/app/Notification.Builder

I believe it might be the problem. Even tried to reproduce a few examples that I found but my java knowledge is very limited so I didn’t succeed on it.

**Comment by mauron85** [comment]
@luisfrancajr I saw this battery notification too. Usually it's shown when Activity provider is used. Not sure what is the issue. I don't think I'm using any deprecated notification builder api though.

**Comment by luisfrancajr** [comment]
@mauron85 I set the LocationProvider to 0 in order to use ANDROID_DISTANCE_FILTER_PROVIDER but it didn’t work as expected to me. The battery warning notification is still there.
I told you about a deprecated function because of what we can see in the following image:

![capturar](https://user-images.githubusercontent.com/12616762/42511053-36e26c4e-8427-11e8-9000-500689a3d9b0.png)

**Comment by mauron85** [comment]
If you're using 2.3.5 then yes, it's using deprecating API, but if 3.x with then not.

https://github.com/mauron85/background-geolocation-android/blob/515f621e0afc824a351016ec490ec3a9c2411b76/src/oreo/java/com/marianhello/bgloc/NotificationHelper.java#L50

**Comment by luisfrancajr** [comment]
@mauron85 How do I install 3.x version?

**Comment by MaximeLassalleHub** [comment]
You can try this one :
(ionic) cordova plugin add cordova-plugin-mauron85-background-geolocation@3.0.0-alpha.38

**Comment by MaximeLassalleHub** [comment]
I'm sorry I had not time to investigate your ios problem.
I'll have a look when I'm available

**Comment by Salamek** [comment]
I'm having same issue with this exception in log:

```log
08-31 13:49:17.902  6262  6262 E AndroidRuntime: Process: io.cordova.pepetevidi:remote, PID: 6262
08-31 13:49:17.902  6262  6262 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.tenforwardconsulting.cordova.bgloc.DistanceFilterLocationService@1ce02c7 with Intent { flg=0x4 cmp=io.cordova.pepetevidi/com.tenforwardconsulting.cordova.bgloc.DistanceFilterLocationService (has extras) }: java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.
08-31 13:49:17.902  6262  6262 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3556)
08-31 13:49:17.902  6262  6262 E AndroidRuntime:        at android.app.ActivityThread.-wrap20(Unknown Source:0)
08-31 13:49:17.902  6262  6262 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
08-31 13:49:17.902  6262  6262 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)
08-31 13:49:17.902  6262  6262 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
08-31 13:49:17.902  6262  6262 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6541)
08-31 13:49:17.902  6262  6262 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-31 13:49:17.902  6262  6262 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
08-31 13:49:17.902  6262  6262 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
08-31 13:49:17.902  6262  6262 E AndroidRuntime: Caused by: java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.
08-31 13:49:17.902  6262  6262 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1942)
08-31 13:49:17.902  6262  6262 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1888)
08-31 13:49:17.902  6262  6262 E AndroidRuntime:        at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:691)
08-31 13:49:17.902  6262  6262 E AndroidRuntime:        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:887)
08-31 13:49:17.902  6262  6262 E AndroidRuntime:        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:469)
08-31 13:49:17.902  6262  6262 E AndroidRuntime:        at com.tenforwardconsulting.cordova.bgloc.DistanceFilterLocationService.setPace(DistanceFilterLocationService.java:162)
08-31 13:49:17.902  6262  6262 E AndroidRuntime:        at com.tenforwardconsulting.cordova.bgloc.DistanceFilterLocationService.onStartCommand(DistanceFilterLocationService.java:113)
08-31 13:49:17.902  6262  6262 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3539)
08-31 13:49:17.902  6262  6262 E AndroidRuntime:        ... 8 more
```
