### ISSUE TITLE
Your app uses the "prefs:root=" non-public URL scheme, which is a private entity

### ISSUE THREAD

**Issue by rajankapila** [mauron85/cordova-plugin-background-geolocation#454]
## Your Environment
IOS
cordova-plugin-mauron85-background-geolocation 2.3.5 "CDVBackgroundGeolocation"
cordova 8.0.0

## Context
From apple:
Your app uses the "prefs:root=" non-public URL scheme, which is a private entity. The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

Continuing to use or conceal non-public APIs in future submissions of this app may result in the termination of your Apple Developer account, as well as removal of all associated apps from the App Store.

in LocationManager.m:

- (void) showLocationSettings
{
    [[UIApplication sharedApplication] openURL:[NSURL URLWithString:@"prefs:root=LOCATION_SERVICES"]];
}

## Expected Behavior
Should be accepted to iOS store

## Actual Behavior
Reject from iOS store

## Steps to Reproduce

1. submit to ios with plugin installed
2.
3.
4.

## Context
Rejected from iOS store

**Comment by rajankapila** [comment]
Any update on this?

**Comment by jdupuis** [comment]
I encountered the same issue but I hesitate to use the version 3 of the plugin which is in alpha version. Your opinion ? Thanks !

**Comment by matthijsbierman** [comment]
Got the same rejection on a previous version. Upgraded to version 3 and happy so far. I'd give it a try.

**Comment by activemapper-teamwork** [comment]
How did you upgrade to v3?

**Comment by rudiminty** [comment]
I see a commit has been made by @mauron85 in this regard but has it been introduced into a version 2.3.X yet?

**Comment by renderin** [comment]
Any solution to the problem ?, thanks

**Comment by rudiminty** [comment]
No solution other than updating to the alpha version 3.0 unfortunately which meant some major plugins version dependencies that needed to be resolved.

Kind regards

Rudi Minty
072 191 4654
Sent from my iPhone

On 22 Aug 2018, at 12:04, renderin <notifications@github.com<mailto:notifications@github.com>> wrote:


Any solution to the problem ?, thanks

-

**Comment by mauron85** [comment]
@rudiminty it's just one line that need to removed to had it working in 2.x branch too. I will accept PR and publish new 2.x version if somebody is willing to do it.

**Comment by renderin** [comment]
@mauron85 Currently Apple rejects ionic apps with version 2.3.5, and in ionic version 3.0 does not work correctly. I do not know if the solution is to eliminate the following line:

`[[UIApplication sharedApplication] openURL:[NSURL URLWithString:@"prefs:root=LOCATION_SERVICES"]];`

And eliminate in Xcode the url Types.
Thanks

**Comment by renderin** [comment]
@rudiminty Have you installed version 3.0 on ionic? If so, could you explain the steps to follow. Thanks!

**Comment by mauron85** [comment]
>I do not know if the solution is to eliminate the following line: [[UIApplication sharedApplication] openURL:[NSURL URLWithString:@"prefs:root=LOCATION_SERVICES"]];

yes indeed is. Basically revert this commit https://github.com/mauron85/react-native-background-geolocation/pull/158/files

**Comment by shzaur** [comment]
same issue
cordova-plugin-mauron85-background-geolocation@3.0.0-alpha.41

**Comment by lightyaer** [comment]
I encountered the same issue, updating to 3.0.0-alpha41 and using in ionic, there is no equivalent ionic-native/npm package for v3, So I get an error that BackgroundLocation plugin is not found, also alot of things are yet to be implemented in the alpha version.

I'm in dire need of this plugin, anyways, I can't find " prefs:root " anywhere in v2.3.5, is it safe to assume that I can upload to store. Gonna double check it before submitting.

**Comment by lightyaer** [comment]
In v2.3.5, under  " node_modules\cordova-plugin-mauron85-background-geolocation\ios\CDVBackgroundGeolocation\LocationManager.m " 

LINE 313, 
```
- (void) showLocationSettings
{
    //[[UIApplication sharedApplication] openURL:[NSURL URLWithString:@"prefs:root=LOCATION_SERVICES"]];
       if (@available(iOS 10, *)) {
        [[UIApplication sharedApplication] openURL:[NSURL URLWithString:@"App-Prefs:root=Privacy&path=LOCATION"]];
    } else {
        [[UIApplication sharedApplication] openURL:[NSURL URLWithString:@"prefs:root=LOCATION_SERVICES"]];
    }
}

```
Is this the solution @mauron85 ?
PS- I have no idea of objective C.

**Comment by mauron85** [comment]
Basically you can remove whole body of the function. That's how it was "fixed" in 3.x branch.

https://github.com/mauron85/background-geolocation-ios/blob/ab6f0e110e6b6a3de9f478327d20b6b7c1c08a14/BackgroundGeolocation/MAURBackgroundGeolocationFacade.m#L329

**Comment by lightyaer** [comment]
@mauron85 Thanks for the quick response. Really appreciate it.

**Comment by renderin** [comment]
@mauron85 thanks

**Comment by mauron85** [comment]
Version 2.3.6 is out which is fixing this.

**Comment by rudiminty** [comment]
Thanks @mauron85 !

**Comment by justgeek** [comment]
> Version 2.3.6 is out which is fixing this.

I see latest release version is 2.3.5. Am I missing something here?

**Comment by AdrianKujawski** [comment]
> > Version 2.3.6 is out which is fixing this.
> 
> I see latest release version is 2.3.5. Am I missing something here?

Just type `cordova plugin add cordova-plugin-mauron85-background-geolocation@2.3.6`
It's special, hidden version!

**Comment by goinnn** [comment]
Same problem than open native settings plugin, this feature is in this plugin too.

Fixed here:

https://github.com/guyromb/Cordova-open-native-settings/commit/aa53c9112109e622b7125ce58545d7ef7af2a063

**Comment by mauron85** [comment]
This has been fixed long time ago. Upgrade your plugin
