### ISSUE TITLE
How to disable the local notification ?

### ISSUE THREAD

**Issue by codeurfou** [mauron85/cordova-plugin-background-geolocation#455]
## Your Environment

* Plugin version: 3.0.0-alpha.36 
* Platform: Android
* OS version: 8.1
* Device manufacturer and model: Oneplus 5T
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): 6.3.0
* Plugin configuration options: 
<variable name="GOOGLE_PLAY_SERVICES_VERSION" value="11+" />
        <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="19+" />
* Link to your project:

## Context
Thank you a lot for your plugin !
I just want to never see the local notification (which is customizable via 'notificationTitle' and 'notificationText'). How to do that ? I tried the 'startForeground' option but not what I look for...

**Comment by jfbourne** [comment]
Same here

**Comment by jfbourne** [comment]
Thanks @mauron85. I was not aware of the previous discussions. On side note, I really appreciate all your hard work, kudos!

**Comment by codeurfou** [comment]
Thx @mauron85. Thx for your work.

**Comment by mohpra** [comment]
@codeurfou 

This plugin creates a Notification Channel on Android O and above. This notification channel has channel ID "bglocservice". So to remove the notification you need to remove/delete this notification channel. 

I have done this in ionic3 using a method from phonegap-push-plugin. 

//First find all the notification channels with this.push.listChannels()

    this.Platform.ready().then(() => {
        this.push.listChannels().then(
            (channels) => {
                this.searchforid(channels);
            },
            () => console.log('No Channels found')
        )
    });

//Look for the channel with channel id as "bglocservice" and then delete it with this.push.delete()

    searchforid(channels) {
        for (var i = 0; i < channels.length; i++) {
            if(channels[i].id == "bglocservice") {
                this.Platform.ready().then(() => {
                    this.push.deleteChannel("bglocservice").then(() => console.log('Channel deleted'));
                });
            }
        }  
    }

Once the notification channel is deleted, you will not see persistant notification in the drawer. 

However you must be careful with this. As explained by @mauron85 "Deleting or disabling notification channel would make plugin service eligible to be killed by the system at any time (specially on recent android)."

**Comment by Fever905** [comment]
That is very interesting.  I am gonna try this.
