### ISSUE TITLE
Not able to turn off debug sounds and messages even though the debug flag is set to false

### ISSUE THREAD

**Issue by angel1st** [mauron85/cordova-plugin-background-geolocation#456]
## Your Environment

* Plugin version: 3.0.0-alpha.37
* Platform: Android
* OS version: 8.0.0
* Device manufacturer and model: S8
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`):
Installed platforms:
  android 7.1.0
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0

* Plugin configuration options: 
```
                    locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
                    desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
                    stationaryRadius: 5,
                    distanceFilter: 5,
                    notificationTitle: 'BG is tracking',
                    notificationText: 'enabled',
                    debug: false,
                    interval: 10000,
                    fastestInterval: 5000,
                    activitiesInterval: 10000,
                    stopOnTerminate: true

```

## Context

This is a very simple app, just to try out the plugin functionality. It is important to note, I am compiling a debug apk.
## Expected Behavior

Nevertheless of the above fact, I am expecting once I set `debug` flag to `false` all sounds and messages to be removed, as stated into the documentation.  
## Actual Behavior

The debug sounds and messages don't stop.

**Comment by dvdpzzt-webmapp** [comment]
Hello,
The problem still persists in version 3.0.0-alpha.39. Seems to be cached in the application: uninstalling and reinstalling it solve the problem

**Comment by angel1st** [comment]
@dvdpzzt-webmapp - the above suggestion does not work at least on *3.0.0-alpha.37*. I will give a try on *39* and let you know.

**Comment by angel1st** [comment]
Actually *3.0.0-alpha.39* works exactly as *3.0.0-alpha.37* - both debug toast messages and sounds remains nevertheless of the `debug` config field value. Uninstalling and installing the app changes nothing.

**Comment by angel1st** [comment]
@dvdpzzt-webmapp - since I moved from *37* to *39*, I believe I followed all the above, but removing platform. 
Probably the order differs but anyway - this one definitely is a bug and needs to be fixed.

**Comment by mauron85** [comment]
Can you post output of

```
BackgroundGeolocation.getConfig(function(c){
  console.log(c);
});
```

You can do it from Chrome about:inspect console when app is running

**Comment by angel1st** [comment]
@mauron85 - sure, here it is:

![bg-location-20180817](https://user-images.githubusercontent.com/8547131/44275795-59a5ff80-a24e-11e8-8939-ef521c4f5987.png)

hope this helps...

**Comment by mauron85** [comment]
ok, that's really strange. Just to make sure, you're getting toast messages and sounds when new location is obtained?

**Comment by angel1st** [comment]
I did some additional testing and to be more precise - I have got toast messages and beeps, **only** when the app is in **background** mode.

**Comment by angel1st** [comment]
@mauron85 - given the above clarification, any ETA on the fix?

**Comment by fredcarneiro** [comment]
Having the same problem here

**Comment by angel1st** [comment]
For anyone, who is experiencing the same problem - as temporary workaround, this is what I have applied:

- Find **.\plugins\cordova-plugin-mauron85-background-geolocation\android\common\src\main\java\com\marianhello\bgloc\provider\AbstractLocationProvider.java** file and open it
- Find `showDebugToast` method and comment its body. It should work like this, after you commented it:
```
protected void showDebugToast (String text) {
        /*
        if (mConfig.isDebugging()) {
            Toast.makeText(mContext, text, Toast.LENGTH_LONG).show();
        }*/
    }
```

- Find `playDebugTone` method (it is just below the above one) and comment line `toneGenerator.startTone(name, duration);`. After the comment the method should look like this:

```
protected void playDebugTone (int name) {
        if (toneGenerator == null || !mConfig.isDebugging()) return;

        int duration = 1000;

        //toneGenerator.startTone(name, duration);
    }
```
- Execute `cordova platform rm android`.
- Execute `cordova platform rm ios`.
- Execute `cordova platform add android@7.1.0`.
- Execute `cordova platform add ios`. These are required, to ensure, the plugin will compile from amended sources
- Execute `cordova build`

Note: I realize, this is quite unpleasant workaround, however, the sounds are really annoying. Since the issue is not fixed for almost two months, this is what I did and wanted to share with you guys.

**Comment by angel1st** [comment]
It seems after all, the issue was on my end. Accidentally, I have forgotten `BackgroundGeolocation.configure({debug: true})` into `background` event handler, which causes debug messages and sounds, when app goes into the background.
I am closing the issue now.

**Comment by robsco-git** [comment]
> It seems after all, the issue was on my end. Accidentally, I have forgotten `BackgroundGeolocation.configure({debug: true})` into `background` event handler, which causes debug messages and sounds, when app goes into the background.
> I am closing the issue now.

This code is in the example code in the README.md - not sure why.
