### ISSUE TITLE
Post url not woking when app is in background

### ISSUE THREAD

**Issue by blgsyrmhnds** [mauron85/cordova-plugin-background-geolocation#460]
## Your Environment

* Plugin version:^2.2.0
* Platform: r Android
* OS version:last
* Device manufacturer and model:Many android devices
* Cordova version (`cordova -v`):cli-8.0.0
* Cordova platform version (`cordova platform ls`):cli-8.0.0
* Plugin configuration options: 
* Link to your project:

  backgroundGeolocation.configure(SetLocationUpdates, onError, {
desiredAccuracy: 10,
stationaryRadius: 10,
distanceFilter: 10,
startOnBoot:true,
saveBatteryOnBackground:false,
startForeground:true,
interval:5000,
fastestInterval:5000,
locationService: 'ANDROID_FUSED_LOCATION',
locationProvider: backgroundGeolocation.provider.ANDROID_DISTANCE_FILTER_PROVIDER,
activitiesInterval: 10000,
debug: false,
url: 'http://ki-tap.com/Admin/xxx',
syncUrl: 'http://ki-tap.com/Admin/xxx',
syncThreshold:50,
stopOnTerminate: false
});
	  
	     
        
        
        
        
		
    
	  backgroundGeolocation.start();

Code works very well,no error(I add alert to callback=SetLocationUpdates function alert work)
but It does not call : http://ki-tap.com/Admin/xxx  that url
In that url I add some data to database but it does not add

**Comment by mauron85** [comment]
2.2.0 is not supported as being too old

**Comment by mauron85** [comment]
Please upgrade to latest version. Your problem should be resolved.
