### ISSUE TITLE
Events never trigger

### ISSUE THREAD

**Issue by yurifw** [mauron85/cordova-plugin-background-geolocation#461]
## Your Environment

* Plugin version: 3.0.0-alpha.38
* Platform: Android
* OS version: 6.0.1
* Device manufacturer and model: Samsung / Galaxy J7
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`):  android 6.3.0
* Plugin configuration options: 
* Link to your project:

## Context

I am running the example code provided in the README page of the plugin and adb logcat to see the logs, but the log has no information about the plugin after it starts. The log shows that the plugin has started and that's it, nothin more gets printed. Here's what I get from the logs:

`08-01 11:13:05.671  1271  1271 D SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 143 : [INFO] BackgroundGeolocation service is running
08-01 11:13:05.671  1271  1271 I chromium: [INFO:CONSOLE(143)] "[INFO] BackgroundGeolocation service is running", source: file:///android_asset/www/js/index.js (143)
08-01 11:13:05.671  1271  1271 D SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 144 : [INFO] BackgroundGeolocation services enabled
08-01 11:13:05.671  1271  1271 I chromium: [INFO:CONSOLE(144)] "[INFO] BackgroundGeolocation services enabled", source: file:///android_asset/www/js/index.js (144)
08-01 11:13:05.671  1271  1271 D SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 145 : [INFO] BackgroundGeolocation auth status: 1
08-01 11:13:05.671  1271  1271 I chromium: [INFO:CONSOLE(145)] "[INFO] BackgroundGeolocation auth status: 1", source: file:///android_asset/www/js/index.js (145)`

Although nothing gets  loged, the toast notification appear on my Android (such as Detected STILL Activity)
Here is the code that is generating the logs:
```
  BackgroundGeolocation.configure({
    locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
    desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
    stationaryRadius: 50,
    distanceFilter: 50,
    notificationTitle: 'Background tracking',
    notificationText: 'enabled',
    debug: true,
    interval: 1000,
    fastestInterval: 5000,
    activitiesInterval: 10000,
    url: 'http://192.168.81.15:3000/location',
    httpHeaders: {
      'X-FOO': 'bar'
    },
    // customize post properties
    postTemplate: {
      lat: '@latitude',
      lon: '@longitude',
      foo: 'bar' // you can also add your own properties
    }
  });

  BackgroundGeolocation.on('location', function(location) {
    // handle your locations here
    // to perform long running operation on iOS
    // you need to create background task
    console.log("Location Acquired:")
    console.log(location)
    BackgroundGeolocation.startTask(function(taskKey) {
      // execute long running task
      // eg. ajax post location
      // IMPORTANT: task has to be ended by endTask
      BackgroundGeolocation.endTask(taskKey);
    });
  });

  BackgroundGeolocation.on('stationary', function(stationaryLocation) {
    console.log('[INFO] stationaryLocation acquired:')
    console.log(stationaryLocation)
    // handle stationary locations here
  });

  BackgroundGeolocation.on('error', function(error) {
    console.log('[ERROR] BackgroundGeolocation error:', error.code, error.message);
  });

  BackgroundGeolocation.on('start', function() {
    console.log('[INFO] BackgroundGeolocation service has been started');
  });

  BackgroundGeolocation.on('stop', function() {
    console.log('[INFO] BackgroundGeolocation service has been stopped');
  });

  BackgroundGeolocation.on('authorization', function(status) {
    console.log('[INFO] BackgroundGeolocation authorization status: ' + status);
    if (status !== BackgroundGeolocation.AUTHORIZED) {
      // we need to set delay or otherwise alert may not be shown
      setTimeout(function() {
        var showSettings = confirm('App requires location tracking permission. Would you like to open app settings?');
        if (showSetting) {
          return BackgroundGeolocation.showAppSettings();
        }
      }, 1000);
    }
  });

  BackgroundGeolocation.on('background', function() {
    console.log('[INFO] App is in background');
    // you can also reconfigure service (changes will be applied immediately)
    BackgroundGeolocation.configure({ debug: true });
  });

  BackgroundGeolocation.on('foreground', function() {
    console.log('[INFO] App is in foreground');
    BackgroundGeolocation.configure({ debug: false });
  });

  BackgroundGeolocation.checkStatus(function(status) {
    console.log('[INFO] BackgroundGeolocation service is running', status.isRunning);
    console.log('[INFO] BackgroundGeolocation services enabled', status.locationServicesEnabled);
    console.log('[INFO] BackgroundGeolocation auth status: ' + status.authorization);

    // you don't need to check status before start (this is just the example)
    if (!status.isRunning) {
      BackgroundGeolocation.start(); //triggers start on start event
    }
  });

  // you can also just start without checking for status
  BackgroundGeolocation.start();

```

Here are all the plugins that I'm using, just in case:
```
com.wmjalak.cordova.fileopener 1.0.0 "File Opener"
cordova-plugin-android-imei 1.0.0 "Android IMEI"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-downloader 0.3.2 "Downloader"
cordova-plugin-file-md5 0.3.3 "MD5 Checksum"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-mauron85-background-geolocation 3.0.0-alpha.38 "CDVBackgroundGeolocation"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"

```

## Expected Behavior
the log should show the lines printed by
`console.log("Location Acquired:")`
`console.log(location)`
Or any other event

## Actual Behavior
Nothing happens, the log shows  that the service is enabled and BackgroundGeolocation service is running, but I only see the logs from the BackgroundGeolocation.checkStatus(), never from the events

## Steps to Reproduce
1. Create the aplication
2. Install the plugin
3. use the code provided to log the events

## Context

I am trying to send a request to my server to save the location, the server should respond and the app should save the response of the request in a local file

## Debug logs

Here is an  [unfiltered log](https://pastebin.com/qmpCRk1V) (except for the jwt token, which wouldn't be of any use since it is still debug and the application hasn't launched yet)

**Comment by mauron85** [comment]
This can only mean no locations were recorded. Check if your app has permission and location services are enabled. I cannot check as your logs doesn't seem to contain result of checkStatus call.
