### ISSUE TITLE
Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']

### ISSUE THREAD

**Issue by manueldois** [mauron85/cordova-plugin-background-geolocation#464]
## Your Environment

* Plugin version: 2.3.5
* Platform: Android
* OS version: not sure
* Device manufacturer and model: SAMSUNG GALAXY S5
* Cordova version (`cordova -v`): 8.0.0 
* Cordova platform version (`cordova platform ls`): android 7.1.1
* Plugin configuration options: default
* Link to your project:

## Context
Build failure apparently due to google services incompatibility

## Expected Behavior
Not fight with other plugins

## Steps to Reproduce

1. clean ionic project
2. install phonegap-plugin-push and this one
3. ionic cordova run android... failed
4. cry

## Context

I installed cordova-android-play-services-gradle-release, cordova-android-firebase-gradle-release and cordova-android-support-gradle-release in an attempt to solve the error. However the error existed before I installed any of those plugins.

Maybe the problem is not on this plugin's side but I do not know where else to find help about versions in Ionic, so forgive me if that is the case.

My config.xml (plugins only):

    <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-device" spec="2.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="^2.0.0" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />
    <plugin name="phonegap-plugin-push" spec="^2.2.3">
        <variable name="ANDROID_SUPPORT_V13_VERSION" value="27.+" />
        <variable name="FCM_VERSION" value="11.6.2" />
        <variable name="SENDER_ID" value="59725559596" />
    </plugin>
    <platform name="android">
        <resource-file src="google-services.json" target="app/google-services.json" />
    </platform>
    <plugin name="uk.co.workingedge.phonegap.plugin.launchnavigator" spec="^4.2.1">
        <variable name="OKHTTP_VERSION" value="3.+" />
    </plugin>
    <plugin name="cordova-android-play-services-gradle-release" spec="^1.4.2">
        <variable name="PLAY_SERVICES_VERSION" value="15.0.0" />
    </plugin>
    <plugin name="cordova-android-firebase-gradle-release" spec="^1.0.1">
        <variable name="FIREBASE_VERSION" value="15.0.0" />
    </plugin>
    <plugin name="cordova-android-support-gradle-release" spec="^1.4.3">
        <variable name="ANDROID_SUPPORT_VERSION" value="26.+" />
    </plugin>
    <plugin name="cordova-support-google-services" spec="^1.1.0" />
    <plugin name="cordova-plugin-mauron85-background-geolocation" spec="^2.3.5">
        <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="11+" />
        <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="23+" />
        <variable name="ICON" value="@mipmap/icon" />
        <variable name="SMALL_ICON" value="@mipmap/icon" />
        <variable name="ACCOUNT_NAME" value="@string/app_name" />
        <variable name="ACCOUNT_LABEL" value="@string/app_name" />
        <variable name="ACCOUNT_TYPE" value="$PACKAGE_NAME.account" />
        <variable name="CONTENT_AUTHORITY" value="$PACKAGE_NAME" />
    </plugin>
    <engine name="android" spec="7.1.1" />

## Debug logs

cordova run android
Android Studio project detected
cordova-android-firebase-gradle-release: Android platform: cordova-android@7
cordova-android-firebase-gradle-release: Wrote custom version '15.0.0' to C:\Ionic\testapp3\platforms\android\app\build.gradle
cordova-android-firebase-gradle-release: Wrote custom version '15.0.0' to C:\Ionic\testapp3\platforms\android\app\cordova-android-firebase-gradle-release\properties.gradle
cordova-android-play-services-gradle-release: Android platform: cordova-android@7
cordova-android-play-services-gradle-release: Wrote custom version '15.0.0' to C:\Ionic\testapp3\platforms\android\app\build.gradle
cordova-android-play-services-gradle-release: Wrote custom version '15.0.0' to C:\Ionic\testapp3\platforms\android\app\cordova-android-play-services-gradle-release\properties.gradle
cordova-android-support-gradle-release: Android platform: cordova-android@7
cordova-android-support-gradle-release: Wrote custom version '26.+' to C:\Ionic\testapp3\platforms\android\app\build.gradle
cordova-android-support-gradle-release: Wrote custom version '26.+' to C:\Ionic\testapp3\platforms\android\app\cordova-android-support-gradle-release\properties.gradle
ANDROID_HOME=C:\Users\Manuel\AppData\Local\Android\Sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_171
studio
Subproject Path: CordovaLib
Subproject Path: app
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
+-----------------------------------------------------------------
| cordova-android-firebase-gradle-release: 15.0.0
+-----------------------------------------------------------------
+-----------------------------------------------------------------
| cordova-android-play-services-gradle-release: 15.0.0
+-----------------------------------------------------------------
+-----------------------------------------------------------------
| cordova-android-support-gradle-release: 26.+
+-----------------------------------------------------------------
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_5tcojuq62vkm55m7pfv5sc5sh.run(C:\Ionic\testapp3\platforms\android\app\build.gradle:149)

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Ionic\testapp3\platforms\android\cordova-support-google-services\starter-build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "11+"

* Try:
...

BUILD FAILED in 1s
(node:4484) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script 'C:\Ionic\testapp3\platforms\android\cordova-support-google-services\starter-build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "11+"

* Try:
...

BUILD FAILED in 1s
    at ChildProcess.whenDone (C:\Ionic\testapp3\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by MiguelSyll** [comment]
I have the same problem. I created a blank project and I added Push plugin. I did not have any Problem. Then I added this geolocation plugin and when I try to run I receive the same error:

BUILD FAILED in 1s
(node:7572) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Script 'C:\ionic\getfm2\platforms\android\cordova-support-google-services\Mobile-build.gradle' line: 16

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "11+"

Some solution?

Thanks
