### ISSUE TITLE
Error on Force Sync, Plugin should use CordovaInterface.getThreadPool() 

### ISSUE THREAD

**Issue by Colombo97** [mauron85/cordova-plugin-background-geolocation#466]
I'm getting erro on syncing locations to the server, using force sync
Plugin should use CordovaInterface.getThreadPool() 

## Your Environment
numeric version changes over the time -->
* Plugin version:^3.0.0-alpha.38
* Platform: Android
* OS version: Android 5.1.1
* Device manufacturer and model: J3 2016
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 7.0.0
* Plugin configuration options: 
* Link to your project:

## Expected Behavior
Sync all stored locations created offline sending it to server.

## Actual Behavior
Having error on force sync.

## Possible Fix
https://www.red-folder.com/blog/cordova-plugins-and-thread-blocking

## Steps to Reproduce
1. run the code on smartphone
2.
3.
4.

## Debug logs
More info in README.md section Debugging.
If you're reporting app crash also provide output of "adb logcat" -->
08-07 15:10:01.164 D/com.marianhello.bgloc.provider.RawLocationProvider(32375): Location change: Location[gps -17,445907,-54,745661 acc=10 e
t=+2d17h27m47s943ms alt=0.0 vel=27.777779 bear=184.14337 mock]
08-07 15:10:01.194 D/com.marianhello.bgloc.LocationService(32375): New location BGLocation[gps -17,445907,-54,745661 id=null acc=10 t=153366
9001174 et=+2d17h27m47s943ms alt=0.0 vel=27.777779 bear=184.14337 mock mocksEnabled locprov=2]
08-07 15:10:01.214 D/com.marianhello.bgloc.BackgroundGeolocationFacade(32375): Received MSG_ON_LOCATION
08-07 15:10:01.224 D/com.marianhello.bgloc.LocationService(32375): Executing PostLocationTask#postLocation
08-07 15:10:01.254 D/com.marianhello.bgloc.LocationService(32375): Posting json to url: http://xxx.ddns.net headers: {}
08-07 15:10:01.254 D/com.tenforwardconsulting.bgloc.cordova.BackgroundGeolocationPlugin(32375): Forced location sync requested
08-07 15:10:01.264 I/System.out(32375): (HTTPLog)-Static: isSBSettingEnabled false
08-07 15:10:01.264 I/System.out(32375): KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-07 15:10:01.274 I/System.out(32375): KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-07 15:10:01.284 D/com.marianhello.bgloc.BackgroundGeolocationFacade(32375): Sync locations forced
08-07 15:10:01.304 W/PluginManager(32375): THREAD WARNING: exec() call to BackgroundGeolocation.forceSync blocked the main thread for 47ms.
Plugin should use CordovaInterface.getThreadPool().
08-07 15:10:05.167 D/com.marianhello.bgloc.provider.RawLocationProvider(32375): Location change: Location[gps -17,446851,-54,745731 acc=10 e
t=+2d17h27m51s944ms alt=0.0 vel=27.777779 bear=184.042 mock]
08-07 15:10:05.187 D/com.marianhello.bgloc.LocationService(32375): New location BGLocation[gps -17,446851,-54,745731 id=null acc=10 t=153366
9005174 et=+2d17h27m51s944ms alt=0.0 vel=27.777779 bear=184.042 mock mocksEnabled locprov=2]
08-07 15:10:05.208 D/com.marianhello.bgloc.LocationService(32375): Executing PostLocationTask#postLocation
08-07 15:10:05.218 D/com.marianhello.bgloc.LocationService(32375): Posting json to url: http://xxx.ddns.net headers: {}
08-07 15:10:05.238 I/System.out(32375): (HTTPLog)-Static: isSBSettingEnabled false
08-07 15:10:05.238 I/System.out(32375): KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-07 15:10:05.238 I/System.out(32375): KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-07 15:10:05.278 D/com.marianhello.bgloc.BackgroundGeolocationFacade(32375): Received MSG_ON_LOCATION
08-07 15:10:05.318 D/com.tenforwardconsulting.bgloc.cordova.BackgroundGeolocationPlugin(32375): Forced location sync requested
08-07 15:10:05.338 D/com.marianhello.bgloc.BackgroundGeolocationFacade(32375): Sync locations forced
08-07 15:10:05.348 W/PluginManager(32375): THREAD WARNING: exec() call to BackgroundGeolocation.forceSync blocked the main thread for 34ms.
Plugin should use CordovaInterface.getThreadPool().
08-07 15:10:09.161 D/com.marianhello.bgloc.provider.RawLocationProvider(32375): Location change: Location[gps -17,447807,-54,745801 acc=10 e
t=+2d17h27m55s944ms alt=0.0 vel=27.777779 bear=183.93166 mock]
08-07 15:10:09.181 D/com.marianhello.bgloc.LocationService(32375): New location BGLocation[gps -17,447807,-54,745801 id=null acc=10 t=153366
9009174 et=+2d17h27m55s944ms alt=0.0 vel=27.777779 bear=183.93166 mock mocksEnabled locprov=2]
08-07 15:10:09.221 D/com.marianhello.bgloc.LocationService(32375): Executing PostLocationTask#postLocation
08-07 15:10:09.241 D/com.marianhello.bgloc.LocationService(32375): Posting json to url: http://xxx.ddns.net headers: {}
08-07 15:10:09.261 I/System.out(32375): (HTTPLog)-Static: isSBSettingEnabled false
08-07 15:10:09.261 I/System.out(32375): KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-07 15:10:09.291 I/System.out(32375): KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-07 15:10:09.342 D/com.marianhello.bgloc.BackgroundGeolocationFacade(32375): Received MSG_ON_LOCATION
08-07 15:10:09.392 D/com.tenforwardconsulting.bgloc.cordova.BackgroundGeolocationPlugin(32375): Forced location sync requested
08-07 15:10:09.402 D/com.marianhello.bgloc.BackgroundGeolocationFacade(32375): Sync locations forced
08-07 15:10:09.422 W/PluginManager(32375): THREAD WARNING: exec() call to BackgroundGeolocation.forceSync blocked the main thread for 32ms.
Plugin should use CordovaInterface.getThreadPool().
08-07 15:10:13.165 D/com.marianhello.bgloc.provider.RawLocationProvider(32375): Location change: Location[gps -17,448780,-54,745845 acc=10 e
t=+2d17h27m59s945ms alt=0.0 vel=27.777779 bear=183.23155 mock]
08-07 15:10:13.205 D/com.marianhello.bgloc.LocationService(32375): New location BGLocation[gps -17,448780,-54,745845 id=null acc=10 t=153366
9013175 et=+2d17h27m59s945ms alt=0.0 vel=27.777779 bear=183.23155 mock mocksEnabled locprov=2]
08-07 15:10:13.225 D/com.marianhello.bgloc.BackgroundGeolocationFacade(32375): Received MSG_ON_LOCATION
08-07 15:10:13.235 D/com.marianhello.bgloc.LocationService(32375): Executing PostLocationTask#postLocation
08-07 15:10:13.255 D/com.marianhello.bgloc.LocationService(32375): Posting json to url: http://xxx.ddns.net headers: {}
08-07 15:10:13.285 I/System.out(32375): (HTTPLog)-Static: isSBSettingEnabled false
08-07 15:10:13.285 I/System.out(32375): KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-07 15:10:13.305 I/System.out(32375): KnoxVpnUidStorageknoxVpnSupported API value returned is false
08-07 15:10:13.315 D/com.tenforwardconsulting.bgloc.cordova.BackgroundGeolocationPlugin(32375): Forced location sync requested
08-07 15:10:13.325 D/com.marianhello.bgloc.BackgroundGeolocationFacade(32375): Sync locations forced
08-07 15:10:13.345 W/PluginManager(32375): THREAD WARNING: exec() call to BackgroundGeolocation.forceSync blocked the main thread for 28ms.
Plugin should use CordovaInterface.getThreadPool().

**Comment by mauron85** [comment]
This is just the warning not an error. But yes, it should be called on a background thread.

**Comment by Colombo97** [comment]
But this is the minor problem, I just used "forceSync ()" to test sending data from "local storage" to the server, since my biggest problem is normal synchronization (from minute to minute and with syncTreshold on 10) is not occurring, it never occurs on online. Incredibly only occurs when the device is without an internet connection. I do not know if I am sure however by researching other topics I saw that you have removed an authorization in the latest releases from config.xml, <what-permission-android: name = "android.permission.GET_ACCOUNTS" />, could that be what happened ?

this is the discussion that I am referring to:
#321

**Comment by mauron85** [comment]
@Colombo97 I think it's must different reason why sync is not working for you. Maybe user disabled syncing for all apps and plugin is strictly follow to this user preference since Since 3.0.0-alpha.25.

**Comment by rathodkaran07** [comment]
Hi Mauron,

We are facing the same issue. When my locations fail to sync only recent few 30 - 40 entries gets synced and rest are not synced.
Can you help with this issue?

Let me know if you need any debugging logs / want me to check anything.
