### ISSUE TITLE
How to simulate location

### ISSUE THREAD

**Issue by dvdpzzt-webmapp** [mauron85/cordova-plugin-background-geolocation#469]
## Your Environment

* Plugin version: 2.3.5 or 3.0.0-alpha.39
* Platform: Android
* OS version: 7.0
* Device manufacturer and model: Huawei P9 Lite
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 6.3.0
* Plugin configuration options: 
                        stationaryRadius: 25,
                        distanceFilter: 5,
                        interval: 800,
                        startForeground: false, //Changes when in background/foreground
                        notificationTitle: 'Title',
                        notificationText: 'Text',
                        notificationIconColor: "#FF00FF",
                        maxLocations: 10000

## Context

I'm trying to simulate the position on the physical device using the sensor tab in the chrome inspector. 

## Expected Behavior
I expect the plugin to take the position set in the inspector and use it

## Actual Behavior
The position is not used by the plugin

## Context

Actually this is not a big problem for me as I can simulate the position in other different ways using directly android features/app.

**Comment by sakthibro** [comment]
Download and install https://play.google.com/store/apps/details?id=fr.dvilleneuve.lockito app . Then Select Mockup Location -> choose lockito app   . Know more 9786252624

**Comment by mauron85** [comment]
Well I don't think it's possible to mock location from chrome developer tools. It only have effect html5 navigator and doesn't have any effect on this plugin as it's using native apis instead. Use lockito or similar app.
