### ISSUE TITLE
Background recording is not working well

### ISSUE THREAD

**Issue by HarelM** [mauron85/cordova-plugin-background-geolocation#470]
## Your Environment

* Plugin version: 3.0.0-alpha.40
* Platform: Android
* OS version: 7.2
* Device manufacturer and model: Xiomi Redmi 4
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`):  7.0.0
* Plugin configuration options: 
* Link to your project: https://github.com/IsraelHikingMap/Site/tree/master/IsraelHiking.Web

## Context
I wanted to be able to record a route while the application is in the background, but I get bad results :-/

## Expected Behavior
Geo-location should be measured in the required intervals with the relevant distance filter

## Actual Behavior
Geo location is measure sporadically and is inaccurate

## Possible Fix
I would love to help out, but I have no clue

## Steps to Reproduce
I've copied most of the code from the example, see here:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/sources/application/services/geo-location.service.ts
The project above can be complied using `npm run build -- -c android` and then packed to apk (cordova run android) to debug locally.
I made sure the battery setting for the app is "no limitation".

## Context
I'm trying to convert the site I currently maintain:
https://israelhiking.osm.org.il/
To be able to record a route when the application is in the background and I can't achieve it using only the browser (as far as I know).

## Debug logs
Probably better if you reproduce it locally, in case this is problematic I'll be glad to try and extract logs from my device.

Here is how the recording looks, can be found here:
https://israelhiking.osm.org.il/share/g5dzPscL9t
![image](https://user-images.githubusercontent.com/3269297/44509197-a445d280-a6b9-11e8-8ece-75ae4240eab1.png)

It might be that I wrote the code wrong, but from the readme it looks fine...

**Comment by zstadler** [comment]
[Here](https://israelhiking.osm.org.il/share/bKqxBlWvkO) is a recording done with the above code (in blue) together with the gps recording obtained by a different app (in red).
![_20180823_150032](https://user-images.githubusercontent.com/1304610/44524254-6ced1b00-a6e5-11e8-9078-0dcb65663955.JPG)

**Comment by HarelM** [comment]
I have changed `locationProvider` from `BackgroundGeolocation.DISTANCE_FILTER_PROVIDER` to `BackgroundGeolocation.RAW_PROVIDER` and it seems to solve this.
Never-the-less I think the above is a workaround and not the right fix, IMO

**Comment by pavankumarkatakam** [comment]
Hi @HarelM , Are you still using the RawProvider. I need to know if raw provider uses interval and fastestInterval.

or Are you satisfied with the results of DISTANCE_FILTER_PROVIDER.

**Comment by HarelM** [comment]
Yes, I haven't changed the configuration since I posted this comment.
I think raw provider uses interval and fastest interval add far as I could observe but it works be better to check with the maintainer of this plugin.
