### ISSUE TITLE
Not working in ionic 3

### ISSUE THREAD

**Issue by rahul-maurya1992** [mauron85/cordova-plugin-background-geolocation#472]
## Your Environment

* Plugin version:^2.3.5
* Platform: iOS
* OS version: 11x
* Device manufacturer and model:
* Cordova version (`cordova -v`):8.0.0
* Cordova platform version (`cordova platform ls`):7.0.0
* Plugin configuration options: 
* Link to your project:

## Context

I'm using ionic 3 and my environment specification is provided above. this plugin not working on background.

## Expected Behavior

According to the repo this plugin use to get location even app is running on background but this is not working  like this. It's working fine on foreground but i'm not able to get the location when app is in background.

## Actual Behavior

I want to get user location(lat,long)when my app running in the background.I used this plugin and it's when app running on foreground but it's not picking up the user location when app is running in the background.

**Comment by jfbourne** [comment]
What provider are you using? Paste you configuration here. One thing to know is that in iOS this plugin uses only the stationaryRadius in background, meaning it will only trigger location event once your iOS have move out of the radius. If this number is super hight, you will need to walk/run/drive pretty long distance before you see and update.
