### ISSUE TITLE
hmm. I can not start backgroundlocationservice. I need your help

### ISSUE THREAD

**Issue by laychar** [mauron85/cordova-plugin-background-geolocation#474]
## Your Environment

* Plugin version:
"cordova-android": "^7.0.0",
"cordova-plugin-mauron85-background-geolocation": "^2.3.5",
"cordova-plugin-background-fetch": "^5.4.1",
"cordova-plugin-camera": "^4.0.3",
"cordova-plugin-device": "^2.0.2",
"cordova-plugin-file": "^6.0.1",
"cordova-plugin-file-transfer": "^1.7.1",
"cordova-plugin-firebase": "^1.0.5",
"cordova-plugin-geolocation": "^4.0.1",
"cordova-plugin-ionic-keyboard": "^2.1.2",
"cordova-plugin-request-location-accuracy": "^2.2.3",
"cordova-plugin-statusbar": "^2.4.2",
"cordova-plugin-whitelist": "^1.3.3",
"cordova.plugins.diagnostic": "^4.0.8"
* Platform: Android
* OS version: Mac
* Device manufacturer and model: galaxy A5
* Cordova version (`cordova -v`):8.0.0
* Cordova platform version (`cordova platform ls`):
android 7.0.0
Available platforms:
browser ~5.0.1
ios ~4.5.4
osx ~4.0.1
windows ~5.0.0
www ^3.12.0
* Plugin configuration options: 
* Link to your project:

## Context

I just want to use your plugin. So I copied the example and rewrite your code to my project. But Nothing happen. So, I call the alert function whether your plugin is working well or not. like this... 
   function onDeviceReadym85() {
    alert('device ready');
  BackgroundGeolocation.configure({
    locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
    desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
    stationaryRadius: 50,
    distanceFilter: 50,
    notificationTitle: 'Background tracking',
    notificationText: 'enabled',
    debug: true,
    interval: 10000,
    fastestInterval: 5000,
    activitiesInterval: 10000,
    url: url+'/sendlocal',
    httpHeaders: {
      'X-FOO': 'bar'
    },
    // customize post properties
    postTemplate: {
      lat: '@latitude',
      lon: '@longitude',
      foo: 'bar' // you can also add your own properties
    }
  });
 alert('1');
  BackgroundGeolocation.on('location', function(location) {
      alert('location');
    // handle your locations here
    // to perform long running operation on iOS
    // you need to create background task
    BackgroundGeolocation.startTask(function(taskKey) {
      // execute long running task
      // eg. ajax post location
      // IMPORTANT: task has to be ended by endTask
      BackgroundGeolocation.endTask(taskKey);
    });
  });
 alert('2');
  BackgroundGeolocation.on('stationary', function(stationaryLocation) {
      alert('stationary');
    // handle stationary locations here
  });
 alert('3');
  BackgroundGeolocation.on('error', function(error) {
    console.log('[ERROR] BackgroundGeolocation error:', error.code, error.message);
      alert('error');
  });
 alert('4');
  BackgroundGeolocation.on('start', function() {
    console.log('[INFO] BackgroundGeolocation service has been started');
      alert('start');
  });
 alert('5');
  BackgroundGeolocation.on('stop', function() {
    console.log('[INFO] BackgroundGeolocation service has been stopped');
      alert('stop');
  });
 alert('6');
  BackgroundGeolocation.on('authorization', function(status) {
      alert('autho');
    console.log('[INFO] BackgroundGeolocation authorization status: ' + status);
    if (status !== BackgroundGeolocation.AUTHORIZED) {
      // we need to set delay or otherwise alert may not be shown
      setTimeout(function() {
        var showSettings = confirm('App requires location tracking permission. Would you like to open app settings?');
        if (showSetting) {
          return BackgroundGeolocation.showAppSettings();
        }
      }, 1000);
    }
  });
 alert('7');
  BackgroundGeolocation.on('background', function() {
      alert('background');
    console.log('[INFO] App is in background');
    // you can also reconfigure service (changes will be applied immediately)
    BackgroundGeolocation.configure({ debug: true });
  });
 alert('8');
  BackgroundGeolocation.on('foreground', function() {
      
      
      alert('foreground');
    console.log('[INFO] App is in foreground');
    BackgroundGeolocation.configure({ debug: false });
  });
 alert('9');
  BackgroundGeolocation.on('abort_requested', function() {
      alert('aborted_requested')
    console.log('[INFO] Server responded with 285 Updates Not Required');
 
    // Here we can decide whether we want stop the updates or not.
    // If you've configured the server to return 285, then it means the server does not require further update.
    // So the normal thing to do here would be to `BackgroundGeolocation.stop()`.
    // But you might be counting on it to receive location updates in the UI, so you could just reconfigure and set `url` to null.
  });
        alert('10');
  BackgroundGeolocation.start();
}
 
document.addEventListener('deviceready', onDeviceReadym85, false);

I call that function after I get location authoriztion.
ONLY alert('device ready') works!. And another alert do not work. I think there is problem with the BackgroundGeolocation.configure.
I need your help. what is the problem which i missed? thank you.
## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
You are using code from 3.x branch but installed 2.x.

**Comment by laychar** [comment]
then how to install 3.x? 
when I write "cordova plugin add cordova-plugin-mauron85-background-geolocation" to the terminal, only 2.x is installed

**Comment by laychar** [comment]
Is there a problem?
