### ISSUE TITLE
cordova plugin add cordova-plugin-mauron85

### ISSUE THREAD

**Issue by laychar** [mauron85/cordova-plugin-background-geolocation#475]
I execute "cordova plugin add cordova-plugin-mauron85" to install latest version- 3.x. 
But 2.x version is installed.
What should I do to install latest(3.×) version?

**Comment by laychar** [comment]
d

**Comment by laychar** [comment]
I solved this problem, thank you.

**Comment by jeancarlos2020** [comment]
what was the solution

**Comment by KMenant** [comment]
#481
