### ISSUE TITLE
Starting Service at Boot Time

### ISSUE THREAD

**Issue by KinjiQaudra** [mauron85/cordova-plugin-background-geolocation#48]
Hello, i want to start automaticaly a backround-geolocalisation when the device start, is it possible ?
thanks

**Comment by mauron85** [comment]
Yes, it will be possible. At the moment it is implemented for Android in development branch. Keep in mind it's in development.
https://github.com/mauron85/cordova-plugin-background-geolocation/tree/next

**Comment by KinjiQaudra** [comment]
Thank you, sorry for the duplicate

**Comment by mauron85** [comment]
NP
