### ISSUE TITLE
cordova-plugin-background-geolocation v 3

### ISSUE THREAD

**Issue by sasiadstar** [mauron85/cordova-plugin-background-geolocation#481]
I wanted to install version 3 but from the link the version 2.3 is still being installed
npm i cordova-plugin-mauron85-background-geolocation = version "2.3.5"

**Comment by rcha103** [comment]
@sasiadstar I think the latest release is version 2.3.5. Changes.md shows that version 3.0.0 is not released yet. That being said, I'm also looking forward to version 3.0 release. The new features are exciting and will be super useful for my projects @mauron85 .

**Comment by angel1st** [comment]
guys, you can always add a specific plugin version by executing `cordova plugin add cordova-plugin-mauron85-background-geolocation@version`, i.e. if you need some of 3.0.0 alpha releases, you can for instance do following:
`cordova plugin add cordova-plugin-mauron85-background-geolocation@^3.0.0-alpha.42`

**Comment by sasiadstar** [comment]
It works!!! Thanks
