### ISSUE TITLE
HTTP locations posting doesn't seem to be working?

### ISSUE THREAD

**Issue by designed2use** [mauron85/cordova-plugin-background-geolocation#482]
Hi All,

I'm trying to setup a basic test so I've created a simple PhoneGap app which simply starts the background service and posts to my specified url.

It should then send me an email from my server with the post results, but nothing seems to be coming through on Android or iOS.

Thanks for you help.

## Your Environment

* Plugin version: ~3.0.0-alpha.41
* Platform: iOS & Android
* OS version: iOS 11 Android 6.0.1
* Device manufacturer and model: iPhone 6SE & VFD 600
* Cordova version (`cordova -v`): 7.1.0, also tried 8.0.0
* Cordova platform version (`cordova platform ls`): cli-7.1.0 (4.5.4 / 6.3.0 / 5.0.0)
* Plugin configuration options: 
ackgroundGeolocation.configure({
    locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
    desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
    stationaryRadius: 50,
    distanceFilter: 50,
    notificationTitle: 'Background tracking',
    notificationText: 'enabled',
    debug: true,
    interval: 10000,
    fastestInterval: 5000,
    activitiesInterval: 10000,
    url: 'http://online.xxxxxxxx.co.uk/ajax.php',
    httpHeaders: {
      'X-FOO': 'bar'
    },
    // customize post properties
    postTemplate: {
      lat: '@latitude',
      lon: '@longitude',
      foo: 'bar' // you can also add your own properties
    }
  });
* Link to your project: n/a

## Context

Doesn't seem to be sending post?

## Expected Behavior

Should post array to provided url

##

**Comment by designed2use** [comment]
Sorry, Nevermind I've figured it out now.

I'm not sure if it made a difference, but I used the xml settings from the example project.

I also used the following php to return the post object as $_POST didn't seem to be working?
`file_get_contents('php://input');`

**Comment by hazaveh** [comment]
can you elaborate which xml settings & your solution? 

I happen to have the same problem. I'm not able to receive the http request even with php://input

**Comment by designed2use** [comment]
Hi Hazaveh,

this was a while ago but I'm pretty sure it was down to the xml settings in the project config file.

I used the following:

    <plugin name="cordova-plugin-mauron85-background-geolocation" source="npm" spec="3.0.0-alpha.37">
        <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="11+" />
        <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="26+" />
        <variable name="ALWAYS_USAGE_DESCRIPTION" value="App requires background tracking enabled" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="App requires motion detection" />
        <variable name="ACCOUNT_NAME" value="@string/app_name" />
        <variable name="ACCOUNT_LABEL" value="@string/app_name" />
        <variable name="ACCOUNT_TYPE" value="$PACKAGE_NAME.account" />
        <variable name="CONTENT_AUTHORITY" value="$PACKAGE_NAME" />
    </plugin>
