### ISSUE TITLE
getCurrentLocation(success, fail, options) is not defined type of BackgroundGeolocation?

### ISSUE THREAD

**Issue by akhilsahu** [mauron85/cordova-plugin-background-geolocation#484]
Trying to call       
 ` this.backgroundGeolocation.getCurrentLocation(success, fail, {});`
but shows undefined. I need to call the current location function sometimes as the last location fetched is same as current. Sometimes it does not updates fastly.

 

## Your Environment

* Plugin version:
* Platform:   Android
* OS version: 6+
* Device manufacturer and model: all android
* Cordova version (`cordova -v`):   7.1
* Cordova platform version (`cordova platform ls`): 
 
Ionic 3.x
## Expected Behavior
It should fetch the location
## Actual Behavior

It does not
## Steps to Reproduce

1.Add the line to your project it and build

**Comment by mauron85** [comment]
I think you're using 2.x branch (because backgroundGeolocation in 3.x starts with capital B).

`getCurrentLocation` method is implemented first in 3.x so it doesn't exists in 2.x branch.

**Comment by tpmoises** [comment]
> I think you're using 2.x branch (because backgroundGeolocation in 3.x starts with capital B).
> 
> `getCurrentLocation` method is implemented first in 3.x so it doesn't exists in 2.x branch.

Good morning, I'm using the correct syntax with "B" and there's the error: getCurrentLocation is not a function. My app is made in javascript. I try to call this function inside the onbackground.

Moisés Santos

**Comment by tpmoises** [comment]
> > I think you're using 2.x branch (because backgroundGeolocation in 3.x starts with capital B).
> > `getCurrentLocation` method is implemented first in 3.x so it doesn't exists in 2.x branch.
> 
> Good morning, I'm using the correct syntax with "B" and there's the error: getCurrentLocation is not a function. My app is made in javascript. I try to call this function inside the onbackground.
> 
> Moisés Santos

Ambiente Cordova.  PhoneGap (iOS / Android / Windows)
                                           cli-7.1.0 (4.5.4 / 6.3.0 / 5.0.0)

I noticed that Phonegap uses version 3.0.0-alpha.14

**Comment by mauron85** [comment]
It was implemented in 3.0.0-alpha.30.

https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/CHANGES.md

**Comment by tpmoises** [comment]
Hi good night! When will the newest version be available on Phonegap Build? Your Plugin works. Except that something strange happens. The Maxima age option in settings as it is implemented. I already searched the available documentation and did not find it. I've seen examples using maximunAge. That's right? or maxAge? Help me and you will not regret it. Thankful. Moisés Santos.




Moisés Santos, Advogado OAB-RN 11.108



84 99653-5787 (Tim)
84 98722-6243 (whatsApp)
Assinatura automática
________________________________
Visite meu site : http://www.drmoisessantos.com

________________________________
De: Marián Hello <notifications@github.com>
Enviado: quarta-feira, 31 de outubro de 2018 18:16:47
Para: mauron85/cordova-plugin-background-geolocation
Cc: Moisés Santos da Silva; Comment
Assunto: Re: [mauron85/cordova-plugin-background-geolocation] getCurrentLocation(success, fail, options) is not defined type of BackgroundGeolocation? (#484)


It was implemented in 3.0.0-alpha.30.

https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/CHANGES.md
