### ISSUE TITLE
Support typescript typing

### ISSUE THREAD

**Issue by HarelM** [mauron85/cordova-plugin-background-geolocation#487]
It would be super useful if this library had a typing file with it much like other cordova plugins. This will help code without making typos...

## Your Environment
I'm using visual studio, and angular-cli on windows 10

* Plugin version: 3.0.0-alpha.40
* Platform: Android 
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 7.0.0
* Plugin configuration options: N/A
* Link to your project: https://github.com/IsraelHikingMap/Site/

## Context
More of a feature request

## Expected Behavior
Be able to code without typos using intelisence

## Actual Behavior
Can't do it, need to copy the code from the documentation

## Possible Fix
Typescript definitely typed.

**Comment by mauron85** [comment]
Implemented in https://github.com/mauron85/cordova-plugin-background-geolocation/commit/d246db998763188691d5d623c5350d8157aee2d3

Closing. Reopen if necessary.

**Comment by mauron85** [comment]
![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/359450/47592506-e3bbc400-d973-11e8-9783-7e617fd553e8.gif)

**Comment by HarelM** [comment]
Looks amazing! Thanks!
From which version I should expect this?

**Comment by mauron85** [comment]
Version with typings is not published to npm yet, but you can use typings today. One of the option is to install plugin from git.

Or copy following definition file to your existing package www folder.
https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/www/BackgroundGeolocation.d.ts

There are several other options how to add typings to your IDE, but not going to mention them here.

On GIF you're seeing Visual Studio Code with installed plugin from git and I believe also has some cordova plugin installed (but not sure if that's necessary).

**Comment by mauron85** [comment]
FYI package is out in npm.

**Comment by jeancarlos2020** [comment]
I have this error :(
![image](https://user-images.githubusercontent.com/6289980/47922647-8d73e700-de85-11e8-8b0f-cc430c4ba878.png)

**Comment by HarelM** [comment]
Thanks for the update and the hard work but it seems there's an issue with the typings file:
```
ERROR in node_modules/cordova-plugin-mauron85-background-geolocation/www/BackgroundGeolocation.d.ts(471,18): error TS2304: Cannot find name 'AccuracyLevel'.
node_modules/cordova-plugin-mauron85-background-geolocation/www/BackgroundGeolocation.d.ts(472,20): error TS2304: Cannot find name 'AccuracyLevel'.
node_modules/cordova-plugin-mauron85-background-geolocation/www/BackgroundGeolocation.d.ts(473,17): error TS2304: Cannot find name 'AccuracyLevel'.
node_modules/cordova-plugin-mauron85-background-geolocation/www/BackgroundGeolocation.d.ts(474,21): error TS2304: Cannot find name 'AccuracyLevel'.
```
Seems like the `AccuracyLevel` is commented out.

Also please note that there are some guideline on how to add this typing file:
http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
Namely the `types": "./www/BackgroundGeolocation.d.ts" in `package.json`.
or use `index.d.ts` file in the root of the npm package.

Let me know if you need a PR for this, I'm guessing this can be done in no time so the hassle of a PR seems a bit too much here, IMHO...

Thanks again!

**Comment by mauron85** [comment]
@HarelM Thank you for pointing this out. Will fix the typing error soon.

About the publication part, you can prepare PR of course. Not sure why solution is "better", but in my preference keeping typings definition file name same as original js make more sense, then index.d.ts.
But it's more like a feeling. :)

**Comment by HarelM** [comment]
I see the logic in using `index.d.ts` to reference the `BackgroundGeolocation.d.ts` file. In any case, it's probably a matter of taste. Maybe @djereg can add this as part of the fix to the comment. It seems like an overkill for me to open a PR for this, please forgive my laziness... :-)

**Comment by djereg** [comment]
@HarelM Thanks ans sorry, this is my banal mistake. [Here](https://github.com/mauron85/react-native-background-geolocation/pull/314#issuecomment-436422419) is a conversation about possible fixes.

And yes, you are right about setting `"types": "./www/BackgroundGeolocation.d.ts"` in package.json. This is the right way. Will make PR in both repositories. @mauron85 it's okay?

**Comment by mauron85** [comment]
Please do

**Comment by HarelM** [comment]
Have you guys managed to make it work using angular (webpack)?
I just now had the time to test it, but I can't make compile without errors...
I have tried all kinds of things but nothing seems to work... :-/

`import BackgroundGeolocation from 'cordova-plugin-mauron85-background-geolocation'` 
complains about channel: 
```
./node_modules/cordova-plugin-mauron85-background-geolocation/www/BackgroundGeolocation.js
Module not found: Error: Can't resolve 'cordova/channel' in '...\node_modules\cordova-plugin-mauron85-background-geolocation\www'
```

`/// <reference types="cordova-plugin-mauron85-background-geolocation"/>` doesn't seem to do anything

adding to types in `tsconfig.json` also doesn't seem to do anything...

Any help will be appreciated.

**Comment by mauron85** [comment]
@HarelM This issue has been resolved. I think your issue is separate thing discussed here:

https://github.com/mauron85/cordova-plugin-background-geolocation/issues/515

**Comment by HarelM** [comment]
@mauron85 thanks! you're probably right. Thanks for the quick response!
