### ISSUE TITLE
iOS in airplane mode - GPS?

### ISSUE THREAD

**Issue by Shane98c** [mauron85/cordova-plugin-background-geolocation#49]
Thanks for keeping this thing rolling.  

I'm wondering if there is any hope of adding support for the standard location service in iOS in addition to the significant-changes api.  We're developing an app that needs to track user location while in airplane mode and in the background. It's my impression that the significant-changes API won't see any change due to never seeing a cell tower shift in this situation.  Is that correct? Would cranking up the accuracy settings force the use of GPS in the plugin as it is built now?  Or if the user is in motion while in foreground and then leaves the app, does there still need to be a significant change?  

Really appreciate the plugin and help!

**Comment by mauron85** [comment]
I believe in airplane mode location services are not available at all.

**Comment by Shane98c** [comment]
After iOS 8.3 GPS is no longer disabled in airplane mode and we've successfully tested geolocation in airplane mode on both Android and iOS with positive results.  I'm just worried about the possibility of the significant changes API not being triggered due to lack of network monitoring and so not triggering the GPS hardware as a result.  Thanks for the thoughts!

**Comment by mauron85** [comment]
@Shane98c Didn't investigated airplane mode, so thank you for update. If you find something regarding significant changes and lack of network, please share it here. Thanks.

**Comment by uzumakinaruto123** [comment]
was testing on ios 9 !  and device was on airplane mode i kept wondering why the plugin-in is not working that freaked me out. saw this issue and figured out the problem :p  so even on ios 9 GPS service seems to be disabled.

**Comment by mauron85** [comment]
@uzumakinaruto123 you're saying actually oposite of @Shane98c ?

**Comment by uzumakinaruto123** [comment]
only this part 

> After iOS 8.3 GPS is no longer disabled in airplane mode

Because when i tested it on ios 9.0 version , no updates were received. After disabling airplane mode , updates were received.

**Comment by mauron85** [comment]
So behaviour has changed in 9.0 back again to prior 8.3?

**Comment by uzumakinaruto123** [comment]
yes i think so based on testing. no documentation source. :p

**Comment by Shane98c** [comment]
This is potentially the problem I was trying to get at with this question.  GPS will continue to work in airplane mode after 8.3, but the problem is that in airplane mode a network change won't be detected to even start the GPS service.  This is a side effect of the significant changes API I suspect.

**Comment by mauron85** [comment]
Can you please try what backgroundGeolocation.isLocationEnabled(success, fail) returns in airplane?

**Comment by mauron85** [comment]
Closing for not receiving any feedback for 2 years.
