### ISSUE TITLE
stopOnTerminate = false does not behave as expected

### ISSUE THREAD

**Issue by angel1st** [mauron85/cordova-plugin-background-geolocation#490]
## Your Environment

* Plugin version: 
3.0.0-alpha.42
* Platform: 
Android 
* OS version: 
7.0.0, 8.0.0
* Device manufacturer and model: 
S8, Redmi Note
* Cordova version (`cordova -v`): 
8.0.0
* Cordova platform version (`cordova platform ls`):
Installed platforms:
android 7.1.0
Available platforms:
browser ~5.0.1
ios ~4.5.4
osx ~4.0.1
windows ~5.0.0
www ^3.12.0
* Plugin configuration options: 
```
{
    locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
    desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY, 
    stationaryRadius: 10,
    distanceFilter: 10,
    notificationTitle: 'App is tracking',
    notificationText: 'enabled',
    debug: false,
    interval: 10000,
    fastestInterval: 5000,
    activitiesInterval: 10000,
    stopOnTerminate: false,
    startOnBoot: false
}
```
* Link to your project:

## Context

When `stopOnTerminate` is set to `false` and the app is closed (by removing it from the **task manager**), its icon stays on device's status bar, which is as it should be.
## Expected Behavior

It is expected, aside of the above, in case the device detects location change outside `distanceFilter` to fire `location` event, hence to track the location.
## Actual Behavior

The `location` event is not fired, hence, the app cannot track the location, after it is being terminated.
## Steps to Reproduce

1. Call `BackgroundGeolocation.configure({stopOnTerminate: false});`
2. Terminate the app (close it from **task manager**) 
3. Change device location and ensure `distanceFilter` is reached
4. The plugin should fire `location` event, but it does not

**Comment by angel1st** [comment]
@mauron85 - could you elaborate on this one as well? I believe it is as important as #486. Thanks!

**Comment by mauron85** [comment]
This is not possible. When app is terminated only service is running, no js callbacks will be fired as main android activity is not present.

**Comment by angel1st** [comment]
@mauron85 - to reprhase my inquiry from the above - if the plugin allegedly continues to work, how it (the plugin) can wakeup / reload the app?

**Comment by mauron85** [comment]
Just run the app. It will bind to running service and start send locations
events again.

**Comment by angel1st** [comment]
@mauron85 - what I need is the plugin to **run** the app instead. Is there a way to "instruct" the plugin to run the app?
On a side question - can we at least count, the plugin continues to collect locations and stores them to its local DB, since it is working?

**Comment by mauron85** [comment]
>what I need is the plugin to run the app instead. Is there a way to "instruct" the plugin to run the app?

not really. it could be done only in very hacky and obtrusive way for the user.
also if you think about it. User kills the app, but since you as developer declared stopOnTerminate false, the main activity will be killed, but location service will still be running collecting locations and if set it could also send them to them server. So why you would want to start an app, which user decided to kill? What for? I don't see any potential use case here.

>On a side question - can we at least count, the plugin continues to collect locations and stores them to its local DB, since it is working?

yes, that's the point.

**Comment by mauron85** [comment]
Event if you are trying to be sneaky and track user even app was killed by, you still can do it. Nothing will stop you with stopOnTerminate false.

**Comment by angel1st** [comment]
Thanks for your answers @mauron85.
To answer your question - the reason behind all my insistent question is one particular use case - I am basically sending locations from my app via socket instead of 'standard' http calls. Hence - when the app is killed, it cannot send locations.
There is nothing related to being sneaky, it is more related to how the locations are send to the outside world actually...
Anyway - now I understand the meaning of this particular flag. I guess `StartOnBoot` flag works on similar fashion - it starts the plugin only on the background, doesn't it?

**Comment by mauron85** [comment]
>I guess StartOnBoot flag works on similar fashion - it starts the plugin only on the background, doesn't it?

well it only starts the service, not the activity so yes, it's similar to state when you kill the app with option stopOnTerminate: false enabled.

**Comment by mauron85** [comment]
Well you can use postTemplate to add userId directly to locations. Or you can https://github.com/mauron85/cordova-plugin-background-geolocation#android-headless-task-experimental, but current implementation is very inefficient.

**Comment by angel1st** [comment]
Yes, this one seems the only viable option (via `postTemplate` setup). Anyway - I believe this issue can be closed, since the plugin seems to work as expected.
@mauron85, I have few other side questions though:

1. Even though HTTP post request succeeds (configured via `option.url` parameter) and the location is deleted it will actually stays into the local DB and will be returned via [getLocations](https://github.com/mauron85/cordova-plugin-background-geolocation#getlocationssuccess-fail) until it is overwritten (`option.maxLocations` is reached)? 
1. It is not quite clear to me the following edge scenario - in case none HTTP post succeeds AND `option.maxLocations` is reached AND `option.syncUrl` is NOT configured, then I guess the plugin will start overwriting its local DB anyway, correct?
1. When `option.maxLocations` is reached, only those locations marked as **deleted** will be overwritten, won't they?
1. Is there a way to retrieve setup options - something opposite to `configure` method? It would be nice to have it (if not present), since it will ease followup configurations.

**Comment by angel1st** [comment]
@mauron85 - I would greatly appreciate your answer on the above questions...or at least on the last one (number 4). Thanks!

**Comment by mauron85** [comment]
Answering your questions:
1. yes, if you need to get only unposted/unsynced location use [getValidLocations](https://github.com/mauron85/cordova-plugin-background-geolocation#getvalidlocationssuccess-fail)

2. yes

3. plugin will overwrite oldest location (not sure if there is any preference over deleted or not without checking source code)

4. yes there is undocumented [getConfig method](https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/www/BackgroundGeolocation.js#L91)

**Comment by angel1st** [comment]
Thanks, mate, I am closing the ticket, then.

**Comment by brucejo75** [comment]
I have another question on this topic.

I ran a test last night with a closed my app and `stopOnTerminate=false` and `interval=5000` and I used a `postTemplate` along with a REST endpoint.

I closed the app at approximately `8:41pm`

In the morning I checked my data and I received updates at these times:
```
8:43
8:48
8:49
8:54
8:56
9:04
```
When I opened the app, My app calls configure and starts the `BackgroundGeolocation` again.  This fired off 3 more location updates.

Is this expected?
1. Shouldn't I expect to see updates as frequent as my interval setting?  e.g. once every 5 seconds.
2. Does `BackgroundGeolocation` detect that the device is sitting still and throttle updates?  And ignore the interval setting?

I am just trying to understand the behavior better.  thanks!

**Comment by mauron85** [comment]
>Shouldn't I expect to see updates as frequent as my interval setting? e.g. once every 5 seconds.

I assume we're talking about Android.  Depends on what provider did you used and what device did you used?

>Does BackgroundGeolocation detect that the device is sitting still and throttle updates? And ignore the interval setting?

again depends on provider used and device used.

For example If you're using activity provider, that interval settings will be ignored when not moving. Same thing with distance filter, if you're stationary then no locations update will be trigerred. Only raw provider will send you location updates constanly every n secs.  

Also some android manufacturers are very aggressive about running app in the background.

**Comment by angel1st** [comment]
@mauron85 - I have questions regarding `interval` and `activitiesInterval` options, when the plugin works w/o application, e.g. the application is either closed (but `stopOnTerminate = false`) OR the application is not started (but `startOnBoot = true`).

1. If I set `interval` to 60 000, does it mean, the minimum time interval in which the plugin might send HTTP post request is 1 minute?
1. If I set `activitiesInterval` to 120 000 (and keep `interval` value from point 1), does it mean the minimum time interval the plugin might send HTTP post request will change to 2 minutes or it will stick to 1 minute?

Thanks in advance for your answers!

**Comment by pserna95** [comment]
For me when I set this config:
`      stopOnTerminate: false,
      startOnBoot: false,
      startForeground: true,
`
My expected behaviour reading the API would be:
1. When the user open the app, background service starts and sends request via HTTP using postTemplate config option.
2. If the app goes to background (user minimizes or sth), the service still running, sending the info to the server (remember we have set url, postTemplate and stuff) and showing up the notification to the user in his notification bar (same behaviour as if the app is in foreground).
3. If the app is killed, the service would still run, sending the info to the backend and displaying the notification.

In my case, 1. and 2. are working like a charm but third point shows the notification to the user however request is not being sent to the server. 

Am I wrong with my explanation or what's going on?

**Comment by brucejo75** [comment]
You are correct, but for #3 to work.  You need to use `url` and let geolocation post directly to your service.  You cannot expect any of the events to fire in your code because it is not running.

**Comment by angel1st** [comment]
@mauron85 - I have one general inquiry regarding correlation between `interval`, `activitiesInterval`, `distanceFilter`, `stationaryRadius`, `provider` parameter and updates send via `url`. I am still trying to figure out how exactly all these work toghether...
Below are my use cases:

#### Provider = ACT
In this scenario `distanceFilter` and `stationaryRadius` are not taken into account. Location updates send via `url` depends on `interval` parameter ONLY. Is that correct?

#### Provider = DIS
In this scenario `distanceFilter` and `stationaryRadius` are taken into account. I am not sure however, when the update via `url` will be send. I can see following cases:
1. When `distanceFilter` is reached. Correct?
1. When `stationaryRadius` is reached. Correct?
1. When `interval` timespan is reached. Correct?

It could be any of the cases above in any combinations. Simple **Yes/No** answer to each of the questions above will be greatly appreciated.

@brucejo75 - if you feel comfortable to answer, based on your own experience, I would also appreciate your feedback as well.

**Comment by mauron85** [comment]
>In this scenario distanceFilter and stationaryRadius are not taken into account. Location updates send via url depends on interval parameter ONLY. Is that correct?

`interval`, `fastestInterval` and `activitiesInterval` are taken into account. but also you must be moving. If you're STILL, then location updates will be paused until you start moving again.

I encourage you to take look in source of particular provider eg. https://github.com/mauron85/background-geolocation-android/blob/6ec6d4f65d0254ab401225dd77c83fa1b4cb7a9a/src/main/java/com/marianhello/bgloc/provider/ActivityRecognitionLocationProvider.java#L105 That's what I also did to answer your question.

>In this scenario distanceFilter and stationaryRadius are taken into account. I am not sure however, when the update via url will be send. I can see following cases

I'm not sure how `distanceFilter` is implemented in Android, but I guess it's just filter that assure that your app will not get locations more often than x milliseconds. This provider adjust this valud of `distanceFilter` based on speed. There is special page written by former author [about distance filter provider](https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/DISTANCE_FILTER_PROVIDER.md).

**Comment by angel1st** [comment]
Thanks, @mauron85 for the above answers. I am aware about [DIS provider](https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/DISTANCE_FILTER_PROVIDER.md) document, but yet, in this particular scenario, I am still not quite sure, if updates are send over `url` depending of `distanceFilter` ONLY or it also takes into an account `interval`. For instance, let's suppose I have, following use case:

- provider = DIS
- interval = 10000 // 10 secs
-  distanceFilter = 500

now, if I am walking slow (i.e. `distanceFilter` won't increase, according to its formula) and I am not able to walk 500 m under 10 seconds, will I have update send over `url` or not?

**Comment by mauron85** [comment]
> or it also takes into an account interval
Yes, it does also take `interval`
https://github.com/mauron85/background-geolocation-android/blob/6ec6d4f65d0254ab401225dd77c83fa1b4cb7a9a/src/main/java/com/tenforwardconsulting/bgloc/DistanceFilterLocationProvider.java#L206

**Comment by mauron85** [comment]
>now, if I am walking slow (i.e. distanceFilter won't increase, according to its formula) and I am not able to walk 500 m under 10 seconds, will I have update send over url or not?

actually this is more question on [android location manager itself](https://developer.android.com/reference/android/location/LocationManager.html#requestLocationUpdates(long,%20float,%20android.location.Criteria,%20android.app.PendingIntent)).

**Comment by angel1st** [comment]
Thanks, @mauron85. The above links were in great help!
Just to have this one documented, this is IMO, the essence, which answers my question above, taken from [Android Location Manager](https://developer.android.com/reference/android/location/LocationManager#requestLocationUpdates(long,%20float,%20android.location.Criteria,%20android.app.PendingIntent) document:

> The `minDistance` parameter can also be used to control the frequency of location updates. If it is greater than 0 then the location provider will only send your application an update when the location has changed by at least `minDistance` meters, AND at least `minTime` milliseconds have passed. 

which basically means, that both criteria - `interval` AND `distanceFilter` has to be met, then, the location update will fire.

**Comment by netbitsolutions** [comment]
> > You are correct, but for #3 to work. You need to use the `url` option and let `BackgroundGeolocation` post directly to your service. You cannot expect any of the events to fire in your code because it is not running.
> 
> I'm using the plugin as you have said:
> 
> ```
> BackgroundGeolocation.configure({
>   locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
>   desiredAccuracy: BackgroundGeolocation.MEDIUM_ACCURACY,
>   stationaryRadius: 30,
>   distanceFilter: 20,
>   interval: 30000, //180000
>   fastestInterval: 20000, //120000,
>   activitiesInterval: 10000,//20000,
>   stopOnTerminate: false,
>   startOnBoot: false,
>   startForeground: true,
>   maxLocations: 2000,
>   stopOnStillActivity: false,
>   url: url + paraID,
>   httpHeaders: header,
>   postTemplate: {
>     'f_latitude': '@latitude',
>     'f_longitude': '@longitude',
>     'f_accuracy': '@accuracy'
>   },
> });
> ```
> I've tried setting the url, header and paraID manually instead of binded inside variables but that's not the problem. My server is still not receiving the request

Ensure you have the approrate  Access-control headers set  to accept Json request

**Comment by pserna95** [comment]
> > > You are correct, but for #3 to work. You need to use the `url` option and let `BackgroundGeolocation` post directly to your service. You cannot expect any of the events to fire in your code because it is not running.
> > 
> > 
> > I'm using the plugin as you have said:
> > ```
> > BackgroundGeolocation.configure({
> >   locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
> >   desiredAccuracy: BackgroundGeolocation.MEDIUM_ACCURACY,
> >   stationaryRadius: 30,
> >   distanceFilter: 20,
> >   interval: 30000, //180000
> >   fastestInterval: 20000, //120000,
> >   activitiesInterval: 10000,//20000,
> >   stopOnTerminate: false,
> >   startOnBoot: false,
> >   startForeground: true,
> >   maxLocations: 2000,
> >   stopOnStillActivity: false,
> >   url: url + paraID,
> >   httpHeaders: header,
> >   postTemplate: {
> >     'f_latitude': '@latitude',
> >     'f_longitude': '@longitude',
> >     'f_accuracy': '@accuracy'
> >   },
> > });
> > ```
> > I've tried setting the url, header and paraID manually instead of binded inside variables but that's not the problem. My server is still not receiving the request
> 
> Ensure you have the approrate Access-control headers set to accept Json request

The problem is already solved. I had a conflict with firebase-plugin which terminates the app when it is destroyed so updating this plugin to its latest version solved my issue :)
