### ISSUE TITLE
Application crashes when BackgroundGeolocation.start is called

### ISSUE THREAD

**Issue by iamjoyce** [mauron85/cordova-plugin-background-geolocation#491]
## Your Environment

* Plugin version: 3.0.0-alpha.43
* Platform: Android
* OS version: 8.1.0
* Device manufacturer and model: OnePlus 5t
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): android 7.1.1
* Plugin configuration options: 
```
{
    desiredAccuracy: 0,
    distanceFilter: 10,
    stationaryRadius: 25,
    debug: true,
    activitiesInterval: 10000,
    stopOnTerminate: false,
    startOnBoot: true,
    startForeground: true,
    fastestInterval: 5000,
    url: 'http://localhost/api',
    syncThreshold: 5000,
    maxLocations: 10000,
}
```

## Context

Possibly related to these issues - #429, #459

When `BackgroundGeolocation.start()` is called, the application will crash _**if**_ the application hasn't got location permission.

## Expected Behavior

1. `BackgroundGeolocation.start()`
1. Check if has permission
    - If yes, continue.
    - *If no, prompt user for permission.
1. Check if user allow
    - If yes, start tracking.
    - *If no, emit event to notify, but still allow user to use application.

\* = Application will crash, i.e., `(Application name) has stopped` dialog will appear

## Actual Behavior

1. ` BackgroundGeolocation.start()`
1. Application crashes + Application prompts user for permission

**If user accepts location permission request,**

1. Restart application
1. `BackgroundGeolocation.start()`
1. Plugins starts tracking, and application can be used as-per-normal.

**If user rejects location permission request,**

1. Restart application
1. `BackgroundGeolocation.start()`
1. Application crashes again

## Possible Fix

Another plugin had a similar problem

[https://github.com/katzer/cordova-plugin-background-mode/pull/389](https://github.com/katzer/cordova-plugin-background-mode/pull/389)

## Context

I need to use v3 instead of v2 (stable) because of `postTemplate` feature.

## Debug logs

```
10-04 09:27:54.833 15121 15121 E AndroidRuntime: FATAL EXCEPTION: main
10-04 09:27:54.833 15121 15121 E AndroidRuntime: Process: (package name), PID: 15121
10-04 09:27:54.833 15121 15121 E AndroidRuntime: android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=-2 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 vis=PRIVATE)
10-04 09:27:54.833 15121 15121 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1867)
10-04 09:27:54.833 15121 15121 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
10-04 09:27:54.833 15121 15121 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
10-04 09:27:54.833 15121 15121 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6753)
10-04 09:27:54.833 15121 15121 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-04 09:27:54.833 15121 15121 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
10-04 09:27:54.833 15121 15121 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by mauron85** [comment]
Please post few line before the exception. From your logs it's not sure which line caused the exception.

**Comment by iamjoyce** [comment]
@mauron85 So sorry 😓, just realised it was caused by another plugin (`cordova-plugin-background-mode`). I was using old codes (but previously workable) to test with this plugin, so I thought the crashes were caused by this plugin.

**Comment by mauron85** [comment]
No problem. It was strange to me anyway, because plugin was adjusted to work with NotificationChannels introduced in Oreo.

**Comment by coyu1314** [comment]
I am having the same issue when I call BackgroundGeolocation.start() in my ionic-v4 angular app. Any idea how to fix it? thanks
plugin v2.3.6
cordova: 7.1.4
