### ISSUE TITLE
syncUrl locations are not deleted after posting.

### ISSUE THREAD

**Issue by Adam4224** [mauron85/cordova-plugin-background-geolocation#492]
## Your Environment

* Plugin version: 2.3.6 (latest stable)
* Platform: Android
* OS version: 8.1.0
* Device manufacturer and model: OnePlus 5t
* Cordova version (`cordova -v`): 8.1.1
* Cordova platform version (`cordova platform ls`): android 7.1.1
* Plugin configuration options: 
const config : BackgroundGeolocationConfig = {
                desiredAccuracy: 0,
                stationaryRadius: 5,
                distanceFilter: 5,
                locationProvider: 0,
                stopOnTerminate: true,
                startForeground: false,
                startOnBoot: true,
                notificationTitle: "Tracking",
                notificationText: "Tracking Location",
                interval: 20000,
                pauseLocationUpdates: false,
                fastestInterval: 20000,
                activitiesInterval: 20000,
                stopOnStillActivity: false,
                url: ApiDefinition.postLocation.getUrl() + "?teamId=" + teamId + "&deviceId=" + deviceId,
                syncUrl: ApiDefinition.postLocationBatch.getUrl(),
                syncThreshold: 5
            };
* Link to your project:

## Context
When providing a sync URL, the server gets overlapping posts with each new location recorded. This is a major issue, because it pwns the data of the client device quadratically.

## Expected Behavior
After a successful post to syncUrl, the locations should be marked as deleted, and not re-posted to the syncUrl

## Actual Behavior
Each additional location adds one record to the records posted to syncUrl, regardless of whether the call to url succeeds or fails.

## Possible Fix
I have no idea. It could just be that the requirements on the server for url and syncUrl haven't been documented, so I'm doing something wrong on that side. Here is my debug server code (ASP.net Web Api):

url:
```
[HttpPost]
[AllowAnonymous]
[ApiReadOnlyTransaction]
[ApiLogAccess]
[Route(nameof(PostLocation))]
public void PostLocation([FromUri] string teamId, [FromUri] string deviceId)
{
    Trace.WriteLine($"TeamId: {teamId}, DeviceId: {deviceId}");

    var raw = Request.Content.ReadAsStringAsync().Result;
    var result = JsonConvert.DeserializeObject<LocationRequest[]>(raw);
    if (result != null)
    {
        foreach (var elem in result)
        {
            Trace.WriteLine(elem);
        }
    }
}
```

And syncUrl:

```
[HttpPost]
[AllowAnonymous]
[ApiReadOnlyTransaction]
[ApiLogAccess]
[Route(nameof(PostLocationBatch))]
public void PostLocationBatch()
{
    var raw = Request.Content.ReadAsStringAsync().Result;
    var result = JsonConvert.DeserializeObject<LocationRequest[]>(raw);
    if (result != null)
    {
        foreach (var elem in result)
        {
            Trace.WriteLine(elem);
        }
    }
}
```

## Steps to Reproduce

1. Supply a url and a syncUrl
2. Observe that syncUrl is called and that locations are never deleted or retired.

## Context
Commercial services marketplace app (new version) with automated check-in/check-out. I cannot use 3-alpha because it requires updating ionic to alpha (which is not stable at the moment).

## Debug logs
None

**Comment by mauron85** [comment]
Are you returning 2xx header in response from the server?

**Comment by Adam4224** [comment]
Returning 200 from the same server method appears to result in the locations being deleted. So I think it was the return code, but I think you should document that a return code of OK - 200 is required, or fix is so that 2xx works.

I can close and submit a new issue if you like.

**Comment by mauron85** [comment]
I thought it's obvious that server should return 2xx success code on success, but agree that's it's could be mentioned in the docs. Will you prepare PR for that?

**Comment by Adam4224** [comment]
Hi,

2xx doesn't work. You must return 200.

**Comment by mauron85** [comment]
Yes, on version 2.3.6 only 200 header is supported. Closing as resolved.
