### ISSUE TITLE
android location not fetching while screen is off

### ISSUE THREAD

**Issue by kzsense** [mauron85/cordova-plugin-background-geolocation#497]
Hi, I am using plugin version 3.0.0-alpha41. It looks like the location fetching on android is not working while screen is off. I upgraded the version from 2.3.5 to 3.0.0, whereas 2.3.5 works fine but 3.0.0 not working as expected.

more details:
1. I tried all the providers, distance_filter is the only one works okay except it didn't fetching data when screen is off.
2. my configs :
        let config = {
            locationProvider: 0,
            desiredAccuracy: 100,
            stationaryRadius: 1,
            distanceFilter: 1, 
            debug: true,

            // Android only
            interval: 2000,
            fastestInterval: 2000,
            startForeground: true,

            notificationTitle: 'Background tracking',
            notificationText: 'enabled',
        };

Can someone help please and thank you...

**Comment by narigondelsiglo** [comment]
Are you calling `BackgroundGeolocation.start()` to launch background job?

**Comment by kzsense** [comment]
> Are you calling `BackgroundGeolocation.start()` to launch background job?

All I did is following the example wrote by author.

`function onDeviceReady() {
  BackgroundGeolocation.configure({
    locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
    desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
    stationaryRadius: 50,
 ...

BackgroundGeolocation.start();
}
`

And I invoke this method in ngOnInit() since I am using angular.

**Comment by rodrigoords** [comment]
Same problem here, when I put my app in the background the location update work fine, but when I put screen off after about 1 minute app stop to send post requests.

With debug logs i check that problem is network connection:

I/com.marianhello.bgloc.LocationService: Network condition changed has connectivity: false
D/libc-netbsd: [getaddrinfo]: mtk netid=0; mark=0
    getaddrinfo( app_uid:10236
    getaddrinfo() uid prop:
    getaddrinfo() getuid():10236
    [getaddrinfo]: mtk ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0
D/libc-netbsd: getaddrinfo: get result from proxy gai_error = 7

I don't know if I need to handle this behavior my self.

@mauron85 can you help in this problem?

**Comment by wrunkel** [comment]
Hey guys,

i hade the same problem. I am using currently v. 2.3.6 and the backgroundGeolocation didn't work when the display of the Android device was locked. So I changed my device settings and turned of the lock screen, and after that, the tracking worked. But now I have the problem that if the app is in background and another app i.e. (Audible, chrome) was active that the background Tracking would still stop :-(

This is just my latest experience maybe that can help you guys

**Comment by AleRohvt** [comment]
> Hi, I am using plugin version 3.0.0-alpha41. It looks like the location fetching on android is not working while screen is off. I upgraded the version from 2.3.5 to 3.0.0, whereas 2.3.5 works fine but 3.0.0 not working as expected.
> 
> more details:
> 
> 1. I tried all the providers, distance_filter is the only one works okay except it didn't fetching data when screen is off.
> 2. my configs :
>    let config = {
>    locationProvider: 0,
>    desiredAccuracy: 100,
>    stationaryRadius: 1,
>    distanceFilter: 1,
>    debug: true,
>    ```
>         // Android only
>         interval: 2000,
>         fastestInterval: 2000,
>         startForeground: true,
>    
>         notificationTitle: 'Background tracking',
>         notificationText: 'enabled',
>     };
>    ```
> 
> Can someone help please and thank you...

I have the same problem too.
