### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by jacorrea** [mauron85/cordova-plugin-background-geolocation#5]
Hello, first thank you for your work. I have no way to contact you or I don't know how, so I put it here, then you erase if you like. I am using your plugin and would like to make a donation, small at this moment, but I would do it on a regular basis as I am developing the application will generate revenue. You can tell me how I could do this?

Thanks again for your effort.

**Comment by mauron85** [comment]
Even I like the idea of having money out this :-). It wouldn't be right. 
All credit should go to christocracy (creator) and other guys (codebling, erikkemperman, huttj), who worked and contributed.

My plan is to maintain and further develop this plugin. And also it be free for everybody.

If you there is some functionality I can implement it the future, we can reopen this issue again :-).
