### ISSUE TITLE
App crash after one day

### ISSUE THREAD

**Issue by frankzhangxd** [mauron85/cordova-plugin-background-geolocation#501]
## Your Environment

* Plugin version: 3.0
* Platform: iOS 
* OS version:12.0.1
* Device manufacturer and model: iPhone 8

* Running in Simulator:
* Cordova version (`cordova -v`): 7.0.0
* Cordova platform version (`cordova platform ls`): cli-8.0.0
* Plugin configuration options: 
`BackgroundGeolocation.configure({
            locationProvider: BackgroundGeolocation.RAW_PROVIDER,
            desiredAccuracy: BackgroundGeolocation.MEDIUM_ACCURACY,
            stationaryRadius: 100,
            distanceFilter: 1000,
            debug: true,
            url: serviceURL + 'geotrack',
            stopOnTerminate: false,
            saveBatteryOnBackground: true, 
            postTemplate: {
              lat: '@latitude',
              lng: '@longitude',
              listid: localStorage.listid // you can also add your own properties
            }
        });`
* Link to your project:
https://github.com/frankzhangxd/logmein

## Context

I built it at https://build.phonegap.com and installed on my iPhone, which works fine, I can see notification on my phone and receive updates on the server. at the beginning, it send geo location whenever I move over certain distance, everything looks perfect.

However,  it always crash after app runs over one day. I have to uninstall the app and reinstall it, then it works for another one day.
## Expected Behavior

keep running
## Actual Behavior

crash after one more day
## Steps to Reproduce

1. see source code at https://github.com/frankzhangxd/logmein
2.
3.
4.

## Context

expect app updates geo location whenever moving

**Comment by mauron85** [comment]
Hey frank. I would need crash log or error message at least.

**Comment by mauron85** [comment]
You can attach phone to computer. And check plugin logs from Safari javascript console:

```
BackgroundGeolocation.getLogEntries(10000, 0, 'ERROR, function(errors) {
console.log(errors);
});
```

Maybe error will be logged there

**Comment by frankzhangxd** [comment]
Thanks, I just reinstall my app and wait for one day when it crash :(

**Comment by frankzhangxd** [comment]
The app crash again and I run the script but nothing return back, it says undefined,  I can see the debug info if I change ERROR to DEBUG. Any ideas?

**Comment by frankzhangxd** [comment]
I notice that it looks like not crash but just send to background and can't bring to foreground

**Comment by frankzhangxd** [comment]
Hi mauron85,

any luck?
