### ISSUE TITLE
Feature Request: Headless task configure options

### ISSUE THREAD

**Issue by brucejo75** [mauron85/cordova-plugin-background-geolocation#502]
With the headless task you have this caution:
> Keep in mind that the callback function lives in an isolated scope. Variables from a higher scope cannot be referenced!

So I need to use some variables in my headless task.  My variables are known at configure time.  So I was thinking that maybe `BackgroundGeolocation.configure()` could accept another parameter, e.g.:

```javascript
headlessParams: {<any object data you want to send>}
```

Then in the `headlessTask` callback you could extend the event with `headlessParams`.  Then I would have access to my initialization parameters.

## My problem I want to solve
Essentially, I want to suspend updates for a period of time.  The time period is configurable by the end user.

I am building this application for businesses that have a mobile workforce.  My clients has requested that location updates only occur during workday time periods.  Then battery will be saved and only workday data would be produced.

My plan was to intercept a `location` event and determine if the event is outside of the running window. If it is then I would:
1. Shut down the location updates with a `BackgroundGeolocation.stop()`... (`this.stop()`?)
2. Set up a timer to fire at the end of the blackout window.
3. When the timer fires call `BackgroundGeolocation.start()` ... (`this.start()`?)

this is predicated on having access to `BackgroundGeolocation` when processing my events, maybe via `this`.  Which may not be true?

Thanks for any help/advice?

## Your Environment

* Plugin version: v3.0.0-alpha.47
* Platform: Android
* OS version: v7.1.1
* Device manufacturer and model: not applicable

* Running in Simulator: no
* Cordova version (`cordova -v`):6.4.0
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mauron85** [comment]
I understand you're currently prototyping and looking for solution that works best. Don't take following as advice how to implement your solution. Just answers to your questions.

>So I need to use some variables in my headless task. My variables are known at configure time. 

If variables are known at configure time, why not include them in constant:

```
BackgroundGeolocation.headlessTask(function(event) {
  var myVariables = {};
  // handle event ...
});

Remark: Keep in ming that headless task is very inefficient, because it has to initialise webview every time new location event arise. There are very few use cases that it make sense to use it. 

Just in short. Normally when app was not killed, you don't headless task whatsoever as you're receiving registered events directly in your app (no matter background or foreground). Let's imagine user killed app and you set the location service to keep running (stopTerminate: false).
You can now use headless task, but what for? User expressed he is not interested in running your app, so the question is what can you actually do with those locations update? You can't render them in app (like on map), because there is no app running (only service). What else? You can send them to server or store them for later use, when user starts app again. And that's exactly what plugin is already doing, without the need for headless task.

So I would like to hear from you, what it your use case for headless task.

**Comment by mauron85** [comment]
> 2. Set up a timer to fire at the end of the blackout window.

In theory yes, you can mimmic job scheduler in this way. In practice I would be careful, how reliable it will be. 

Also keep in mind app must be running. You can't start plugin from headless task as you don't have access to BackgroundGeolocation (or any other) plugin in headless task. I will probably work on mitigating this limitation, but it will take some time.

**Comment by brucejo75** [comment]
Hi @mauron85, thanks for your prompt response!

Indeed, [cordova-background-geolocation-lt](https://github.com/transistorsoft/cordova-background-geolocation-lt) looks like it has all the features I need.  I will need to think about how I proceed.  Thanks for the tip.

### My Use Scenario
I am working with a landscaping company.  Their "crew leads":
1. Get their tablet from the work shed in the morning.
2. Keep the tablet in the truck as they move from work site to work site during the day.
3. Return the tablet to the work shed in the evening.

The business owners want to track their time at each work location so that they can "true up" the amount they charge customers.  They do not charge by the hour, but they think that they have some wide differences between the amount they receive from customers and the amount of work performed at their locations.

They also want some data to support disputes.  They sometimes get complaints that their crews are only on site for 10 minutes, when the team believes they were scheduled to spend 45 minutes at the location.  The sounds of lawnmowers is not always an indication of the amount time they spend at a location.

In order to save the battery and save the work life of the tablet it is important for my customers that the tablets are using the least amount of battery while sitting in the work shed.

Users have so far been capable of pretty much doing everything and anything on the tablets.  But mostly they forget things.  Asking them to turn on applications or turn off tablets has been challenging.

So I use `stopOnTerminate=false` and assume I will be able to continue to send location data to the server via the POST requests.  But when it is on the shelf, I just want to turn it off.

### Scheduling
It looks like this constraint:
>Also keep in mind, that app must be running. You can't start plugin from headless task as you don't have access to BackgroundGeolocation (or any other) plugin in headless task. I will probably work on mitigating this limitation, but it will take some time.

Will keep me from implementing my own scheduler from within the headless task, as I cannot control the application state.

### Feedback
I still think the concept of sending variables via configure to the headless task can be useful.

Regarding:
>if variables are known at configure time, why not include them in constant:
>```javascript
>BackgroundGeolocation.headlessTask(function(event) {
>  var myVariables = {};
>  // handle event ...
>});
>```

I think this implies that I know the variables at coding time which I do not.  Here is what I would need to do:

```javascript
var myVariables = {stopTime: xxx, startTime:yyy};
BackgroundGeolocation.headlessTask(function(event) {
  // Use My variables
  if(myVariables.stopTime > currentTime && currentTime < myVariables.startTime) {
    BackgroundGeolocation.stop();
    //setup timer, etc...
  }
  // handle event ...
});
```

Which implies that closure variables are available which I am not sure they are.  (I will have to try)
