### ISSUE TITLE
forceSync does not call success nor failure callback

### ISSUE THREAD

**Issue by tlajer** [mauron85/cordova-plugin-background-geolocation#504]
## Your Environment

* Plugin version: 3.0.0-alpha.47
* Platform: Android
* OS version: 8.0
* Device manufacturer and model:

* Running in Simulator: Yes
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): 6.4.0
* Plugin configuration options: 			{ locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
			desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
			stationaryRadius: 50,
			distanceFilter: 50,
			notificationTitle: "Kørebog (GPS Tracking, UPDATE 2.0)",
			notificationText: "aktiveret",
			stopOnStillActivity: false,
			startForeground: true,
			startOnBoot: true,
			pauseLocationUpdates: false,
			debug: false,
			url: "https://mydomain.com/modules/mileage/index.php",
			syncUrl: "https://mydomain.com/modules/mileage/index.php?syncUrl=true",
			postTemplate: {
				latitude: '@latitude',
				longitude: '@longitude',
				accuracy: '@accuracy',
				time: '@time',
				mileage_id: localStorage.getObject("mileage").mileage_id
			} }

## Context

I'm tracking the user, when the user drives in a car. When the user stops the tracking, I want to make sure, that ALL locations has been sent to the server.

To achive this, I call BackgroundGeolocation.forceSync, after checking uf there are rows available in getValidLocations.

The forceSync call works fine. It forces all locations to be sent with no issue. However, no callbacks are made to either success or error.

## Expected Behavior

Was expecting either success or failure callback to be called.

## Actual Behavior

Nothing...

## Steps to Reproduce

1. Load GPX to simulator and run it
2. Run BackgroundGeolocation.start() via console
3. Enable flight mode for a minute or two (just make sure, that new locations are recorded, and not sent to the server)
4. Disable flight mode
5. Run: BackgroundGeolocation.forceSync(function() {
					alert("SUCCESS!");
				}, function () {
					alert("FAILURE");
				});
6. Wonder why neither alert is being called

## Context

Full production stop. I can't release the app without a fix for this.

**Comment by mauron85** [comment]
Thank you for the report. Docs are misleading. There are no callbacks. It's not even possible, as sync job usually live in separate process (at least on android) and totally in control of the system.

**Comment by tlajer** [comment]
Hi Mauron85,

Thank you for looking into this.

How do you propose, that I make sure that all locations are in sync with the server then?

My thoughts so, is to forceSync(), and then wait 3 seconds and check if getValidLocations() has any records. If not, everything must be in sync. I would create this as an recursive method.

Would work in theory. But, lets be honest - thats not the prettiest of solutions.

Do you have any other ideas?

It's seems to me, that making sure that everything is in sync at any given time, would be a standard use case.

Thanks in advance.

**Comment by mauron85** [comment]
Well, locations will be eventually synced when there is network connection.
If you think about it, even if there is error callback, how it will help?
What else can you do? Call forceSync again wouldn’t help in that case.
Plugin will automatically retry to send locations autimatically.

**Comment by mauron85** [comment]
And actually it's better to leave plugin to manage location syncing. It will do it in battery saving fashion.

**Comment by tlajer** [comment]
An enterprise level version of the plugin might be interesting for us in the near future though.

We are on a tight schedule on this one, so for now, we will do something similar to this... In theory, it should work - although, its quite ugly.

// Pseudo code
function finishTrip()
{
	BackgroundGeolocation.getValidLocations(function (locations) {

		if (locations.length > 0) {
			BackgroundGeolocation.forceSync();

			// Recall check, to see if everything is in sync in 2.5 seconds...
			setTimeout(finishTrip, 2500);
		}
		else {

			// TODO: Finish the trip

		}

	}, function () {
		//	TODO: Handle error from getValidLocations
	});
}

**Comment by mauron85** [comment]
Well what can I say. It’s terrible hack, but understand your motivation.
(No offence)

**Comment by tlajer** [comment]
None taken. I would have prefered a succes callback in the first case ;-)

Thank you for your time. I will look forward to an enterprise version of this plugin.
