### ISSUE TITLE
Android: After 5 min requests are not sending. They are in pending status

### ISSUE THREAD

**Issue by goinnn** [mauron85/cordova-plugin-background-geolocation#505]
Android: After 5 min requests are not sending. They are in pending status. And when the app come to foregorund they are completed

## Your Environment
* Plugin version: 2.3.6
* Platform: Android 6.3.0
* OS version: Android 5.1, Android 6.0, Android 8.1.0
* Device manufacturer and model: Nexus 5, Sony Xperia, Nexus 5X
* UserAgent example: "Mozilla/5.0 (Linux; Android 8.1.0; Nexus 5X Build/OPM7.181005.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/70.0.3538.80 Mobile Safari/537.36".
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): Installed platforms: android 6.3.0
* Plugin configuration options: 

    desiredAccuracy: this.backgroundGeolocation.Accuracy.HIGH,
    stationaryRadius: 10,
    interval: 15 * 1000,
    fastestInterval: this.JUP.TIME_UPDATE_POSITION * 1000,
    distanceFilter: 30,
    stopOnStillActivity: false,
    debug: false,
   locationProvider: this.backgroundGeolocation.LocationProvider.ANDROID_ACTIVITY_PROVIDER,
   notificationTitle: "XXXX",
   notificationText: "YYY",
   notificationIconSmall: "icon",
   notificationIconLarge: "icon"

* Link to your project: Private

## Context
I think it is very related with this chrome feature:
https://www.xda-developers.com/google-chrome-android-stop-background-tabs/

I think it is very related with this too:
https://github.com/WICG/page-lifecycle

I think is very important the userAgent "Chrome/70", 2-3 month ago our app worked perfectly. And we don't change anything. I think the problem is Chrome was updated.

## Expected Behavior
After 5 minutes requests are sending to backend.

## Actual Behavior
After 5 minutes requests are not sending to backend.

## Steps to Reproduce
1. Enable background geolocation
2. Put your application in background. And every 15-30 seconds send the position to the backend
3. Wait exactly 5 minutes
4. Every next request will be in pending status. Like in the image. ![pending](https://user-images.githubusercontent.com/1101467/48140696-9ad80980-e2a9-11e8-95da-ae68bd56ce11.png)
5. Wait 1 minute or 1 hour
6. Put your application in foreground. Every request will complete in this moment. 

## Context
We have a little DDoS attacks. Sometimes 2000 - 5000 requests per minute.

## Debug logs
Nothing

**Comment by mauron85** [comment]
First I can only recommend to try to use 3.x branch.

Second use plugins internal http location posting and you should be fine.

>I think it is very related with this chrome feature:...

yes, seems like it

**Comment by goinnn** [comment]
@mauron85 thanks for your quickly response.

> First I can only recommend to try to use 3.x branch.

I use the last stable version. But I think in 3.x branch will be the same problem. Currently 3.x is alpha version, isn't it?

> Second use plugins internal http location posting and you should be fine.

I'm sorry I don't understand it. Do you recomend me change my configuration like something like this?

**url: URL_BACKEND**,
desiredAccuracy: this.backgroundGeolocation.Accuracy.HIGH,
stationaryRadius: 10,
interval: 15 * 1000,
fastestInterval: this.JUP.TIME_UPDATE_POSITION * 1000,
distanceFilter: 30,
stopOnStillActivity: false,
debug: false,
locationProvider: this.backgroundGeolocation.LocationProvider.ANDROID_ACTIVITY_PROVIDER,
notificationTitle: "XXXX",
notificationText: "YYY",
notificationIconSmall: "icon",
notificationIconLarge: "icon"

I think I tested it today and I think I got the same error. But I can test it tomorrow and I confirm it.

If I get the same error always, Will you try to solve it?

**Comment by goinnn** [comment]
@mauron85 Thanks. Doing the requests with native part works right. I have used this plugin:

https://ionicframework.com/docs/native/http/

Feel free to add a comment in documentation about this problem, or if you want reopen this issue.

Thank another time!
