### ISSUE TITLE
Module cordova-plugin-mauron85-background-geolocation.BackgroundGeolocation does not exist

### ISSUE THREAD

**Issue by globules-io** [mauron85/cordova-plugin-background-geolocation#507]
## Your Environment
* Plugin version: 3.0.0-alpha.47
```
   <plugin name="cordova-plugin-mauron85-background-geolocation" spec="^3.0.0-alpha.47">
        <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="15+" />
        <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="26+" />
        <variable name="ICON" value="@mipmap/icon" />
        <variable name="SMALL_ICON" value="@mipmap/icon" />
        <variable name="ALWAYS_USAGE_DESCRIPTION" value="This app always requires location tracking" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="This app requires motion detection" />
    </plugin>
```
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`):   android@7.1.2  ios@4.5.5
* Plugin configuration options: 
```
BackgroundGeolocation.configure({
                locationProvider:BackgroundGeolocation.ACTIVITY_PROVIDER,
                desiredAccuracy:BackgroundGeolocation.HIGH_ACCURACY,
                stationaryRadius:50,
                distanceFilter:50,
                notificationTitle:'Background tracking',
                notificationText:'enabled',
                debug: true,
                interval: 10000,
                fastestInterval: 5000,
                activitiesInterval: 10000,
                url: url,    
                httpHeaders: {
                    'Content-Type': 'application/json'
                },            
                // customize post properties
                postTemplate: {    
                    data:{                
                        lat:'@latitude',
                        lng:'@longitude',
                    },
                    service:'track',
                    access_token:access_token
                }
 });
```
## Actual Behavior

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
cordova.js:1462 Uncaught Error: Module cordova-plugin-mauron85-background-geolocation.BackgroundGeolocation does not exist.
    at addEntry (cordova.js:1462)
    at Object.exports.clobbers (cordova.js:1472)
    at onScriptLoadingComplete (cordova.js:1883)
    at scriptLoadedCallback (cordova.js:1916)
    at HTMLScriptElement.<anonymous> (cordova.js:1870)
```

## Steps to Reproduce

1.  install @lastest 
2.  test

**Comment by globules-io** [comment]
It works with android@7.1.1 though

**Comment by mauron85** [comment]
Does it compile normally? Did you try to observe console log in Chrome? Or any adb logs or plugin logs?

https://developers.google.com/web/tools/chrome-devtools/remote-debugging/

**Comment by globules-io** [comment]
yup it compiled fine just like 7.1.1. No futher error than the one I posted in chrome debug.

**Comment by mauron85** [comment]
Ok, will try to replicate your issue on 7.1.2

**Comment by mauron85** [comment]
Can't reproduce on 7.1.2. Any chance you installed 2.x branch instead of 3?
If you invoke:
```
cordova plugin add cordova-plugin-mauron85-background-geolocation
```
it will install 2.x version by default, which doesn't have BackgroundGeolocation (but backgroundGeolocation - lower case b) object exported, thus that error you have.

I've changed install instructions to:
```
cordova plugin add cordova-plugin-mauron85-background-geolocation@alpha
```
which will install 3.x version.

Only explanation I have is that maybe you installed 2.x then upgraded to 3.x via package.json/config.xml and downgraded the android platform to 7.1.1, which installed 3.x branch automatically. Keep in mind if you change versions in package.json or config.xml you have to manualy remove add readd plugin or whole platform.

**Comment by globules-io** [comment]
Weird, I can try later to update to 7.1.2 again. Maybe it was related to Cordova and not this plugin...

**Comment by mauron85** [comment]
@latest is ok too

**Comment by pserna95** [comment]
I had the same problem then removed the plugin, added again with @alpha (which installed me) the alpha.47 version and now I have another problem.

`Ionic Native: tried calling BackgroundGeolocation.start, but the BackgroundGeolocation plugin is not installed.
Install the BackgroundGeolocation plugin: 'ionic cordova plugin add cordova-plugin-mauron85-background-geolocation'`

I don't know what's going on

**Comment by globules-io** [comment]
Well my guess is Cordova messed up when I upgraded from 2 to 3...
