### ISSUE TITLE
Could not find play-services-tasks-license.aar or play-services-basement.aar / com.google.android.gms:play-services-basement

### ISSUE THREAD

**Issue by patrickbussmann** [mauron85/cordova-plugin-background-geolocation#509]
## Your Environment
* Plugin version: Tested 2.3.6 and 3.0.0-alpha.47
* Platform: Android
* Cordova version (`cordova -v`): 8.0.0
* Plugin configuration options: Tested with `none` and ` --variable GOOGLE_PLAY_SERVICES_VERSION=11+ --variable ANDROID_SUPPORT_LIBRARY_VERSION=23+ --variable ALWAYS_USAGE_DESCRIPTION="App requires ..." --variable MOTION_USAGE_DESCRIPTION="App requires motion detection"`
* Link to your project: https://github.com/patrickbussmann/cordova-plugin-background-geolocation-bug-example

## Context
With this plugin installed the compiling process can't find the `com.google.android.gms:play-services-basement` things. Like `play-services-basement.aar` or `play-services-tasks-license.aar`. (depends on the ANDROID_SUPPORT_LIBRARY_VERSION with 23+ and none specified)

## Expected Behavior
No error in build process.

## Actual Behavior
I get a build error.

```
:app:preReleaseBuild FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Could not resolve all files for configuration ':app:releaseCompileClasspath'.
> Could not find play-services-tasks-license.aar (com.google.android.gms:play-services-tasks-license:11.8.0).
  Searched in the following locations:
      https://jcenter.bintray.com/com/google/android/gms/play-services-tasks-license/11.8.0/play-services-tasks-license-11.8.0.aar
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 58s
14 actionable tasks: 14 executed
(node:4061) UnhandledPromiseRejectionWarning: Error: /bitrise/src/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
FAILURE: Build failed with an exception.
* What went wrong:
Could not resolve all files for configuration ':app:releaseCompileClasspath'.
> Could not find play-services-tasks-license.aar (com.google.android.gms:play-services-tasks-license:11.8.0).
  Searched in the following locations:
      https://jcenter.bintray.com/com/google/android/gms/play-services-tasks-license/11.8.0/play-services-tasks-license-11.8.0.aar
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 58s
    at ChildProcess.whenDone (/bitrise/src/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:4061) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4061) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Possible Fix
Don't use the plugin 😭 

## Steps to Reproduce
1. `$ git clone https://github.com/patrickbussmann/cordova-plugin-background-geolocation-bug-example.git`
2. `$ npm install`
3. `$ ionic "cordova" "platform" "add" "android"`
4. `$ ionic "cordova" "build" "--release" "--emulator" "android"`

## Context
I wanted to use this plugin.

See log file attached.
[7c7526d86167b479.log](https://github.com/mauron85/cordova-plugin-background-geolocation/files/2576950/7c7526d86167b479.log)
[f65bcc1481fcfd66.log](https://github.com/mauron85/cordova-plugin-background-geolocation/files/2576951/f65bcc1481fcfd66.log)

**Comment by mauron85** [comment]
I think you need to update your platform to 7.1.2 https://cordova.apache.org/announcements/2018/11/07/cordova-android-7.1.2.html

Specialy CB-14127: Always put the Google repo above jcenter is what affects you.

**Comment by patrickbussmann** [comment]
Yes thank you very much @mauron85.
The funny thing is that in my original project `config.xml` I had this.

    <engine name="android" spec="7.1.2" />

And in Bitrise it uses `latest` which seems to be 7.1.1 or something like that.
Interesting!

Now it works!
Thanks! 🎉
