### ISSUE TITLE
iOS Background Tracking Indicator flickers 2-3 times before fading and not tracking in background

### ISSUE THREAD

**Issue by willmero** [mauron85/cordova-plugin-background-geolocation#510]
## Your Environment

* Plugin version: 3.0.0-alpha.47
* Platform: iOS
* OS version: 12.1
* Device manufacturer and model: Apple, iPhone X

* Running in Simulator: No
* Cordova version (`cordova -v`): 8.1.1
* Cordova platform version (`cordova platform ls`): ios 4.5.5
* Plugin configuration options: 
`locationProvider        : BackgroundGeolocation.ACTIVITY_PROVIDER,
					    desiredAccuracy         : BackgroundGeolocation.HIGH_ACCURACY,
					    stationaryRadius        : 50,
					    distanceFilter          : 50,
					    debug                   : false,
					    interval                : 10000,
					    fastestInterval         : 5000,
					    activitiesInterval      : 10000,
					    saveBatteryOnBackground : false,
					    stopOnStillActivity     : false,
					    stopOnTerminate         : false,
					    url                     : '/location',
					    httpHeaders             : {
					      Authorization : `Bearer ${idToken}`,
					    },
					    // customize post properties
					    postTemplate : {
					      latitude  : '@latitude',
					      longitude : '@longitude',
					      time      : '@time',
					    },`
* Link to your project:
N/A App in development

## Context

The blue location tracking indicator is usually a good thing to see to make sure that the app is able to persist in the background of the iOS system and obtain location updates. I am seeing that I will sometimes see the blue indicator show up briefly 1 - 3 times before fading out. On an odd occasion, after the second or third flicker of the blue indicator, it will stay on and will continue to track user location in the background. 

In Settings --> App --> Location --> Allow Location Access = "While Using App" (this is the default for apps, and I would like to achieve background location tracking persistance even though this is currently set to "While Using App", I understand this is possible if the blue "Location in use" indicator can be shown in the status bar)

## Expected Behavior

I would expect that as soon as the app gets sent to the background, the blue indicator will show up notifying the user that the location is persisting with its tracking, and that it will actually send information to the server 

## Actual Behavior

I am seeing that I will sometimes see the blue indicator show up briefly 1 - 3 times before fading out. On an odd occasion, after the second or third flicker of the blue indicator, it will stay on and will continue to track user location in the background. 

## Possible Fix

Not sure if this is accurate, but I have noticed that if one of my own javascript based location checks runs within the first couple seconds after the app is sent to the background (if it was about to run just as the user was sending the app to the background or something similar) the device will realize that I am actually using the location, and to persist the tracking capabilities of the app (though this is rare still)

## Steps to Reproduce
!!!VIDEO!!!
https://youtu.be/odV1RNWQKkc

`BackgroundGeolocation.configure({
					    locationProvider        : BackgroundGeolocation.ACTIVITY_PROVIDER,
					    desiredAccuracy         : BackgroundGeolocation.HIGH_ACCURACY,
					    stationaryRadius        : 50,
					    distanceFilter          : 50,
					    debug                   : false,
					    interval                : 10000,
					    fastestInterval         : 5000,
					    activitiesInterval      : 10000,
					    saveBatteryOnBackground : false,
					    stopOnStillActivity     : false,
					    stopOnTerminate         : false,
					    url                     : 'https://test.cabtreks.com/api/deliverer/location',
					    httpHeaders             : {
					      Authorization : 'Bearer ${idToken}',
					    },
					    // customize post properties
					    postTemplate : {
					      latitude  : '@latitude',
					      longitude : '@longitude',
					      time      : '@time',
					    },
					});

					BackgroundGeolocation.start();`

**Comment by mauron85** [comment]
BackgroundGeolocation.ACTIVITY_PROVIDER doesn't work in background unfortunately. Docs should be updated. 

There is already issue for that in https://github.com/mauron85/react-native-background-geolocation/issues/275

**Comment by rodrigoords** [comment]
Exists any locationProvider that I can use on both Android and IOs?

**Comment by willmero** [comment]
Ah dang. @mauron85 The crazy bit though is that **sometimes** it will maintain this task, and apps like Google Maps employs this type of functionality, so a public API is available for background geolocation tracking 🧐

**Comment by mauron85** [comment]
@rodrigoords all three of them can be used on android and ios. Only BackgroundGeolocation.ACTIVITY_PROVIDER has this limitation. It's not plugin bug, but iOS limitation, that it won't provide activity detection for apps in background. Maybe you can use it even on iOS but on `background` event, you will reconfigure plugin to use eg. RAW_PROVIDER (an fg event back on).
