### ISSUE TITLE
Android Pie: stopOnTerminate- false no longer working

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#511]
## Your Environment
* Plugin version: 3.0.0-alpha.47
* Platform: Android
* OS version: 9
* Device manufacturer and model: Nokia 6.1 Plus
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): Android 7.1.0
* Plugin configuration options: 
```
BackgroundGeolocation.configure({
            //locationProvider: backgroundGeolocation.provider.ANDROID_DISTANCE_FILTER_PROVIDER,  //Distance Provider
            locationProvider: 1,         //Activity Provider
            debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
            stopOnTerminate: false, // <-- enable this to clear background location settings when the app terminates
            startOnBoot: true,  //Android Only, starts location tracking on device boot
            interval: this.callbackInterval,                   //2min //In ms, Minimum time interval before update //Only for Android
            startForeground: true,       //Keep background location tracking active in foreground

            url: this.globals.webApiBaseUrl + "/" + this.globals.apiVersion+ "/Location/AddMauron85Locations?UserId="+ model.UserId,
            syncUrl: this.globals.webApiBaseUrl + "/" + this.globals.apiVersion + "/Location/AddMauron85Locations?UserId="+ model.UserId,
            syncThreshold: 10,     //Http post occurs after failed post locations number is beyond syncThreshold
            maxLocations: 100000,   //Max locations to store in local db

            desiredAccuracy: 10,    //In Meters
            stationaryRadius: 60,  //30,  //In Meters
            distanceFilter: 40, // 20,     //In Meters, minimum distance a user must move horizontally before update

            notificationsEnabled: true,
            activityType: 'AutomotiveNavigation',   //IOS Only
            notificationIconSmall: 'notification',
            notificationIconLarge: 'icon',
            notificationIconColor: '#f86900',
            notificationTitle: 'SmartTask', // <-- android only, customize the title of the notification
            notificationText: 'Click to open App',

            //ANDROID_ACTIVITY_PROVIDER 
            fastestInterval: (this.callbackInterval/3),     //fatest interval in ms.
            activitiesInterval: this.callbackInterval,      //2 min //Activity recognition interval in ms
            stopOnStillActivity: false,       //Incase of still activity donot record location
            postTemplate: model
        });
```
* Link to your project:

## Context
`stopOnTerminate` not working anymore. The app gets killed in the background it seems. The notification too is not longer visible after sometime of app being in background

**Comment by mauron85** [comment]
I'm not aware about additional restrictions in Android Pie. I'm guessing this is result of some kind of Nokia "optimization".

**Comment by mauron85** [comment]
Actually checking android developers site. There are new battery saver improvements, vaguely described. https://developer.android.com/about/versions/pie/power#battery-saver


1. The system puts apps in app standby mode more aggressively, instead of waiting for the app to be idle.
2. Background execution limits apply to all apps, regardless of their target API level.
3. Location services may be disabled when the screen is off.
4. Background apps do not have network access.

Not sure how this translate to real world. But some of them sounds scary and guess can impact how this works. 

I'm afraid there is not much we can here, apart asking user to disable these battery optimizations in **Settings > Battery Saver**

**Comment by shyamal890** [comment]
Hmm, seems like switching off Battery saver did the trick, there was a another `Adaptive Battery` option which I turned off. Its seems to be working alright. 

However, given the direction Android and IOS are taking they surely don't want developers to track continuous location.

**Comment by shyamal890** [comment]
Hi @mauron85 the above solution doesn't seem to work anymore. The system is killing the app randomly. However, I have 2 apps installed which trigger a notification every morning waking up their respective apps/services ( Todoist, Any.do ) 

Can't set something like that? To make sure that the service is running? Something like a scheduler which checks if the service is running, if not it would restart the service.

If notification from server is needed to restart the service, that too may work out.

**Comment by bsikatti16** [comment]
When App is killed or Removed from Background
**stopOnTerminate: false** it is not working in devices like **(Mi, Vivo, Oppo)** which has OS like **MIUI, ColorOs, Funtouch os** with Android Oreo 8.1.0.

**Comment by bsikatti16** [comment]
@shyamal890 @mauron85  Any solution?
**stopOnTerminate: false** it is not working

**Comment by ShafiqShams** [comment]
Its not working on iOS 12.1.2

I want my iOS app to run even after terminated.
Someone help -_-
