### ISSUE TITLE
Empty body on IOs request

### ISSUE THREAD

**Issue by rodrigoords** [mauron85/cordova-plugin-background-geolocation#512]
When using the plugin with IOs it is sending an empty body to serve.

## Your Environment
 let config = {
            locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
            desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
            startForeground: true,
            stationaryRadius: 20,
            stopOnStillActivity: false,
            pauseLocationUpdates: false,
            distanceFilter: 10,
            interval: 3000,
            fastestInterval: 1000,
            activitiesInterval: 3000,
            maxLocations: 10000,
            startOnBoot: false,
            stopOnTerminate: true,
            notificationTitle: 'Acompanhamento de localização',
            notificationText: 'ativado',
            notificationIconLarge: 'notification_icon',
            notificationIconSmall: 'notification_icon',
            debug: false,
            url: Config.GEOLOCALIZACAO_MOTORISTA.replace(new RegExp('{id}', 'gi'), this.motoristaProvider.getMotorista().$id.toString()),
            httpHeaders: {
                'Content-Type': 'application/json'
            },
            postTemplate: {
                latitude: '@latitude',
                longitude: '@longitude'
            }
        };

* Plugin version: 3.0.0-alpha.47
* Platform: iOS
* OS version: 12.1

## Expected Behavior
Post body send as Array to serve

## Actual Behavior
Post body sent empty

## Debug logs
When debug the plugin code one i saw one thing:
The location JSON Object that has a key value map was:
 @"longitude": @"@lon"
 @"latitude": @"@lat"

MAURPostLocationTask line:118 
NSData *data = [NSJSONSerialization dataWithJSONObject:locations options:0 error:outError];

**Comment by mauron85** [comment]
It might server issues. Please try to replicate with example server https://github.com/mauron85/background-geolocation-server.

**Comment by rodrigoords** [comment]
I don't think so, I use the same server and work perfectly with android, only in IOS I got this error.
I have a nodejs server with express.

**Comment by mauron85** [comment]
Also remove httpHeaders: {
'Content-Type': 'application/json'
},

That is not necessary, plugin is sending already that content time. It caused troubles in the past as far I remember

**Comment by rodrigoords** [comment]
Ok, I will remove and test, I'm trying to debug and use Wireshark to help me log the request if I found something I will keep in touch.

**Comment by mauron85** [comment]
Yes, removing that content-type header definitely works ! Just tested it.

**Comment by mauron85** [comment]
When you print the headers they look like:
```
Headers:
 { host: '192.168.81.15:3000',
  'content-type': 'application/json,application/json',
  connection: 'keep-alive',
  accept: '*/*',
  'user-agent': 'BG%20Example/2.0.0 CFNetwork/975.0.3 Darwin/18.2.0',
  'accept-language': 'en-us',
  'accept-encoding': 'gzip, deflate',
  'content-length': '84' }
Locations:
 {}
```
As you can see, application/json was added twice. Removing that header will resolve your problem.

**Comment by rodrigoords** [comment]
I removed the header key from config but still error, only work with i comment this code: 
For any reason self.config.httpHeaders still with content type value.
//    if (httpHeaders != nil) {
//        for(id key in httpHeaders) {
//            id value = [httpHeaders objectForKey:key];
//            [request addValue:value forHTTPHeaderField:key];
//        }
//    }

**Comment by rodrigoords** [comment]
That solves thanks.
