### ISSUE TITLE
AccuracyLevel on ine 14 of BackgroundGeolocation.d.ts is commented out and causes errors

### ISSUE THREAD

**Issue by allensutton** [mauron85/cordova-plugin-background-geolocation#514]
## Your Environment

* Plugin version: 3.0.0-alpha.47
* Platform: Android
* OS version: 8.0.0
* Device manufacturer and model: Google Pixel XL

* Running in Simulator: Yes
* Cordova version (`cordova -v`): 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (`cordova platform ls`): 
Installed platforms:
  android 7.1.2
  ios 4.5.5
Available platforms: 
  browser ~5.0.1
  osx ~4.0.1
  windows ~6.0.0
* Plugin configuration options: N/A (this issue is during build)
* Link to your project: Unfinished

## Context

I have pulled the latest copy of the plugin and while troubleshooting some other issues I have been deleting node_modules and rebuilding it for one reason or another.  During that process, I keep getting an error of :
```
ERROR in node_modules/cordova-plugin-mauron85-background-geolocation/www/BackgroundGeolocation.d.ts(471,18): error TS2304: Cannot find name 'AccuracyLevel'.
node_modules/cordova-plugin-mauron85-background-geolocation/www/BackgroundGeolocation.d.ts(472,20): error TS2304: Cannot find name 'AccuracyLevel'.
node_modules/cordova-plugin-mauron85-background-geolocation/www/BackgroundGeolocation.d.ts(473,17): error TS2304: Cannot find name 'AccuracyLevel'.
node_modules/cordova-plugin-mauron85-background-geolocation/www/BackgroundGeolocation.d.ts(474,21): error TS2304: Cannot find name 'AccuracyLevel'.

```
...because line 14 is commented out.  This is where AccuracyLevel is instantiated, so lines 471-474 throw an error because of it.
## Expected Behavior

No errors on AccuracyLevel variable.
## Actual Behavior

Comment causes error because AccuracyLevel is never instantiated before being used.
## Possible Fix

Remove // from line 14
## Steps to Reproduce

1. cordova plugin add cordova-plugin-mauron85-background-geolocation@latest 
2. ng --build
3. you will see the errors

## Context

It requires me to go back and remove the comment every time I do something to reinstall the plugin
## Debug logs

allen@tornado:~/projects/mileage-tracker$ ng build --prod
                                                                                     
Date: 2018-11-16T01:18:59.730Z
Hash: d8d74064d4c551466a6b
Time: 10043ms
chunk {0} runtime.ec2944dd8b20ec099bf3.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main.9868d9b237c3a48c54da.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills.85f47f0bf59079cbc23a.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} styles.254a64e6ae38a8bf3664.css (styles) 64.6 kB [initial] [rendered]

ERROR in node_modules/cordova-plugin-mauron85-background-geolocation/www/BackgroundGeolocation.d.ts(471,18): error TS2304: Cannot find name 'AccuracyLevel'.
node_modules/cordova-plugin-mauron85-background-geolocation/www/BackgroundGeolocation.d.ts(472,20): error TS2304: Cannot find name 'AccuracyLevel'.
node_modules/cordova-plugin-mauron85-background-geolocation/www/BackgroundGeolocation.d.ts(473,17): error TS2304: Cannot find name 'AccuracyLevel'.
node_modules/cordova-plugin-mauron85-background-geolocation/www/BackgroundGeolocation.d.ts(474,21): error TS2304: Cannot find name 'AccuracyLevel'.

**Comment by mauron85** [comment]
This has been already fixed in master. Please wait for upgraded package or install from git.

**Comment by allensutton** [comment]
OK, that sounds like a good solution - thanks!
