### ISSUE TITLE
Plugin keeps displaying debug notifications despite this prop is disabled

### ISSUE THREAD

**Issue by luisapuyen** [mauron85/cordova-plugin-background-geolocation#516]
## Your Environment

* Plugin version: 3.0.0-alpha.47
* Platform: Android
* OS version: 8.0.0
* Device manufacturer and model: LG G6

* Running in Simulator: No
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`): android 7.1.2
* Plugin configuration options: 

```
    <plugin name="cordova-plugin-mauron85-background-geolocation" spec="^3.0.0-alpha.47">
        <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="11+" />
        <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="26+" />
        <variable name="ICON" value="@mipmap/icon" />
        <variable name="SMALL_ICON" value="@mipmap/icon" />
        <variable name="ACCOUNT_NAME" value="@string/app_name" />
        <variable name="ACCOUNT_LABEL" value="@string/app_name" />
        <variable name="ACCOUNT_TYPE" value="$PACKAGE_NAME.account" />
        <variable name="CONTENT_AUTHORITY" value="$PACKAGE_NAME" />
    </plugin>
```

```
BackgroundGeolocation.configure({
                    locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
                    desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
                    stationaryRadius: 50,
                    distanceFilter: 50,
                    notificationTitle: 'MyAPP',
                    notificationText: 'Geolocalization ON',
                    interval: 10000,
                    fastestInterval: 5000,
                    activitiesInterval: 10000,
                    storeForeground: true,
                    stopOnTerminate: false
                });
```

* Link to your project:

## Context

I'm testing the plugin with the option debug: false (both explicitly or omitting it to use default value), but it keeps displaying "Detected STILL activity".

## Expected Behavior

It shouldn't be displaying that notification.

## Actual Behavior

What I said above plus I've checked it still occasionally plays the sound which indicated the change of state.

## Steps to Reproduce

1. Open app
2. When it comes from background or goes background, the notification is displayed.

**Comment by mauron85** [comment]
I don't see debug: false in you config options

**Comment by luisapuyen** [comment]
I thought you may omit this property and it should fall back to its default value **false**, as specified here in the plugin documentation on npmjs:
https://www.npmjs.com/package/cordova-plugin-mauron85-background-geolocation

**Comment by mauron85** [comment]
No, if you already configured it before. Configurations are persisted and partially applied, meaning once you set `debug: true` you must configure plugin with `debug: false` to disable it.
