### ISSUE TITLE
having a second instance of plugin to getcurrent position while app is running.

### ISSUE THREAD

**Issue by uzumakinaruto123** [mauron85/cordova-plugin-background-geolocation#52]
is it possible to run a second instance of plugin only to get the current position of the user while app is active  ?`(independent of ongoing background service)`

I know getcurrentposition is possible with `$cordovageolocation` or `html5 geolocation api` .

But those are not working  on android < 4.4. ! Kitkat above those work without any issue.
Below kitkat always getting timeout no matter highaccuracy is set to true or false or no matter how long the timeout is set to.

Interestingly, this `background geolocation plugin` works like a charm `even on jellybean devices.`

It would be great if theres a way to do that with this plugin ! then no cordova geolocation plugin will be required !

is there a way i can do it ?

Thanks ! help is appreciated !

**Comment by dinhtuan1991vt** [comment]
are there any answers for this issue?

**Comment by mauron85** [comment]
Never thought about this kind of usage, but actually this might be possible in version 2. Should be possible to register multiple position receivers within one app.

**Comment by uzumakinaruto123** [comment]
good to know @mauron85  :)  will wait for version 2 ...

**Comment by shyamal890** [comment]
@uzumakinaruto123 Can you please give a use case for this request. This plugin even works when the app is in foreground right?

**Comment by mauron85** [comment]
In version 3 you can add multiple location listeners with .on('location')...
