### ISSUE TITLE
How to prevent notification sound on configure method calls?

### ISSUE THREAD

**Issue by hoisel** [mauron85/cordova-plugin-background-geolocation#521]
## Your Environment

* Plugin version:^3.0.0-alpha.41
* Platform: Android
* OS version: 8
* Device manufacturer and model: Moto z2 play

* Running in Simulator:
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`): android 6.4.0
* Plugin configuration options: 
* Link to your project:

## Actual Behavior

Notification sound plays on every configure call

**Comment by murat0** [comment]
Turn off the debugging mode with "debug: false" whilst configuring
