### ISSUE TITLE
No location in background on iOS when authorization is "WhenInUse"

### ISSUE THREAD

**Issue by eommer** [mauron85/cordova-plugin-background-geolocation#524]
## Your Environment

* Plugin version: 2.3.6
* Platform: iOS
* OS version: 12.1
* Device manufacturer and model: iPhone 6S
* Running in Simulator: No
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): cordova-ios 4.5.5
* Plugin configuration options: 
``` 
var config = {
           PauseLocationUpdates : false,
           desiredAccuracy: 0,
           stationaryRadius: 5,
           distanceFilter: 5,
           debug: false,           
           stopOnTerminate: true,
           interval: 3000, 
           notificationTitle: 'Coach AAC', 
           notificationText: 'Trajet en cours', 
           fastestInterval: 1000, 
           useActivityDetection: false 
        };
```
* Link to your project: N/A

## Context
I need to retrieve locations when the app is in background. It works well on iOS when I select the "Always" authorization but I would like to use the "WhenInUse" because with this mode, a notification is displayed on screen in background. 

Retrieving locations in background with the "WhenInUse" authorization works fine with Christocracy plugin but not with your plugin. The blue notification is display for few seconds when I put the application in background but no location is given by the plugin. Then , the notification disapears and I still don't get any location (in background). 

Do you have any idea to make this configuration works or do you know if there any other solution to use the "Always" authorization and having a notification ? 

## Expected Behavior
background notification saying that the gps is in use

## Actual Behavior
(WhenInUse authorization ) : Notification for few seconds and then and no position retrieved in background 
(Always authorization ) : No notification but get normal locations in background

**Comment by mauron85** [comment]
That's pretty much expected behaviours. "WhenInUse" means only sending locations when app is foreground and not when in background.

**Comment by eommer** [comment]
Yes but it was working in background, with this authorization, with the Christocracy plugin. I don't know how it was possible, but it allowed me to have the notification.

Do you have any idea of how I could retrieve locations in background (with the "Always" auth) and still have a blue notification displayed ?

**Comment by OJ7** [comment]
@mauron85 [Apple's documentation](https://developer.apple.com/documentation/corelocation/choosing_the_authorization_level_for_location_services) suggests that it should work in foreground and background for both. The main difference is getting location when the app is suspended in background (when-in-use) or app is not running (always).

**Comment by mauron85** [comment]
@OJ7 yes, you right. I was wrong. Can somebody else confirm this issue?

**Comment by rodneyweaver** [comment]
I'm seeing the same issue.

**Comment by OJ7** [comment]
I did some testing with both 2.3.1 and 3.0.0-alpha.50 by starting the app and then putting it in the background.

The former seems to work fine showing the blue notification bar and getting location regularly in background.

The latter seems to be similar to what @eommer described with blue notification bar showing only with _WhenInUse_ (not with _Always_) permission but background location is tracked for minute or so and then stops. With _Always_ permission continues tracking (but not as consistently as 2.x though) and only when there is motion as opposed to periodically.

**Comment by OJ7** [comment]
I have created a [sample app](https://github.com/OJ7/background-geolocation-issue) with instructions to reproduce the issue.

**Comment by OJ7** [comment]
@mauron85 any updates on this issue?

**Comment by bogdanflorea83** [comment]
Hello, any updates on this issue? I have the same behavion, on IOS when app is in backgroud I do not receive locations. Or maybe if someone can share with me some “best practices” for plugjn configuration (basically I want to take the location every 30 seconds in Android/IOS when app is is use and when is in background)

**Comment by josemanuelsouto** [comment]
Same issue as @bogdanflorea83 in iOS, I select "Always" but coords are not being sent.
