### ISSUE TITLE
ionic build error

### ISSUE THREAD

**Issue by RajanYugtia** [mauron85/cordova-plugin-background-geolocation#529]
I have installed this plugin using npm install. Then i have done code of location.
Then i have triggered command ionic cordova build android and got this error

**Comment by RajanYugtia** [comment]
Error: ./node_modules/cordova-plugin-mauron85-background-geolocation/www/BackgroundGeolocation.js
Module not found: Error: Can't resolve 'cordova/channel' in 'D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova-plugin-mauron85-background-geolocation\www'
resolve 'cordova/channel' in 'D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova-plugin-mauron85-background-geolocation\www'
  Parsed request is a module
  using description file: D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova-plugin-mauron85-background-geolocation\package.json (relative path: ./www)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova-plugin-mauron85-background-geolocation\package.json (relative path: ./www)
    resolve as module
      looking for modules in D:\Rajan\Ionic\Mauron85Demo\node_modules
        using description file: D:\Rajan\Ionic\Mauron85Demo\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\Rajan\Ionic\Mauron85Demo\package.json (relative path: ./node_modules)
          using description file: D:\Rajan\Ionic\Mauron85Demo\package.json (relative path: ./node_modules/cordova/channel)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\channel doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\channel.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\channel.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\channel.json doesn't exist
            as directory
              D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\channel doesn't exist
[D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\channel]
[D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\channel.ts]
[D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\channel.js]
[D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\channel.json]
[D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\channel]
 @ ./node_modules/cordova-plugin-mauron85-background-geolocation/www/BackgroundGeolocation.js 13:14-40
 @ ./src/pages/home/home.ts
 @ ./src/app/app.module.ts
 @ ./src/app/main.ts,./node_modules/cordova-plugin-mauron85-background-geolocation/www/BackgroundGeolocation.js
Module not found: Error: Can't resolve 'cordova/exec' in 'D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova-plugin-mauron85-background-geolocation\www'
resolve 'cordova/exec' in 'D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova-plugin-mauron85-background-geolocation\www'
  Parsed request is a module
  using description file: D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova-plugin-mauron85-background-geolocation\package.json (relative path: ./www)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova-plugin-mauron85-background-geolocation\package.json (relative path: ./www)
    resolve as module
      looking for modules in D:\Rajan\Ionic\Mauron85Demo\node_modules
        using description file: D:\Rajan\Ionic\Mauron85Demo\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\Rajan\Ionic\Mauron85Demo\package.json (relative path: ./node_modules)
          using description file: D:\Rajan\Ionic\Mauron85Demo\package.json (relative path: ./node_modules/cordova/exec)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\exec doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\exec.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\exec.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\exec.json doesn't exist
            as directory
              D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\exec doesn't exist
[D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\exec]
[D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\exec.ts]
[D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\exec.js]
[D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\exec.json]
[D:\Rajan\Ionic\Mauron85Demo\node_modules\cordova\exec]
 @ ./node_modules/cordova-plugin-mauron85-background-geolocation/www/BackgroundGeolocation.js 12:11-34
 @ ./src/pages/home/home.ts
 @ ./src/app/app.module.ts
 @ ./src/app/main.ts
    at new BuildError (D:\Rajan\Ionic\Mauron85Demo\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at callback (D:\Rajan\Ionic\Mauron85Demo\node_modules\@ionic\app-scripts\dist\webpack.js:121:28)
    at emitRecords.err (D:\Rajan\Ionic\Mauron85Demo\node_modules\webpack\lib\Compiler.js:265:13)
    at Compiler.emitRecords (D:\Rajan\Ionic\Mauron85Demo\node_modules\webpack\lib\Compiler.js:371:38)
    at emitAssets.err (D:\Rajan\Ionic\Mauron85Demo\node_modules\webpack\lib\Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (D:\Rajan\Ionic\Mauron85Demo\node_modules\webpack\lib\Compiler.js:364:12)
    at next (D:\Rajan\Ionic\Mauron85Demo\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (D:\Rajan\Ionic\Mauron85Demo\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (D:\Rajan\Ionic\Mauron85Demo\node_modules\tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit (D:\Rajan\Ionic\Mauron85Demo\node_modules\webpack\lib\Compiler.js:361:9)



Now please help me. Its a new fresh build.

**Comment by ShafiqEssani** [comment]
I am facing the same build issue. Please check and give your valuable input.
![image](https://user-images.githubusercontent.com/24293253/50591200-220fbb00-0eb0-11e9-9a9a-3e0ebfecb2a7.png)

**Comment by RajanYugtia** [comment]
In that mauron plugin js file use Cordova.require instead of only require.

**Comment by adappter** [comment]
Can you please be a little bit more precise? Where do we need to change it?

**Comment by RajanYugtia** [comment]
Go to plugin folder -> mauron85 -> www -> then js file.
change cordova.require instead of require.

**Comment by adappter** [comment]
so `var channel = require('cordova/channel');` should be `var channel = cordova.require('cordova/channel');` ?

**Comment by RajanYugtia** [comment]
yes.

**Comment by adappter** [comment]
Did not work :/

**Comment by RajanYugtia** [comment]
channel and it's above line.

**Comment by adappter** [comment]
That's how the requires looks like, and did not work:

```
var exec = cordova.require('cordova/exec');
var channel = cordova.require('cordova/channel');
var radio = require('./radio');
var TAG = 'CDVBackgroundGeolocation';

```

**Comment by adappter** [comment]
Okay fixed the problem. It's important to change the `require` in `node_modules\cordova-plugin-mauron85-background-geolocation\www\BackgroundGeolocation.js`
Also be sure if the changes are inside the `platform/(ios or android)/www/plugins/cordova-plugin-mauron85-background-geolocation\www\BackgroundGeolocation.js`

**Comment by seanfisher** [comment]
Just to put here for people landing here from Google (like me).

This worked for me, based on [this snippet from @mauron85 in #515](https://github.com/mauron85/cordova-plugin-background-geolocation/issues/515#issuecomment-446228432):

```typescript
import { BackgroundGeolocationPlugin }  from '@mauron85/cordova-plugin-background-geolocation';
declare const BackgroundGeolocation: BackgroundGeolocationPlugin;

// ... Usage
BackgroundGeolocation.configure({...});
```
