### ISSUE TITLE
crash app on start in Galaxy J7 with android 8.1.0

### ISSUE THREAD

**Issue by shomid** [mauron85/cordova-plugin-background-geolocation#530]
I created a app with ionic 4-rc0 and use cordova-plugin-mauron85-background-geolocation version 2.3.6 with ionic-native 5-beta22 and cordova-android 7.1.4.
app work in some devices correctly but crash in Galaxy J7.
how to resolve this problem ?

**Comment by julienthomasdc** [comment]
I have a Galaxy J7 Prime with Android 8.1.0 too and that is the error logged :

`android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 number=0 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)`

**Comment by shomid** [comment]
I use version 3 alpha without @ionic-native/background-geolocation and this work correctly.

**Comment by julienthomasdc** [comment]
Thank you shomid, I tried to install alpha version 3 but I can't import BackgroundGeolocation from the plugin in my project. I tried lot of things but It's never able to locate export...

`import { BackgroundGeolocation } from 'cordova-plugin-mauron85-background-geolocation';`

**Comment by shomid** [comment]
You should use this:

    import { Injectable } from '@angular/core';
     ...
    declare var BackgroundGeolocation: any;

    @Injectable()
    export class LocationService {

       constructor(...) {
          ...
       }

       watchLocation() {
         const config = {
             desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
             stationaryRadius: 20,
             distanceFilter: 30,
             interval: 60000,
             debug: false, //  enable this hear sounds for background-geolocation life-cycle.
         };

         BackgroundGeolocation.configure(config);

         BackgroundGeolocation.on('location', (location) => {
             console.log(JSON.stringify(location));
             this.sendLocation(location.latitude, location.longitude);
         });
      }

       startBackgroundLocation() {
           this.watchLocation();
           BackgroundGeolocation.start();
       }

        ...
     }

**Comment by julienthomasdc** [comment]
Thank you shomid! It's working when I put the apk on my device but if I try `ionic serve` I got this error on the console:

```
ERROR Error: Uncaught (in promise): ReferenceError: BackgroundGeolocation is not defined
ReferenceError: BackgroundGeolocation is not defined
```

**Comment by RajanYugtia** [comment]
Same issue with me.

**Comment by shomid** [comment]
> Thank you shomid! It's working when I put the apk on my device but if I try `ionic serve` I got this error on the console:
> 
> ```
> ERROR Error: Uncaught (in promise): ReferenceError: BackgroundGeolocation is not defined
> ReferenceError: BackgroundGeolocation is not defined
> ```

only work in android and ios,not work in browser

**Comment by RajanYugtia** [comment]
I am getting this error on live device and emulator.

**Comment by stsfaroz** [comment]
I too have this issue, any solution??

**Comment by rodrigosoareschaves** [comment]
I could fix this error in Ionic using:

```
declare var window: any;

...

window.backgroundGeolocation.configure(location=>{
     //My track code
},error=>{console.log(error),options});

window.backgroundGeolocation.start(...);
```

If this don't works inspect the App in Chrome and try check if the backgroundGeolocation variable exists in cordova, cordova.plugins or window.plugins.

**Comment by crgrove** [comment]
> I could fix this error in Ionic using:
> 
> ```
> declare var window: any;
> 
> ...
> 
> window.backgroundGeolocation.configure(location=>{
>      //My track code
> },error=>{console.log(error),options});
> 
> window.backgroundGeolocation.start(...);
> ```
> If this don't works inspect the App in Chrome and try check if the backgroundGeolocation variable exists in cordova, cordova.plugins or window.plugins.

Could you provide a complete example of this?  I'm not following what "window" is.
