### ISSUE TITLE
This plugin always displays toast message

### ISSUE THREAD

**Issue by RajanYugtia** [mauron85/cordova-plugin-background-geolocation#531]
Plugin version:2.3.6
 Platform:  Android
 OS version: Oreo
 Device manufacturer and model:
 Cordova version (`7.1.0`):
 Cordova-android version (6.3.0):

After adding this plugin the toast message is always displaying in screen. i want to stop that toast message.

## Expected Behavior
Toast should not come.

## Actual Behavior
Always displays a toast message

please help me asap. It's urgent.

**Comment by ShafiqEssani** [comment]
Which toast msg?
you can turn off the debug setting to false when configuring the plugin.

**Comment by RajanYugtia** [comment]
ok will try the same

**Comment by ShafiqEssani** [comment]
worked?
