### ISSUE TITLE
Plugin not working in background after 5 min

### ISSUE THREAD

**Issue by RajanYugtia** [mauron85/cordova-plugin-background-geolocation#532]
Plugin not working in background after 5 min

 Plugin version:2.3.6
 Platform: Android
 OS version: Oreo

 Cordova version (7.1.0):
 Cordova-android platform version (6.3.0):

## Expected Behavior
This plugin should be working in background for long time

## Actual Behavior
This plugin is working in background for 5 min then it is stopped working,

**Comment by RajanYugtia** [comment]
Mauron85 Please help me.

**Comment by DevlprArup** [comment]
@RajanYugtia Could you solve the issue ? if not please let me know.

**Comment by RajanYugtia** [comment]
you have to enable background mode. And your issue will be solved.

**Comment by jrcichra** [comment]
Yes, how do I enable background mode?

**Comment by RajanYugtia** [comment]
https://ionicframework.com/docs/v3/native/background-mode/

**Comment by zhaoxu666** [comment]
@RajanYugtia   Do you have any samples or related articles About these two plugins？ I need this. thanks a lot

**Comment by RajanYugtia** [comment]
![Oreo not working](https://user-images.githubusercontent.com/46106411/60654567-d98a8780-9e69-11e9-9e56-edb3368adef1.PNG)

**Comment by zhaoxu666** [comment]
@RajanYugtia  
my plugin version is 3.0.3.
I can get location information in the open area, but when I enter the subway or the building, there will be no information to return. I expect that when I return to the open area, it will work properly.
ps:
Stop from the building in a short time, then go out can get the location information, about an hour, then go out, is unable to get the location information.

**Comment by RajanYugtia** [comment]
is it working continuously over 30 min outside ?

**Comment by jrcichra** [comment]
> is it working continuously over 30 min outside ?

See if my solution to my own question here is helpful:

https://stackoverflow.com/questions/56414678/cordova-app-that-uploads-my-location-every-minute-to-a-back-end-server-even-whe
