### ISSUE TITLE
is plugin 3.0.0-alpha.50 compatible with angular js ?

### ISSUE THREAD

**Issue by RajanYugtia** [mauron85/cordova-plugin-background-geolocation#535]
I have project in angularjs with ionic 1. In 2.x version there is only one js file there. Since i have updated it to 3.x it contains 3 file 2 js file and 1 ts file. My question is will it work on my angularjs project ?

## Your Environment
* Plugin version: 3.0.0-alpha.50
* Platform: Android
* OS version: Pie
* Device manufacturer and model: MI A2
* Running in Simulator: No
* Cordova version (`7.1.0`):
* Cordova platform version (`6.3.0`):
* Plugin configuration options: 

        desiredAccuracy: 10,
        stationaryRadius: 20,
        distanceFilter: 30,
        interval: 30000,
        fastestInterval: 5000,
        maxLocations: 10,
        stopOnTerminate: false,

* Link to your project:

## Context
I have project working on angularjs (angular 1) and ionic 1. Plugin version 2.x version there is only one js file there. Since i have updated it to 3.x it contains 3 file 2 js file and 1 ts file. Since angularjs is not supporting typescript file. how plugin will work ?

## Expected Behavior
Plugin should work in angularjs projects.

## Actual Behavior
It's not working in angularjs project.

## Steps to Reproduce
1. install plugin version 3.x
2. generate build
3. run on android pie
4. plugin will not work and says undefined

## Context

This bug will affect my whole project.

## Debug logs

 D/SystemWebChromeClient: file:///android_asset/www/js/app.js: Line 91 : Uncaught ReferenceError: BackgroundGeolocation is not defined

[INFO:CONSOLE(91)] "Uncaught ReferenceError: BackgroundGeolocation is not defined", source: file:///android_asset/www/js/app.js (91)

**Comment by OJ7** [comment]
Do you have code that shows how you are attempting to use it? Have you tried `window.BackgroundGeolocation`?

**Comment by RajanYugtia** [comment]
yes i have tried that as well but no success.
