### ISSUE TITLE
Question: Running custom code on "location" via the background service.

### ISSUE THREAD

**Issue by murat0** [mauron85/cordova-plugin-background-geolocation#538]
## Your Environment

* Plugin version: 3.0.0-alpha.50
* Platform: Android and iOS
* OS version: 8.0.0 and 12.0
* Device manufacturer and model: Samsung S8 and Apple iPhone7
* Running in Simulator: No
* Cordova version: 8.1.2
* Cordova platform version: android 7.1.4 and ios 4.5.5
* Link to your project: N/A

## Context

First of all thank you very much for this useful plugin. Mine is a question rather than an issue. I would like to know if there is a feasible way of running custom code (with no previous context is OK too) on "location" event whilst the app is killed - but with the app being started with "stopOnTerminate: false" in the previous run so the background service is available and actively posting location data to the provided URL in the background.

Posting to the provided URL works ok in short term however as I am after calculating geofence intersection on each "location" update I would rather do this locally rather than sending the location data along with user information to a remote server and doing the calculation there. Thinking about the long run this will generate an incredibly high volume of traffic to the server I would need to use. 

Simply, is there a way to run custom code rather than posting data to the provided URL or any other way to achieve what I am after? 

Thank you in advance.

**Comment by mauron85** [comment]
You can register headless task. But you can't have interactions with your UI code.

**Comment by mauron85** [comment]
Headless tasks however are not very effective in current implementation, because they start webview instance for every location update.

**Comment by murat0** [comment]
Right, if headless task is the only way of achieving this then there is no possible way of carrying out the same action in iOS environment as headless task is an Android only feature. 

Question answered - thanks.
