### ISSUE TITLE
Unable to inject backgroundGeoLocation object

### ISSUE THREAD

**Issue by prashant-krixi** [mauron85/cordova-plugin-background-geolocation#54]
I have created ionic project. I have added plugin by " cordova plugin add cordova-plugin-mauron85-background-geolocation".

I have created a controller as follow:

angular.module('mymodule').controller('backgroundGeolocation', function($scope, backgroundGeoLocation){
	console.log("In backgroundGeolocation");
	 $scope.startBackgroundGeoLocation = function(){

        var failureFn = function(error) {
            console.log('BackgroundGeoLocation error');
        };

        var callbackFn = function(location) {
            console.log('[js] BackgroundGeoLocation callback:  ' + location.latitude + ',' + location.longitude);
            backgroundGeoLocation.finish();
        };

        backgroundGeoLocation.configure(callbackFn, failureFn, {
            desiredAccuracy: 10,
            stationaryRadius: 20,
            distanceFilter: 30,
            debug: true, // <-- enable this hear sounds for background-geolocation life-cycle. 
            stopOnTerminate: false, // <-- enable this to clear background location settings when the app terminates 
        });
        backgroundGeoLocation.start();
    }

});

In above controller I am not able to inject "backgroundGeoLocation" object. Do I missing something?

**Comment by uzumakinaruto123** [comment]
You dont need to inject it. its plain javascript plugin and not a angular wrapper. Once the device is ready you can directly use it like `backgroundGeoLocation.start();` . No injection required.

**Comment by mauron85** [comment]
@prashant-krixi did @uzumakinaruto123 answered your question?

**Comment by mauron85** [comment]
please reopen, with more info
