### ISSUE TITLE
Show notification tracking even if plugin is stoped

### ISSUE THREAD

**Issue by robertolocal** [mauron85/cordova-plugin-background-geolocation#540]
## Your Environment

* Plugin version: 3.0.0-alpha.50
* Platform: Android
* OS version: 6.0
* Device manufacturer and model: LG k10
* Running in Simulator: Not
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): android 7.1.0
* Plugin configuration options: 
 {
    locationProvider: 0,
    desiredAccuracy: 10,
    stationaryRadius: 10,
    distanceFilter: 40,
    interval: 60000*2,
    pauseLocationUpdates: false,
    activitiesInterval: 30000,
    fastestInterval: 30000,
    startForeground: true,
    startOnBoot: false,
    stopOnTerminate: true,
    stopOnStillActivity: false,
    notificationTitle: 'LocalDrive',
    notificationText: 'Rastreador do Smartphone Ativo',
    notificationIconLarge: 'icon',
    notificationIconSmall: 'ic_smartphone_tracker',
    notificationIconColor: '#bb1800',
};

## Context

On some devices, even without running the start function, the trace notification appears after closing the application.

## Expected Behavior

Do not show notification when background geolocation is disabled

## Actual Behavior

Show notification tracking even if plugin is stoped

## Possible Fix

No ideia.

## Steps to Reproduce

1. Start app
2. Call method configure
3. Close App

## Context

This bug affects me because it shows that my apps are tracking users who did not enable this feature

**Comment by robertolocal** [comment]
additional information: this bug appears when update plugin from 3.0.0-alpha.38 to 3.0.0-alpha.50

**Comment by wildhart** [comment]
I have Android users with 3.0.0-alpha.42  and 3.0.0-alpha.50 with the same issue.  This is serious because I am getting complaints from users who are not using my tracking feature but get the notification that they are being tracked.

Are #551 or #552 related?  Seems like something is causing the tracking to start all by itself when the app is closed...

**Comment by hoisel** [comment]
+1

**Comment by niccolobonelli** [comment]
I have tried to hide notification by calling:
```
NotificationManager notificationManager = (NotificationManager) getApplicationContext().getSystemService(Context.NOTIFICATION_SERVICE);
notificationManager.cancel(NOTIFICATION_ID);
```
both in `stop` and in `stopForeground` (in file LocationServiceImpl.java). However, the notification is still there, even after calling BackgroundGeolocation.stop. Any hint?
