### ISSUE TITLE
tried calling BackgroundGeolocation.stop, but the BackgroundGeolocation plugin is not installed

### ISSUE THREAD

**Issue by franzisk** [mauron85/cordova-plugin-background-geolocation#543]
After I did some updates on Android SDK inside Android Studio my app doesn't work anymore with the Geolocation Plugin, when I try to get the location is says:
```
[15:28:26]  console.warn: Ionic Native: tried calling BackgroundGeolocation.configure, but the BackgroundGeolocation plugin is not installed.
[15:28:26]  console.warn: Install the BackgroundGeolocation plugin: 'ionic cordova plugin add cordova-plugin-mauron85-background-geolocation@alpha'
[15:28:26]  console.warn: Ionic Native: tried calling BackgroundGeolocation.isLocationEnabled, but the BackgroundGeolocation plugin is not installed.
[15:28:26]  console.warn: Install the BackgroundGeolocation plugin: 'ionic cordova plugin add cordova-plugin-mauron85-background-geolocation@alpha'
```

## Your Environment
Trying to get background geolocation in Android device.

* Plugin version: **2.3.6**
* Platform: **Android**
* OS version: **macOS Mojave**
* Device manufacturer and model: **Samsung S5**

* Running in Simulator: (not using simulator)
* Cordova version (`cordova -v`): **7.1.0**
* Cordova platform version (`cordova platform ls`): **android 6.3.0**
* Plugin configuration options: 
```
let config: BackgroundGeolocationConfig = {
  desiredAccuracy: 10,
  stationaryRadius: 20,
  distanceFilter: 1,
  debug: false,
  stopOnTerminate: false,
  activityType: 'AutomotiveNavigation',
  notificationTitle: 'Japp',
  notificationText: 'Sharing Location',
  locationProvider: 1,
  startForeground: true,
  interval: 2000,
  fastestInterval: 5000,
  activitiesInterval: 10000
};

from(this.backgroundGeolocation.configure(config)).pipe(takeUntil(this.unsubscribeAll)).subscribe((location: BackgroundGeolocationResponse) => {
  this.zone.run(() => {
    this.setLocation(location.latitude, location.longitude);
  });
}, (err) => {
  console.log('=== Error on BackgroundGeolocation ===');
  console.log(err.message);
});

this.backgroundGeolocation.isLocationEnabled().then((rta) => {
  if (rta) {
    this.backgroundGeolocation.start();
  } else {
    this.help.showPopup('Location', 'Please, enable Location', () => {
      this.backgroundGeolocation.showLocationSettings();
      this.backgroundGeolocation.start();
    });
  }
})
```
* Link to your project: (it's not online)

## Context

It just doesn't work as it should, as it is not recognized as an installed plugin it must be something inside the code.
## Expected Behavior

It should at least not acuse that the plugin it's not installed since it is.

## Actual Behavior

Shows on the console output that the plugin is not installed

## Possible Fix

Not sure, maybe find out why and where the plugin is being considered not installed.

## Steps to Reproduce

I just ran that code with that config data.

## Context

This has affected a lot, I have been struggling with this for 6 days, I am trying just to get the user's location and send to a web service, with this issue I can't send the app. I wonder when migrating to Ionic 4 how many problems will come out, since the only option to background geolocation is this plugin.

## Debug logs

```
[app-scripts] [16:50:37]  console.warn: Ionic Native: tried calling BackgroundGeolocation.configure, but the BackgroundGeolocation
[app-scripts]             plugin is not installed.
[app-scripts] [16:50:37]  console.warn: Install the BackgroundGeolocation plugin: 'ionic cordova plugin add
[app-scripts]             cordova-plugin-mauron85-background-geolocation@alpha'
[app-scripts] [16:50:37]  console.warn: Ionic Native: tried calling BackgroundGeolocation.isLocationEnabled, but the
[app-scripts]             BackgroundGeolocation plugin is not installed.
[app-scripts] [16:50:37]  console.warn: Install the BackgroundGeolocation plugin: 'ionic cordova plugin add
[app-scripts]             cordova-plugin-mauron85-background-geolocation@alpha'
```

**Comment by henkkelder** [comment]
I see the same problem using ionic 4. 
I now use the plugin without the Ionic component.

I have the following line outside any Typescript class.
`declare const BackgroundGeolocation: any;`

Then inside my class I have:

 ```
this.platform.ready().then(() => {

            if (typeof BackgroundGeolocation !== "undefined") {
                this.bgLocation = BackgroundGeolocation;
                if (this.userSvc.locationPermission) {
                    this.doTheTracking();
                }

                this.userSvc.locationPermissionChanges().subscribe((permission) => {
                    if (permission) {
                        if (this.initDone) {
                            this.bgLocation.start();
                        } else {
                            this.doTheTracking();
                        }
                    } else {
                        this.bgLocation.stop();
                    }
                });
            }
        });
```

And an example of a event handler:

```
 this.bgLocation.on("location", location => {
                console.log("onLocation");
                this.onPositionFound(location);
                // this.bgLocation.startTask(taskKey => {
                //     this.bgLocation.endTask(taskKey);
                // });
            });
```

**Comment by veeravel** [comment]
```import { Component } from '@angular/core';

import { Platform } from '@ionic/angular';
import { SplashScreen } from '@ionic-native/splash-screen/ngx';
import { StatusBar } from '@ionic-native/status-bar/ngx';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html'
})

declare const BackgroundGeolocation: any;


export class AppComponent {
  constructor(
    private platform: Platform,
    private splashScreen: SplashScreen,
    private statusBar: StatusBar,
  ) {
    this.initializeApp();

    this.bgLocation.on("location", location => {
      console.log("onLocation");
      this.onPositionFound(location);
      // this.bgLocation.startTask(taskKey => {
      //     this.bgLocation.endTask(taskKey);
      // });
  });
  }

  initializeApp() {
    this.platform.ready().then(() => {
      this.statusBar.styleDefault();
      this.splashScreen.hide();

      if (typeof BackgroundGeolocation !== "undefined") {
        this.bgLocation = BackgroundGeolocation;
        if (this.userSvc.locationPermission) {
            this.doTheTracking();
        }

        this.userSvc.locationPermissionChanges().subscribe((permission) => {
            if (permission) {
                if (this.initDone) {
                    this.bgLocation.start();
                } else {
                    this.doTheTracking();
                }
            } else {
                this.bgLocation.stop();
            }
        });
    }
    });
  }

  
}
```

**Comment by veeravel** [comment]
its not working

**Comment by veeravel** [comment]
how to use this ?

**Comment by franzisk** [comment]
> I see the same problem using ionic 4.
> I now use the plugin without the Ionic component.
> 
> I have the following line outside any Typescript class.
> `declare const BackgroundGeolocation: any;`
> 
> Then inside my class I have:
> 
> ```
> this.platform.ready().then(() => {
> 
>            if (typeof BackgroundGeolocation !== "undefined") {
>                this.bgLocation = BackgroundGeolocation;
>                if (this.userSvc.locationPermission) {
>                    this.doTheTracking();
>                }
> 
>                this.userSvc.locationPermissionChanges().subscribe((permission) => {
>                    if (permission) {
>                        if (this.initDone) {
>                            this.bgLocation.start();
>                        } else {
>                            this.doTheTracking();
>                        }
>                    } else {
>                        this.bgLocation.stop();
>                    }
>                });
>            }
>        });
> ```
> And an example of a event handler:
> 
> ```
>  this.bgLocation.on("location", location => {
>                 console.log("onLocation");
>                 this.onPositionFound(location);
>                 // this.bgLocation.startTask(taskKey => {
>                 //     this.bgLocation.endTask(taskKey);
>                 // });
>             });
> ```

Sorry, I am not following your solution, I tried your way and I got an `undefined` for that constant `BackgroundGeolocation`, so nothing inside the `if` was executed.

**Did you see my environment? All the versions?**

**Comment by henkkelder** [comment]
No I did not see your environment.

In the constructor you pasted here you are referencing this.bgLocation. That does however not yet exist at that moment. It will be fill in the platform.ready handler.  You should move your handlers within the platform.ready handler. I have them in the DoTheTracking function.

Secondly, The BackgroundLocation is only defined on a real device or Emulator where the plugin itself can be loaded. It is undefined on my windows development computer. I assume it will be undefined on a mac as well.

The DoTheTracking function is only an example. You should define your own version that handles the tracking. In my version if configure the plugin and my "on" handlers are there.

**Comment by franzisk** [comment]
> No I did not see your environment.
> 
> In the constructor you pasted here you are referencing this.bgLocation. That does however not yet exist at that moment. It will be filled in the platform.ready handler. You should move your handlers within the platform.ready handler. I have them in the DoTheTracking function.
> 
> Secondly, The BackgroundLocation is only defined on a real device or Emulator where the plugin itself can be loaded. It is undefined on my windows development computer. I assume it will be undefined on a mac as well.
> 
> The userSvc is a service I have that keeps track of the permisssion the user has given. You should replace that and the "permission" var with something of your own.
> 
> The DoTheTracking function is only an example. You should define your own version that handles the tracking. In my version if configure the plugin and my "on" handlers are there.

Thanks for your answer,

And yes, I did just the way you said:

1. declared the constant outside of any TS class: `declare const BackgroundGeolocation: any;`
2. removed the declaration from the constructor
3. created a private var for my geolocation variable: `private backgroundGeolocation: any;`
4. inside the `this.platform.ready` I check that if and it returns an **undefined**
5. yes, I am using a real device, **Samsung Galaxy S5**

**Comment by henkkelder** [comment]
There is no need to completely paste my reply every time :-).

I am getting confused.  Could you paste your current code?

**Comment by franzisk** [comment]
Here it is,

In my service, before the `@Injectable()`:
`declare const BackgroundGeolocation: any;`

Inside my service class:
`private backgroundGeolocation: any;`

Method to start tracking the position in background:
```
startTracking() {
    this.platform.ready().then(() => {
      if (typeof BackgroundGeolocation !== "undefined") {
        this.backgroundGeolocation = BackgroundGeolocation;
        if (this.platform.is('cordova')) {
          ...
        } // is cordova?
      } else {
        console.error("BackgroundGeolocation is undefined"); // this is what I get
      }
    });

    ...

  }
```

**Comment by henkkelder** [comment]
Are you sure the plugin is included in your build?

**Comment by veeravel** [comment]
still having problem. please share any  examples

**Comment by henkkelder** [comment]
I have already shared the relevant code fragments. Like I said, if the BackgroundGeolocation is undefined I suspect the plugin not being included in your build.

**Comment by franzisk** [comment]
That is exactly the problem, the plugin is included and when I run it says it is not.
```
% cordova plugin list
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-android-support-gradle-release 2.0.1 "cordova-android-support-gradle-release"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-facebook4 3.1.0 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googleplus 5.3.2 "Google SignIn"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-linkedin 1.2.1 "LinkedIn"
cordova-plugin-mauron85-background-geolocation 2.3.6 "CDVBackgroundGeolocation"
cordova-plugin-media 5.0.2 "Media"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-nativegeocoder 3.1.2 "NativeGeocoder"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-streaming-media 2.2.0 "StreamingMedia"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.1 "SocialSharing"
cordova-sqlite-storage 2.5.0 "Cordova sqlite storage plugin"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 8.0.0 "BarcodeScanner"
phonegap-plugin-push 2.1.2 "PushPlugin"
twitter-connect-plugin 0.6.0 "Twitter Connect"
```

**Comment by henkkelder** [comment]
Please use the 3.0 alpga versuon.




Outlook voor Android downloaden







On Thu, Jan 31, 2019 at 10:14 AM +0100, "Francisco Vieira Souza" <notifications@github.com> wrote:












That is exactly the problem, the plugin is included and when I run it says it is not.
% cordova plugin list
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-android-support-gradle-release 2.0.1 "cordova-android-support-gradle-release"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-facebook4 3.1.0 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googleplus 5.3.2 "Google SignIn"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-linkedin 1.2.1 "LinkedIn"
cordova-plugin-mauron85-background-geolocation 2.3.6 "CDVBackgroundGeolocation"
cordova-plugin-media 5.0.2 "Media"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-nativegeocoder 3.1.2 "NativeGeocoder"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-streaming-media 2.2.0 "StreamingMedia"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.1 "SocialSharing"
cordova-sqlite-storage 2.5.0 "Cordova sqlite storage plugin"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-barcodescanner 8.0.0 "BarcodeScanner"
phonegap-plugin-push 2.1.2 "PushPlugin"
twitter-connect-plugin 0.6.0 "Twitter Connect"

**Comment by franzisk** [comment]
Mr. @henkkelder can you please show me your android platform `project.properties` file?

**Comment by henkkelder** [comment]
# This file was originally created by the Android Tools, but is now
# used by cordova-android to manage the state of the various third party
# libraries used in your application

# This is the Library Module that contains the Cordova Library, this is not
# required when using an AAR

# This is the application project.  This is only required for Android Studio Gradle projects

# Project target.
target=android-27
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.system.library.1=com.google.android.gms:play-services-analytics:11.6.2
cordova.system.library.2=com.android.support:support-annotations:27.+
cordova.system.library.3=com.google.android.gms:play-services-location:11.6.2
cordova.system.library.4=com.android.support:support-v4:26+
cordova.system.library.5=com.android.support:appcompat-v7:26+
cordova.gradle.include.1=cordova-plugin-mauron85-background-geolocation/opwekking-dependencies.gradle
cordova.system.library.6=com.android.support:support-v4:24.1.1+
cordova.gradle.include.2=cordova-support-google-services/opwekking-build.gradle
cordova.gradle.include.3=phonegap-plugin-multidex/opwekking-multidex.gradle
cordova.system.library.7=com.android.support:support-v13:27.+
cordova.system.library.8=me.leolin:ShortcutBadger:1.1.17@aar
cordova.system.library.9=com.google.firebase:firebase-messaging:11.6.2
