### ISSUE TITLE
First position retrieval when stationary too slow

### ISSUE THREAD

**Issue by JaimeFerBec** [mauron85/cordova-plugin-background-geolocation#55]
Currently I'm looking at a 40 ~ 50 seconds wait until I get the first gelocation after starting the background geolocation plugin (`backgroundGeoLocation.start()`) when my phone is sitting in a fixed position.
I guess that I could use the `fastestInterval` option on Android, and `changePace` on iOS to trigger a faster first retrieval of a position. The problem with the `fastestInterval` option is that I only really need to get a first fast geolocation read, and after that updates when the position does change. Is that possible?

**Comment by mauron85** [comment]
It's because on first boot, plugin is not using cached positions. It's inherited code from original project. And probably it can be improved.

**Comment by JaimeFerBec** [comment]
So I assume that whole time (40 ~ 50 seconds) is spent calculating the first position. Is that right?
I guess setting a lower `desiredAccuracy` would yield a lower calculating time for the retrieval of that first position.

**Comment by mauron85** [comment]
Actually I was referring to ANDROID_DISTANCE_FILTER provider. But you're using ANDROID_FUSED_LOCATION (as fastestInterval is available only for that one). With ANDROID_FUSED_LOCATION there should be no delay other then waiting for GPS lock. And yes, lovering desiredAccuracy would help.

**Comment by mauron85** [comment]
Might be related to #58

**Comment by mauron85** [comment]
Please try updated version 0.9.5.

**Comment by mauron85** [comment]
Fixed in 0.9.6. Reopen if necessary.
