### ISSUE TITLE
Geolocation not working on iOS

### ISSUE THREAD

**Issue by projjwalg** [mauron85/cordova-plugin-background-geolocation#555]
## Your Environment

* Plugin version: 3.0.0
* Platform: iOS
* OS version: 11.4
* Device manufacturer and model: iPhone 5S

* Running in Simulator:
* Cordova version (`cordova -v`): cli 8.0.0
* Cordova platform version (`cordova platform ls`): 4.5.4
* Plugin configuration options: 
* Link to your project:

## Context

This plugin is working absolutely fine on Android. But on iOS, it is not working at all. Is there any specific setting for iOS? Any working example available for iOS ? 
## Expected Behavior

When the app launches, iOS should ask for permission to access the location. If granted permission, GPS location should turn on. Location icon should be visible on the status bar.
## Actual Behavior

When the app is launched, iOS does not ask for any permission to access the location. Location does not get turned on. Nothing happens. No location icon is visible on the status bar. Neither the app crashes.

**Comment by Rasmusmm96** [comment]
I have the exact same issue.
