### ISSUE TITLE
junit framework not found

### ISSUE THREAD

**Issue by TdoubleG** [mauron85/cordova-plugin-background-geolocation#558]
## Your Environment

* Plugin version: 3.0.0 alpha 50
* Platform: Android

* Running in Simulator:
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`): Android 8.0.0
* Plugin configuration options: 
```
ionic cordova plugin add cordova-plugin-mauron85-background-geolocation@alpha --save 
--variable ANDROID_SUPPORT_LIBRARY_VERSION="23+" 
--variable GOOGLE_PLAY_SERVICES_VERSION="11.+" 
--variable ICON="@mipmap/ic_launcher" 
--variable SMALL_ICON="@mipmap/ic_launcher" 
--variable ACCOUNT_NAME="@string/app_name" 
--variable ACCOUNT_LABEL="@string/app_name"
--variable ACCOUNT_TYPE="$PACKAGE_NAME.account"
--variable CONTENT_AUTHORITY="$PACKAGE_NAME" 
--variable ALWAYS_USAGE_DESCRIPTION="description" 
--variable MOTION_USAGE_DESCRIPTION="description"
```

## Context

```
Task :app:compileDebugJavaWithJavac FAILED
25 actionable tasks: 25 executed
BUILD FAILED in 40s
/../platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: /../platforms/android/CordovaLib/src/org/apache/cordova/engine/SystemCookieManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/../platforms/android/app/src/main/java/com/marianhello/bgloc/service/LocationServiceIntentBuilder.java:26: error: package junit.framework does not exist
import junit.framework.Assert;
                      ^
/../platforms/android/app/src/main/java/com/marianhello/bgloc/service/LocationServiceIntentBuilder.java:164: error: cannot find symbol
        Assert.assertNotNull("Context can not be null!", mContext);
        ^
  symbol:   variable Assert
```

## Expected Behavior

After calling `cordova android build`, the build process should be successful

## Actual Behavior

The error pops up when running `cordova android build `

## Steps to Reproduce

1. Install plugin with config above
2. run `cordova build android`

**Comment by matthijsbierman** [comment]
It looks like scope has changed from ``compile`` to ``implementation``  for dependencies in ``cordova-android```:
https://github.com/apache/cordova-android/pull/486

That means they are no longer available on the classpath. This plugin probably depends on JUnit transitively.

**Comment by mauron85** [comment]
I think this has been fixed in common package. Need to release new version.

**Comment by adappter** [comment]
@mauron85 when you will be able to fix this with a new version?

**Comment by TomDemulierChevret** [comment]
Have the same issue, do you have an ETA for this ?

**Comment by matthijsbierman** [comment]
> I think this has been fixed in common package. Need to release new version.

This one?
https://github.com/mauron85/background-geolocation-android/issues/26

**Comment by mauron85** [comment]
If I remember correctly this has been fixed in common module, which was just updated to latest version.
Try plugin version 3.0.0.0 (released just now).

**Comment by adappter** [comment]
Cool!! I will give a try, and will give you feedback!

**Comment by adappter** [comment]
still present with android 8.0.0, but works with android 7.1.4... I'll reopen it

**Comment by TomDemulierChevret** [comment]
Hum, did you resintall correctly your platforms ?
I don't have the issue with cordova-android 8.0.0.

**Comment by adappter** [comment]
Okay.. I just removed the android platform. I'll try reinstalling everything (removing node_modules and plugins)

**Comment by TomDemulierChevret** [comment]
Yes I had the error with the ressources and fixed it with the arguments "@mipmap/ic_launcher".

**Comment by adappter** [comment]
where exactly did you fix this? I just changed the name from ic_launcher to icon

**Comment by TomDemulierChevret** [comment]
My current package.json looks like this :
```json
"cordova-plugin-mauron85-background-geolocation": {
        "GOOGLE_PLAY_SERVICES_VERSION": "11+",
        "ANDROID_SUPPORT_LIBRARY_VERSION": "26+",
        "ICON": "@mipmap/ic_launcher",
        "SMALL_ICON": "@mipmap/ic_launcher",
        "ACCOUNT_NAME": "@string/app_name",
        "ACCOUNT_LABEL": "@string/app_name",
        "ACCOUNT_TYPE": "$PACKAGE_NAME.account",
        "CONTENT_AUTHORITY": "$PACKAGE_NAME",
        "ALWAYS_USAGE_DESCRIPTION": "",
        "MOTION_USAGE_DESCRIPTION": ""
      },
```

With the same values in config.xml.

**Comment by adappter** [comment]
> Unfortunately it doesn't work.
> 
> I got some other errors preventing the build:
> 
> ```
> > Task :app:transformClassesWithDexBuilderForDebug
> BUILD FAILED in 40s
> 34 actionable tasks: 11 executed, 23 up-to-date
> /../Desktop/dev/customers/Polizeikontrollen/platforms/android/gradlew: Command failed with exit code 1 Error output:
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> D8: Type com.google.android.gms.common.internal.zzf is referenced as an interface from `com.google.android.gms.internal.zzhv`.
> D8: Type com.google.android.gms.common.internal.zzg is referenced as an interface from `com.google.android.gms.internal.zzhw`.
> D8: Type com.google.android.gms.common.internal.zzf is referenced as an interface from `com.google.android.gms.internal.zzcar`.
> com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /../.gradle/caches/transforms-1/files-1.1/play-services-ads-11.0.4.aar/32610580b004c3897c4feb772e218069/jars/classes.jar
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>         at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
>         at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
>         at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
>         at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:146)
>         at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:420)
>         at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
>         at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
>         at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
>         at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
>         at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
>         at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
>         at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
>         at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
>         at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
>         at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
>         at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
>         at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
>         at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
>         at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
>         at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
>         at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
>         at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
>         at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
>         at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
>         at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
>         at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
>         at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
>         at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
>         at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
>         at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
>         at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:74)
>         at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:143)
>         at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:40)
>         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:40)
>         at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:24)
>         at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:46)
>         at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:49)
>         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:40)
>         at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:33)
>         at org.gradle.initialization.DefaultGradleLauncher$ExecuteTasks.run(DefaultGradleLauncher.java:355)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
>         at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
>         at org.gradle.initialization.DefaultGradleLauncher.runTasks(DefaultGradleLauncher.java:219)
>         at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
>         at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:124)
>         at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:77)
>         at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:74)
>         at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:154)
>         at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38)
>         at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:96)
>         at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:74)
>         at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
>         at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
>         at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
>         at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:50)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
>         at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
>         at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
>         at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
>         at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:44)
>         at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:79)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:44)
>         at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
>         at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
>         at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
>         at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
>         at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
>         at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
>         at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
>         at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
>         at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
>         at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
>         at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
>         at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
>         at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
>         at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
>         at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
>         at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
>         at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
>         at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
>         at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
>         at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
>         at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
>         at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
>         at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
>         at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
>         at org.gradle.util.Swapper.swap(Swapper.java:38)
>         at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
>         at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
>         at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
>         at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
>         at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:81)
>         at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
>         at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
>         at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
>         at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
>         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
>         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
>         at java.lang.Thread.run(Thread.java:745)
> Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /../.gradle/caches/transforms-1/files-1.1/play-services-ads-11.0.4.aar/32610580b004c3897c4feb772e218069/jars/classes.jar
>         at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:909)
>         at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.lambda$convertToDexArchive$6(DexArchiveBuilderTransform.java:834)
>         at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
>         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
>         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
>         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
>         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
> Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.
>         at com.android.builder.dexing.D8DexArchiveBuilder.getExceptionToRethrow(D8DexArchiveBuilder.java:124)
>         at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:101)
>         at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:904)
>         ... 6 more
> Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
>         at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:70)
>         at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:43)
>         at com.android.tools.r8.D8.run(D8.java:94)
>         at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:99)
>         ... 7 more
> Caused by: com.android.tools.r8.utils.AbortException: Error: Type com.google.android.gms.common.internal.zzf is referenced as an interface from `com.google.android.gms.internal.zzhv`.
>         at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:89)
>         at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:60)
>         at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:64)
>         ... 10 more
> ```

**Comment by pserna95** [comment]
This issue is happening again with the Google Firebase updates from 17th June, forcing devices to update android platform to 8.0.0.
After the update, using **cordova-plugin-mauron85-background-geolocation@3.0.0-alpha.50** causes the error appear again, making impossible the build for Android with Ionic

**Comment by SteysiCenteno** [comment]
@pserna95 i have the same problem, any solution?

**Comment by pserna95** [comment]
No, it seems that cordova v8.0.0 does not work aproppiately with this plugin so I'm stucked here because I really need to update to that version of cordova (so I can use Firebase plugin too that has this requirement)

**Comment by sqrt0x01E4** [comment]
I'm currently facing the same issue. What's the cordova version that works?

**Comment by sudinmondal19** [comment]
https://build.phonegap.com using given error for this plugin 

<plugin name="cordova-plugin-mauron85-background-geolocation" spec="3.0.0" />

apk build error:
 Android resource linking failed
  /var/gimlet/tmp/47273923680480/3781717/app/src/main/res/xml/authenticator.xml:2: AAPT: error: resource mipmap/icon (aka com.appid:mipmap/icon) not found.

how can i resolve this issue using phonegap 9 <preference name="phonegap-version" value="cli-9.0.0" /> and using ionic 4 freamwork

please help me

**Comment by mowaiskalam** [comment]
I am facing the same issue of "package junit.framework does not exist"

`\platforms\android\app\src\main\java\com\marianhello\bgloc\service\LocationServiceIntentBuilder.java:26: error: package junit.framework does not exist
import junit.framework.Assert;
                      ^
\platforms\android\app\src\main\java\com\marianhello\bgloc\service\LocationServiceIntentBuilder.java:164: error: cannot find symbol
        Assert.assertNotNull("Context can not be null!", mContext);
        ^
  symbol:   variable Assert
  location: class LocationServiceIntentBuilder
Note: Some input files use or override a deprecated API.

> Task :app:compileDebugJavaWithJavac FAILED
26 actionable tasks: 4 executed, 22 up-to-date
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
Error: \platforms\android\gradlew: Command failed with exit code 1 Error output:
F:\My Works\AtiqueTraders\aetasaal-mobile\platforms\android\app\src\main\java\com\marianhello\bgloc\service\LocationServiceIntentBuilder.java:26: error: package junit.framework does not exist
import junit.framework.Assert;
                      ^
\platforms\android\app\src\main\java\com\marianhello\bgloc\service\LocationServiceIntentBuilder.java:164: error: cannot find symbol
        Assert.assertNotNull("Context can not be null!", mContext);
        ^
  symbol:   variable Assert
  location: class LocationServiceIntentBuilder
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.`

I am using "cordova-plugin-mauron85-background-geolocation": "^3.0.0-alpha.50" version

**Comment by le0dime** [comment]
@mowaiskalam 

Hey guys, for anyone having this issue the fix is quite simple:

jUnit is used for testing purposes, I don't know why the dependecy is there. So what you have to do is open `LocationServiceIntentBuilder.java` and comment (or remove, it's the same) the following lines:

26 - `import junit.framework.Assert;`
164 - `Assert.assertNotNull("Context can not be null!", mContext);`

After that everything should be working as expected.

I'm going to submit a PR with those changes.
