### ISSUE TITLE
Continuous geo-location tracking

### ISSUE THREAD

**Issue by iBasit** [mauron85/cordova-plugin-background-geolocation#56]
I wanted to use this for tracking movement of the user continuously, but I have read the following on your doc:

> /*
>         IMPORTANT:  You must execute the finish method here to inform the native plugin that you're finished,
>         and the background-task may be completed.  You must do this regardless if your HTTP request is successful or not.
>         IF YOU DON'T, ios will CRASH YOUR APP for spending too much time in the background.
>         */

So I wanted to ask you and confirm, I cannot track user continuously, even tho I do not sent ajax request at all? 

What can I do to get continous location while in background, if this is not a proper plugin for it.

**Comment by mauron85** [comment]
You can track users just fine. But you make sure you call finish method. It's just iOS requirement for background tasks.

**Comment by iBasit** [comment]
but if I call background.finish() method, wouldn't that stop posting geolocation location in background?

**Comment by mauron85** [comment]
no, finish method will not stop background tracking nor posting. There is stop method that does that.
