### ISSUE TITLE
Ionic4 - android merged manifest build error

### ISSUE THREAD

**Issue by lcatania** [mauron85/cordova-plugin-background-geolocation#562]
## Your Environment

* Plugin version: 3.0.0-alpha.50
* Platform: Android
* OS version: /
* Device manufacturer and model: 

* Running in Simulator:
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): 8.0.0
* Plugin configuration options: 
* Link to your project:

## Context

Hey, i tried to get the background geolocation working in my ionic 4 app.

I added the sample code into my app but tried to build the android project but it throws an building error:

```
Android resource linking failed
D:\Amicido\99-Users-l.catania\ion4\android\app\build\intermediates\merged_manifests\debug\AndroidManifest.xml:113: error: resource string/mauron85_bgloc_content_authority (aka com.amicido.app:string/mauron85_bgloc_content_authority) not found.
error: failed processing manifest.
```

I added the code sample to the entry point (app.component.ts)

```
 async initializeApp() {
    this.objWindow = this.windowRef.nativeWindow;

    this.setupDefaults();

    await this.platform.ready();
    this.setupAndroidHeaderColor();
    this.setupStatusBar()
    const config: BackgroundGeolocationConfig = {
      desiredAccuracy: 10,
      stationaryRadius: 20,
      distanceFilter: 30,
      debug: true, //  enable this hear sounds for background-geolocation life-cycle.
      stopOnTerminate: false, // enable this to clear background location settings when the app terminates
    };

    this.backgroundGeolocation.configure(config)
      .then(() => {

        this.backgroundGeolocation.on(BackgroundGeolocationEvents.location).subscribe((location: BackgroundGeolocationResponse) => {
          console.log(location);

          // IMPORTANT:  You must execute the finish method here to inform the native plugin that you're finished,
          // and the background-task may be completed.  You must do this regardless if your operations are successful or not.
          // IF YOU DON'T, ios will CRASH YOUR APP for spending too much time in the background.
          this.backgroundGeolocation.finish(); // FOR IOS ONLY
        });

      });

    // start recording location
    this.backgroundGeolocation.start();

    // If you wish to turn OFF background-tracking, call the #stop method.
    this.backgroundGeolocation.stop();
  }
```

Does someone know why this happens.

Thanks in advantage

## Steps to Reproduce

1.
2.
3.
4.

**Comment by TobiasFP** [comment]
Why would you close it without responding what the fix was?
Please, provide a fix for other people who are dealing with the same issue.

**Comment by TobiasFP** [comment]
For those migrating to capacitor, the problem is most probably with your android manifest.
In the old cordova config.xml you had a section like so:

`    <plugin name="cordova-plugin-mauron85-background-geolocation" spec="^3.0.1">
        <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="11.6.2" />
        <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="23+" />
        <variable name="ICON" value="@mipmap/icon" />
        <variable name="SMALL_ICON" value="@mipmap/icon" />
        <variable name="ACCOUNT_NAME" value="@string/app_name" />
        <variable name="ACCOUNT_LABEL" value="@string/app_name" />
        <variable name="ACCOUNT_TYPE" value="$PACKAGE_NAME.account" />
        <variable name="CONTENT_AUTHORITY" value="$PACKAGE_NAME" />
    </plugin>`

This needs to be transfered to the new capacitor strings, here:
/platforms/android/app/src/main/res/values/strings.xml
like so:
(Make sure to use your own app id)
<string name="mauron85_bgloc_content_authority">com.company.appname</string>

Write here if you need a follow up

**Comment by baluworks** [comment]
Hi Guys,

 i have tried using this background geo location plugin. i did the changes you suggested. but stil i am getting this error

 My Tech StackL Ionic4+react+capacitor :
* What went wrong:
```
Execution failed for task ':capacitor-cordova-android-plugins:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/admin/Documents/544368/SNI/Schbneider-new/schneider-master/android/capacitor-cordova-android-plugins/build/intermediates/aapt_friendly_merged_manifests/release/processReleaseManifest/aapt/AndroidManifest.xml:57: error: resource string/mauron85_bgloc_content_authority (aka capacitor.android.plugins:string/mauron85_bgloc_content_authority) not found.
  error: failed processing manifest.
```
