### ISSUE TITLE
Edit android native code

### ISSUE THREAD

**Issue by mtnskb** [mauron85/cordova-plugin-background-geolocation#563]
## Your Environment

* Plugin version: 3
* Platform: Android
* OS version:
* Device manufacturer and model:

* Running in Simulator:
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

## Context
it's not a issue. 
I need edit format data in http post. In the older versions, when you download the plugin you can modified directly in the folder android/common. But in the newest version when I download the plugin, the folder common is empty.
Can you tell me some indications?

**Comment by mauron85** [comment]
You probably downloaded version 3.0.2, which was erroneous and I had it pulled down. Try v3.0.3

**Comment by Zerkk** [comment]
@mauron85 this version do work with ionic?.
I am trying to install but it not working

**Comment by mauron85** [comment]
I can't really tell. I don't use ionic myself. I'll have to try. There are some ionic related threads here on github issues. Maybe check those.

**Comment by mtnskb** [comment]
> You probably downloaded version 3.0.2, which was erroneous and I had it pulled down. Try v3.0.3

![Screenshot 2019-03-29 at 21 24 18 3](https://user-images.githubusercontent.com/46711519/55260629-29edba00-5269-11e9-8a9e-df11e690fa74.png)
![Screenshot 2019-03-29 at 21 35 47](https://user-images.githubusercontent.com/46711519/55261234-aaf98100-526a-11e9-8533-ebfe6556e3d3.png)

I think I didn't explain very well. In the first attachment picture is the folder android, from 3.0.3 version. And the common folder is empty. However in the second picture, at github, the folder contain java files with native android code. I need put some code in onlocationchaged...

thanx!

**Comment by mauron85** [comment]
I thought we are talking about package downloaded from npm.

If you clone github repo localy. I have clone `common` submodule:

```
git submodule init
git submodule update
```

PS: github is linking submodules automatically, but when you click you can check you're at different project.

**Comment by enzonotario** [comment]
Hi @mtnskb , try to clone https://github.com/mauron85/background-geolocation-android inside `common`... that worked for me!
