### ISSUE TITLE
Play Services Problem - PhoneGap Build

### ISSUE THREAD

**Issue by Gazoop** [mauron85/cordova-plugin-background-geolocation#564]
## Your Environment

* Plugin version: 3.0.3
* Platform: Android
* OS version: 
* Device manufacturer and model: Samsung Galaxy S9

* Running in Simulator:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

## Context

I am unable to successfully specify a play services version in config.xml for a Phone Gap Build project, it is conflicting with another plugin which is using a specific newer version, but this app default is 11+.

## Expected Behavior

Be able to specify a version number such as.

 `<plugin name="@mauron85/cordova-plugin-background-geolocation">
   		<variable name="PLAY_SERVICES_VERSION" value="xxxx" />
   </plugin>`

## Actual Behavior

Keeps to default 11+

## Possible Fix

https://blog.phonegap.com/the-play-services-problem-with-cordova-applications-489c9aeb2e89

https://github.com/floatinghotpot/cordova-admob-pro/pull/645

## Steps to Reproduce

1. Install plugins pushwoosh-pgb-plugin and @mauron85/cordova-plugin-background-geolocation in Phone Gap Build.

## Context

Unable to build application.

## Debug logs

BUILD FAILED in 23s
28 actionable tasks: 28 executed
Error: /var/gimlet/tmp/47444662808800/794826/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/var/gimlet/tmp/47444662808800/794826/app/src/main/java/com/marianhello/bgloc/data/BackgroundActivity.java:20: error: cannot access zzbfm
        confidence = activity.getConfidence();
                             ^
  class file for com.google.android.gms.internal.zzbfm not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

**Comment by mauron85** [comment]
You can specify google play version. Check https://github.com/mauron85/cordova-plugin-background-geolocation#installing-the-plugin

**Comment by Gazoop** [comment]
So much google'ing, hunting, and reading your old documentation, followed by repeat build failures, ahh! I have no clue how I managed to miss that. Thanks for your help.
