### ISSUE TITLE
Ionic - start() not returning Promise neither failing

### ISSUE THREAD

**Issue by doj04t** [mauron85/cordova-plugin-background-geolocation#566]
## Your Environment

* Plugin version: 3.0.3
* Platform: Android
* OS version: 9
* Device manufacturer and model: Xiaomi MI A1 + simulator

* Running in Simulator: Yes
* Cordova version (`cordova -v`): 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (`cordova platform ls`): android 7.1.4
* Plugin configuration options: 
```
public GEOLOCATION_CONFIG: any = {
    desiredAccuracy: 0,
    locationProvider: 0,
    stationaryRadius: 15,
    distanceFilter: 10,
    debug: false,
    stopOnTerminate: false,
    notificationTitle: 'APP',
    notificationText: 'Background geolocation enabled',
    notificationsEnabled: true,
    interval: 10000,
    fastestInterval: 5000,
    activityType: 'AutomotiveNavigation',
    pauseLocationUpdates: false,
    saveBatteryOnBackground: false,
    stopOnStillActivity: false,
    startForeground: true
  };
```
* Link to your project: not public adding code fragment
```
BackgroundGeolocation.start().then(value => {
  console.log('GeolocationService.startGeoLocation.start: ' + value);
  return value;
}).catch(reason => {
  console.log('GeolocationService.startGeoLocation.start.error: ' + reason);
});
```
## Context

Despite the start() method definition:
```
    /**
     * Turn ON the background-geolocation system.
     * The user will be tracked whenever they suspend the app.
     * @returns {Promise<any>}
     */
    start(): Promise<any>;
```

is not returning any Promise. 

## Expected Behavior

"Then" or "catch" section for start() method are reached after starting the background geolocation

## Actual Behavior

"Then" and "catch" sections for start() method are inaccesible

## Steps to Reproduce

I was trying to execute the following code but the code inside the then or catch sections for start() is not being reached:

```
BackgroundGeolocation.configure(this.GEOLOCATION_CONFIG).then(value => {
  BackgroundGeolocation.start().then(value => {
    // Not hiting this code
    const currentPositionConfig: BackgroundGeolocationCurrentPositionConfig = {
      enableHighAccuracy: true,
      maximumAge: 10000,
      timeout: 300000
    };

    BackgroundGeolocation.getCurrentLocation(currentPositionConfig).then(location => {
      // Do some stuf with location
    });
  }).catch(reason => {
    // Not hiting this code
    console.log(reason);
  });
}).catch(reason => {
  console.log(reason);
});
```

If I try to get current location without waiting for the start() method to finalize the app is crashing:

```
// Configure background geolocation plugin
BackgroundGeolocation.configure(this.GEOLOCATION_CONFIG);

// Start background geolocation
BackgroundGeolocation.start();

const currentPositionConfig: BackgroundGeolocationCurrentPositionConfig = {
  enableHighAccuracy: true,
  maximumAge: 10000,
  timeout: 300000
};

// APP crash when performing this call
BackgroundGeolocation.getCurrentLocation(currentPositionConfig).then(location => {
  // Do some stuf with location
});
```

**Comment by mauron85** [comment]
I believe that ionic does support v2 only.

**Comment by mauron85** [comment]
There are some workaround discussed here on some issue thread, how to use v3 with ionic.

**Comment by xyboox** [comment]
> There are some workaround discussed here on some issue thread, how to use v3 with ionic.

@mauron85 can you please point to them? I can't seem to find them. Thanks!

**Comment by mauron85** [comment]
I think it was this one. https://github.com/mauron85/cordova-plugin-background-geolocation/issues/449#issuecomment-413816127

**Comment by xyboox** [comment]
Thanks @mauron85 ! Got it!

**Comment by coolvasanth** [comment]
> Thanks @mauron85 ! Got it!

Can you please guide me step by step on how to use it on Ionic 3 ?
