### ISSUE TITLE
stopOnTerminate does not work in iOS

### ISSUE THREAD

**Issue by Gurjit-ONEBCG** [mauron85/cordova-plugin-background-geolocation#568]
Background location service doesn't work in iOS on app terminate. But in android it works as expected

Here is the configuration

 const config: BackgroundGeolocationConfig = {
      desiredAccuracy: 10,
      stationaryRadius: 10,
      distanceFilter: 10,
      debug: true, //  enable this hear sounds for background-geolocation life-cycle.
      stopOnTerminate: false, // enable this to clear background location settings when the app terminates
      notificationTitle: "Test App",
      notificationText: "Route Tracking..",
      pauseLocationUpdates: false,
      activitiesInterval: 2000,
      stopOnStillActivity: false,
      saveBatteryOnBackground: false,
      //startOnBoot: true,
      locationProvider: this.backgroundGeolocation.LocationProvider.ANDROID_ACTIVITY_PROVIDER,
      interval: 2000,
      fastestInterval: 1000, 
      syncUrl:  
      syncThreshold: 100       // old value 100
    };

 

## Your Environment 
* Plugin version:2.3.6
* Platform: iOS  
* OS version:12 
* Device manufacturer and model:iPhone 6
  
* Cordova platform version (`cordova platform ls`):7.0  
 

## Expected Behavior
Plugin should work as expected in iOS as well

## Actual Behavior
Background location service does not work on app terminate

**Comment by gmix** [comment]
Hi! Did you find solution to fix problem?

**Comment by himanshu849** [comment]
Hi, when i kill the application background services is not working. Please help me guys.

device name: redmin note 5 pro
android os: Oreo

please help me with code. This will be grateful.

Thanks

**Comment by manpreetpc** [comment]
I have same issue in IOS . I have set 
stopOnTerminate: false
Its mean location will work after the app kill. But its not working. I have tried many time

Please help me
Thanks you in advance

**Comment by DhruvSakhiya** [comment]
having a same issue it is not working in ios if any one have any suggestions how it works i am using 3.1.0 version plugin and @ionic-native/background-geolocation": "^4.20.0.
