### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by PhillippOhlandt** [mauron85/cordova-plugin-background-geolocation#569]
## Your Environment

* Plugin version: ^3.0.3
* Platform: Android
* OS version: 9
* Device manufacturer and model: Oneplus 6

* Running in Simulator: no
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): android 8.0.0
* Plugin configuration options: Standard from Readme
* Link to your project:

## Context
I installed the plugin with the default config from the readme (for config.xml) and tried to generate the APK.

## Expected Behavior
The APK gets generated properly and the app functions the same way as before.

## Actual Behavior
I get a compile error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> Android resource linking failed
  /project-path/platforms/android/app/src/main/res/xml/authenticator.xml:2: AAPT: error: resource mipmap/icon (aka app.package.name:mipmap/icon) not found.

  error: failed linking file resources.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
23 actionable tasks: 1 executed, 22 up-to-date
/project-path/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> Android resource linking failed
  /project-path/platforms/android/app/src/main/res/xml/authenticator.xml:2: AAPT: error: resource mipmap/icon (aka app.package.name:mipmap/icon) not found.

  error: failed linking file resources.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
```

## Possible Fix
There seems to be something missing in my project I think.

## Steps to Reproduce
1. run the installation command from README
2. add the config entries to `config.xml`
3. deleted plugins and platforms folder content
4. run `cordova prepare` to regenerate plugins and platforms
5. run `cordova build android --release`

## Context
At this stage, I just want the APK to generate with the plugin being installed

## Debug logs
Relevant compile output is shown above.

**Comment by rathodkaran07** [comment]
Is this solved?

**Comment by PhillippOhlandt** [comment]
Yes, I had to configure the plugin to use `ic_launcher` instead of `icon`.
