### ISSUE TITLE
Unexpected behavior when installing from config 

### ISSUE THREAD

**Issue by globules-io** [mauron85/cordova-plugin-background-geolocation#573]
## Your Environment
* Plugin version: 3.0.3
* Cordova version: 7.1

## Context
Documentation states to install by adding to config.xml

`<plugin name="@mauron85/cordova-plugin-background-geolocation">
  <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="11+" />
  <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="23+" />
  <variable name="ALWAYS_USAGE_DESCRIPTION" value="App requires background tracking enabled" />
  <variable name="MOTION_USAGE_DESCRIPTION" value="App requires motion detection" />
</plugin>`

## Actual Behavior
The build crashes and plugin does not install properly

## Possible Fix
Documentation should be updated to

`<plugin name="cordova-plugin-mauron85-background-geolocation" spec="@mauron85/cordova-plugin-background-geolocation@~3.0.3">
        <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="11+" />
        <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="26+" />
        <variable name="ICON" value="@mipmap/icon" />
        <variable name="SMALL_ICON" value="@mipmap/icon" />
        <variable name="ALWAYS_USAGE_DESCRIPTION" value="App requires background tracking enabled to track deliveries" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="App requires motion detection to track deliveries" />
    </plugin>`

**Comment by mauron85** [comment]
Thank you for the report. Can you prepare PR for this? Should be easy. :)

**Comment by globules-io** [comment]
Done
