### ISSUE TITLE
build Code compilation error

### ISSUE THREAD

**Issue by UTSOURCE** [mauron85/cordova-plugin-background-geolocation#574]
## Your Environment
Plugin version: 
Cordova version: 7.1
![image](https://user-images.githubusercontent.com/14830459/55949198-a5e1fc00-5c84-11e9-8797-0d2e47375f19.png)

* Plugin version: 3.0.3
*Cordova  Platform: Android  7.1.1
* OS version: Windows 10
* Device manufacturer and model:

* Running in Simulator:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

## Steps to Reproduce

1.
![image](https://user-images.githubusercontent.com/14830459/55949333-eb9ec480-5c84-11e9-909b-3cdc210274a4.png)

**Comment by Able1991** [comment]
How did you solve the problem?
