### ISSUE TITLE
Stop posting HTTP background geolocation post to server after 1 hour

### ISSUE THREAD

**Issue by shermansmithh** [mauron85/cordova-plugin-background-geolocation#576]
## Your Environment

* Plugin version: 3.0.3
* Platform: Android
* OS version: Android 8.0 Oreo Samsung Experience 9.0
*cordova v = 8.1.2
* Frame work ionic v4
* Device manufacturer and model: Samsung S9

## Context
I run the application after one hour its stops working in the background and stop posting to the  
server. When i set the intervals in a lower rate it goes like 2 hours but then it also stops.

## Expected Behavior
I expect that the plugin goes forever in the background without stopping and keep sending to the server

## Possible Fix

I tried to uninstall webview , this was freezing the app after hours of background but it didnt fixed it.

## Steps to Reproduce

1. ionic cordova run android 
2.
3.
4.

## Context

I tired to run a realtime background traking application on firebase.

## Debug logs

When i debug and  call the function BackgroundGeolocation. checkStatus in the chome console debug its says its running and when i call the functions BackgroundGeolocation. getLocations() i also get the locations locally on the phone but after 1 or 2 hours it doesnt keep sending the location to the server but it keep storing them locally.

This is my code:
```
 firebase.auth().currentUser.getIdToken().then(data => {
            var vm = this;
            const authkey = data
            const userid = vm.userId
            this.plt.ready().then(() => {
                let config = {
                    locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
                    desiredAccuracy: BackgroundGeolocation.MEDIUM_ACCURACY,
                    stationaryRadius: 50,
                    debug: true,
                    distanceFilter: 50,
                    stopOnTerminate: false,
                    startOnBoot: true,
                    interval: 10000,
                    fastestInterval: 5000,
                    activitiesInterval: 10000,
                    stopOnStillActivity: false,
                    notificationsEnabled: false,
                    startForeground: true,
                    saveBatteryOnBackground: true,
                    notificationTitle: "Buzzer",
                    notificationText: "Explore Your Surroundings!",
                    url: "https://b/locations/" + userid+ ".json?auth=" + authkey,
                    syncUrl: "https://b/locations/" + userid+ ".json?auth=" + authkey
                }
                BackgroundGeolocation.configure(config);
                BackgroundGeolocation.start();
            });
        })```

**Comment by shermansmithh** [comment]
I found the error it was not the plugin it was that firebase token expired after one hour , How is a good way to Refresh de token?

**Comment by CaptainNelis** [comment]
@shermansmithh Firebase uses a token ID. This token is short lived and expires after 1 hour. I'm also looking for a way to refresh the token. Did you find a solution?

**Comment by shermansmithh** [comment]
@CaptainNelis  yes this worked for me `firebase.auth().currentUser.getIdToken(/ forceRefresh / true)
.then(function(idToken) {

}).catch(function(error) {

});`

**Comment by zhaoxu666** [comment]
When my ionic project retreated to the background for a few minutes, it could not be located.

**Comment by CaptainNelis** [comment]
I resolved the issue by using session cookies instead of the tokenId.
https://firebase.google.com/docs/auth/admin/manage-cookies
