### ISSUE TITLE
[Solved] @latitud and @longitud are sent as strings

### ISSUE THREAD

**Issue by sbellver** [mauron85/cordova-plugin-background-geolocation#578]
## Your Environment

* Plugin version: 3.0.1
* Platform:  Android
* OS version: MacOs 10.14.4
* Device manufacturer and model: Simulator and LG k9

cordova 8.1.2 (cordova-lib@8.1.1)
cordova-android 7.1.4
ionic 4.12.0
ionic 1 app

## Context
In postTemplate, when i set lat/long to '@latitude' it send as literal string, not as float number

## Expected Behavior
@latitude needs to be as 39,xxxxxx

## Actual Behavior
@latitude is  '@latitude'
(and long, time, ... whatever event'

## Steps to Reproduce

`
BackgroundGeolocation.configure({
                  locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
                  desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
                  stationaryRadius: 20,
                  distanceFilter: 30,
                  debug: false,
                  interval: 10000,
                  fastestInterval: 5000,
                  activitiesInterval: 10000,
                  url: $scope.usuario['hostgeo'],
                  httpHeaders: {
                    'Content-Type': 'application/x-www-form-urlencoded'
                  },
                  // customize post properties
                  postTemplate: {
                    id_tecnico : $scope.usuario.id,
                    plataforma : ionic.Platform.platform(),
                    terminalmo : $scope.deviceInUse.manufacturer+' '+$scope.deviceInUse.model,
                    timestamp : '@time',
                    latitude: '@latitude',
                    longitude: '@longitude'
                  }
                });
`
## Debug logs

` 	[2019/04/15 15:39:52] com.marianhello.bgloc.BackgroundGeolocationFacade:Service configured with: Config[distanceFilter=30 stationaryRadius=20.0 desiredAccuracy=0 interval=10000 fastestInterval=5000 activitiesInterval=10000 isDebugging=true stopOnTerminate=true stopOnStillActivity=true startOnBoot=false startForeground=true notificationsEnabled=true locationProvider=1 nTitle=Background tracking nText=ENABLED nIconLarge= nIconSmall= nIconColor= url=https://URL/api/acciones.php?action=setUbicacion syncUrl= syncThreshold=100 httpHeaders={Content-Type=application/x-www-form-urlencoded} maxLocations=10000 postTemplate={"terminalmo":"LGE LM-X210","plataforma":"android","id_tecnico":3,"latitude":@latitude,"longitud":@longitude,"timestamp":@time}]`

**Comment by sbellver** [comment]
When it arrives to server lat/long are correct. Not sure why here are showed as strings.

**Comment by allensutton** [comment]
@sbellver - what solved your issue?  I am having a similar problem, but with @provider.  For iOS it is sent as a literal string instead of actually sending the location provider.  I am wondering if whatever you found with your code will help me as well.

**Comment by sbellver** [comment]
Not sure.
Maybe is a cordova version or a cordova-ios version.
Now i use cordova 8 and cordova-ios 4.5.5
