### ISSUE TITLE
subscribe does not exist on type 'Promise<any>'

### ISSUE THREAD

**Issue by VictorManuelC** [mauron85/cordova-plugin-background-geolocation#582]
## Your Environment

* Plugin version:cordova-plugin-mauron85-background-geolocation 3.0.0-alpha.50
* Platform:  Android 8.0
* Device manufacturer and model:Samsung Galaxy S7

* Running in Simulator: x
* Cordova version (`cordova -v`): 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (`cordova platform ls`):android@6.4.0, ios@4.5.5
* Plugin configuration options: 

config: BackgroundGeolocationConfig = {
    desiredAccuracy: 10,
    stationaryRadius: 20,
    distanceFilter: 30,
    debug: false, //  habilitar los sonidos y los toast del rastreo
    stopOnTerminate: false, // forzar el cierre del backgroungeolocation

    /* para android */
    startOnBoot: true,  //para que empiece el tracking cuando prende el celular

    /* para ios */
    activityType: "Fitness",
    pauseLocationUpdates: false
  };

this.backgroundGeolocation.configure(this.config)
      .subscribe((location: BackgroundGeolocationResponse) => {
        console.log("debug del location " + location);       
        
        this.latitud = location.latitude;
        this.longitud = location.longitude;
        
        this.insertcoordenada(this.insertid, this.latitud, this.longitud, this.time, this.fecha);
               
        // IMPORTANT:  You must execute the finish method here to inform the native plugin that you're finished,
        // and the background-task may be completed.  You must do this regardless if your HTTP request is successful or not.
        // IF YOU DON'T, ios will CRASH YOUR APP for spending too much time in the background.
        this.backgroundGeolocation.finish(); // FOR IOS ONLY
      }, error => console.log(error));

      // start recording location
      this.backgroundGeolocation.start();
  }

## Context

good, working with the plugin in ionic that I have been a series of conflicts, the first was that I always marked this error with new versions of the plugin "Property 'subscribe' does not exist on type 'Promise<any>'.", investigating I managed to find a stable version that did not mark me that error, the version is: "2.3.6", pero con esa version se tiene un detalle que es el startonboot que se detiene al reiniciar el celular, otra vez investigando encontre que actualizando en el alpha ya estaba solucionado ese detalle.

but since I am new in this the new configuration I do not know where to fit it and the configuration that already had me marks the following error:

 typescript: .../Manuel Cabrera/Desktop/MyLoyaltyMX2_0_Mobile/src/providers/tracking/tracking.ts, line: 95
            Property 'subscribe' does not exist on type 'Promise<any>'.

      L94:  this.backgroundGeolocation.configure(this.config)
      L95:    .subscribe((location: BackgroundGeolocationResponse) => {
      L96:      console.log("debug del location " + location);

Error: Failed to transpile program
[DEBUG] Error: Failed to transpile program
            at new BuildError (C:\Users\Manuel
        Cabrera\Desktop\MyLoyaltyMX2_0_Mobile\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
            at C:\Users\Manuel
        Cabrera\Desktop\MyLoyaltyMX2_0_Mobile\node_modules\@ionic\app-scripts\dist\transpile.js:159:20
            at new Promise (<anonymous>)
            at transpileWorker (C:\Users\Manuel
        Cabrera\Desktop\MyLoyaltyMX2_0_Mobile\node_modules\@ionic\app-scripts\dist\transpile.js:107:12)
            at Object.transpile (C:\Users\Manuel
        Cabrera\Desktop\MyLoyaltyMX2_0_Mobile\node_modules\@ionic\app-scripts\dist\transpile.js:64:12)
            at C:\Users\Manuel
        Cabrera\Desktop\MyLoyaltyMX2_0_Mobile\node_modules\@ionic\app-scripts\dist\build.js:109:82
            at "< anonymous >"

If someone could help me, I would thank you for it, using the then and nothing happens

**Comment by ValentinKlinghammer** [comment]
I'm sorry man, but this is hard to read, you're switching languages mid-sentence.

You literally just need to copy & paste the code from [ionic-native](https://ionicframework.com/docs/native/background-geolocation). Your error is that you subscribe to the return value of `.configure` which returns a promise. It's not meant to be subscribed to. You subscribe to e.g. `this.backgroundGeolocation.on('location').subscribe(location => console.log(location));`

```
this.backgroundGeolocation.configure(config)
  .then(() => {

    this.backgroundGeolocation.on('location').subscribe((location: BackgroundGeolocationResponse) => {
      console.log(location);

      // IMPORTANT:  You must execute the finish method here to inform the native plugin that you're finished,
      // and the background-task may be completed.  You must do this regardless if your operations are successful or not.
      // IF YOU DON'T, ios will CRASH YOUR APP for spending too much time in the background.
      this.backgroundGeolocation.finish(); // FOR IOS ONLY
    });

  });

```
