### ISSUE TITLE
does not contain a package.json

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#585]
## Your Environment

* Plugin version: 3.0.3
* Platform: iOS or Android
* OS version: 7
* Device manufacturer and model:

* Running in Simulator: NO
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`): 
* Plugin configuration options: 
* Link to your project:

## Context
For some reason, whenever, I try to build the application after I install this plugin I am getting the following error: 
`Could not install from "@mauron85/cordova-plugin-background-geolocation@~3.0.3" as it does not contain a package.json file.`

Happening only with this plugin. I tried removing the platform, removing `node_modules` folder, reinstalling the plugin, nothing is working.

**Comment by Genarito** [comment]
Same problem here

**Comment by Genarito** [comment]
Ok, thanks to [this answer in another plugin's issue](https://github.com/ionic-team/ionic-cli/issues/2454#issuecomment-320839317) I could solve It. Hope It helps.
