### ISSUE TITLE
Unable to start service Intent U=0: not found on start

### ISSUE THREAD

**Issue by leobaccili** [mauron85/cordova-plugin-background-geolocation#586]
## Your Environment

* Plugin version: 3.0.3
* Platform: Android
* OS version: 8.1.0
* Device manufacturer and model:

* Running in Simulator: Yes
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

## Context

This error appears when i start tracking.
## Steps to Reproduce

1.
2.
3.
4.

## Debug logs

05-06 11:27:18.849  4341  4460 D com.marianhello.bgloc.BackgroundGeolocationFacade: Starting service
05-06 11:27:18.862  4341  4445 D com.marianhello.bgloc.data.sqlite.SQLiteConfigurationDAO: Configuration persisted with rowId = 1
05-06 11:27:18.866  4341  4445 D com.marianhello.bgloc.BackgroundGeolocationFacade: Service configured with: Config[distanceFilter=0 stationaryRadius=10.0 desiredAccuracy=0 interval=600000 fastestInterval=120000 activitiesInterval=10000 isDebugging=false stopOnTerminate=false stopOnStillActivity=true startOnBoot=false startForeground=true notificationsEnabled=true locationProvider=0 nTitle=Rastreamento nText=ativo nIconLarge= nIconSmall= nIconColor= url=http:///api/coordinate syncUrl= syncThreshold=100 httpHeaders={Authorization=Bearer, Content-Type=application/json} maxLocations=99999 postTemplate={"route":[{"latitude":"@latitude","time":"@time","longitude":"@longitude"}],"coordinateId":"5cd01a1e8cabd9275066a62a"}]
05-06 11:27:18.871  4341  4460 I com.marianhello.bgloc.BackgroundGeolocationFacade: User granted requested permissions
05-06 11:27:18.874  4341  4400 E eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
05-06 11:27:18.874  4341  4400 E eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
05-06 11:27:18.898  4341  4460 I com.marianhello.bgloc.BackgroundGeolocationFacade: Attempt to start bg service
05-06 11:27:18.918  1638  2460 W ActivityManager: Unable to start service Intent { cmp=com.package.name/com.marianhello.bgloc.service.LocationServiceImpl (has extras) } U=0: not found

**Comment by kumaartarun** [comment]
**Enviroment**

- Plugin version: 3.0.3
- Platform: Android
- OS version: OxygenOS version 9.0.13 Build A6010_41_190403
- Device manufacturer and model: OnePlus 6T
- Running in Simulator: No
- Cordova version (cordova -v): 9.0.0 (cordova-lib@9.0.1)
- Plugin Specific config.xml  : 
- <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="10.+" /> 
- <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
- Other Plugin using Play Services : 
- cordova-plugin-firebase-extended-notification
**Context**
Error occur while starting background Services on debug.apk running on real device(OnePlus 6T) 

**Steps to Reproduce**
Plugin configuration options:
stopOnTerminate: false, startOnBoot: true, startForeground: true, notificationsEnabled: true,

BackgroundGeolocation.configure(bgGeoOptions);
BackgroundGeolocation.start();

BackgroundGeolocation.on('start', function () {
startFunction(); // Note:  Never Executed 
});
**Debug Log** 
05-15 10:23:37.564 3838-3993/inn.tikona.ontime I/com.marianhello.bgloc.BackgroundGeolocationFacade: Attempt to start bg service
05-15 10:23:37.564 886-7963/? E/LocationManagerService: requestLocationUpdates: uid=10221, pid=3838, provider=fused, package=inn.tikona.ontime listener= android.location.ILocationListener$Stub$Proxy@2008168 intent= null
05-15 10:23:37.568 886-909/? W/ActivityManager: Unable to start service Intent { cmp=inn.tikona.ontime/com.marianhello.bgloc.service.LocationServiceImpl (has extras) } U=0: not found
05-15 10:23:37.570 886-7963/? D/LocationManagerService: DumpUpdateRecord
