### ISSUE TITLE
i want remove "tracking enable notification" from background

### ISSUE THREAD

**Issue by nisalmalinga** [mauron85/cordova-plugin-background-geolocation#588]
i want remove notification from "tracking enable notification"
how can i do that
![41916397-92fc5036-791d-11e8-9b6d-f92dfe21fdde](https://user-images.githubusercontent.com/14048635/57352002-8eae0580-7181-11e9-963a-2a42c3d04355.jpg)
please see image

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\Mihindu-LAP\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.1.0
   @angular-devkit/build-angular : 0.12.1
   @angular-devkit/schematics    : 7.1.4
   @angular/cli                  : 7.3.7
   @ionic/angular-toolkit        : 1.2.2

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 3.1.2, (and 5 other plugins)

System:

   Android SDK Tools : 26.1.1 (D:\AndroidSDK\sdk)
   NodeJS            : v8.11.4 (C:\Program Files\nodejs\node.exe)
   npm               : 5.6.0
   OS                : Windows 10

@mauron85

**Comment by AleRohvt** [comment]
I have the same problem too. @mauron85

**Comment by RidClick** [comment]
Any solution of this?

**Comment by manpreetpc** [comment]
set 
debug: true
In config

**Comment by JackyLau** [comment]
I tried Disable "notificationsEnabled" … but no effect

**Comment by shalini-github** [comment]
tried this still the notification is not removed

> set
> debug: false
> In config
