### ISSUE TITLE
Next version

### ISSUE THREAD

**Issue by piotrekfracek** [mauron85/cordova-plugin-background-geolocation#59]
Hi,
When do you guys planning (approximately of course) to release next version?

Very good job btw.!

**Comment by mauron85** [comment]
As I'm too busy with my own business, I cannot give you any ETA. Sorry. But any help on new version is welcome. Like auto posting of position over HTTP...

**Comment by uzumakinaruto123** [comment]
@mauron85  i implemented a custom async task from handleLocation which works pretty well for my requirement. and i somehow managed to make it work in background without notification in the drawer. did nothing rocket science but i just stopped it from starting in foreground. lol. which is ok for my requirement. 

any drawback of stopping it to start in foreground ?( except the callback not reaching cordova plugin)

**Comment by mauron85** [comment]
@uzumakinaruto123 it would be great if you can send PR here. You'll be recognised as contributor with all the fame and glory :-). The code doesn't have to be perfect (I'm not fascist) We can discuss what are the drawbacks or ask users of this plugin. Actually there is some discussion regarding this in #20.

**Comment by uzumakinaruto123** [comment]
@mauron85  i never did a pull request. till now i have been making changes in my app so it includes all raw coding(noob :p) . i mean all properties like `url,post data,server api key` are not coming from javascript. i simply hard coded those. 
  my changes are not worth a PR .   i will try adding new plugin object properties if i could so that i can make a PR.
I followed you on twitter few days back to discuss and show my code. but i couldn't message since you dont follow me. :p  

anyways thanks for your work :) appreciate.

**Comment by shyamal890** [comment]
@uzumakinaruto123 @mauron85 Wow! You guys are doing great job. Thanks a lot. Really appreciate.

**Comment by shyamal890** [comment]
@uzumakinaruto123 can you please post your code here, may be someone can improvise on it if needed. I for one would like to utilize the raw code itself.

**Comment by btdevn** [comment]
@uzumakinaruto123 even if not as a PR, but please share your raw code. it will be a lot of help to the community.

**Comment by mauron85** [comment]
I've just pushed update to next version branch. It has very basic http posting of location, currently for Android only. There are two option attributes currently (url and httpHeaders). Read docs of next branch, specially [configure](https://github.com/mauron85/cordova-plugin-background-geolocation/tree/next#backgroundgeolocationconfiguresuccess-fail-option) and [HTTP location posting](https://github.com/mauron85/cordova-plugin-background-geolocation/tree/next#http-location-posting).

Install via:
```
cordova plugin add cordova-plugin-mauron85-background-geolocation@next
```

And tell me what you think/need.

**Comment by uzumakinaruto123** [comment]
@shyamal890  @btdevn  Ok here its but it might not be perfect. and **understand**  i have nothing to do with javascript i only configure and toggle background service from javascript. <br>

That means no kind of callback would return to your javascript file. it has to be like this because callbacks in javascript are of no use when app is terminated.<br>



In your added android platform , you can catch all location updates here .
`platforms/android/src/com/tenforwardconsulting/cordova/bgloc/AbstractLocationService.java`

<br>
> i assume we all use some editor and not android studio so its difficult to know the packages to import. these are the packages needed. I am just posting all i used you can figure which one you need.

```
import java.util.Random;
import org.json.JSONException;
import org.json.JSONArray;
import org.json.JSONObject;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.*;
import java.net.URLConnection;
import java.io.*;
import android.os.AsyncTask;
import java.util.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import com.your.package.NotificationHelper; // <-- Custom sql database helper i needed for the app
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteDatabase;
```



<br><br>




find   `protected void handleLocation (Location location) { }`
<br><br>

```
 protected void handleLocation (Location location) {
      final LocationProxy bgLocation = LocationProxy.fromAndroidLocation(location);
      bgLocation.setServiceProvider(config.getServiceProvider());


       if (config.isDebugging()) {
            bgLocation.setDebug(true);
            persistLocation(bgLocation);
        }


       //here we have location in bgLocation. we need to convert it to string to pass it to async task.
       // we want to make http calls in background mode so we need do it in async task.


        try {
            String locStr = bgLocation.toJSONObject().toString();
            Intent intent = new Intent(Constant.ACTION_FILTER);

             CustomfunctionTask task = new AbstractLocationService.CustomfunctionTask();
              task.execute(locStr);  // THIS INITIATES OUR ASYNC


           //REST OF try catch block
          }


        //REST OF THE handle location() CODE BELOW

}


```

<br><br>
Create this Async task in he same file
<br>


```
private class CustomfunctionTask extends AsyncTask<String, Void, String> {

       @Override
        protected String doInBackground(String... locStr) {

                 try {
                          Log.i(TAG,"Entered Background Posting"+locStr[0]);
                          JSONObject mylocation = new JSONObject(locStr[0]);
                          Log.i(TAG,"Custom FunctionLatiitude:"+mylocation.getString("latitude"));




                    //here i fetch some data from my custom database. like user preference for radius etc
                   // create a string object to post it to the URL. please ignore the additional properties from below object.



                   String testdata =  "{\"radius\":"+userradii+",\"usercity\":\""+cityman+"\",\"latitude\": "+mylocation.getString("latitude")+",\"longitude\":"+mylocation.getString("longitude")+"}"; 

    
                     // before posting you can add your logic here whether to post data or not.
     
                      // example i connect  to two urls in this async. once to perform some user checks on the server.
                      // based on that response i decide whether to post notification or not.






                       HttpURLConnection conn=null;
              try{
                URL url = new URL("http://www.xyz.in/your/check.php");
                conn = (HttpURLConnection) url.openConnection();
                conn.setRequestMethod("POST");
                conn.setDoInput(true);
                conn.setDoOutput(true);
                conn.setRequestProperty("Content-Type", "application/json");
                conn.setRequestProperty("Accept", "application/json");
                conn.setUseCaches(false);

                DataOutputStream writer = new DataOutputStream(conn.getOutputStream());
               writer.writeBytes(testdata);
               writer.flush();
               writer.close();

               //Get Response

                InputStream is = conn.getInputStream();
                BufferedReader rd = new BufferedReader(new InputStreamReader(is));
                String line="";
                StringBuffer response = new StringBuffer();
                while((line = rd.readLine()) != null) {
                  response.append(line);
                  response.append('\r');
                }
                rd.close();

                JSONArray temp1 = new JSONArray(response.toString());






                //here temp1 array has response from the server. similarly i post notification here using calling rest api endpoint of my push service.


                  if(send){
                               http connection to push service rest api. same way we did for the first link above
                   }





                         }catch (MalformedURLException e) {
                                 Log.d(TAG,Log.getStackTraceString(e));
                         }


                  } catch (Throwable e) {
                           Log.e(TAG,"Exception posting data: " + e);
                   }

         }

         @Override
        protected void onPostExecute(String result) {

        }


}
```

**Comment by uzumakinaruto123** [comment]
the code might be confusing but i tried my best. 

@mauron85 has updated the plugin with next branch if you simply want to post data.  :)

**Comment by mauron85** [comment]
@uzumakinaruto123  your implementation is very close to mine in next branch. 👍  The next branch is missing some sync mechanism, when there is no network and iOS part.

**Comment by uzumakinaruto123** [comment]
yes :) Thanks for the  update. am planning on updating to the next branch. only the thing is i need to connect to two links.where second is dependent on first ones response. but i guess i can handle that once i update.

just to confirm `ANDROID_FUSED_LOCATION` is renamed to `ANDROID_ACTIVITY_PROVIDER` right?
working is same ? Thanks.

**Comment by mauron85** [comment]
@uzumakinaruto123 yes it's renamed to express more that it uses activities. Also Intent communication bgservice -> app main activity was replaced with IPC messenger pattern, but it should behave same.

Also I've start implementing other methods for iOS (showLocationSettings, ....) so maybe checkout from git instead of npm.

**Comment by uzumakinaruto123** [comment]
is opening settings in ios possible ? i found no plugin for that. even cordova diagnostic doesn't have that option. 

The only issue now that bothers me is restart of the service. even when notification is in the panel the service is taking a lot of time to restart.  I have been trying to resolve this.

if user kills the app, service tries to restart again . If by any chance user locks the device before its restarted then it would take forever to restart again. It wont even try to restart in locked state.

After reading some stackoverflow posts what i found was `START_STICKY` resumes immediately. i am trying to find that post again. But since we have intents to restart with, app crashes if we use `START_STICKY`.  I have seen some apps which behave like our service they try to restart. but they resume immediately. 

Thanks ! :)

**Comment by mauron85** [comment]
> is opening settings in ios possible ?

Yes, it is. Code is already in git.

> START_STICKY resumes immediately

I've experimented a lot with those values. Currently START_REDELIVER_INTENT is used, so 

> if this service's process is killed while it is started (after returning from onStartCommand(Intent, int, int)), then it will be scheduled for a restart and the last delivered Intent re-delivered to it again via onStartCommand(Intent, int, int)

which assures, it will also restart service always with same config options. You can replace it with START_STICKY and reload config from db (config is also persisted). But it doubt it would help. Anyway, let know your results.

The main problem with service crash (and slow restart) is [Android bug](https://code.google.com/p/android/issues/detail?id=53313) as I wrote in issue #9.

**Comment by uzumakinaruto123** [comment]
ya ! i saw the next branch i think you have pushed one of the workarounds  from that android issue tracker.  DummyActivity ones. So  i think before trying anything weird i should try next branch as it is :p 

Thanks for the great work. appreciate.

**Comment by uzumakinaruto123** [comment]
@mauron85  I updated the plugin ,it works good. service resumes quickly. that was great Thanks ! appreciate your work. I need to check on other android versions and other RAM eating ROM's :D
