### ISSUE TITLE
Aplicativo não captura localização após ser encerrado - Android 9

### ISSUE THREAD

**Issue by rafaelgalle** [mauron85/cordova-plugin-background-geolocation#593]
## My Environment

* Plugin version: 3.0.3
* Platform: Android
* OS version: 9
* Device manufacturer and model: MOTOROLA G6 PLUS and (NEXUS 5X - VIRTUAL DEVICE)
* Running in Simulator: MOTOROLA - NO / NEXUS - YES
* Cordova version (`cordova -v`): 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (`cordova platform ls`):
Installed platforms:
  android 7.1.4
Available platforms:
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~6.0.0
* Plugin configuration options: 
* Link to your project: https://github.com/rafaelgalle/test-background-geo

## Context

After calling the start action the app starts capturing and notifying, while minimizing it it continues capturing and with the notification being displayed correctly, but when it closes it for capture and the notification continues to be displayed for a few seconds, and then the message that the app crashed, but the notification still displays, but when you click it the app is not opened, as if it were alone, loose, with no connection to the application.

The settings for removing the application from the battery optimization list were performed, so this is not a reason for the error.

Tests were performed with android versions lower than 9 and all worked correctly except version 9.
 
## Expected Behavior
Closing the app should continue capturing the location

## Actual Behavior
When you close the application the capture is canceled, notification continues to be displayed, but when you click it the app is not reopened, and the service is not in the list of services running the device.

## Possible Fix
...

## Steps to Reproduce
Link https://github.com/rafaelgalle/test-background-geo

1.Click the _configure() button.
2.Click the _start() button.
3.Minimize the app. 
4.Close the app. 
5.Click on the notification and verify that the application is not open.

To verify that the location worked while it was closed we can click the getLocations button to fetch the last captured locations

## Debug logs
...

**Comment by willmero** [comment]
I also seem to be having this issue with my app on Android 9 :(
