### ISSUE TITLE
Not working in background

### ISSUE THREAD

**Issue by homen** [mauron85/cordova-plugin-background-geolocation#6]
The plugin is working fine when the application is opened.But when the application is closed it is not working.I used your sample code as same it is.Any idea?

**Comment by mauron85** [comment]
Your platform is Android? And you're probably using ANDROID_FUSED_LOCATION service provider. If so, just wait for upcoming version. It will be fixed. And till then switch to ANDROID_DISTANCE_FILTER.

**Comment by homen** [comment]
Ok thank you.

**Comment by mauron85** [comment]
Ok. I'm closing this one.
