### ISSUE TITLE
Not able to get co-ordinates on regular interval

### ISSUE THREAD

**Issue by dhavalkakkad** [mauron85/cordova-plugin-background-geolocation#60]
Hi there,

The plugin works fine on my Android device, this is exactly I was looking for, The only need I have is regardless of the user's state, every 2 minutes I need the co-ordinates. I am using these cofigurations right now as suggested in doc and mentioned in some of the issues. But no luck. Please let me know if I am missing anything.

This is the code I have. 

`function onDeviceReady () {

  var callbackFn = function(location,$scope) {
   alert(location.latitude);
 alert(location.longitude);
  $scope.lat.push(location.latitude);
    $scope.lang.push(location.longitude);
  };
   var failureFn = function(error) {
       alert('BackgroundGeoLocation error');
    };
  backgroundGeoLocation.configure(callbackFn, failureFn, {
    desiredAccuracy: 10,
    notificationIconColor: '#4CAF50',
    notificationTitle: 'Traking Status',
    notificationText: 'ON',
    notificationIcon: 'notification_icon',
    debug: true, 
    stopOnTerminate: false,
    locationService: backgroundGeoLocation.service.ANDROID_FUSED_LOCATION,
    interval: 1000, 
    activitiesInterval: 1000
   });
 $scope.start = function()
 {
    backgroundGeoLocation.start();
 }
  $scope.stop = function()
 {
     backgroundGeoLocation.stop();
}`

One more thing, I am not able to see the text,icon,status I set for the notification area.

Any help is appreciated.

**Comment by uzumakinaruto123** [comment]
dhaval 
```

 interval: 120000, // <!-- poll for position every two minute
 fastestInterval: 120000
```


notification Icon property is applicable for only android >= api level 21, just incase you are testing it on jellybean/kitkat. try without setting icon

**Comment by mauron85** [comment]
Use ANDROID_FUSED_LOCATION and set interval as @uzumakinaruto123 is suggesting.
BUT keep in mind, when device is idle, it turn's gps off to save power (so there's no guarantee you'll get updates every 2 mins). However you can suggest that position didn't changed anyway.

**Comment by dhavalkakkad** [comment]
Thanks guys. Gonna make changes you both suggested and make some journeys today. 

@uzumakinaruto123 I am testing on Android 5.1 and API level is 23. What could be the other issue you think ?

@mauron85 I used disableElasticity:true as a config parameter and its giving me location update almost every 2 mins. This is just a first test though, can say more after more testing.

**Comment by mauron85** [comment]
There is no such option disableElasticity in this plugin. I know there is disableElasticity in former project cordova-background-geolocation-lt, which I have forked from.

**Comment by dhavalkakkad** [comment]
Lol. I thought that's why m getting updates. Will remove it then. Thanks

**Comment by mauron85** [comment]
To achieve regular updated for version 2.0.0 ise ANDROID_ACTIVITY_PROVIDER with option stopOnStillActivity false
