### ISSUE TITLE
Failed to install because no package.json

### ISSUE THREAD

**Issue by vlafranca** [mauron85/cordova-plugin-background-geolocation#600]
Hi everyone,
I am facing an issue on WIndows 10. WHen I'm adding the plugin to the project, all works fine. The plugin installs well and works well when compiled.
But when I try to freshly `npm install` my project, I get this message :
`Could not install from "@mauron85/cordova-plugin-background-geolocation@~3.0.3" as it does not contain a package.json`

The same error occur when executing cordova platform rm/add.

Thanks in advance for your help.

**Comment by HarelM** [comment]
I had the same issue. I also thought it was a glitch and reported it here: #596
But clearly it doesn't happen only to me, and I could reproduce it on another machine now.
The solution it to remove the `@mauron85/cordova-plugin-background-geolocation@~3.0.3` entry from the `dependencies` section (the entire line).
This is added after you add a platform, I think.
@mauron85 Can you take a look at this? I think it has to do with the fact that the name of the cordova plugin and the name in npm are not the same, or it has to do with the name change as it didn't happen before the rename.

**Comment by vlafranca** [comment]
Yes indeed if it's linked only in config.xml the plugin installs correctly but it is annoying to exclude particular package from package.json :/

**Comment by AleRohvt** [comment]
Hi, same problem for me too.

**Comment by acidumirae** [comment]
Hack to workaround the issue (it looks for the path in a weird location):

`(mkdir @mauron85 && cd @mauron85 && ln -s ../plugins/cordova-plugin-mauron85-background-geolocation cordova-plugin-background-geolocation@~3.0.3)`
