### ISSUE TITLE
Android build doesn't working

### ISSUE THREAD

**Issue by Taxi4you** [mauron85/cordova-plugin-background-geolocation#602]
I have installed as instructed:
1. cordova plugin add @mauron85/cordova-plugin-background-geolocation
2. Added this to config xml:

```
    <plugin name="cordova-plugin-mauron85-background-geolocation" spec="@mauron85/cordova-plugin-background-geolocation@~3.0.3">
        <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="11+" />
        <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="26+" />
        <variable name="ICON" value="@mipmap/icon" />
        <variable name="SMALL_ICON" value="@mipmap/icon" />
        <variable name="ALWAYS_USAGE_DESCRIPTION" value="Taxi4you requires background tracking to offer relevant nearby order" />
        <variable name="MOTION_USAGE_DESCRIPTION" value="Taxi4you requires motion detection to offer relevant nearby order" />
    </plugin>
```

3. Installed the required SDKS using Android Studio.

and receive this error when run **cordova run android**

```
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=/Users/razbuchnik/Library/Android/sdk (DEPRECATED)
Subproject Path: CordovaLib
Subproject Path: app

> Configure project :app
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Task :app:cdvCreateAssetManifest UP-TO-DATE
> Task :app:preBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:checkDebugManifest UP-TO-DATE
> Task :CordovaLib:processDebugManifest UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :CordovaLib:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :CordovaLib:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript UP-TO-DATE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateDebugSources UP-TO-DATE
> Task :CordovaLib:compileDebugRenderscript UP-TO-DATE
> Task :CordovaLib:generateDebugBuildConfig UP-TO-DATE
> Task :CordovaLib:generateDebugResValues UP-TO-DATE
> Task :CordovaLib:generateDebugResources UP-TO-DATE
> Task :CordovaLib:packageDebugResources UP-TO-DATE
> Task :CordovaLib:generateDebugRFile UP-TO-DATE
> Task :CordovaLib:prepareLintJar UP-TO-DATE
> Task :CordovaLib:generateDebugSources UP-TO-DATE
> Task :CordovaLib:javaPreCompileDebug UP-TO-DATE
> Task :CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
> Task :CordovaLib:processDebugJavaRes NO-SOURCE
> Task :CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mainApkListPersistenceDebug UP-TO-DATE
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:mergeDebugResources
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  /Users/razbuchnik/Projects/taxi4you/apps/drivers/cordova/platforms/android/app/src/main/res/xml/authenticator.xml:2: AAPT: error: resource mipmap/icon (aka il.co.taxi4you.drivers:mipmap/icon) not found.
      
  error: failed linking file resources.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.

BUILD FAILED in 8sSee https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings
24 actionable tasks: 3 executed, 21 up-to-date

/Users/razbuchnik/Projects/taxi4you/apps/drivers/cordova/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  /Users/razbuchnik/Projects/taxi4you/apps/drivers/cordova/platforms/android/app/src/main/res/xml/authenticator.xml:2: AAPT: error: resource mipmap/icon (aka il.co.taxi4you.drivers:mipmap/icon) not found.
      
  error: failed linking file resources.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taxi4you-drivers@1.0.0 android: `cross-env NODE_ENV=development && cd cordova && cordova run android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the taxi4you-drivers@1.0.0 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/razbuchnik/.npm/_logs/2019-06-25T12_42_34_952Z-debug.log
```

**Comment by vlafranca** [comment]
Hi,
You have android library version conflict, try to add something like this to your config.xml, then remove and readd your platform :

```
<plugin name="cordova-android-play-services-gradle-release" spec="^1.4.2">
        <variable name="PLAY_SERVICES_VERSION" value="15+" />
    </plugin>
    <plugin name="cordova-android-support-gradle-release" spec="^1.4.3">
        <variable name="ANDROID_SUPPORT_VERSION" value="26.+" />
    </plugin>```

**Comment by zhaoxu666** [comment]
> Hi,
> You have android library version conflict, try to add something like this to your config.xml, then remove and readd your platform :
> 
> ```
> <plugin name="cordova-android-play-services-gradle-release" spec="^1.4.2">
>         <variable name="PLAY_SERVICES_VERSION" value="15+" />
>     </plugin>
>     <plugin name="cordova-android-support-gradle-release" spec="^1.4.3">
>         <variable name="ANDROID_SUPPORT_VERSION" value="26.+" />
>     </plugin>```
> ```

Hi,
Thank you for your reply. when I add this in my comfig.xml ,remove my platform and readd my platform

Android project created with cordova-android@8.0.0
Installing "cordova-android-play-services-gradle-release" for android
Failed to install 'cordova-android-play-services-gradle-release': CordovaError: Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\Context.js:57:15)
    at module.exports (D:\ionicDemo\ionic_demo1\plugins\cordova-android-play-services-gradle-release\scripts\apply-changes.js:99:20)
    at runScriptViaModuleLoader (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:181:32)
    at runScript (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:157:16)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:125:20
Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at process._tickCallback (internal/process/next_tick.js:68:7)
[ERROR] An error occurred while running subprocess cordova.

        cordova platform add android --save exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

**Comment by tfisc** [comment]
Hi, you have this error because the values of your variables "icon" and "small icon" are incorrect.
If you look in your mipmaps folders, the image name must be "ic_launcher".

In these case, just do the following : 
-replace "@mipmap/icon" by "@mipmap/ic_launcher" for variables icon and small icon in BOTH package.json and config.xml.

then : 
ionic cordova platform rm android
rm -rf plugins
ionic cordova build android

and you should build successfully.

**Comment by zhaoxu666** [comment]
How to implement this step？ rm -rf plugins？
Remove-Item : 找不到与参数名称“rf”匹配的参数。
所在位置 行:1 字符: 4
+ rm -rf plugins
+    ~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item]，ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

After I downloaded the plug-in, I replaced icon with ic_launcher in package. JSON and config. XML

But D: ionicDemo myApp platforms android app src main res xml authenticator. xml: 2: AAPT: error: resource mipmap / icon (aka. jindast: mipmap / icon) did not appear.

package.json:
 "cordova-plugin-mauron85-background-geolocation": {
        "GOOGLE_PLAY_SERVICES_VERSION": "11+",
        "ANDROID_SUPPORT_LIBRARY_VERSION": "26+",
        "ICON": "@mipmap/ic_launcher",
        "SMALL_ICON": "@mipmap/ic_launcher",
        "ACCOUNT_NAME": "@string/app_name",
        "ACCOUNT_LABEL": "@string/app_name",
        "ACCOUNT_TYPE": "$PACKAGE_NAME.account",
        "CONTENT_AUTHORITY": "$PACKAGE_NAME"
      }

config.xml:
   <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-statusbar" spec="2.4.2" />
    <plugin name="cordova-plugin-device" spec="2.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="^4.0.0" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />
    <plugin name="cordova-plugin-mauron85-background-geolocation" spec="@mauron85/cordova-plugin-background-geolocation@~3.0.3">
        <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="11+" />
        <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="26+" />
        <variable name="ICON" value="@mipmap/ic_launcher" />
        <variable name="SMALL_ICON" value="@mipmap/ic_launcher" />
        <variable name="ALWAYS_USAGE_DESCRIPTION" value="App requires background tracking " />
        <variable name="MOTION_USAGE_DESCRIPTION" value="App requires motion detection" />
    </plugin>

If I change the icon in authenticator. XML to ic_launcher and then execute ionic Cordova build and roid. authenticator. xml, I change ic_launcher to icon.

**Comment by zhaoxu666** [comment]
config.xml:
` <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-statusbar" spec="2.4.2" />
    <plugin name="cordova-plugin-device" spec="2.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="^4.0.0" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />
    <plugin name="cordova-plugin-mauron85-background-geolocation" spec="@mauron85/cordova-plugin-background-geolocation@~3.0.3">
        <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="11+" />
        <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="26+" />
        <variable name="ICON" value="@mipmap/ic_launcher" />
        <variable name="SMALL_ICON" value="@mipmap/ic_launcher" />
        <variable name="ALWAYS_USAGE_DESCRIPTION" value="App requires background tracking " />
        <variable name="MOTION_USAGE_DESCRIPTION" value="App requires motion detection" />
    </plugin>`

**Comment by HarelM** [comment]
I have the same issue, it actually started when updating the android version of cordova from 7.1.2 to 8.0.0.
Also there's an issue here since Cordova 9.0 is deprecating the plugin configuration through the config.xml. I'm not sure if this plugin is reading the package.json or the config.xml, @mauron85 any idea?

**Comment by HarelM** [comment]
I'm able to build the android version.
I'm guessing this issue can be closed.
