### ISSUE TITLE
App stop send post after some minutes

### ISSUE THREAD

**Issue by gabrielpotumati** [mauron85/cordova-plugin-background-geolocation#604]
## Your Environment
* Plugin version: 3.0.3
* Platform: iOS or Android
* OS version: 7
* Device manufacturer and model: Xaomi Redmi 3 Pro

## Context
My App stop send post after some minutes, Im sending direct post to my server. Gps keeps running, however I get error that dns can not resolve the server address.

BackgroundGeolocation.configure({
            locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
            desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
            stationaryRadius: 50,
            distanceFilter: 50,
            interval: 60000,
            fastestInterval: 60000,
            activitiesInterval: 60000,
            debug: false,
            pauseLocationUpdates: false,
            stopOnStillActivity: false,
            startOnBoot: true,
            stopOnTerminate: false,
            notificationTitle: 'My App',
            notificationText: 'Monitoring',
            url: 'http://mysite.com/api/updateloc.ashx',
            postTemplate: {
                longitude: '@longitude',
                latitude: '@latitude'
            }
        });

**Comment by zhaoxu666** [comment]
I have the same question

**Comment by willmero** [comment]
@gabrielpotumati and @zhaoxu666 what version of Android are you guys using? Might be related to these other bugs that other folk are listing:
https://github.com/mauron85/cordova-plugin-background-geolocation/issues/598
https://github.com/mauron85/cordova-plugin-background-geolocation/issues/609
