### ISSUE TITLE
ITMS-90338: Non-public API usage

### ISSUE THREAD

**Issue by acidumirae** [mauron85/cordova-plugin-background-geolocation#606]
## Your Environment

* Plugin version: 3.0.3
* Platform: iOS
* OS version: N/A
* Device manufacturer and model: N/A

* Running in Simulator: No
* Cordova version (`cordova -v`): 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (`cordova platform ls`): ios 5.0.0
* Plugin configuration options: GOOGLE_PLAY_SERVICES_VERSION=15.0.1 ANDROID_SUPPORT_LIBRARY_VERSION=27.+
* Link to your project: private

## Context

Got a message from App Store Connect <no_reply@email.apple.com>: 
ITMS-90338: Non-public API usage - The app references non-public selectors in  databasePool:didAddDatabase:, databasePool:shouldAddDatabaseToPool:, ddSetLogLevel:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. If you think this message was sent in error and that you have only used Apple-published APIs in accordance with the guidelines, send the app's Apple ID, along with detailed information about why you believe the above APIs were incorrectly flagged, to appreview@apple.com. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

Is it a false-positive by any chance?

## Details

```
./Plugins/cordova-plugin-mauron85-background-geolocation/CocoaLumberjack.m:2997:    SEL setterSel = @selector(ddSetLogLevel:);
./Plugins/cordova-plugin-mauron85-background-geolocation/CocoaLumberjack.m:3138:        [aClass ddSetLogLevel:level];
./Plugins/cordova-plugin-mauron85-background-geolocation/CocoaLumberjack.h:760: * + (void)ddSetLogLevel:(DDLogLevel)level
./Plugins/cordova-plugin-mauron85-background-geolocation/CocoaLumberjack.h:771:+ (void)ddSetLogLevel:(DDLogLevel)level;
./Plugins/cordova-plugin-mauron85-background-geolocation/FMDB.m:1884:                    if (shouldNotifyDelegate && [self->_delegate respondsToSelector:@selector(databasePool:didAddDatabase:)]) {
./Plugins/cordova-plugin-mauron85-background-geolocation/FMDB.m:1875:            if ([self->_delegate respondsToSelector:@selector(databasePool:shouldAddDatabaseToPool:)] && ![self->_delegate databasePool:self shouldAddDatabaseToPool:db]) {

```

**Comment by ben349** [comment]
I have the exact same error

**Comment by kolbasa** [comment]
Same here
![Bildschirmfoto 2019-07-12 um 11 17 42](https://user-images.githubusercontent.com/3901582/61133813-78446300-a4be-11e9-8927-a4057250bf47.png)

**Comment by fmendoza** [comment]
Any workaround?

**Comment by ptisserand** [comment]
Here is a quick and dirty patch I have wrote as a workaround for this issue:
[https://gist.github.com/ptisserand/29dd8d4643c67fad47599d77a1198b25](url)

**Comment by tlacroix** [comment]
@ptisserand Thanks for the patch! I've been facing the same problem on 3 projects. I'll try to turn into a PR so it gets into the code base more quickly (and of course, give you all the credit you're due).

**Comment by tlacroix** [comment]
@ptisserand Your patch won't apply on 3.0.1 nor on 3.0.3 (been trying on a git clone of this specific project). Maybe I'm trying it wrong. Does your patch apply to the plugin, or to the `platforms/ios/` directory? 

The first file you're trying to patch is 'ios/CDVBackgroundGeolocation/CocoaLumberjack.h', but it doesn't exist* on 3.0.1 or on 3.0.3. Maybe it's created at compile-time in the platforms/ios/ directory?

* https://github.com/mauron85/cordova-plugin-background-geolocation/tree/master/ios/CDVBackgroundGeolocation (3.0.3, but same for 3.0.1)

**Comment by tlacroix** [comment]
@ptisserand Ok. Your patch should go in a submodule here (https://github.com/mauron85/background-geolocation-ios.git), but it can't be applied as is. I'll try to make one based on your code in the upcoming days.

**Comment by ptisserand** [comment]
@tlacroix really sorry about this.
My patch is really just a quick and dirty workaround I have used for this issue.
I was in rush to publish an update  for a mobile application I didn't wrote...
Really thanks to manage it.

**Comment by tlacroix** [comment]
@ptisserand Thanks again for your patch. I integrated it into the proper project and sent a PR. I also made the changes directly to my apps, and Apple stopped rejecting them. 👍

**Comment by tlacroix** [comment]
The PR is still open and has not yet been merged. It effectively fixes the problem on my side.
