### ISSUE TITLE
Can I use this in Android for free?

### ISSUE THREAD

**Issue by zulhfreelancer** [mauron85/cordova-plugin-background-geolocation#61]
From what I understand, [original project](https://github.com/transistorsoft/cordova-background-geolocation-lt) only free for iOS. If I want to use it in Android, I need to buy premium one.

Can I use this project in Android for free?

OR, do I need to buy premium license too?

Please help. Thanks.

**Comment by mauron85** [comment]
]you can use this plugin for free, without buying any license.

**Comment by zulhfreelancer** [comment]
Nice. Thanks!
