### ISSUE TITLE
plugin_not_installed

### ISSUE THREAD

**Issue by borjalo** [mauron85/cordova-plugin-background-geolocation#613]
Trying to use the plugin, but when running on android device it says that the plugin is not installed
## Your Environment

* Plugin version: 3.0.1
* Platform: Android
* OS version: 8.0.0
* Device manufacturer and model:

* Running in Simulator:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

## Context

Building a Ionic 3 application, I have followed the steps to use the plugin:

`ionic cordova plugin add cordova-plugin-mauron85-background-geolocation@alpha`
`npm install --save @ionic-native/background-geolocation@4`

and when trying to run the app in an Android device, message error `plugin_not_installed` is shown

## Expected Behavior

Show an alert with the `BackgroundGeolocationResponse` 
## Actual Behavior

`plugin_not_intalled` error message
## Possible Fix

I am trying other versions of the plugins and the new plugin `@mauron85/cordova-plugin-background-geolocation`
## Steps to Reproduce

1.
2.
3.
4.

**Comment by felipegonzalez1994** [comment]
this.platform.ready().then(() => { logic plugin code}

**Comment by anRoswell** [comment]
You are installing version alpha, install [https://github.com/mauron85/cordova-plugin-background-geolocation](url)

**Comment by lucasprogamer** [comment]
@anRoswell  yeah, i'm following the docs from ionic framework, https://ionicframework.com/docs/v3/native/background-geolocation/

**Comment by borjalo** [comment]
You have to install this package https://www.npmjs.com/package/@mauron85/cordova-plugin-background-geolocation 

This one https://www.npmjs.com/package/cordova-plugin-mauron85-background-geolocation is deprecated

**Comment by mauron85** [comment]
Try installing exact version with:

```
cordova plugin add @mauron85/cordova-plugin-background-geolocation@^3.1.0
```

**Comment by mauron85** [comment]
Also I believe there is still issue with scoped packages in cordova. Meaning that when you create platform with `cordova platform add` it may install also non scoped package `cordova-plugin-background-geolocation`. It's different package, so beware.

The best way to avoid this, is to add plugin in `config.xml` with spec declaration. Check https://github.com/mauron85/cordova-plugin-background-geolocation-example/blob/96b0497013f56515c2ab84a16eacceeb4826c31a/config.xml#L50

**Comment by anRoswell** [comment]
Thank you @mauron85 for your answer, i see there are an actualization about the plugin 3.1.0, i going to try you suggestion

**Comment by RaschidJFR** [comment]
Yes, the problem seems to be the scoped package, thanks for pointing that out @mauron85 . It didn't work for me to add it in `config.xml` because the plugin in `package.json` kept changing back to `cordova-plugin-background-geolocation` insteado of `@mauron85/cordova-...`. So what finally worked for me was adding the plugin directly in package.json so the correct plugin gets installed when adding or preparing the platform.

```json
// package.json
{
  "@mauron85/cordova-plugin-background-geolocation": "^3.1.0",
  "cordova": {
    "plugins": {
      "@mauron85/cordova-plugin-background-geolocation": {}
    }
  }
}
```

After adding a platform, the old package keeps being added to the package.json but that doesn't seem to interfere so far.
