### ISSUE TITLE
iOS 12.3: Http request fail when app is in the background

### ISSUE THREAD

**Issue by edento** [mauron85/cordova-plugin-background-geolocation#615]
## Your Environment

* Plugin version: 3.0.3
* Platform: iOS
* OS version: 12.3.1
* Device manufacturer and model: iphone 6s+
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`):
  android 7.1.4
  ios 5.0.1
* Plugin configuration options: 
```
{
      desiredAccuracy: 0,
      stationaryRadius: 1,
      distanceFilter: 1,
      interval: 1000, // poll location each 1000 ms
      debug: false, //  enable this hear sounds for background-geolocation life-cycle.
      stopOnTerminate: true, // enable this to clear background location settings when the app terminates
    }
```

## Context
When user location changes, the `location` callback is executed. The callback contains a get http request, that fails when the app is in the background.

## Expected Behavior
The http request should be completed, like when the app is in the foreground.

## Actual Behavior
The http request fails, whenever that app is in the background (even for a couple of seconds)

## Possible Fix
Maybe change some configs to allow this http request? maybe the issue is with angular's package? is there a package that works?

## Steps to Reproduce

A working scenario:
1. Open the app
2. Start background geolocation plugin
3. Move, to activate a location change event
5. The triggered http request succeeds.

A failure scenario:
1. Open the app
2. Start background geolocation plugin
3. Minimize the app (activate background by clicking the iphone home button)
4. Move, to activate a location change event
5. The triggered http request fails.

### Code example ###

I activate the plugin:

```
    this.backgroundGeolocation.on(BackgroundGeolocationEvents.location)
      .subscribe((location: BackgroundGeolocationResponse) => {
        this.backgroundGeolocation.startTask().then(async (taskId) => {
          await this.fetchData();
          await this.backgroundGeolocation.endTask(taskId);
        });
      });
```

When `fetchData`:
```
  private async fetchData(): Promise<any> {
    try {
      // When in foreground
      const data = await this.http.get(`my-server-endpoint`).toPromise();
      console.log(TAG, `Received data`, data);
    }
    catch (e) {
      // When in background mode, we always catch an error
      console.error(TAG, `Error getting data ${JSON.stringify(e)}`, e)
    }
  }
```
 
`Http` package is `HttpClient`:
```
import {HttpClient} from "@angular/common/http";
```

## Context
When the user changes their location, the app should fetch new data from the server, then make some client-side calculations and send local notification. 
While the app is in the background, the http request **always** fails, and therefore, no notification is sent to the user.

## Debug logs
These are the error that are shown in Safari (and also Xcode):
```
{
        "headers": {"normalizedNames": {}, "lazyUpdate": null, "headers": {}},
        "status": 0,
        "statusText": "Unknown Error",
        "url": null,
        "ok": false,
        "name": "HttpErrorResponse",
        "message": "Http failure response for (unknown url): 0 Unknown Error",
        "error": {"isTrusted": true}
}
```
And right after that:
```
Failed to load resource: The operation couldn’t be completed. Software caused connection abort
```

 **It is important to mention that the location is working just fine, but the background activity that is triggered when location changes doesn't**

This seems to be related to #203 , but I am not sure since the error is not specified there.

Maybe you can assist?
Thanks

**Comment by mauron85** [comment]
Sorry this is not relevant to this plugin, as you're doing http request "yourself". However I believe you're missing some iOS project permissions.

Checkout https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/

**Comment by borjalo** [comment]
Try to add the `url` parameter in the config object.
