### ISSUE TITLE
App crash when get background location

### ISSUE THREAD

**Issue by Bhagirath123** [mauron85/cordova-plugin-background-geolocation#616]
Hi

i am using this plugin for get background location when app in background mode

this problem accrued when i am update  android-targetSdkVersion 28    before i am using android-targetSdkVersion 26 that time not any problem 
but with android-targetSdkVersion 26 i am not upload my app in play store

ionic cordova plugin add cordova-plugin-mauron85-background-geolocation@alpha
npm install --save @ionic-native/background-geolocation@4

for this problem i am use android permission for get permission of background location but not getting any prompt to ask location permission   

this is my code plz check 

    this.androidPermissions.checkPermission(this.androidPermissions.PERMISSION.ACCESS_BACKGROUND_LOCATION).then((result) =>{
        console.log('Has permission?',result);
        if(result.hasPermission){
            const config: BackgroundGeolocationConfig = {
              desiredAccuracy: 10,
              stationaryRadius: 0,
              distanceFilter: 0,
              // interval:60000,
              notificationTitle: 'Background Tracking',
              notificationText: 'Enabled',
              debug: false, //  enable this hear sounds for background-geolocation life-cycle.
              stopOnTerminate: false,
            };
            this.backgroundGeolocation.configure(config)
              .subscribe((location: BackgroundGeolocationResponse) => {
                console.log(location,"location");
              },(err)=>{
              })
            }
            else{
              this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.ACCESS_BACKGROUND_LOCATION);
            }
          },(err) =>{
            this.androidPermissions.requestPermission(this.androidPermissions.PERMISSION.ACCESS_BACKGROUND_LOCATION);
          });
          window.app = this;

    });

in this.androidPermissions.PERMISSION.ACCESS_BACKGROUND_LOCATION i am always getting false 

please help me
thanks

**Comment by mauron85** [comment]
`cordova-plugin-mauron85-background-geolocation@alpha` is not supported anymore. Try search issues for ionic integration with newer versions of this plugin.
