### ISSUE TITLE
Foreground service permission is required since Android 28

### ISSUE THREAD

**Issue by HarelM** [mauron85/cordova-plugin-background-geolocation#623]
## Your Environment
* Plugin version: 3.0.6
* Platform: Android
* OS version: 7.2
* Device manufacturer and model: N/A
* Running in Simulator: NO
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (`cordova platform ls`): android 8.0.0
* Plugin configuration options: 
* Link to your project: https://github.com/IsraelHikingMap/Site/

## Context
I have recently updated cordova and min sdk version due to Goggle requirements
When using a newer version and using foreground service true the following permissions are needed, otherwise the plugin crashes with the following exception:
`09-13 09:17:07.430 10150 10150 E com.marianhello.bgloc.service.LocationServiceImpl: processCommand: exceptionjava.lang.SecurityException: Permission Denial: startForeground from pid=10150, uid=10273 requires android.permission.FOREGROUND_SERVICE`

## Expected Behavior
The documentation should specify it or the plugin should configure it.

## Actual Behavior
App doesn't work for no apparent reason.

## Possible Fix
Add docs or update plugin.xml
Workaround: use this in the config.xml:
```
        <edit-config file="AndroidManifest.xml" mode="merge" target="/manifest/uses-permission" xmlns:android="http://schemas.android.com/apk/res/android">
          <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
        </edit-config>
```

## Steps to Reproduce
1. use the following when creating the app in config.xml:
```
        <preference name="android-targetSdkVersion" value="28" />
        <preference name="android-minSdkVersion" value="28" />
```

**Comment by mauron85** [comment]
Please publish PR. Should be 5 min job. Thanks.
-- 
S pozdravom,

Marián Hello
freelance programmer

About.me <http://about.me/marian.hello> | LinkedIn
<https://www.linkedin.com/in/marianhello/> | Twitter
<http://twitter.com/mauron85>


In case of sensitive data, please consider using encryption using my public
PGP key <https://keybase.io/mauron85/key.asc>.
If you don't have PGP enabled email, you can also copy and paste encrypted
message generated here <https://keybase.io/encrypt#mauron85>.

**Comment by HarelM** [comment]
Sure, which solution would you like? the docs or the plugin.xml?

**Comment by mauron85** [comment]
plugin.xml would be nice

**Comment by HarelM** [comment]
Done, See here: #624. (Haven't tested the plugin code itself, but the permissions fixed the problem I had).
Let me know if you need anything else.
Thanks for all your hard work!

**Comment by mauron85** [comment]
fix has been merged
