### ISSUE TITLE
Background geolocation is not working in redmi 8.1 android mobile when app is in background

### ISSUE THREAD

**Issue by SathyaNagaraj** [mauron85/cordova-plugin-background-geolocation#625]
## Your Environment

* Plugin version: ionic 4
* Platform:  Android
* OS version: 8.1
* Device manufacturer and model: redmi

* Running in Simulator:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

## Expected Behavior

I want to get user location even when the app is in background.
## Actual Behavior

It is working in android mobile which has a version 8.0 or less than that.  In 8.0 , I can get the user location in the foreground as well as in background and update it to the server. In 8.1 background tracking notification is shown, but I can't get the location.

## Steps to Reproduce

1.
2.
3.
4.

## Context

 let config: BackgroundGeolocationConfig = {
  desiredAccuracy: 10,
  stationaryRadius: 0,
  distanceFilter: 0,
  notificationTitle: 'Background Tracking',
  notificationText: 'Enabled',
  debug: false,
  interval: 10000,
  stopOnTerminate: false,
  url: 'http://192.168.81.15:3000/location',,
  httpHeaders: {
    'Content-Type': 'application/json'
  },

  postTemplate: {
    lat: '@latitude',
    lng: '@longitude',
    time: '@time',
  },
}
this.backgroundGeolocation.configure(config).then((location: BackgroundGeolocationResponse) => {

         this.backgroundGeolocation.on(BackgroundGeolocationEvents.location).subscribe((location: BackgroundGeolocationResponse) => {
        console.log(location);
  this.locationUpdate("Background");
     this.zone.run(() => {
      this.lat = location.latitude;
      this.lng = location.longitude;
      this.time = location.time;

         	    

    });
        // IMPORTANT:  You must execute the finish method here to inform the native plugin that you're finished,
        // and the background-task may be completed.  You must do this regardless if your operations are successful or not.
      // IF YOU DON'T, ios will CRASH YOUR APP for spending too much time in the background.
      this.backgroundGeolocation.finish(); // FOR IOS ONLY
    });
 }, (err) => {
  console.log("configure err"+err);
});

**Comment by mansur-usis** [comment]
> ## Your Environment
> * Plugin version: ionic 4
> * Platform:  Android
> * OS version: 8.1
> * Device manufacturer and model: redmi
> 
> * Running in Simulator:
> * Cordova version (`cordova -v`):
> * Cordova platform version (`cordova platform ls`):
> * Plugin configuration options:
> * Link to your project:
> 
> ## Context
> ## Expected Behavior
> I want to get user location even when the app is in background.
> 
> ## Actual Behavior
> It is working in android mobile which has a version 8.0 or less than that. In 8.0 , I can get the user location in the foreground as well as in background and update it to the server. In 8.1 background tracking notification is shown, but I can't get the location.
> 
> ## Possible Fix
> ## Steps to Reproduce
> 
> ## Context
> let config: BackgroundGeolocationConfig = {
> desiredAccuracy: 10,
> stationaryRadius: 0,
> distanceFilter: 0,
> notificationTitle: 'Background Tracking',
> notificationText: 'Enabled',
> debug: false,
> interval: 10000,
> stopOnTerminate: false,
> url: 'http://192.168.81.15:3000/location',,
> httpHeaders: {
> 'Content-Type': 'application/json'
> },
> 
> postTemplate: {
> lat: '@latitude',
> lng: '@longitude',
> time: '@time',
> },
> }
> this.backgroundGeolocation.configure(config).then((location: BackgroundGeolocationResponse) => {
> 
> ```
>      this.backgroundGeolocation.on(BackgroundGeolocationEvents.location).subscribe((location: BackgroundGeolocationResponse) => {
>     console.log(location);
> ```
> 
> this.locationUpdate("Background");
> this.zone.run(() => {
> this.lat = location.latitude;
> this.lng = location.longitude;
> this.time = location.time;
> 
> ```
> });
>     // IMPORTANT:  You must execute the finish method here to inform the native plugin that you're finished,
>     // and the background-task may be completed.  You must do this regardless if your operations are successful or not.
>   // IF YOU DON'T, ios will CRASH YOUR APP for spending too much time in the background.
>   this.backgroundGeolocation.finish(); // FOR IOS ONLY
> });
> ```
> 
> }, (err) => {
> console.log("configure err"+err);
> });
> 
> ## Debug logs

Hi SathyaNagaraj,

I am also used this plugin. For every 3 seconds background API calling working fine. But, getting empty location array response for every api calling in background mode. Please help me with this issue.

**Comment by PollerBoom** [comment]
In Android 9.0, adding line 
`<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />` 
to AndroidManifest.xml solve my issue with background tracking.
Hope this helps with Android 8.1 too
