### ISSUE TITLE
plugin doesn't let cordova-plugin-fcm-with-dependecy-updated ^2.4.0 plugin handle notification

### ISSUE THREAD

**Issue by dzziwny** [mauron85/cordova-plugin-background-geolocation#627]
## Your Environment

* Plugin version: 3.0.3
* Platform: iOS
* OS version: 11.0.3 and 12.3.1
* Device manufacturer and model: iPhone 6, iPhone 6s

* Running in Simulator: no
* Cordova version (`cordova -v`): 8.1.2
* Cordova platform version (`cordova platform ls`): ios 4.5.4
* Plugin configuration options:

```
geolocation.configure({
            locationProvider: _geolocation.ACTIVITY_PROVIDER,
            desiredAccuracy: _geolocation.MEDIUM_ACCURACY,
            stationaryRadius: 0,
            distanceFilter: 0,
            debug: false,
            stopOnTerminate: true,
            stopOnStillActivity: false,
            startForeground: true,
            fastestInterval: 10000,
            interval: 10000,
            maxLocations: 1
        }
```

* Link to your project:

## Context

in CDVBackgroundGeolocation.m file debugger never goes into if statement

```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
       willPresentNotification:(UNNotification *)notification
         withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
{
    if (prevNotificationDelegate && [prevNotificationDelegate respondsToSelector:@selector(userNotificationCenter:willPresentNotification:withCompletionHandler:)])
    {
        // Give other delegates (like FCM) the chance to process this notification

        [prevNotificationDelegate userNotificationCenter:center willPresentNotification:notification withCompletionHandler:^(UNNotificationPresentationOptions options) {
            completionHandler(UNNotificationPresentationOptionAlert);
        }];
    }
    else
    {
        completionHandler(UNNotificationPresentationOptionAlert);
    }
}
```

## Expected Behavior

plugin should let others handle push data (in my case fcm, which works properly without this plugin)

## Actual Behavior

debugger always choses else statement and only displays notification in upper banner, no matter if app is foreground

## Steps to Reproduce

1. clear project
2. cordova plugin add cordova-plugin-fcm-with-dependecy-updated@^2.4.0
3. cordova plugin add @mauron85/cordova-plugin-background-geolocation@3.0.3
4. put breakpoint on line 484 in CDVBackgroundGeolocation.m
5. send any test push from firebase console

**Comment by ProximaHaiz** [comment]
I have the same issue.
@dzziwny Do you find a solution?

**Comment by ProximaHaiz** [comment]
So, i just removed code, that handle notification and its solved the problem

**Comment by dzziwny** [comment]
@ProximaHaiz I used https://github.com/arnesson/cordova-plugin-firebase instead

**Comment by walfridosp** [comment]
@ProximaHaiz just in case you haven't fix this issue yet, I solved it from my side by commenting these lines in plugin cordova-plugin-mauron85-background-geolocation/CDVBackgroundGeolocation.m

```
    // [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onAppPause:) name:UIApplicationDidEnterBackgroundNotification object:nil];
    // [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onAppResume:) name:UIApplicationWillEnterForegroundNotification object:nil];
    // [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onFinishLaunching:) name:UIApplicationDidFinishLaunchingNotification object:nil];
    // [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onAppTerminate:) name:UIApplicationWillTerminateNotification object:nil];
```
After that Push Notifications worked as expected.

Hope this helps.

**Comment by ProximaHaiz** [comment]
> @ProximaHaiz just in case you haven't fix this issue yet, I solved it from my side by commenting these lines in plugins/cordova-plugin-mauron85-background-geolocation/CDVBackgroundGeolocation.m
> 
> ```
>     // [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onAppPause:) name:UIApplicationDidEnterBackgroundNotification object:nil];
>     // [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onAppResume:) name:UIApplicationWillEnterForegroundNotification object:nil];
>     // [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onFinishLaunching:) name:UIApplicationDidFinishLaunchingNotification object:nil];
>     // [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onAppTerminate:) name:UIApplicationWillTerminateNotification object:nil];
> ```
> 
> After that Push Notifications worked as expected.
> 
> Hope this helps.

Thanks, i commented these lines too)
Also if you use this plugin or BackgroundMode plugin with sound off, remove **audio** key from UIBackgroundModes which located in plugin.xml file. Because App Store not allowed to publish my application with that

**Comment by nuno** [comment]
I have the same problem. I had to comment those lines abone too.
 @mauron85  There is a way make the plugin work with all others that suport  push notification, like fcm for exemple?
Thanks for you time.

**Comment by nuno** [comment]
Anyone? @dzziwny @ProximaHaiz @walfridosp @mauron85

**Comment by walfridosp** [comment]
Hi Nuno,

I did find a solution for this issue, I will get back to you later.

Thanks

**Comment by ynunez** [comment]
@nuno @ProximaHaiz @walfridosp @dzziwny @mauron85 I have a PR that fixes the issue https://github.com/mauron85/cordova-plugin-background-geolocation/pull/696

The problem is that it's overriding the notification center delegate. It should only override it when it is in debugging mode. There is no need to comment out the `addObserver` lines
