### ISSUE TITLE
Add a config to automatically close the background tracking as soon as status code 285 is received

### ISSUE THREAD

**Issue by cryo243** [mauron85/cordova-plugin-background-geolocation#628]
## Your Environment

* Plugin version: 3.0.6
* Platform: iOS and Android
* OS version:  Android 6,7,8,9 and iOS 10,11,12
* Device manufacturer and model:iPhone 6, iPhone X, Samsung Galaxy s10

* Running in Simulator: no
* Cordova version (`cordova -v`): 8.0.0
* Cordova platform version (`cordova platform ls`): ios 4.5.4 and android 6.4
* Plugin configuration options: {
      desiredAccuracy: 0,
      stationaryRadius: 10,
      distanceFilter: 1,
      stopOnTerminate: false,
      pauseLocationUpdates: false,
      saveBatteryOnBackground: false,
      interval: 25000,
      url: updateLocationUrl,
      debug: false,
      maxLocations: 10,
      notificationText: option.notificationText,
      notificationTitle: option.notificationTitle,
      postTemplate: {
        location: {
          latitude: '@latitude',
          longitude: '@longitude',
          accuracy: '@accuracy'
        },
        accessToken: option.accessToken
      }
    }
* Link to your project:

## Context

In PostLocationTask.java line 156
`   if (responseCode == 285) {
            // Okay, but we don't need to continue sending these

            logger.debug("Location was sent to the server, and received an \"HTTP 285 Updates Not Required\"");

            if (mTaskListener != null)
                mTaskListener.onRequestedAbortUpdates();
        }`
## Expected Behavior

It will be great if we can have a config value that allows to stop the plugin automatically stop/terminate the background tracking upon receiving status code 285, rather than only firing the onRequestedAbortUpdates event. The reason is that if a user ever force close his app while in background tracking mode, theonRequestedAbortUpdates  event won't be passed to Javascript codes hence causing the background tracking to continue even if it isn't needed anymore
## Actual Behavior

Background tracking continues after status code 285 is sent when the app is force closed
## Steps to Reproduce

1.
2.
3.
4.

## Context

Our server got flooded with  a lot of location updates events because most users force closed their app while in background tracking mode

**Comment by mauron85** [comment]
Not sure if event with statusCode 285 is propagated to headless task, but if yes, you can create headless task and stop plugin from there.

**Comment by cryo243** [comment]
@mauron85.  Sorry I am going to close  the issue.  I realised that it seems like you are already doing  what I am requesting as in `
  case LocationServiceImpl.MSG_ON_ABORT_REQUESTED: {
                    logger.debug("Received MSG_ON_ABORT_REQUESTED");

                    if (mDelegate != null) {
                        // We have a delegate, tell it that there's a request.
                        // It will decide whether to stop or not.
                        mDelegate.onAbortRequested();
                    } else {
                        // No delegate, we may be running in the background.
                        // Let's just stop.
                        stop();
                    }`
Please confirm my understanding:
 if I do not register for BackgroundGeolocationEvents.abort_requested event,
the service will be stopped immediately upon receiving status code 285 from the server?
