### ISSUE TITLE
no response on android 9 [Real me C2 device]

### ISSUE THREAD

**Issue by indraraj26** [mauron85/cordova-plugin-background-geolocation#632]
## Your Environment

* Plugin version: 3.1.0
* Platform: Android
* OS version: 9
* Device manufacturer and model: real me c2

* Running in Simulator:
* Cordova version (`cordova -v`):   cordova -v 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (`cordova platform ls`):  "cordova-android": "8.1.0",
* Plugin configuration options:   https://github.com/indraraj26/background-geolocation-test
```
 locationProvider: BackgroundGeolocation.RAW_PROVIDER, //ACTIVITY_PROVIDER
        desiredAccuracy: BackgroundGeolocation.MEDIUM_ACCURACY,
        stationaryRadius: 1,
        distanceFilter: 2,
        notificationTitle: 'Background tracking',
        notificationText: 'Enabled',
        saveBatteryOnBackground: false,
        debug: true,
        startForeground: true,
        startOnBoot: true,
        stopOnTerminate: false,
        interval: 10000,
        fastestInterval: 5000,
        activitiesInterval: 10000,
        url: 'https://test.indra.com:9000/location',
        syncUrl: 'https://test.indra.com:9000/location',
        syncThreshold: 2,
        httpHeaders: {
          'Content-Type': 'application/json',
        },
        // customize post properties
        postTemplate: {
          myId: 100,
          lat: '@latitude',
          lon: '@longitude',
        },
```
* Link to your project:

## Expected Behavior
It should fire location post to request

## Actual Behavior

It is not even producing beep sound and notification toast in android 9 but it is working fine in 7.1.2 android os

## Steps to Reproduce

1. Clone this project : https://github.com/indraraj26/background-geolocation-test
2. npm install && ionic cordova platform add android@8.1.0
3. ionic cordova build android 
4. Test in android os version 7.1.2 and 9

## Debug logs

[bg_location.txt](https://github.com/mauron85/cordova-plugin-background-geolocation/files/3656606/bg_location.txt)

**Comment by biswas123** [comment]
@indraraj26  Does it hit the .on('start', function() {}) event ?

**Comment by indraraj26** [comment]
@biswas123 Yes as per console.log, After that no log other than that app is in background or app is in foreground
```
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
vendor.js:124044 Ionic Native: deviceready event fired after 3326 ms
main.js:149 [INFO] BackgroundGeolocation service is running true
main.js:150 [INFO] BackgroundGeolocation services enabled true
main.js:151 [INFO] BackgroundGeolocation auth status: 1
main.js:103 last location Objectaccuracy: 20altitude: -40.20000076293945isFromMockProvider: falselatitude: 19.079861longitude: 72.8956749provider: "network"time: 1569494645355__proto__: Object
main.js:130 [INFO] App is in background
main.js:135 [INFO] App is in foreground
```

**Comment by wimZ** [comment]
Same here.  Since Android 9 update yesterday the start event does not trigger. 
The service is running.  on stop the stop event does trigger. 

Samsung: SM-J330FN
Android: 9
Cordova: 7.1.4

Appreciate support.

**Comment by anRoswell** [comment]
It's so stranger @wimZ , because  in my case, since the last update from plugin (3.1.0), my app is working so good, _**but i began a proyect from the start.**_ and migrated all my application

Options that are not working before me are working, like

`stopOnTerminate, Background en Android 9.0, etc`

Like the background option in Android 9.0 is working wonders for me.

I don't know it's was the update but the plugin it's working great.

Thank you @mauron85 .

**Comment by wimZ** [comment]
@anRoswell:  Thanks for your reply and mentioning yur version. I had not noticed there was an update since 3.0.3

All seems to work fine now.
