### ISSUE TITLE
Android resource linking failed   C:\IONIC\saha-tour-travels\platforms\android\app\src\main\res\xml\authenticator.xml:2: AAPT: error: resource mipmap/icon (aka com.stt.business:mipmap/icon) not found.

### ISSUE THREAD

**Issue by rupamhazra** [mauron85/cordova-plugin-background-geolocation#636]
Android resource linking failed
  C:\IONIC\saha-tour-travels\platforms\android\app\src\main\res\xml\authenticator.xml:2: AAPT: error: resource mipmap/icon (aka com.stt.business:mipmap/icon) not found.

## Your Environment

* Plugin version:
* Platform: iOS or Android
* OS version: 
* Device manufacturer and model:

* Running in Simulator: Android
* Cordova version (`cordova -v`): 8.0
* Cordova platform version (`cordova platform ls`): 
* Plugin configuration options: 
* Link to your project:

## Context

Android resource linking failed
  C:\IONIC\saha-tour-travels\platforms\android\app\src\main\res\xml\authenticator.xml:2: AAPT: error: resource mipmap/icon (aka com.stt.business:mipmap/icon) not found.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Maikell84** [comment]
Still an issue with `cordova 9` and `cordova-android 8`
As a workaround, manually create a folder  `platforms\android\app\src\main\res\mipmap` and put your app-icon.png in there.

**Comment by rupamhazra** [comment]
please tell me what should be the name of icon ? is it app-icon.png or else

**Comment by blinkuz** [comment]
@rupamhazra I just had to place icon.png inside the folder and it worked perfectly.
