### ISSUE TITLE
Possible bug as to when iOS displays the "this app would like to track you in the background" popup

### ISSUE THREAD

**Issue by pugwonk** [mauron85/cordova-plugin-background-geolocation#64]
I'm using this plugin on both iOS and Android and it works great (and saved me a ton of work - thanks!). There's one slightly odd idiosyncracy on iOS - only certain parts of my app need background tracking, so I don't use it at startup. I do, however, use the normal navigator.geolocation tracking all the time the app is running.

On iOS, the prompt is displayed saying "this app wants to track you in the background". However - it's displayed before I've ever called anything to do with backgroundGeoLocation! From testing it seems to be fired when I initialise the **foreground** geolocation service, on the line:

`posWatchID = navigator.geolocation.watchPosition(tickPosition, geoErrorHandler, options);
`

Can anyone tell me whether this is a foible of iOS itself or a problem with this plugin? My guess would be that it's the former but if that's the case it surprises me that Apple haven't fixed it.

**Comment by mauron85** [comment]
Tried to replicate your use case on Sample App. Prompt was displayed until I've called `backgroundGeoLocation.start();` method. So I cannot confirm your issue. 

Please check your code, if you're not calling `backgroundGeoLocation.start();` somewhere.

**Comment by mauron85** [comment]
please reopen, when necessary

**Comment by pugwonk** [comment]
Upon further investigation, it seems this behaviour seems to occur when the old org.apache.cordova.geolocation plugin is still active. Removing that and replacing it with the newer cordova-plugin-geolocation seems to stop it happening.

**Comment by mauron85** [comment]
nice. thank u for the update
