### ISSUE TITLE
Ionic 4 build Error class file for com.google.android.gms.internal.zzbej not found

### ISSUE THREAD

**Issue by sivakumar55** [mauron85/cordova-plugin-background-geolocation#646]
## Your Environment

* Plugin version:3.1.0
* Platform: android
* Running in Simulator:
* Cordova version (`cordova -v`): 8.1.2 
* Cordova platform version (`cordova platform ls`): android 7.1.1

## Debug logs
/Users/sys/Documents/TAGPROJECTS/ola_ionic4/platforms/android/app/src/main/java/com/marianhello/bgloc/data/BackgroundActivity.java:20: error: cannot access zzbfm
        confidence = activity.getConfidence();
                             ^
  class file for com.google.android.gms.internal.zzbfm not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
38 actionable tasks: 38 executed
/Users/sys/Documents/TAGPROJECTS/ola_ionic4/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/sys/Documents/TAGPROJECTS/ola_ionic4/platforms/android/app/src/main/java/com/marianhello/bgloc/data/BackgroundActivity.java:20: error: cannot access zzbfm
        confidence = activity.getConfidence();
                             ^
  class file for com.google.android.gms.internal.zzbfm not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by loggier** [comment]
Add this: 

ionic cordova plugin add cordova-plugin-androidx
ionic cordova plugin add cordova-plugin-androidx-adapter

fix problem
