### ISSUE TITLE
How can i disable activity toast notification ?

### ISSUE THREAD

**Issue by mario-berardo** [mauron85/cordova-plugin-background-geolocation#647]
## Your Environment

* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer and model:

* Running in Simulator:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by bhammack** [comment]
Seconding this issue. Setting debug: false doesn't appear to disable the toast from displaying. Nothing in the documentation mentions this toast activity should exist. Anyone able to solve this?
