### ISSUE TITLE
enableHighAccuracy gives much better results

### ISSUE THREAD

**Issue by GuyBrand** [mauron85/cordova-plugin-background-geolocation#65]
We have tried tweaking the 
distanceFilter , desiredAccuracy parameters as well as stationaryRadius , locationTimeout , 
ANDROID_FUSED_LOCATION interval = 5000 , fastestInterval and   activitiesInterval but could not get similar results to Navigator.WatchPosition with enableHighAccuracy = true .
the results with the plugin vary from 5-2500 meters while on same device , same route , navigator's results were constantly < 10 with am average of ~5 and some results of 1.5-2 meters .

if the software was opened, and we opened google maps on as well , suddenly the plugin results were as good , i.e accuracy < 10 constantly as well .

Can you state a parameter set that will indicate "maximum accuracy" (device battery is not an issue) , that will give similar results to Navigator.enableHighAccuracy = true ?

Thanks.

**Comment by mauron85** [comment]
It would be desiredAccuracy = 0.

FYI: The actual mapping of desiredAccuracy is done in  `translateDesiredAccuracy` method.
https://github.com/mauron85/cordova-plugin-background-geolocation/blob/master/src/android/FusedLocationService.java#L182

**Comment by GuyBrand** [comment]
We have tried it , and it does not always give the best results , we 
assume that its falling to netword GPS resolution , and now trying to 
use ANDROID_DISTANCE_FILTER instead of ANDROID_FUSED_LOCATION as 
suggested in some threads ...

------ Original Message ------

**Comment by shyamal890** [comment]
@GuyBrand I have a similar issue, even though I set desiredAccuracy to say 10, I get results with accuracy more than 100 sometimes. What did you do to resolve this?

**Comment by GuyBrand** [comment]
I believe the "locationServiceType" solved it , this is what we use now 
:


{
  "desiredAccuracy": 0,
  "stationaryRadius": 5,
  "distanceFilter": 1,
  "debug": false,
  "stopOnTerminate": true,
  "locationServiceType": "ANDROID_DISTANCE_FILTER",
  "interval": 5000,
  "fastestInterval": 2000,
  "locationTimeout": 2,

   }


Please note that we have found that different devices react better to 
differnt configuration (some does not support FUSED , and some get 
lesser results without it...) , so we allowed a per device configuration 
, and even think about doing a "scan" when the app starts up , to see 
which reacts better .

The weirdest is a different SIM from different communication providers 
(e.g. AT&T / Verison etc) changes the behavior as well !

Last but not least , the above configuration probably has high power 
consumption , please consider .

Good luck and hope this will help ,
     Guy .

------ Original Message ------

**Comment by mauron85** [comment]
Good to hear, you got it resolved.
