### ISSUE TITLE
Android 9 -- no detecting position at all

### ISSUE THREAD

**Issue by Taxi4you** [mauron85/cordova-plugin-background-geolocation#650]
I am using Samsung Galaxy S7, I have just updated the Android version to 8, now when trying to find position it doesn't find at all. I have tried for one hour, usually it takes half a second.
I have enabled GPS, the app is the same app with same geolocation services permission enabled and Waze finds the position just in half a second but my app using this plugin not.

Doesn't this plugin support Android 8?

**Comment by Taxi4you** [comment]
Nobody support this repo?

**Comment by mauron85** [comment]
You didn't used the issue template. So there is no info about plugin version, logs, ... Please use issue template. There is explicit warning PLEASE DON'T DELETE THIS TEMPLATE, OR YOUR ISSUE WILL BE CLOSED/IGNORED !!!

**Comment by Taxi4you** [comment]
Okay I create a new one I will make it properly. Sorry.
