### ISSUE TITLE
Android v8 barely detects position at start method and Android 9 even harder to find

### ISSUE THREAD

**Issue by Taxi4you** [mauron85/cordova-plugin-background-geolocation#651]
## Your Environment
I am using Android v8 and Android v9 for testing purposes.

* Plugin version:
```
"cordova-plugin-mauron85-background-geolocation": {
                "GOOGLE_PLAY_SERVICES_VERSION": "11+",
                "ANDROID_SUPPORT_LIBRARY_VERSION": "23+",
                "ALWAYS_USAGE_DESCRIPTION": "App requires ...",
                "MOTION_USAGE_DESCRIPTION": "App requires motion detection",
                "ICON": "@mipmap/icon",
                "SMALL_ICON": "@mipmap/icon",
                "ACCOUNT_NAME": "@string/app_name",
                "ACCOUNT_LABEL": "@string/app_name",
                "ACCOUNT_TYPE": "$PACKAGE_NAME.account",
                "CONTENT_AUTHORITY": "$PACKAGE_NAME"
            },
```

* Platform: Android

* OS version: issues appear in both in Android 8 and 9.

* Device manufacturer and model:
Samsung Galaxy S7 and also tested on Samsung Note 7

* Cordova version 8.1.2 (cordova-lib@8.1.1)

* Cordova platform version (`cordova platform ls`):
**Installed platforms:
  android 8.0.0
  browser 5.0.4
  ios 4.5.5
Available platforms: 
  osx ~4.0.1
  windows ~6.0.0**

* Plugin configuration options: 
```
BackgroundGeolocation.configure({
    locationProvider: BackgroundGeolocation.ACTIVITY_PROVIDER,
    desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
    stationaryRadius: 50,
    distanceFilter: 50,
    notificationIconColor: "#9D5DF1",
    notificationTitle: "App running in background",
    notificationText: "Enabled",
    debug: false,
    interval: 3000,
    fastestInterval: 1500,
    activitiesInterval: 3000,
  })
```

BTW what "fastestInterval" means? I didn't understand this in docs maybe could you please clarify this?

## Context
Before I have updated my Android version to 8, the plugin could detect my position very fast.
I am talking about the FIRST initiate of the plugin, that now, after update fails to detect.
At first I need to try like 20 or 30 times in order to actually detect the position, while other apps like Waze detects the position very quickly and on first time.
(after finds the position, usually there is no problem and background mode actually works as expected).

Note that when I try this in my vehicle, the rate of success is 50% and at the office (with very good reception) the rate can be as low as 5%. Other apps success to detect the position at ease - even at the office.

## Expected Behavior
Position should be detected immediately on Android - as long as have good receive and other GPS apps success to find position.

## Actual Behavior
Waze (another GPS app) finds position on first shot and immediately, but my Cordova app fails like 20-30 times in order to do that.

## Possible Fix
I don't know if this is related to this issue, but I want to add that in iOS the plugin asks for Bluetooth permission. Why? in iOS it detects the position at ease and with 100% success rate. Therefore I think that this permission requirement should be omitted since in iOS position is getting found either way.

## Steps to Reproduce
1. Running Backgroundgeolocation.start() method.
2. When timeout ends (10,000ms) position is not getting detected.
3. Trying to close the app and try again 20 times and position is finally detected.
4. After opening Waze app, usually location is getting found immediately (usually, not always).

## Context
I need to subscribe me drivers to their polygons using the GPS coordinates - without this - I cannot send them work and orders to apply, since I don't know where they are and can't give them nearby orders.

## Debug logs
Actually no error is getting throwed, just the timeout is reaching out. I have tried to put the timeout 30,000ms but it didn't do the trick.

**Comment by mauron85** [comment]
Can you reproduce this, with other provider? Let's say RAW provider?

**Comment by Taxi4you** [comment]
@mauron85 
I have changed it to RAW provider as you said but it didn't work, also to the DISTANCE_FILTER_PROVIDER but also didn't work.
Should I change something else in the configuration as well?

**Comment by mauron85** [comment]
What does it mean "didn't work"? Do you mean same issue, or plugin doesn't work at all?

**Comment by Taxi4you** [comment]
Yes I mean the same issue as described above. Once plugin detects the position, no problem it can work for hours at ease and even find when device screen is lock and black. But the first initiate of the plugin is failed to achieve positioning - it can take up to 20 tries while other apps easily detects position, like Waze.

**Comment by Taxi4you** [comment]
I add something that maybe can help to solve the issue, when starting using the start method there is a GPS icon appear at top of the status bar. After 1.5 seconds this disappears and vanish (see the two images attached).

![20191105_112125 11 24 29](https://user-images.githubusercontent.com/41004207/68195073-e2799a00-ffbe-11e9-821d-b890695beb93.jpg)
![20191105_112107](https://user-images.githubusercontent.com/41004207/68195077-e3123080-ffbe-11e9-86b7-907fabe79b58.jpg)

When actually finding position, this icon doesn't get disappear. 
However, sometimes this icon remains and even so - not finding the position.

Hope it helps.

**Comment by Taxi4you** [comment]
Any update in here?
