### ISSUE TITLE
Android 8 is crashing on getValidLocations, getLocations...

### ISSUE THREAD

**Issue by david7117** [mauron85/cordova-plugin-background-geolocation#653]
## Your Environment
* Plugin version: 3.1.0
* Platform: Android
* OS version: Android Oreo
* Device manufacturer and model:
Simulator and Note3
* Running in Simulator: No
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`): 8.1.0
* Plugin configuration options: 
* Link to your project:

## Context
Using the method getValidLocations or getLocations leads in crashing the app, functions like „start geotracking“ works. also under ios the methods are still working. 

Based on an ionic (cli 4.7.0) app

## Expexted Behavior
The locations are returned and the app is not crashing under android 8

## Actual Behavior
The app crashes 

## Steps to Reproduce
1. use the Plugin in an ionic 4 app 
2 call the method getValidLocations in android simulator/ device

**Comment by HarelM** [comment]
@david7117 did you manage to fix/work around this issue?
I would like to getValidLocations when the app returns to the foreground in order to get the locations that I have "missed" while in the background. I hope this is the right way to do it...

**Comment by david7117** [comment]
Actually I have no workaround and this exactly my use case...

With iOS this works great, but not with android...

**Comment by HarelM** [comment]
Bummer... :-( Did you get a chance to see the crash on a logcat log file to better understand what caused it?

**Comment by HarelM** [comment]
Seems like I was able to use this method after all.
The problem I was facing is using this method before I got the first location - so I added an if to make sure I got the first location and it started to work afterwords, not sure if this is related to android 8 or not...

**Comment by diachedelic** [comment]
I experienced similar crashes on Android v5 and possibly v8 too, it was an out of memory error resulting from, I assume, too many locations being deserialized at once. While iOS appears to respect the`maxLocations` option, I could not find any code in this plugin which limits the number of locations inserted in the DB on Android.

```
java.lang.OutOfMemoryError: 
  at java.lang.String.<init> (String.java:400)
  at java.lang.AbstractStringBuilder.toString (AbstractStringBuilder.java:633)
  at java.lang.StringBuilder.toString (StringBuilder.java:663)
  at org.json.JSONStringer.toString (JSONStringer.java:430)
  at org.json.JSONArray.toString (JSONArray.java:586)
  at org.apache.cordova.PluginResult.<init> (PluginResult.java:49)
  at org.apache.cordova.CallbackContext.success (CallbackContext.java:88)
  at com.tenforwardconsulting.bgloc.cordova.BackgroundGeolocationPlugin$4.run (BackgroundGeolocationPlugin.java:226)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
  at java.lang.Thread.run (Thread.java:818)
```

**Comment by david7117** [comment]
@HarelM this also fixed my issue
