### ISSUE TITLE
ios: debug mode produces endless loop in notification handling

### ISSUE THREAD

**Issue by Ritzlgrmft** [mauron85/cordova-plugin-background-geolocation#657]
## Your Environment

* Plugin version: 3.1.0
* Platform: iOS
* OS version: 13.1
* Device manufacturer and model:

* Running in Simulator: Yes
* Cordova version (`cordova -v`): Capacitor 1.3.0
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: debug: true, desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY, saveBatteryOnBackground: true
* Link to your project:

## Context

In `CDVBackgroundGeolocation`, the notification delegate gets set:
```
center.delegate = self;
```

Immediately afterwards, in **debug** mode, this value gets stored in `prevNotificationDelegate`:
```
prevNotificationDelegate = center.delegate;
center.delegate = self;
```

When handling the notification, it calls always the handler of `prevNotificationDelegate` (which is `self`). This leads to and endless loop.

## Expected Behavior

Notification should be handled in debug mode as well.

## Actual Behavior

App crashes.

## Possible Fix

IMHO `prevNotificationDelegate` is completely useless. Probably you can just remove it. Or at least call it only, if it `!= self`.
 
## Steps to Reproduce

1.
2.
3.
4.

**Comment by StevieWag** [comment]
any news on that?!

**Comment by jackie-d** [comment]
This still happens with `@mauron85/cordova-plugin-background-geolocation@~3.1.0 + "@ionic-native/background-geolocation": "^5.22.0"`.

![Schermata 2020-03-18 alle 12 26 39](https://user-images.githubusercontent.com/20744688/76957334-e4ad1700-6915-11ea-89ce-0ace9d361ba2.png)

The fix proposed by @Ritzlgrmft it's mandatory to keep the iOs version working, otherwise it will just crash at start.

**Comment by jackie-d** [comment]
Related to: 
https://github.com/mauron85/cordova-plugin-background-geolocation/issues/645
https://github.com/mauron85/cordova-plugin-background-geolocation/pull/633

The latest and this one explain the issue details really well and address the fix. 
Any maintaner or iOs dev to open a PR?

**Temporary solution: disable debug mode in config **

```
this.backgroundGeolocation.configure({
  // ...
  debug: **false**
  // ...
});
```

**Comment by jdnichollsc** [comment]
Oh why?
