### ISSUE TITLE
Help when using Firebase as backend

### ISSUE THREAD

**Issue by ivanssa** [mauron85/cordova-plugin-background-geolocation#66]
Hi mauron85, First I would like to congratulate to keep this great repo for the community, I believe that everyone can collaborate can make this a great new Geolocation plugin in the background .. I am currently working on a project that uses Firebase. there my question is whether the plugin is compatible with this backend. They provide the javascript api and prefer not to use traditional client / server protocols.

I currently use the same code to communicate with the app when it is active and works, but for some reason the same code does not work in the background when having to add to execute within the CallbackFn plugin, anyone could help?

```
document.addEventListener ( 'deviceready' onDeviceReady, false);

onDeviceReady function () {

  var callbackFn = function (location) {
        
console.log ( '[js] BackgroundGeoLocation callback:' + location.latitude + ',' + location.longitude);

               // FireBase Post Backend
var = new firebase Firebase ( 'https://myapp.firebaseio.com/');
var = markersRef firebase.child ( 'maps /');

markersRef.child (myUuid) .set ({
coords: {
latitude: location.latitude,
longitude: location.longitude,
},
type: 'BGgeo'
timestamp: Math.floor (Date.now () / 1000)
});
                  
                   //backgroundGeoLocation.finish ();
 };
```

**Comment by mauron85** [comment]
Still an issue?

**Comment by ivanssa** [comment]
Yes I managed to find a way firebird accepts update via the plugin with the put method, the final code in the settings was so >> 
url:"https://myapp.firebaseio.com/maps/map/userid.json",
method: 'PUT',

**Comment by countrdd** [comment]
Can you post up a ref?
