### ISSUE TITLE
Android run error: package org.apache.http does not exist

### ISSUE THREAD

**Issue by arcarruda** [mauron85/cordova-plugin-background-geolocation#661]
## Your Environment

macOS Catalina (Version 10.15.1)
I usually add the platform from the command line and run it on Android Studio.

* Plugin version: "^3.1.0"
* Platform: Android
* OS version: macOS Catalina (Version 10.15.1)
* Device manufacturer and model: Samsung SM-A205W

* Running in Simulator: no
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1)

* Ionic Version ('ionic info'): 
Ionic:
   Ionic CLI                     : 5.4.9 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1
Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 8 other plugins)
Utility:
   cordova-res : 0.6.0 (update available: 0.8.1)
   native-run  : 0.2.9 
System:
   Android SDK Tools : 26.1.1 (/Users/arruda/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v12.6.0 (/usr/local/bin/node)
   npm               : 6.13.1
   OS                : macOS Catalina
   Xcode             : Xcode 11.2.1 Build version 11B500

* Plugin List ('ionic cordova plugin list'): 
   cordova-plugin-actionsheet 2.3.3 "ActionSheet"
   cordova-plugin-background-geolocation 1.0.6 "CDVBackgroundGeoLocation"
   cordova-plugin-device 2.0.3 "Device"
   cordova-plugin-dialogs 2.0.2 "Notification"
   cordova-plugin-geolocation 4.0.2 "Geolocation"
   cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
   cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
   cordova-plugin-splashscreen 5.0.3 "Splashscreen"
   cordova-plugin-statusbar 2.4.3 "StatusBar"
   cordova-plugin-whitelist 1.3.4 "Whitelist"
   uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"

## Context

After adding the Android platform and I try to run on my device I get the following error: "error: package org.apache.http does not exist"

I'm kind of new here... Thanks guys for the help.

**Comment by jancellor** [comment]
I can't remember exactly what the issue with the org.apache.http library is, but if it helps, I have this in my `config.xml` in the `<platform name="android">...` section:

        <config-file target="AndroidManifest.xml" parent="/*/application">
            <uses-library android:name="org.apache.http.legacy" android:required="false"/>
        </config-file>

Not sure what the equivalent on Ionic is.

**Comment by arcarruda** [comment]
Thank you for you help @jancellor. But didn't work. Same answer: error: package org.apache.http does not exist.

**Comment by arcarruda** [comment]
One think that helped me was first add the Android platform to after install the BG Geolocation plugin. But if I try to add the Android platform after the plugin is in my package.json, it cause this error related by me.

**Comment by KevinToala** [comment]
@arcarruda Thank you, your solution worked for me
