### ISSUE TITLE
How to turn off logging? 

### ISSUE THREAD

**Issue by davidpadych** [mauron85/cordova-plugin-background-geolocation#668]
## Your Environment
* Plugin version: 2.3.6 (all versions)
* Platform: Android
* OS version: Android 9
* Device manufacturer and model: Samsung

* Running in Simulator: no (real device)
* Cordova version (`cordova -v`): 7.1.0
* Cordova platform version (`cordova platform ls`): Android 7.1.0

## Context
Package com.marianhello.logging logs every event to SQL DB. For half a year of using the application (with plugin cordova-plugin-background-geolocation) - **the log specifically had logback.db size of 11 GB**. There is some way to turn off logging? for example, to limit writing to DB (days, count of records), or even better to select a given logLevel..

## Expected Behavior
Possibility to set logging level or complete shutdown.

## Actual Behavior
Write everything and increase db

**Comment by davidpadych** [comment]
background-geolocation-android/src/main/java/com/marianhello/logging/LoggerManager.java // line 41

root.setLevel(Level.TRACE); // root.setLevel(Level.OFF);

**Comment by Ayoitswiz** [comment]
I believe there's an option to set Max Locations. Currently on my app the locations are getting logged and then deleted immediately. This is however unintentional, as I actually want to store the locations. Does your app continue to store locations in the db after 3-4 minutes and if you've already fixed your issue did it store locations in the d-b beyond that 3-4 minute mark? I'm also using Android but version 8.0.1.

**Comment by davidpadych** [comment]
I am writing here about the problem of logging .. not about storing positions - of course I know that they can be limited with the maxLocations parameter

**Comment by Ayoitswiz** [comment]
If its logging the locations and not deleting them isn't that considered storing them?

**Comment by heartmon** [comment]
I also encounter the same issue. Have you been able to turn-off the logging or any workaround?
