### ISSUE TITLE
get the distance between two callbacks 

### ISSUE THREAD

**Issue by hatimox** [mauron85/cordova-plugin-background-geolocation#67]
hello , i need to get the distance between the old position and the new position so is this is integrated on this plugin or should i calculate it manually ?

thanks

**Comment by mauron85** [comment]
Hi, you have to do it yourself.

**Comment by hatimox** [comment]
hello thanks for your reply

**Comment by hatimox** [comment]
do you have any idea how to calculate the distance because my function it not exact i have always 5% to 7% of error in the distance here is my code : 

`function getDistanceFromLatLonInKm(lat1,lon1,lat2,lon2) {
    var R = 6371; // Radius of the earth in km
    var dLat = deg2rad(lat2-lat1);  // deg2rad below
    var dLon = deg2rad(lon2-lon1); 
    var a = 
      Math.sin(dLat/2) * Math.sin(dLat/2) +
      Math.cos(deg2rad(lat1)) * Math.cos(deg2rad(lat2)) * 
      Math.sin(dLon/2) * Math.sin(dLon/2)
      ; 
    var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a)); 
    var d = R * c; // Distance in km
    return d
  }

  function deg2rad(deg) {
    return deg * (Math.PI/180)
  }`

**Comment by mauron85** [comment]
Yes, you can do it on client side as @hatimox is suggesting.
