### ISSUE TITLE
ionic cordova build android - error: package org.apache.http does not exist import org.apache.http.HttpResponse;

### ISSUE THREAD

**Issue by mirceah13** [mauron85/cordova-plugin-background-geolocation#670]
## Your Environment

* Plugin version: ^3.1.0
* Platform: iOS or Android
* OS version: Windows 10 Home (1903)
* Device manufacturer and model: Samsung Galaxy S10+

* Running in Simulator: No
* Cordova version (`cordova -v`): 9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (`cordova platform ls`): 
Installed platforms:
  android 8.1.0
Available platforms:
  browser ^6.0.0
  electron ^1.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0
* Plugin configuration options: 
"cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-geolocation": {
        "GEOLOCATION_USAGE_DESCRIPTION": "To log kms travel"
      },
      "cordova-plugin-advanced-http": {},
      "cordova-plugin-background-geolocation": {
        "GOOGLE_PLAY_SERVICES_VERSION": "11+",
        "ANDROID_SUPPORT_LIBRARY_VERSION": "26+",
        "ICON": "@mipmap/icon",
        "SMALL_ICON": "@mipmap/icon",
        "ACCOUNT_NAME": "@string/app_name",
        "ACCOUNT_LABEL": "@string/app_name",
        "ACCOUNT_TYPE": "$PACKAGE_NAME.account",
        "CONTENT_AUTHORITY": "$PACKAGE_NAME"
      },
      "cordova-android-support-gradle-release": {
        "ANDROID_SUPPORT_VERSION": "27.+"
      }
    },
* Link to your project:

## Context

running **_ionic cordova build android_**

## Expected Behavior

Successful build 

## Actual Behavior

C:\Work\kms-app\platforms\android\gradlew: Command failed with exit code 1 Error output:
C:\Work\kms-app\platforms\android\app\src\main\java\com\zencity\cordova\bgloc\LocationUpdateService.java:6: error: package org.apache.http does not exist
import org.apache.http.HttpResponse;
                      ^
C:\Work\kms-app\platforms\android\app\src\main\java\com\zencity\cordova\bgloc\LocationUpdateService.java:7: error: package org.apache.http.client.methods does not exist
import org.apache.http.client.methods.HttpPost;
                                     ^
C:\Work\kms-app\platforms\android\app\src\main\java\com\zencity\cordova\bgloc\LocationUpdateService.java:8: error: package org.apache.http.entity does not exist
import org.apache.http.entity.StringEntity;
                             ^
C:\Work\kms-app\platforms\android\app\src\main\java\com\zencity\cordova\bgloc\LocationUpdateService.java:9: error: package org.apache.http.impl.client does not exist
import org.apache.http.impl.client.DefaultHttpClient;
                                  ^
C:\Work\kms-app\platforms\android\app\src\main\java\com\zencity\cordova\bgloc\LocationUpdateService.java:662: error: cannot find symbol
            DefaultHttpClient httpClient = new DefaultHttpClient();
            ^
  symbol:   class DefaultHttpClient
  location: class LocationUpdateService
C:\Work\kms-app\platforms\android\app\src\main\java\com\zencity\cordova\bgloc\LocationUpdateService.java:662: error: cannot find symbol
            DefaultHttpClient httpClient = new DefaultHttpClient();
                                               ^
  symbol:   class DefaultHttpClient
  location: class LocationUpdateService
C:\Work\kms-app\platforms\android\app\src\main\java\com\zencity\cordova\bgloc\LocationUpdateService.java:663: error: cannot find symbol
            HttpPost request = new HttpPost(url);
            ^
  symbol:   class HttpPost
  location: class LocationUpdateService
C:\Work\kms-app\platforms\android\app\src\main\java\com\zencity\cordova\bgloc\LocationUpdateService.java:663: error: cannot find symbol
            HttpPost request = new HttpPost(url);
                                   ^
  symbol:   class HttpPost
  location: class LocationUpdateService
C:\Work\kms-app\platforms\android\app\src\main\java\com\zencity\cordova\bgloc\LocationUpdateService.java:677: error: cannot find symbol
            StringEntity se = new StringEntity(params.toString());
            ^
  symbol:   class StringEntity
  location: class LocationUpdateService
C:\Work\kms-app\platforms\android\app\src\main\java\com\zencity\cordova\bgloc\LocationUpdateService.java:677: error: cannot find symbol
            StringEntity se = new StringEntity(params.toString());
                                  ^
  symbol:   class StringEntity
  location: class LocationUpdateService
C:\Work\kms-app\platforms\android\app\src\main\java\com\zencity\cordova\bgloc\LocationUpdateService.java:691: error: cannot find symbol
            HttpResponse response = httpClient.execute(request);
            ^
  symbol:   class HttpResponse
  location: class LocationUpdateService
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Work\kms-app\platforms\android\app\src\main\java\org\apache\cordova\file\AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
11 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.

**Comment by harithFED** [comment]
hi, can run "cordova plugin ls" and paste here?

**Comment by abalad** [comment]
same here

**Comment by dioslibre** [comment]
Edit your builde.gradle file so that it looks like this:

`...

android {
    useLibrary 'org.apache.http.legacy'

    ...
}`

**Comment by developerjaag** [comment]
> Edit your build.gradle file so that it looks like this:
> 
> ```
> ...
> 
> android {
>     useLibrary 'org.apache.http.legacy'
> 
>     ...
> }
> 
> ...
> ```

Same problem here....
Thanks for your answer, but it does not work for me

**Comment by Daelus1** [comment]
I'm experiencing this problem as well

**Comment by dioslibre** [comment]
Can you check your build.gradle file to see if it was overwritten or something?  or paste it here, because I don't see any other solution.

The cordova ecosystem is filled with unmaintained and erroneous plugins, even if you solve this you'll run into all sorts of other problems with other plugins. I don't mean any disrespect to the cordova community, but it's true. Just move to Xamarin, code your front-end just like you do with cordova, and create the a webview on the Xamarin side, and you're set. The .Net ecosystem is a far better environement to code in.

Check this out.
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview
https://forums.xamarin.com/discussion/155941/developing-a-location-background-service.

Hope this helps.

**Comment by dioslibre** [comment]
Also, try addid this to AndroidManifest.xml file:
`<uses-library android:name="org.apache.http.legacy" android:required="true"/>`

**Comment by developerjaag** [comment]
Totally agree. With many plugins we reach a difficult alley; However this worked for me:
https://github.com/apache/cordova-android/issues/678#issuecomment-544961990

**Comment by harithFED** [comment]
i also faced this issue. but solved by reinstall back the plugin because of geolocation plugin.
