### ISSUE TITLE
 BackgroundGeolocation plugin is not installed Issue 

### ISSUE THREAD

**Issue by abalad** [mauron85/cordova-plugin-background-geolocation#675]
## Your Environment

* Plugin version: 3.1.0
* Platform: iOS or Android
* OS version: Android
* Device manufacturer and model: device

* Running in Simulator:
* Cordova version (`cordova -v`): 9.0.0
* Cordova platform version (`cordova platform ls`):  
```bash
Installed platforms:
  android 8.1.0
Available platforms:
  browser ^6.0.0
  electron ^1.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0
```
* Plugin configuration options: 

```js
{
desiredAccuracy: 10,
stationaryRadius: 20,
distanceFilter: 30,
debug: true, //  enable this hear sounds for background-geolocation life-cycle.
stopOnTerminate: false // enable this to clear background location settings when the app terminates
}
```

## Context
I'm trying to run my application with the plugin but it always returns this message to me.
I've tried to reinstall, remove and add the platform, reinstall the platform, uninstall and install the npm packages, and even then this message does not come out. And the plugin is not loaded.

## Actual Behavior

![image](https://user-images.githubusercontent.com/5459282/73996181-ad704100-4939-11ea-8902-5241f7c8772f.png)

## Steps to Reproduce

1. ionic cordova plugin add @mauron85/cordova-plugin-background-geolocation
2. npm install --save @ionic-native/background-geolocation
3. ionic cordova platform add android
4. ionic cordova prepare android

**Comment by stefanotauriello** [comment]
I've the same problem!

**Comment by abalad** [comment]
Same issue here

**Comment by stefanotauriello** [comment]
Solved!

`import { BackgroundGeolocation, BackgroundGeolocationConfig, BackgroundGeolocationEvents, BackgroundGeolocationResponse } from '@ionic-native/background-geolocation/ngx';`

instead of 
`import { BackgroundGeolocation, BackgroundGeolocationConfig, BackgroundGeolocationEvents, BackgroundGeolocationResponse } from '@ionic-native/background-geolocation';`

**Comment by RaschidJFR** [comment]
This may be related to #613
