### ISSUE TITLE
Uncaught ReferenceError: backgroundGeoLocation is not defined

### ISSUE THREAD

**Issue by Jpsankaran** [mauron85/cordova-plugin-background-geolocation#68]
I have installed plugin "https://github.com/mauron85/cordova-plugin-background-geolocation.git" into Cordova project.
And removed android platform & re-added android platform

But still i am getting this error "Uncaught ReferenceError: backgroundGeoLocation is not defined"

I want to get geolocation for every 5 sec in my cordova app.
Any suggestion..?

**Comment by gandhirajan** [comment]
@Jpsankaran How did you resolved this?
