### ISSUE TITLE
Google version api 28 with android 8.0 does not work the geolocation services

### ISSUE THREAD

**Issue by torkcavera** [mauron85/cordova-plugin-background-geolocation#680]
with google moving to api 28 the plugin @ mauron85 /cordova-plugin-background-geolocation is not possible to activate the tracker to monitor the user's geolocation and their positions

cordova-plugin-background-geolocation  v3.1.0

Installed platforms:
  android 8.0.0
  browser 5.0.4
  ios 4.5.5
Available platforms: 
  electron ^1.0.0
  osx ^5.0.0
  windows ^7.0.0

**Comment by lander854** [comment]
Same issue here

**Comment by koczka** [comment]
I got a working build dropping my versions back to cordova 7.1 and android platform 6.3

**Comment by spinninghamster** [comment]
What does this mean? The plugin is unusable?

Since all apps now require Android 28 or even 29..
