### ISSUE TITLE
BackgroundGeolocation is not defined and Module cordova-plugin-background-geolocation.BackgroundGeolocation does not exist.

### ISSUE THREAD

**Issue by programercek** [mauron85/cordova-plugin-background-geolocation#681]
## Your Environment

* Plugin version:  3.1.0
* Platform: Android
* OS version:
* Device manufacturer and model:

* Running in Simulator:
* Cordova version (`cordova -v`): 9.0.1
* Cordova platform version (`cordova platform ls`): android 8.1.0
* Plugin configuration options: 
* Link to your project:

## Context
In console I got:
BackgroundGeolocation is not defined and Module cordova-plugin-background-geolocation.BackgroundGeolocation does not exist.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by nuno** [comment]
Duplicated https://github.com/mauron85/cordova-plugin-background-geolocation/issues/675
