### ISSUE TITLE
[iOS] phonegap-plugin-push has different behaviour when you have installed background-geolocation-plugin

### ISSUE THREAD

**Issue by varreba** [mauron85/cordova-plugin-background-geolocation#682]
## Your Environment

Plugin version:
cordova-plugin-background-geolocation: 3.1.0

Package.json ->

            "cordova-plugin-background-geolocation": {
                "GOOGLE_PLAY_SERVICES_VERSION": "15+",
                "ANDROID_SUPPORT_LIBRARY_VERSION": "27+",
                "ICON": "@mipmap/icon",
                "SMALL_ICON": "@mipmap/icon",
                "ACCOUNT_NAME": "@string/app_name",
                "ACCOUNT_LABEL": "@string/app_name",
                "ACCOUNT_TYPE": "$PACKAGE_NAME.account",
                "CONTENT_AUTHORITY": "$PACKAGE_NAME",
                "ALWAYS_USAGE_DESCRIPTION": "",
                "MOTION_USAGE_DESCRIPTION": ""
            }
Config.xml

    <plugin name="cordova-plugin-background-geolocation" spec="https://github.com/mauron85/cordova-plugin-background-	geolocation.git#67a605a413e9fa3bfad5a129a06afed943004901">
        <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="15+" />
        <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="27+" />
        <variable name="ICON" value="@mipmap/icon" />
        <variable name="SMALL_ICON" value="@mipmap/icon" />
        <variable name="ACCOUNT_NAME" value="@string/app_name" />
        <variable name="ACCOUNT_LABEL" value="@string/app_name" />
        <variable name="ACCOUNT_TYPE" value="$PACKAGE_NAME.account" />
        <variable name="CONTENT_AUTHORITY" value="$PACKAGE_NAME" />
    </plugin>

[cordova-plugin-ionic-webview: 2.5.3](https://github.com/ionic-team/cordova-plugin-ionic-webview)
[phonegap-plugin-push: 2.2.3](https://github.com/phonegap/phonegap-plugin-push)
angular: 5.0.3

* Platform: iOS

* OS version:
 13.3.1 (phone 6s)
 12.3.1 (Iphone 5)

* Device manufacturer and model:
 Iphone 6s (13.3.1)
 Iphone 5 (12.3.1)

I specified both models to tell you i testing on different devices, and the behavior is the same in both. Also my work mates have tested in other IOS devices (iphone 5, iphone 7,  iphone xi, ipad, etc) and they have checked too.

* Running in Simulator: 
No

* Cordova version (`cordova -v`):
8.1.2

* Cordova platform version (`cordova platform ls`):
ios 5.0.1

* Plugin configuration options: 

Package.json ->

            "cordova-plugin-background-geolocation": {
                "GOOGLE_PLAY_SERVICES_VERSION": "15+",
                "ANDROID_SUPPORT_LIBRARY_VERSION": "27+",
                "ICON": "@mipmap/icon",
                "SMALL_ICON": "@mipmap/icon",
                "ACCOUNT_NAME": "@string/app_name",
                "ACCOUNT_LABEL": "@string/app_name",
                "ACCOUNT_TYPE": "$PACKAGE_NAME.account",
                "CONTENT_AUTHORITY": "$PACKAGE_NAME",
                "ALWAYS_USAGE_DESCRIPTION": "",
                "MOTION_USAGE_DESCRIPTION": ""
            },

Config.xml

    <plugin name="cordova-plugin-background-geolocation" spec="https://github.com/mauron85/cordova-plugin-background-geolocation.git#67a605a413e9fa3bfad5a129a06afed943004901">
        <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="15+" />
        <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="27+" />
        <variable name="ICON" value="@mipmap/icon" />
        <variable name="SMALL_ICON" value="@mipmap/icon" />
        <variable name="ACCOUNT_NAME" value="@string/app_name" />
        <variable name="ACCOUNT_LABEL" value="@string/app_name" />
        <variable name="ACCOUNT_TYPE" value="$PACKAGE_NAME.account" />
        <variable name="CONTENT_AUTHORITY" value="$PACKAGE_NAME" />
    </plugin>

## Context

There is a problem between the background-geolocation plugin, the [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push), and the [cordova-plugin-ionic-webview](https://github.com/ionic-team/cordova-plugin-ionic-webview). The problem is that the [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push) has a different behaviour when you have installed background-geolocation-plugin. The error happens from version 3.0.0 and next versions.

## Expected Behavior
Our backend send the notification push without the content-available flag. The app is in foreground, when push arrives, the native part comunicates the notification to the Webview

## Actual Behavior
Our backend send the notification push without the content-available flag. The app is in foreground, when push arrives, the native part **is not** comunicating the notification to the Webview.
However, with the content-available flag, the native part communicate the push notification.

## Steps to Reproduce

1. Create a app with these plugins
2. Open the app and register push notifications
3. Backend send push notification without content-available flag
4. You can see the push notification, but the webview part doesn't receive this push notification.

## Context

We  have seen the bug when we have upgraded the version of the plugin. The plugin change the behavior between versions. The error happens from version 3.0.0 and next versions. We have tested with every version from 2.2.5 to the latest version (3.1.0) 

## Note
We only test with the [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push), but it is posible other plugins or features have the same (or similar) issue.

**Comment by ynunez** [comment]
@varreba  I think the issue that you are facing is due to the override of the notification center handler. The fix I provided should fix your issue. Before it gets approved and merged you can manually change the code inside `CDVBackgroundGeolocation.m`. Follow the PR as a guide

**Comment by ProximaHaiz** [comment]
@ynunez You removed the code that allows to push notification appears. But also cordova-plugin-background-geolocation  handle tap event on notification. So you must remove code, that handle tap event too.
