### ISSUE TITLE
Callback will not fire if location has not changed.

### ISSUE THREAD

**Issue by camerondykeman** [mauron85/cordova-plugin-background-geolocation#69]
Hi there,

great job on the fork.
The one question I have is regarding the callback on Android - currently the callback will not fire if the location returned has not changed since the previous location request, even when using ANDROID_FUSED_LOCATION with interval, fastestInterval, and activitiesInterval set super low (eg.1).
I totally understand that this is done to preserve battery life but in my use-case its important that a location be returned and recorded on our servers every 30seconds regardless of whether the location has changed or not. On iOS this functionality is achievable by calling changePace(true) every 30seconds; however, this does not seem to carry over to Android and I do not register a callback.

Is there any way to ensure that the plugin ALWAYS fires the callback at the interval, regardless of an actual position change?
Thanks!

**Comment by mauron85** [comment]
Hi, changePace should only work with ANDROID_DISTANCE_FILTER provider.

**Comment by galichmark** [comment]
Hi!

+1

It is real to get callback by timeout if position not changed?

**Comment by btdevn** [comment]
+1
Yes this feature is definitely needed for our app as well. Even if location has not changed we should be able to store the location to server at set intervals.

**Comment by mauron85** [comment]
Ok, too many of you requesting this. So I've just added option ```stopOnStillActivity```. Set it to false and it should behave like you requested.

**Comment by galichmark** [comment]
Yahooo! Great!

Thanks a lot!

**Comment by klidifia** [comment]
Could someone please provide me with an example of how to get regular timed interval locations? I can't seem to do it properly on either iOS or Android but seemingly some of you have done this?
