### ISSUE TITLE
Disable background geolocation after logout and clear notification "Background Tracking Enabled"

### ISSUE THREAD

**Issue by shalini-github** [mauron85/cordova-plugin-background-geolocation#699]
Hello Mauro, 
I see "Background Tracking Enabled" notification all the time on android devices. The scenario is when the user logs out or kill the app, the notification should be removed. Calling .stop() method on logoutbutton click. To clear the notification i have to uninstall the app every time. Please suggest. 

If i set "startForeground : false" will it stop background location tracking on foreground.

Below is my config.
```
const config: BackgroundGeolocationConfig = { 

  desiredAccuracy: 10,

  stationaryRadius: 20,

  distanceFilter: 30,

  debug: false, //  enable this hear sounds for background-geolocation life-cycle.

  stopOnTerminate: true, // enable this to clear background location settings when the app terminates

};

```
I use "@mauron85/cordova-plugin-background-geolocation": "3.0.6"

**Comment by HarelM** [comment]
I think I have the same problem.
See here:
https://github.com/mauron85/cordova-plugin-background-geolocation/issues/683
It has links to other two issues as well.
Let me know if you figured out how to solve this issue.
