### ISSUE TITLE
Can Not Build IOS

### ISSUE THREAD

**Issue by blntylmn** [mauron85/cordova-plugin-background-geolocation#7]
I can build it on android but not on ios. The error is below :

** BUILD FAILED **

The following build commands failed:
	CompileC build/geolocation.build/Debug-iphonesimulator/geolocation.build/Objects-normal/i386/CDVBackgroundGeoLocation.o geolocation/Plugins/cordova-plugin-mauron85-background-geolocation/CDVBackgroundGeoLocation.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/catsoft/desktop/geolocation/platforms/ios/cordova/build-debug.xcconfig,-project,geolocation.xcodeproj,ARCHS=i386,-target,geolocation,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/catsoft/desktop/geolocation/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/catsoft/desktop/geolocation/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Users/catsoft/desktop/geolocation/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Users/catsoft/desktop/geolocation/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:139:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by mauron85** [comment]
Are you able to build older version?
In example/SampleApp.

Remove plugin first
```
cordova plugin rm cordova-plugin-mauron85-background-geolocation
```

Add older version of the plugin
```
cordova plugin add cordova-plugin-mauron85-background-geolocation@0.4.3
```

```
cordova build ios
```

**Comment by mauron85** [comment]
And what is your cordova version?

```
cordova -v
```

Try to update it to the latest version. According this thread https://github.com/driftyco/ionic-cli/issues/282#issuecomment-91307167 this might help.

```
sudo cordova platform remove ios
sudo cordova platform add ios
```

**Comment by mauron85** [comment]
Another one describing code error 65. Please try and report if it helps.

http://michael.lavaveshkul.com/blog/2011/12/xcodebuild-exit-code-65/

**Comment by catsoftware** [comment]
Ok I tried your suggestions. Here is details :
First of all my system configurations
OSX El Capitan Version 10.11.1 (15B42)
Cordova Version 5.3.3
XCode Version 7.0.1 (7A1001)

When I tried older version (0.4.3) it builds  no more error but i am getting this error
ReferenceError: Can't find variable: backgroundGeoLocation, http://192.168.1.2:8100/js/app.js, Line: 83
which line 83 contains > backgroundGeoLocation.finish();

On the other hand when I googled the error in in my first post I saw other plugins had this issue too. And most of answers points to Xcode7 and swift2 compatibility issue. And suggestions are usually fork a copy and add missing files etc. but I am not familiar with writing cordova plugins :( 
So I am waiting your answer and thanks for the quick reply ( sorry about my english I am still learning :)

**Comment by catsoftware** [comment]
I am confusing about your last post. I did not understand what he means with "Make sure you’ve installed an up to date certificate in your Keychain". Do I need a developer account for cordova testing on a simulator (not a real device). Because everything else worked until now.

**Comment by mauron85** [comment]
> ReferenceError: Can't find variable: backgroundGeoLocation, http://192.168.1.2:8100/js/app.js, Line: 83

I don't have access to you app.js (obviously), so I can only guess. The only thing in my mind is that, if your code is called after deviceready event? Before that event, backgroundGeoLocation is not defined.

> Do I need a developer account for cordova testing on a simulator (not a real device). Because everything else worked until now.

I think not needed for emulator. You can ignore that hint.

**Comment by mauron85** [comment]
Can you try version 0.7.2? Just published to npm.

**Comment by mauron85** [comment]
@blntylmn What is the status? Can I close this one?

**Comment by blntylmn** [comment]
Sorry I was on vacation. Yes you can close it. Works fine after update.
