### ISSUE TITLE
How to check whether background GPS permission is enabled?

### ISSUE THREAD

**Issue by sazima** [mauron85/cordova-plugin-background-geolocation#705]
## Your Environment

* Plugin version: 3.1.0
* Platform: Android
* OS version: Adroid 9
* Device manufacturer and model:

* Running in Simulator: false
* Cordova version (`cordova -v`):  9.0.0 (cordova-lib@9.0.1)
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options:  
* Link to your project:

## Expected Behavior

If the user does not enable background permission, give him a prompt.  such as:

```
if (!hasBackGroundGPSPermission) {
   alert(...)
}
```

## Actual Behavior

null

## Possible Fix

null
## Steps to Reproduce

1.
2.
3.
4.

**Comment by ZumelzuR** [comment]
You can use a different plugin for do this.

https://www.npmjs.com/package/cordova-plugin-android-permissions

Hope that work for you
