### ISSUE TITLE
Write the time in the notification

### ISSUE THREAD

**Issue by Davids89** [mauron85/cordova-plugin-background-geolocation#71]
Is there any option to show the real time in the notification? At the moment I get the time where the app is launched, but I need to put the real time.

Is this important to prevent that Android close the service or it can be working only with the notification?

**Comment by mauron85** [comment]
> Is there any option to show the real time in the notification?  At the moment I get the time where the app is launched, but I need to put the real time.

Notification text is static. You call call configure plugin to change it dynamically, but don't think it's good idea. Maybe use some kind of cordova notification plugin will be good idea.

>Is this important to prevent that Android close the service or it can be working only with the notification?

Not sure I understand. But when you see notification, background service should be running.
