### ISSUE TITLE
changePace question

### ISSUE THREAD

**Issue by culland** [mauron85/cordova-plugin-background-geolocation#72]
I read the following in the plugin description:

> The plugin uses iOS Significant Changes API, and starts triggering callbackFn only when a cell-tower switch is detected (i.e. the device exits stationary radius). The function changePace(isMoving, success, failure) is provided to force the plugin to enter "moving" or "stationary" state.

Can the changePace function be used to over-ride the cell-tower switch requirement so that it starts triggering callbackFn from the start rather than waiting for the switch detection?

**Comment by kristfal** [comment]
Yes,

here is an example of an aggressive background track setting which should give quite similar results for iOS and Android:


```js

debug = true // make them sounds
deviceType = cordova.platformId

if (deviceType === 'ios') {
  window.backgroundGeoLocation.configure(
    this._onBackgroundGeolocationSuccess.bind(this),
    this._onBackgroundGeolocationFailure.bind(this), {
      desiredAccuracy: 10,
      stationaryRadius: 20,
      distanceFilter: 50,
      debug: debug,
      stopOnTerminate: true,

      // iOS specifics
      activityType: 'OtherNavigation'
    }
  );
}
else if (deviceType === 'android') {
  window.backgroundGeoLocation.configure(
    this._onBackgroundGeolocationSuccess.bind(this),
    this._onBackgroundGeolocationFailure.bind(this), {
      desiredAccuracy: 0,
      stationaryRadius: 10,
      distanceFilter: 5,
      debug: debug,
      stopOnTerminate: true,

      // Android specifics
      locationService: window.backgroundGeoLocation.service.ANDROID_FUSED_LOCATION,
      notificationIconColor: '#bada55',
      notificationTitle: 'Tracking',
      notificationText: 'ENABLED',
      notificationIcon: 'notification_icon',
      interval: 10000, // Prefer a poll every 10 sec
      fastestInterval: 5000, // If other apps are also using geolocation actively, update at fastest every 5 sec
      activitiesInterval: 15000 // Check if device is standing still or moving with accelerometer every 15 sec
    }
  );
}

window.backgroundGeoLocation.changePace(true);
window.backgroundGeoLocation.start();

```

**Comment by uzumakinaruto123** [comment]
@kristfal  you config with comments is helping me alot understanding difference between all the interval  :p

using higher `activitiesInterval ` helps battery saving. i tried with 60000 i.e every minute.
I would like to know what was the impact on battery when you use 15 sec as the `activitiesInterval `

another thing i noiticed was after every interval it checks whether device is `still `or `moving`. but at that point if device is `still ` doesn't  return any location.

have you figured a way to return a location after that interval irrespective of device state ?

Thanks  Help is appreciated.

**Comment by mauron85** [comment]
Behaviour change in 2.0.0. You can force detection with switchMode method.
