### ISSUE TITLE
Android build failure: Dex exception

### ISSUE THREAD

**Issue by kristfal** [mauron85/cordova-plugin-background-geolocation#73]
Hey,

I've been building with this plugin flawlessly for quite a while, but updated my Android support libs and now the build is failing:

```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/MessengerCompat$1;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
```

Plugin list:

```
com.telerik.plugins.wkwebview 0.6.9 "WKWebView Polyfill"
cordova-plugin-crosswalk-webview 1.7.0 "Crosswalk WebView Engine"
cordova-plugin-device 1.1.2-dev "Device"
cordova-plugin-device-orientation 1.0.1 "Device Orientation"
cordova-plugin-disable-bitcode 1.2.1 "DisableBitcode"
cordova-plugin-facebook4 1.7.1 "Facebook Connect"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-file-transfer 1.5.0 "File Transfer"
cordova-plugin-geolocation 2.1.1-dev "Geolocation"
cordova-plugin-globalization 1.0.2 "Globalization"
cordova-plugin-inappbrowser 1.1.1 "InAppBrowser"
cordova-plugin-inapppurchase 0.5.0 "In App Purchase"
cordova-plugin-intercom 1.1.5 "Intercom"
cordova-plugin-ios-no-export-compliance 0.0.1 "iOS No Export Compliance"
cordova-plugin-keyboard 1.1.3 "Keyboard"
cordova-plugin-mauron85-background-geolocation 0.9.6 "CDVBackgroundGeoLocation"
cordova-plugin-network-information 1.0.1 "Network Information"
cordova-plugin-splashscreen 3.1.1-dev "Splashscreen"
cordova-plugin-statusbar 2.1.1-dev "StatusBar"
cordova-plugin-transport-security 0.1.1 "App Transport Security"
cordova-plugin-webserver 1.0.3 "CordovaWebServer"
cordova-plugin-whitelist 1.2.2-dev "Whitelist"
cordova.plugins.diagnostic 2.3.17 "Diagnostic"
nl.x-services.plugins.insomnia 4.0.1 "Insomnia (prevent screen sleep)"

```

Removing this plugin resolves these build issues.

#### Debugging so far:

This is the resulting `build.grade` from the plugin list above:

```
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    debugCompile project(path: "CordovaLib", configuration: "debug")
    releaseCompile project(path: "CordovaLib", configuration: "release")
    compile "com.facebook.android:facebook-android-sdk:4.8.+"
    compile "com.google.android.gms:play-services-gcm:8.+"
    compile "com.google.android.gms:play-services-location:+"
    compile "com.android.support:support-v4:+"
    compile "com.android.support:support-v4:23.+"
    compile "com.android.support:appcompat-v7:23.+"
    // SUB-PROJECT DEPENDENCIES END
}
```

`com.android.support:support-v4:23.+` is required by `cordova.plugins.diagnostic`. Removing that plugin will resolve the `support:support` dependency conflict, but the build will still fail at the `MessengerCompat` dex conflict.

Additionally, removing `<framework src="com.android.support:support-v4:+" />` from this plugin's plugin.xml will not resolve the dex issue either, so I'm guessing the next obvious thing would be to start looking at the `com.google.android.gms:play-services-location`. 

Any idea how to proceed?

**Comment by kristfal** [comment]
Update:

Build works with dependencies:

```
  <framework src="com.google.android.gms:play-services-location:8.+" />
  <framework src="com.android.support:support-v4:23.+" />
```

The conflicting other plugins are:

`cordova-plugin-intercom 1.1.5 "Intercom"` with `com.google.android.gms:play-services-gcm:8.+` 

which is incompatible with `com.google.android.gms:play-services-location:+` 

and `cordova.plugins.diagnostic 2.3.17 "Diagnostic"` as described in the initial post.


This plugin seems to work fine with the updated framework dependencies. How do you think we should proceed?

**Comment by mauron85** [comment]
Hi @kristfal, thank you for the report. To be honest, I'm not fully aware how version declaration in framework tag works. Because current declaration is

        <framework src="com.google.android.gms:play-services-location:+" />
        <framework src="com.android.support:support-v4:+" />

I thought + means satisfy all versions (like star in npm). So help needed, to clarify how versioning works here.

**Comment by mauron85** [comment]
Ok. There is unwritten rule that all cordova plugins should like against same version of google support library to prevent dex issue. Apparantly cordova.plugins.diagnostic is not following that rule :-)

Ask author to link against change plugin.xml to:

```
<framework src="com.android.support:support-v4:+" />
```
