### ISSUE TITLE
Cannot build on iOS because random errors

### ISSUE THREAD

**Issue by peechyfloof** [mauron85/cordova-plugin-background-geolocation#731]
## Your Environment
* Plugin version: 3.1.0
* Platform: iOS  (Android works fine tho)
* OS version: 
* Device manufacturer and model:
* Cordova version (`cordova -v`):
* Cordova platform version (`cordova platform ls`):
* Plugin configuration options: 
* Link to your project:

## Context
I was writing my app when suddenly, without making changes in package.json, config.xml or something else, it stopped working
Package json

        "@mauron85/cordova-plugin-background-geolocation": "^3.1.0",

config xml
```
<plugin name="cordova-plugin-background-geolocation" spec="@mauron85/cordova-plugin-background-geolocation@~3.1.0">
        <variable name="GOOGLE_PLAY_SERVICES_VERSION" value="15+" />
        <variable name="ANDROID_SUPPORT_LIBRARY_VERSION" value="23+" />
        <variable name="ALWAYS_USAGE_DESCRIPTION" value="Wir brauchen deinen Standort, um dir die Meldungen anzuzeigen." />
        <variable name="MOTION_USAGE_DESCRIPTION" value="Wir brauchen deinen Standort, um dir die Meldungen anzuzeigen." />
        <variable name="ICON" value="@mipmap/icon" />
        <variable name="SMALL_ICON" value="@mipmap/icon" />
        <variable name="ACCOUNT_NAME" value="@string/app_name" />
        <variable name="ACCOUNT_LABEL" value="@string/app_name" />
        <variable name="ACCOUNT_TYPE" value="$PACKAGE_NAME.account" />
        <variable name="CONTENT_AUTHORITY" value="$PACKAGE_NAME" />
    </plugin>
```

## Expected Behavior
install the plugin and build the app
## Actual Behavior
Failed to fetch plugin cordova-plugin-background-geolocation@@mauron85/cordova-plugin-background-geolocation@~3.1.0 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
CordovaError: Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@mauron85/cordova-plugin-background-geolocation@~3.1.0" as it does not contain a package.json file.
npm ERR! A complete log of this run can be found in:

## Possible Fix
i dunno man

## Steps to Reproduce
no  fucking idea, 

## Context

How can this happen? This happend so many times. I also removed platform, added platform, remove node_modules/ and platforms/ nothing works

**Comment by Vasek18** [comment]
I think you just have a typo. Try just "npm i @mauron85/cordova-plugin-background-geolocation"

**Comment by peechyfloof** [comment]
i already dumped cordova because its crap, but what makes you think its a typo?

**Comment by Vasek18** [comment]
> i already dumped cordova because its crap, but what makes you think its a typo?

Because you just try to install a npm package there is nothing to fail)
