### ISSUE TITLE
Remove Notification

### ISSUE THREAD

**Issue by ivent** [mauron85/cordova-plugin-background-geolocation#74]
Hello Mauro first congratulations for keeping this repository, for me it worked perfectly, I have only one doubt it is possible to remove the notification bar ?, know this has been discussed here, but I saw that Chris has found a solution then it is possible, my problem is many users are bothering with the constant notice that you can not remove and click it has a shortcut to uninstall and had several uninstalls after :-( include this plugin would be perfect to find a solution, hugs ...

**Comment by mauron85** [comment]
It's probably fact, that users are not used to it. They're two views on this. First ethical, people should be aware that the app is constantly doing background tracking and notification does exactly that. And second is technical. When you remove notification, there is higher chance app will be killed by the system as background task without notification has far lower priority. If you really decided to remove notification check next branch. There is code how to do it, but you have been warned. :-)

**Comment by ivent** [comment]
Hello Mauro, thanks for the quick response, I understand the reasons, I believe that a simple solution is to just allow plugin let desenolvedor decide whether to contain notifications or not through the former settings: notification: true / false so it would be ideal, would like to enable this functionality?

**Comment by mauron85** [comment]
it will be option in next version, but don't expect it any time soon. i don't have much time these days.

**Comment by ivent** [comment]
Tanks....

**Comment by Stiveknx** [comment]
Well, but if I go to system background process, I see a lot of background tasks, and none of them have a notification in drawer ...
Facebook, Messenger, WhatsApp, imo, Instagram, Motorola Update ..
How do they work, without the notification?

**Comment by ivent** [comment]
@Stiveknx These applications use the background but are not as specific in using your location constamente so may have some differences with respect to privacy, but to be more accurate the new "Nearby Friends" facebook uses geolocation in the background and not nescessita notification and it is also worth remembering that the original script cris this issue has been resolved, I believe that soon mauro will find a solution.

**Comment by mauron85** [comment]
Hi @Stiveknx. Not 100% sure, but I would guess those apps are not using background geolocation. Make no sense for Messenger and others to track you in the background. They probably have hooks to update location when app is resumed from sleep.

**Comment by shyamal890** [comment]
Hi @mauron85 I just got started with the plugin. On the first few runs it seems that GPS icon is also displayed when the app is running in background. Is there a way to hide GPS icon indicator too?

**Comment by guicouto** [comment]
Hi @mauron85 I started use your plugin and it is amazing. If I want to remove the notification text by myself, what I need to do? Can I help you with this?

**Comment by ivent** [comment]
@guicouto I believe that the GPS icon in the status bar is native android own and can not be removed, I believe there is no need to remove it until tb coz it shows that the GPS is active as well as Wifi connection, Bluetooth etc .. what we are discussing here and the need to remove the constant notification that can not be removed by the user and can cause discomfort and uninstalls of our apps, I believe that the solution leaving the pro user option to enable or disable notifications through the settings would be a ideal solution.

**Comment by mauron85** [comment]
Implemented in 2.0.0. Option startForeground false

**Comment by shyamal890** [comment]
@mauron85  For scenario in which location should also be tracked in foreground without notification, what do you suggest?

**Comment by ivent** [comment]
@mauron85  Again thank you and congratulations, to implement this feature worked perfectly now without notification, @shyamal890 for monitoring the active you can choose to work with the Cord-Plugin-Geolocation native plugin that for me worked perfectly together with the the BGgeo ...
