### ISSUE TITLE
Android M rejects the ANDROID_DISTANCE_FILTER string

### ISSUE THREAD

**Issue by leifwells** [mauron85/cordova-plugin-background-geolocation#75]
I ran into this "bug" today and wanted to make sure I mentioned it before I forgot.

In all the examples I see (on this site and elsewhere) I see this line:

`locationService: 'ANDROID_DISTANCE_FILTER',`

On my Android M phone this line throws an error stating that Java can't convert a string to an int.

Looking at the source, I **_assume_** this setting should be a 0 (not '0'), which is working on both iOS and Android. Please let me know if that is incorrect or if there is a different way of doing this.

**Comment by mauron85** [comment]
it's not a string but number. It works kind like enum.

Valid options for version 2.0.0
```
locationProvider: backgroundGeolocation.provider.ANDROID_DISTANCE_FILTER_PROVIDER
```
or
```
locationProvider: backgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER
```
