### ISSUE TITLE
Building android version doesn't work

### ISSUE THREAD

**Issue by tux240** [mauron85/cordova-plugin-background-geolocation#76]
Hey,

I'm building on IOS, no problem.
But, when I'm trying to build on Android, I have this error message:

`A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-location:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-location/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-location/
     Required by:
         :android:unspecified
   > Could not find any version that matches com.android.support:support-v4:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
     Required by:
         :android:unspecified`

I don't know how resolve this error. thanks for your help.

**Comment by mauron85** [comment]
Check that you have all dependencies. Probably you're missing play services. Install all deps from android sdk manager.

https://github.com/mauron85/cordova-plugin-background-geolocation#android

**Comment by mauron85** [comment]
Missi

**Comment by yuriploc** [comment]
@mauron85 would you mind reopening it?

It's conflicting with new Android SDK versions:

```shell
:generateArmv7DebugResources
:mergeArmv7DebugResources

:processArmv7DebugManifest
/home/yuri/codes/platforms/android/AndroidManifest.xml:27:9-31 Error:
        Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:appcompat-v7:25.3.1] AndroidManifest.xml:27:9-31
	is also present at [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:34 to override.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

:processArmv7DebugManifest FAILED

FAILURE: Build failed with an exception.
```
