### ISSUE TITLE
testing for battery consumption in ideal state

### ISSUE THREAD

**Issue by uzumakinaruto123** [mauron85/cordova-plugin-background-geolocation#77]
Hii mauron,

i am testing the plugin with different configurations (in ideal state)

**with`ANDROID_FUSED_LOCATION`** 

```
         backgroundGeoLocation.configure(callbackFn, failureFn, {
         desiredAccuracy: 0,
         stationaryRadius: 5,
         distanceFilter: 5,
         debug: true,
         stopOnTerminate: false,
         locationService: backgroundGeoLocation.service.ANDROID_FUSED_LOCATION,
         interval: 60000,
         fastestInterval: 60000
         });
```

> Result
> On keeping it on for 8 hours overnight (100 % charged) GPS ON.
> Charge left was 90%. Total battery consumption was 10%.
>  of which google play services consumed 28% and the app 23 %. rounding it to total 50%.
>  that means app was responsible for 50% consumption of total 10%.
>  i.e overall app used 5% of the battery overnight.

<br>

**with`ANDROID_DISTANCE_FILTER`** 

```
        backgroundGeoLocation.configure(callbackFn, failureFn, {
        desiredAccuracy: 0,
        stationaryRadius: 5,
        distanceFilter: 5,
        debug: true,
        stopOnTerminate: false,
        locationService: backgroundGeoLocation.service.ANDROID_DISTANCE_FILTER,
        locationTimeout: 60000
      });
```

> Result
> Charge left was 85%. Total battery consumption was 15%.
> 5 % more than ANDROID_FUSED_LOCATION.
> stats showed app used 38% and FusedLocation used 15%. (approx i dont remember exact figure)
> i.e 53% of total consumed 15%.

**DOUBTS**
- according to docs `ANDROID_DISTANCE_FILTER` is battery optimized but while testing it consumed 5% more comparitively. am i using **locationTimeout** in wrong way ?

<br>
- For `ANDROID_FUSED_LOCATION` i tried using this config options 

```
             interval: 600000, (10 minutes)
             fastestInterval: 600000

              but i was still getting location callbacks more frequently and not after 10     
              minutes  (not   the   js  callback, debug toast update). i wanted to keep the 
              service running but give updates after 10 minutes.
```

<br>
- is it possible to change config setting once service is started ? like only changing **locationTimeout** value without restarting service.

<br>
**what i am trying to acheive** 

while app  is active and running the location updates should be frequent like evey half a minute or per minute. but once in background the locatio updates should be after 10 minutes. **will this help in battery saving ?**

<br>
what will be the effect on battery under following situations :- 
1. app is in background GPS is ON and sevice is running.
2. app is in background service is running but GPS is OFF.
3. GPS is ON and service is running too , but location updates are set at interval of 10 minutes.(does this help in any way)

<br><br>
I am sorry for such a long post , but I am trying to make app more battery optimized. **It would be great if you can take some time to clear few of these doubts. Thanks ! Help is appreciated**

**Comment by mauron85** [comment]
You cannot reconfigure service in the moment. You've to stop, configure and start again. Probably it could be implemented easily, but it will behave almost exactly same, because you probably have to stop locationManager or fused provider anyway.

**Comment by uzumakinaruto123** [comment]
Thanks mauron ! do you think increasing the update intervals can help reducing battery consumption ?

I am facing a issue

I have a simple function to stop the service.
```
$scope.stopService=function(){
  backgroundGeoLocation.stop();
}
```

**It does not work everytime.** my settings preference changes succesfully but geolocation does not stop.
I have to restart the app then it stops on toggling again. that too does not work sometimes. how to forcefully stop it ? Thanks !

**Comment by mauron85** [comment]
IMHO it should reduce battery consumption. Stopping and starting service should work fine. Actually I'm using it in SampleApp to switch between providers.

**Comment by uzumakinaruto123** [comment]
Ok thanks alot @mauron85 . i will see what i can do :)

**Comment by uzumakinaruto123** [comment]
@mauron85   can you please tell the difference between `option.locationTimeout` | `option.interval` | `option.fastestInterval` | `option.activitiesInterval`

Thanks

**Comment by mauron85** [comment]
option.activitiesInterval - the activity detection update interval (fused provider only), if detected activity is STILL, location tracking is put on hold, until motion is detected
option.interval - (fused provider only) how often pull sensors for location updates

More info in the docs.
https://github.com/mauron85/cordova-plugin-background-geolocation#android_fused_location-provider-options

**Comment by uzumakinaruto123** [comment]
@mauron85 

when the is app killed , i want to update `activitiesInterval ` to `60000`
when the app is resumed/started in foreground `activitiesInterval ` to `30000`

I  just wanted to ask where can hook this code , so that i can update config only when app is about to terminate.

I tried  in **MainActivity.java** 

 ```
@Override
    public void onDestroy() {
       Toast.makeText(context, "App Destroyed", Toast.LENGTH_SHORT).show();
        super.onDestroy();
    }
```

Sometimes this works, but most of the times app crashes as soon as app is killed.
same when i do it in BackgroundGeolocationPlugin.java

In **BackgroundGeolocationPlugin.java**

 ```
@Override
    public void onDestroy() {
        Log.d(TAG, "destroying plugin");
        
         Toast.makeText(this, "App Destroyed", Toast.LENGTH_SHORT).show();

        unregisterLocationModeChangeReceiver();
        // Unbind from the service
        doUnbindService();
        if (config.getStopOnTerminate()) {
            stopBackgroundService();
        }

        super.onDestroy();
    }
```

Can you suggest a better way to do this ? does the service has any mechanism where it detects that now its in background. ?

Thanks !

**Comment by mauron85** [comment]
Post crash message from `adm logcat`

**Comment by uzumakinaruto123** [comment]
I already checked it 

```
06-13 17:39:45.037: E/AndroidRuntime(3389): FATAL EXCEPTION: main
06-13 17:39:45.037: E/AndroidRuntime(3389): java.lang.RuntimeException: Unable to destroy activity {com.zap.thefooddost/com.zap.thefooddost.MainActivity}: java.lang.NullPointerException
06-13 17:39:45.037: E/AndroidRuntime(3389): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3661)
06-13 17:39:45.037: E/AndroidRuntime(3389): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3679)
06-13 17:39:45.037: E/AndroidRuntime(3389): 	at android.app.ActivityThread.access$1200(ActivityThread.java:162)
06-13 17:39:45.037: E/AndroidRuntime(3389): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
06-13 17:39:45.037: E/AndroidRuntime(3389): 	at android.os.Handler.dispatchMessage(Handler.java:107)
06-13 17:39:45.037: E/AndroidRuntime(3389): 	at android.os.Looper.loop(Looper.java:194)
06-13 17:39:45.037: E/AndroidRuntime(3389): 	at android.app.ActivityThread.main(ActivityThread.java:5371)
06-13 17:39:45.037: E/AndroidRuntime(3389): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-13 17:39:45.037: E/AndroidRuntime(3389): 	at java.lang.reflect.Method.invoke(Method.java:525)
06-13 17:39:45.037: E/AndroidRuntime(3389): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
06-13 17:39:45.037: E/AndroidRuntime(3389): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
06-13 17:39:45.037: E/AndroidRuntime(3389): 	at dalvik.system.NativeStart.main(Native Method)
06-13 17:39:45.037: E/AndroidRuntime(3389): Caused by: java.lang.NullPointerException
06-13 17:39:45.037: E/AndroidRuntime(3389): 	at com.tenforwardconsulting.cordova.BackgroundGeolocationPlugin.onDestroy(BackgroundGeolocationPlugin.java:289)
06-13 17:39:45.037: E/AndroidRuntime(3389): 	at org.apache.cordova.PluginManager.onDestroy(PluginManager.java:298)
06-13 17:39:45.037: E/AndroidRuntime(3389): 	at org.apache.cordova.CordovaWebViewImpl.handleDestroy(CordovaWebViewImpl.java:480)
06-13 17:39:45.037: E/AndroidRuntime(3389): 	at org.apache.cordova.CordovaActivity.onDestroy(CordovaActivity.java:305)
06-13 17:39:45.037: E/AndroidRuntime(3389): 	at android.app.Activity.performDestroy(Activity.java:5291)
06-13 17:39:45.037: E/AndroidRuntime(3389): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1112)
06-13 17:39:45.037: E/AndroidRuntime(3389): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3648)
06-13 17:39:45.037: E/AndroidRuntime(3389): 	... 11 more
```

happens when service is not running and app is terminated. if service is not running still it enters onDestroy of plugin.

this works well but i just need to do it only if background tracking was enabled.so that it does not crash

`line 289 is unregisterLocationModeChangeReceiver();`



I i implement onDestroy in Main then it throws NullPointer at `if (config.getStopOnTerminate()) {`  in BackgroundGeolocationPlugin.java

**Comment by uzumakinaruto123** [comment]
anything on this ?

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Comment by mauron85** [comment]
Battery consumption since this thread was started. I'm closing it. Please feel free to raise new issue, if you think this is still an issue.
