### ISSUE TITLE
"FusedLocationService.java uses unchecked or unsafe operations" on cordova build

### ISSUE THREAD

**Issue by sourdenis** [mauron85/cordova-plugin-background-geolocation#78]
Hi!

When I set the option.locationService to backgroundGeoLocation.service.ANDROID_FUSED_LOCATION and build a cordova app, I get the error below 
```
Note: /Users/dev/repos/ColApp-Cordova/App/platforms/android/src/com/tenforwardconsulting/cordova/bgloc/BackgroundGeolocationPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/dev/repos/ColApp-Cordova/App/platforms/android/src/com/tenforwardconsulting/cordova/bgloc/FusedLocationService.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```
I have the latest version on plugin and all the dependencies are download and updated.

**Comment by sourdenis** [comment]
Just tried without the option.locationService and still got the error.

**Comment by mauron85** [comment]
They're only warnings, not errors. You can ignore them.

**Comment by mauron85** [comment]
Closing as those are just warning not errors. Reopen when neccesary
