### ISSUE TITLE
Setting notificationIcon removes notificationTitle & notificationText

### ISSUE THREAD

**Issue by roblav96** [mauron85/cordova-plugin-background-geolocation#8]
When I set my icon like so:
```
	self.opts = {}
	self.opts.notificationIcon = 'icon'
	self.opts.notificationTitle = 'My app Background GPS'
	self.opts.notificationText = 'ENABLED'
	self.opts.debug = false
	self.opts.stopOnTerminate = false
```
The icon shows up great, but then I'm left with:
Title: 'app-name is running'
Text: 'Touch for more information or to stop the...'

When I remove the icon setting from my config, the text works.

Android#5.1.1
Cordova#latest
cordova-plugin-background-geolocation#latest

**Comment by mauron85** [comment]
In my experience, this happens when icon is not present in res/drawable. In your case, there should be two icons: icon_small.png and icon_large.png in res/drawable. Rename apk to zip and unzip and check if icons are present.

**Comment by roblav96** [comment]
ahhh. I didn't know the names of the files were proprietory to 'icon_large.png' and 'icon_small.png' :X

**Comment by mauron85** [comment]
I don't like it either. I will introduce two separate config options for small and large icon, with real icon name as parameter. No magic.

**Comment by roblav96** [comment]
Is there a specific size these icons need to be? I took my icon.png and just copied it twice and renamed it lol the area turned into a white square and didn't work as expected.

**Comment by mauron85** [comment]
Hmm. Try sample app, which is using custom icons. And let me know if it works. I'll take a look on this later.

**Comment by roblav96** [comment]
No worries man. I'll run the sample and see how it goes. Thank you!!

**Comment by mauron85** [comment]
@roblav96 Can I close this one?

**Comment by mauron85** [comment]
Closing
