### ISSUE TITLE
backgroundGeoLocation.isLocationEnabled returns always 1 even GPS turned off

### ISSUE THREAD

**Issue by sourdenis** [mauron85/cordova-plugin-background-geolocation#81]
Hi!

Using backgroundGeoLocation.isLocationEnabled to validate, if GPS is turned off or on, but it returns always 1.
Device is Huawei P7, Android 4.4.2. The latest Cordova and geolocation plugin

**Comment by mauron85** [comment]
Can you post code?

**Comment by sourdenis** [comment]
`plugins.insomnia.keepAwake(
    function(){
        backgroundGeoLocation.isLocationEnabled(function (response) {
            if (response === 1) {
                backgroundGeoLocation.configure(setPosition, service.showError, service.gpsOptions);
                backgroundGeoLocation.start(function(){
                    if (service.modalInstance !== null)
                        service.modalInstance.close();
                });
                setStatus(gpsStatus.ON);
            }else{
                backgroundGeoLocation.showLocationSettings();
            }
        });
    },
    function () {
        backgroundGeoLocation.isLocationEnabled(function (response) {
            if (response === 1) {
                backgroundGeoLocation.configure(setPosition, service.showError, service.gpsOptions);
                backgroundGeoLocation.start(function(){
                    if (service.modalInstance !== null)
                        service.modalInstance.close();
                });
                setStatus(gpsStatus.ON);
            }else{
                backgroundGeoLocation.showLocationSettings();
            }
        });
    }
);`

**Comment by sourdenis** [comment]
found the answer - isLocationEnabled() checks if the location services is enabled but I was expecting it to check if GPS is turned on.
So it's my mistake
