### ISSUE TITLE
No callback when GPS is turned off by user

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#82]
This is the configuration I am using currently: 

```
backgroundGeoLocation.configure(this.callbackFn, this.failureFn, {
            desiredAccuracy: 1,    //In Meters
            stationaryRadius: 1,   //In Meters
            distanceFilter: 1, // 30,     //In Meters, minimum distance a user must move horizontally before update
            locationTimeout: 10,    //In Secs, Minimum time interval before update //Only for Android
            activityType: 'AutomotiveNavigation',   //IOS Only
            notificationIcon: 'mappointer',
            notificationIconColor: '#FEDD1E',
            notificationTitle: 'Background tracking', // <-- android only, customize the title of the notification
            locationService: backgroundGeoLocation.service['ANDROID_DISTANCE_FILTER'],  //Only Android
            debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
            stopOnTerminate: false // <-- enable this to clear background location settings when the app terminates
        });
```

When I turn off GPS from notification tray, no location callback is received. Starts working when I switch GPS back on. Can't figure out why? Shouldn't this be handled by plugin itself @mauron85 ?

**Comment by mauron85** [comment]
No. The plugin itself do not touch any location settings.

**Comment by shyamal890** [comment]
@mauron85 Ohk, I think I haven't really understood this point. From what I gather:

1. The plugin lets the device decide how to discern location. So it has no bearing on whether GPS is turned or not.

2. If GPS is turned off, the device's location provider would than fallback to wifi or cell network for change in location. 

3. Given point 2 is correct, that would mean if one is using an emulator and GPS is turned off, there wont be any callbacks since the emulator is dependent on the PC's wifi adapter and there is no cell network. 

4. Lets say the `desiredAccuracy` is set to 1 or 0 and GPS is turned off by the user. Will cell tower change or wifi change trigger a callback? 
Or does `desiredAccuracy` == 0 mean that the `locationProvider` would only utilize GPS data for change in location and can't fallback to cell network or wifi in case GPS data is not available?

**Comment by mauron85** [comment]
Not sure what device are you referring, but in vanilla android, there is no such thing as turning on/off just one provider. In vanilla you simple turn on/off location. So no fallback is possible.

**Comment by shyamal890** [comment]
Ah! Ok. So is there a way in which we can turn on location provider automatically?

**Comment by mauron85** [comment]
There are already watchLocationMode, showLocationSettings, and isLocationEnabled methods exactly for that.
