### ISSUE TITLE
Multiple dex files define Lcom/google/android/gms/iid/MessengerCompat$1

### ISSUE THREAD

**Issue by pugwonk** [mauron85/cordova-plugin-background-geolocation#84]
Using this plugin in combination with pushwoosh-phonegap-plugin (and, I believe, some other push notification plugins) causes the following error on build for Android:

> UNEXPECTED TOP-LEVEL EXCEPTION:
> com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/MessengerCompat$1;
>     at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
>     at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
>     at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
>     at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
>     at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
>     at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
>     at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
>     at com.android.dx.command.dexer.Main.run(Main.java:246)
>     at com.android.dx.command.dexer.Main.main(Main.java:215)
>     at com.android.dx.command.Main.main(Main.java:106)
> 

According to https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/issues/179, this is because this plugin uses an incorrect way to refer to Google Play Services?

This only started happening after the upgrade to recent version of the Android SDK tools (25.1.6).

**Comment by mauron85** [comment]
I have same mention about dex in README.md and using correct way of declaring google play. Now it's time to find someone to blame.

Not sure but probably they declaration is colliding with this plugin.
<framework src="com.google.android.gms:play-services-gcm:8.4.0" />

They specify version 8.4.0 and this plugin declares any version
<framework src="com.google.android.gms:play-services-location:+" />

Can you try rebuild pushwoosh with my declaration
<framework src="com.google.android.gms:play-services-location:+" />

One more remark why pushwoosh, when there is excellent and free https://github.com/phonegap/phonegap-plugin-push ?

**Comment by mauron85** [comment]
@pugwonk the issue #179 on pushwoosh has been updated. Any chance, you have same problem, meaning you're using old and deprecated cordova-plugin-mauron85-background-geolocation-phonegapbuild ?

**Comment by pugwonk** [comment]
Hey there! I'm not using your old plugin, but you're quite right - the bug is theirs, they were referencing a specific version of the v4 support library in plugin.xml. They appear to have actually fixed it now and everything works great.

Sorry for the red herring, and thanks for the speedy response!
