### ISSUE TITLE
IOS version No Work 

### ISSUE THREAD

**Issue by ivanssa** [mauron85/cordova-plugin-background-geolocation#86]
Hello Mauro a few months the plugin no longer works properly on iOS I can not get any return, the debug get some location update: MOVING but do not receive any updates through callaback or the url also tried adding the changepace () but nothing changed , Android seems to work normally, I saw the recommendation to leave the range up to 2km but I drove for 30 minutes and nothing worked, I need to update the movement in real time as in Android while he was moving or not as a running app that it's possible?

Follow the code I'm using
``
// BACKGROUND GEOLOCALIZAÇÃO

document.addEventListener('deviceready', onDeviceReady, false);

function onDeviceReady () {

```
var callbackFn = function(location) {
    console.log('[js] BackgroundGeoLocation callback:  ' + location.latitude + ',' + location.longitude);

    backgroundGeoLocation.finish();
};

var failureFn = function(error) {
    console.log('BackgroundGeoLocation error');
};
```

   var postUser="https://myserver.com/maps/geolocation.php"; 

```
backgroundGeoLocation.configure(callbackFn, failureFn, {
    desiredAccuracy:0,
    stationaryRadius:20,
    distanceFilter:30,
    debug: true, // <-- enable this hear sounds for background-geolocation life-cycle.
    stopOnTerminate:true, // <-- enable this to clear background location settings when the app terminates

    locationService: backgroundGeoLocation.service.ANDROID_FUSED_LOCATION,
    activityType: 'AutomotiveNavigation',

    // Notificações
    notificationIcon: 'icon',
    notificationTitle: 'MyApp',
    notificationIconColor: '#FC6932',
    notificationText: 'back to MyApp',

    url:postUser,
            method: 'PUT',
            autoSync: true,
            maxDaysToPersist: 1,
            headers: {
             "X-FOO": "bar"
              },
            params: {
        "type": "BgGeo"
    }
});

 backgroundGeoLocation.changePace(true);
 backgroundGeoLocation.start();

// If you wish to turn OFF background-tracking, call the #stop method.
// backgroundGeoLocation.stop();
```

}

// BACKGROUND GEOLOCALIZAÇÃO
``

**Comment by mauron85** [comment]
Hi, are you using next branch (version 2.0.0?)

**Comment by ivanssa** [comment]
Mauro thanks for the feedback, I am using the latest version compile in phonegapbuild via npm, this postuser is nothing new just added a variable in place with the value of Url did I because in my final version I need to pass the id of the User and make a junction something like: postUser = "https://myserver.com/maps/geolocation.php?user=" + $ UserId;it is possible to do so with variables? or settings only accept stings values?Another doubt I'm using a function monitotar the GPS via plugin cordovageolocation when the app is active but qndo it goes I background wanted to hear only the return of the js in callback or via url server settings but the android he seems to ignore the callback and url and even background it continues updating via my function $ cordovaGeolocation.watchPosition (watchOptions);how do you solve?

**Comment by ivanssa** [comment]
@mauron85  believe discover the problem in IOS and it is with some conflict with the plugin $ cordovaGeolocation.getCurrentPosition he was called before the cord-plugin-background-$ Geolocation in my config.xml but he only asked the local location and background not could request permission as always, because I believe that only a plugin can request location permission once, I believe that the solution is the background-geolocation also monitor the real-time location, is this possible? how I could do to use a function $backgroundGeoLocation.getCurrentPosition ?

**Comment by ivanssa** [comment]
@mauron85 Any solution? It is possible to use cordovaGeolocation along with backgroundGeoLocation or have any possibility of monitoring the getCurrentPosition through backgroundGeoLocation without the native plugin cordovaGeolocation?

**Comment by mauron85** [comment]
Yes, you should be able to use this plugin with other geolocation plugins or pure html5 geolocation api.

**Comment by ivanssa** [comment]
Yes I decided to figure out a way to update the position through the PUT method added the following path in the Plugin settings

url: "https://myapp.firebaseio.com/maps/maps/user.json"
method, 'PUT'

**Comment by ivanssa** [comment]
Mauro This worked for a while, but I believe the latest changes in the api IOS require only a plugin for permission so if I add the plugin cord Geolocation he first asks permission to monitor local location but the plugin corvabackground does not ask for permission to run background "gPS set to always" if I add the first cordovabackground he can monitor in the background but the plug cord geolocation for work, so the only solution is plugincordovabackground also play the role of monitoring the location in primero plan without the nescessidade of using the native plugin cord is this possible? there is a function getCurrentPosition this plugin? check the same question being discussed in the original plugin cris >> https://github.com/transistorsoft/cordova-background-geolocation-lt/issues/104

**Comment by ivanssa** [comment]
Mauro This worked for a while, but I believe the latest changes in the api IOS require only a plugin for permission so if I add the plugin cord Geolocation he first asks permission to monitor local location but the plugin corvabackground does not ask for permission to run background "gPS set to always" if I add the first cordovabackground he can monitor in the background but the plug cord geolocation for work, so the only solution is plugincordovabackground also play the role of monitoring the location in primero plan without the nescessidade of using the native plugin cord is this possible? there is a function getCurrentPosition this plugin? check the same question being discussed in the original plugin cris >> transistorsoft/cordova-background-geolocation-lt#104
