### ISSUE TITLE
Bug: backgroundGeoLocation.watchLocationMode not called

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#87]
When I toggle location settings from on to off, there is no callback in `backgroundGeoLocation.watchLocationMode()`

Btw I am using the `@next` version.

**Comment by mauron85** [comment]
Please Post your implementation. There is new Example project for @next branch, which implements watchLocationMode. Check it out.

https://github.com/mauron85/cordova-plugin-background-geolocation-example/blob/master/www/app.js#L84

**Comment by shyamal890** [comment]
```
backgroundGeoLocation.watchLocationMode((result) => {
            console.log("Location Mode Changed: " + result);
            if (result == false) {
                this.popupSwitchOnLocationService();
            }
        }, (error) => {
            console.log("Location Mode Change Error: " + JSON.stringify(error,null,4));
            })
```
`console.log("Location Mode Changed: " + result)` is never triggered

**Comment by mauron85** [comment]
Which android version are you using?

**Comment by shyamal890** [comment]
6.0.1

Sent from Yahoo Mail on Android 
 
  On Sat, 11 Jun, 2016 at 2:11 a.m., Marián Hello<notifications@github.com> wrote:   
Which android version are you using?

**Comment by ronakkaria** [comment]
Working fine on 6.0 for me. If you were using the @next version, backgroundGeoLocation was renamed to backgroundGeolocation.

But you would have caught the reference error on the console wouldn't you.
You're using the console plugin right?

**Comment by mauron85** [comment]
@shyamal890 as @ronakkaria is suggesting. In case of error, error handler should be called. Please post output of console.log("Location Mode Change Error: " + JSON.stringify(error,null,4));

**Comment by ronakkaria** [comment]
If it's simply a case of using the wrong variable name, a direct reference error 'cannot call method watchLocationMode of undefined' (something like that) would show up on console. Error handler won't be invoked. 

Again, that's if anything at all is being outputted in console. I think (not sure) you need to use the cordovaConsole plugin for anything to show up

**Comment by shyamal890** [comment]
I am not getting any callback not even an error that is for sure! I will get back with more details.

**Comment by shyamal890** [comment]
@mauron85 Please consider this issue closed for now. I am not able to recreate.

**Comment by mauron85** [comment]
@shyamal890 good to hear that. Closing for now, reopen if needed.

**Comment by dagatsoin** [comment]
I have exactly the same error with the commit #8acb476e58ec9d6874a2857aeb6a36dd66a6374c (August) but it was just because it was not implemented yet :p 

```
 } else if (ACTION_ADD_MODE_CHANGED_LISTENER.equals(action)) {
            registerLocationModeChangeReceiver(callbackContext);
            // TODO: call success/fail callback

            return true;
```

**Comment by dagatsoin** [comment]
mmm I am wrong, coding too early in the morning is dangerous. It IS implemented but only for KITKAT and I use Jelly Bean.
