### ISSUE TITLE
Did not send location to server in Background Mode.

### ISSUE THREAD

**Issue by ramveersgh** [mauron85/cordova-plugin-background-geolocation#88]
@mauron85 
Thanks for this plugin.. this is very helpful.

I am facing issue when main app is suspended and background service is running, it does not post location to server. When i click on the notification icon, then app run and send coordinates to server.
I have set server url in Url parameter to send location on server.

Why it is not working in background??
Here is my settings - 
 ```
backgroundGeoLocation.configure(callbackFn, failureFn, {
            desiredAccuracy: 100, //Desired accuracy in meters. Possible values [0, 10, 100, 1000]. The lower the number, the more power devoted to GeoLocation resulting in higher accuracy readings. 1000 results in lowest power drain and least accurate readings.
            stationaryRadius: 1, //Stationary radius in meters. When stopped, the minimum distance the device must move beyond the stationary location for aggressive background-tracking to engage.
            distanceFilter: 30,
            debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
            stopOnTerminate: false, // <-- enable this to clear background location settings when the app terminates
            notificationTitle: 'Tranzol Tracker',
            notificationText: 'Tracking your trip.',
            notificationIconColor: '#4b98a8',
            locationProvider: backgroundGeoLocation.provider.ANDROID_DISTANCE_FILTER,
            interval: 2 * 60 * 1000, // <!-- poll for position every minute
            fastestInterval: 2 * 60 * 1000,
            url: app.postUrl,
            httpHeaders: {
                "deviceId": device.uuid
            },
            startOnBoot: true
        });
```

**Comment by mauron85** [comment]
Hi and thank you. I will check it out.

**Comment by mauron85** [comment]
Is it happening on iOS or Android?

**Comment by ramveersgh** [comment]
I worked on Android so its happening in Android. No idea about iPhone.
Just want to inform you that its take lot of time to identify the location. I have set 100 desired accuracy at sometimes it is tale more then 5 minutes to take GPS location.
If i turn on google map, then it find location very quick. I am still testing developing and testing the app.

Thanks for you help.

**Comment by mauron85** [comment]
What platform and plugin version?

**Comment by ramveersgh** [comment]
Thanks for the suggestion.
I am using Android platform. I am using code from Next branch https://github.com/mauron85/cordova-plugin-background-geolocation.git.

Now I am using ANDROID_FUSED_LOCATION.
Here are my settings now -
```
backgroundGeoLocation.configure(callbackFn, failureFn, {
            desiredAccuracy: 100, //Desired accuracy in meters. Possible values [0, 10, 100, 1000]. The lower the number, the more power devoted to GeoLocation resulting in higher accuracy readings. 1000 results in lowest power drain and least accurate readings.
            stationaryRadius: 50, //Stationary radius in meters. When stopped, the minimum distance the device must move beyond the stationary location for aggressive background-tracking to engage.
            distanceFilter: 500,
            debug: false, // <-- enable this hear sounds for background-geolocation life-cycle.
            stopOnTerminate: false, // <-- enable this to clear background location settings when the app terminates
            notificationTitle: 'Tranzol Tracker',
            notificationText: 'Tracking your trip.',
            notificationIconColor: '#4b98a8',
            locationProvider: backgroundGeoLocation.provider.ANDROID_FUSED_LOCATION,
            interval: 15 * 60 * 1000, // <!-- poll for position every minute
            fastestInterval: 30 * 60 * 1000,
            activitiesInterval: 30 * 60 * 1000,
            url: app.postUrl,
            httpHeaders: {
                "deviceId": device.uuid
            },
            startOnBoot: true
        });
```

Still the issue i am facing is background data posting to server.

**Comment by uzumakinaruto123** [comment]
if you are you using next version , it should be
`locationProvider: backgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,`

You are not even getting location updates to post it ! and set debug to true so that you whether you getting location updates.

**Comment by ronakkaria** [comment]
Faced the same issue yesterday.

In my case it was because of service closing when the foreground is terminated. Service can take arbitarily long to restart. Anyone have any ideas on how to make the service not terminate when foreground is closed?

Isn't that what "unbinding of service" is supposed to accomplish already?

**Comment by mauron85** [comment]
Did you guys also use option `startForeground: false` ?

**Comment by ronakkaria** [comment]
Only tested this on Android. When I swipe app from list (onAppTerminate), the service also terminates, and Android schedules it for a restart. But it can take very long for that happen. 

Will have to properly log and check if the service was unbinded properly before app terminated.

**Comment by uzumakinaruto123** [comment]
This was the issue with version 1.0. since, 2.0 service resumes within 10 to 15 secs. first it took years .. :p

**Comment by ronakkaria** [comment]
Oh.. How was that improvement achieved? I thought it's out of our control.

I was testing on 2.0 rc3 only. Maybe my phone was running out of memory, and Android OS decided to immediately kill my service once I terminated app.

I will test again, but this time with the service running in foreground. That enormously decreases the probability of Android killing the service, according to the docs.

**Comment by ronakkaria** [comment]
Also, according to Android docs, if you call onStartCommand() first, then binding/unbinding doesn't mean the service is automatically terminated when the activity is terminated. 

So now I'm confused as to why the service would have to 'resume' at all, unless there's low memory. 
Does the service terminate and resume every time in your experience @uzumakinaruto123 ?

**Comment by ronakkaria** [comment]
https://developer.android.com/guide/components/services.html

Quoting the Android Docs here for convenience:

> If a component calls bindService() to create the service (and onStartCommand() is not called), then the service runs only as long as the component is bound to it. Once the service is unbound from all clients, the system destroys it.


> If a component starts the service by calling startService() (which results in a call to onStartCommand()), then the service remains running until it stops itself with stopSelf() or another component stops it by calling stopService()

> Although this documentation generally discusses these two types of services separately, your service can work both ways—it can be started (to run indefinitely) and also allow binding.

**Comment by uzumakinaruto123** [comment]
@ronakkaria  Yes it does everytime ! As I stated here [#59](https://github.com/mauron85/cordova-plugin-background-geolocation/issues/59#issuecomment-225561757) , I am yet to test this on other devices and ROMS. But , I am sure its going to work since already I am testing on a low end device android 4.2.2 , which can run out of memory quite quickly. Latest devices with high config , dont go out of memory tha easily.


Anyways , I tested on low end device while keeping eye on running sevices , and it resumed every damn time.  

Service not resuming is also related to Android bug , which @mauron85  mentions here [#59](https://github.com/mauron85/cordova-plugin-background-geolocation/issues/59#issuecomment-225561757).  But one of the workarounds has already been pushed and i think that has solved the issue.

**Comment by mauron85** [comment]
@ronakkaria  what do you mean by resume? But probably the answer is android bug I'am mentioning https://github.com/mauron85/cordova-plugin-background-geolocation/issues/9#issuecomment-177318045

**Comment by uzumakinaruto123** [comment]
Do you think , its still not solved yet ? Or am i under wrong impression

**Comment by mauron85** [comment]
@uzumakinaruto123 Go ahead and try. Don't have Android > 5.0 device at hand. Just enable stopOnTerminate: false. Swipe app from the list and watch adb logcat for something like 
```
I/ActivityManager(14677): Killing 31586:net.dinglisch.android.tasker/u0a10002: remove task
```
(name of the package will be different probably com.marianhello.bgloc.LocationService or other class from that package)

**Comment by uzumakinaruto123** [comment]
Even I don't have. maybe @ronakkaria  can test.

**Comment by siddiq** [comment]
I have also seen this issue on iOS

**Comment by mauron85** [comment]
Behaviour was improved since 2.2.0. Reopen and please post logs, if you still have problem.

**Comment by tedeum** [comment]
@mauron85 you mean android can't > 5.0?
