### ISSUE TITLE
Keep service running when app is closed

### ISSUE THREAD

**Issue by ElieSauveterre** [mauron85/cordova-plugin-background-geolocation#9]
I noticed that some app have services that keep running even when the app is killed.
I found this plugin sample https://github.com/Red-Folder/bgs-sample , it's a simple timer which put some information in logcat. I tried it and the timer is still running after the app is killed.

It seems possible to not have the service been killed, is that possible to do the same for the background-geolocation plugin ?

**Comment by mauron85** [comment]
On special occasions (low memory,...) main activity can be killed by the system, but in my experience bg service was never killed. And I strongly believe, that adding timer service will not help preventing system to kill bg service nor main actitivity.

**Comment by mauron85** [comment]
Also, in case of main activity is killed by the system, bg should continue working when stopOnTerminate option is true. Read docs for more information. It's kind of experimental right now, because I have no success to replicate main activity being killed (which means my phone have plenty of free resources eg. ram...). But if you've problems with plugin being killed by the system, you're more than welcome to share your experience here so I can improve plugin for those cases.

**Comment by ElieSauveterre** [comment]
It's not the system that kill the app, it's me, press the button to show all running app that "swap" the app to kill it.
I tried with stopOnTerminate at true or false, in both case the service is killed.

Using a timer is not the best idea, what I was trying to says, is that this example of a service seems to keep running even when I "swap" the app. So, maybe it's not what the service does, but how it's created or initiated.

For the background geolocation plugin, in logcat when I do a "swap" to kill the app I just see : 
`Destroyed Location update Service`

With the Red-Folder example plugin, I see : 
`11-01 09:12:42.459: D/BackgroundServicePluginLogic(10380): On Destroy Start`
`11-01 09:12:42.459: D/BackgroundServicePluginLogic(10380): Checking for services`
`11-01 09:12:42.459: D/BackgroundServicePluginLogic(10380): Found services`
`11-01 09:12:42.459: D/BackgroundServicePluginLogic(10380): Calling service.close()`
`11-01 09:12:42.459: D/ServiceDetails(10380): Close called`
`11-01 09:12:42.459: D/ServiceDetails(10380): Removing ServiceListener`
`11-01 09:12:42.459: D/BackgroundService(10380): Listener removed`
`11-01 09:12:42.459: D/ServiceDetails(10380): Removing ServiceConnection`
`11-01 09:12:42.461: D/ServiceDetails(10380): Close finished`
`11-01 09:12:42.461: D/BackgroundServicePluginLogic(10380): On Destroy Finish`
`11-01 09:12:43.823: D/BackgroundService(13275): onStartCommand run`
`11-01 09:12:43.824: I/BackgroundService(13275): Initialising the service`
`11-01 09:12:43.824: I/BackgroundService(13275): Syncing result`

The service is killed and then restarted.

**Comment by mauron85** [comment]
Ah ok. Now I see your point. I will take a look.

**Comment by mauron85** [comment]
Interesting discussion https://github.com/Red-Folder/bgs-core/issues/43

http://stackoverflow.com/questions/20677781/in-android-4-4-swiping-app-out-of-recent-tasks-permanently-kills-application-wi
http://www.howtogeek.com/169549/what-exactly-happens-when-you-swipe-an-android-app-from-the-recent-apps-list/
http://developer.android.com/intl/ja/reference/android/app/Service.html#onTaskRemoved(android.content.Intent)

**Comment by Kujbor** [comment]
It seems that christocracy realized this in his 'Premium Version":
> * Auto-start tracking on device boot
> * Continue tracking even after application is terminated

**Comment by ElieSauveterre** [comment]
@Kujbor The plugin works great when the app is on foreground or in background. The problem is when the app is killed. I have tested the demo app of Christocracy and the service continue to run even when the app is killed.

**Comment by Kujbor** [comment]
It would be great if this plug-in also started to work on closing the application. Otherwise, for me it makes no sense... Is there a free plug-in works when the application is closed?

**Comment by ElieSauveterre** [comment]
Yes, there is this plugin sample https://github.com/Red-Folder/bgs-sample

**Comment by Kujbor** [comment]
Thanks, but I mean ready to use plug-in for geocoding, not a basis for its development. I do not have the skills of native development. Only HTML5.

**Comment by mauron85** [comment]
@Kujbor as @ElieSauveterre already explained to you, this plugin works in background and only doesn't work when app is killed, which is AFAIK intentionally on android to save battery life etc.

But if there is way how to do it, I'm pretty sure I'll find it and implement it :-). But cannot give you any time frame now.

**Comment by renevaessen** [comment]
A repro for killing of the app is easy with Android 5.1+
1) Go to settings -> battery  "blacklist" your app, for always optimize.
2) Start your app
3) open as many apps as possible, consume a lot of memory this way
4) = Your app get's closed
5) = Background services keeps running
6) Wait a little while, for enough gps positions to be captured and stored in SqlLite
7) Open your app using the Application List
8) See what happins when your app does  backgroundGeoLocation.getLocations()
9) = first parameter of successCallback always contains an empty array

I have:
forceReloadOnLocationChange: false, 
forceReloadOnMotionChange: false
forceReloadOnGeofence: false,    
stopOnTerminate: false

**Comment by renevaessen** [comment]
Another issue, the -phonegapbuild version of the plugin, does not build with cradle,
maybe some incompatibility with one of the other plugins?

  
  <gap:plugin name="cordova-plugin-battery-status" version="1.1.0" source="npm" />
  <gap:plugin name="cordova-plugin-camera" version="1.2.0" source="npm" />
  <gap:plugin name="cordova-plugin-file" version="3.0.0" source="npm" />
  <gap:plugin name="cordova-plugin-device" version="1.0.1" source="npm" />
  <gap:plugin name="cordova-plugin-geolocation" version="1.0.1" source="npm" />

  <gap:plugin name="cordova-plugin-inappbrowser" version="1.0.1" source="npm"/>
  <gap:plugin name="cordova-plugin-splashscreen" version="2.1.0" source="npm" />
  <gap:plugin name="cordova-plugin-media" version="1.0.1" source="npm" />
  <gap:plugin name="cordova-plugin-network-information" version="1.0.1" source="npm" />
  
  <gap:plugin name="phonegap-plugin-barcodescanner" version="4.1.0" source="npm" />

  
  <gap:plugin name="cordova-plugin-push-notification" version="2.5.2" source="npm" gap:platform="ios" />
  <gap:plugin name="cordova-plugin-statusbar" version="1.0.1" source="npm" />

  <gap:plugin name="cordova-plugin-insomnia" version="4.0.1" source="npm"  gap:platform="ios" />
  <gap:plugin name="cordova-plugin-powermanagement" version="1.0.1" source="npm" />
  <gap:plugin name="cordova-plugin-whitelist" version="1.0.0" source="npm" />
  <gap:plugin name="cordova-plugin-mauron85-background-geolocation" version="0.7.3" source="npm" />
  <gap:plugin name="cordova-plugin-keyboard" version="1.1.2" source="npm" />

Phonegap build log:

Build Date: 2015-11-26 14:46:14 +0000
----------------------------------------------
Running: /project/gradlew cdvBuildRelease -b /project/build.gradle -Dorg.gradle.daemon=true -x lintVitalRelease
:preBuild
:compileReleaseNdk
:preReleaseBuild
:checkReleaseManifest
:CordovaLib:compileLint
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:preBuild
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar
:CordovaLib:compileReleaseNdk
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease
:prepareProjectCordovaLibUnspecifiedReleaseLibrary
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources
:processReleaseManifest
:processReleaseResourceswarning: string 'menu_settings' has no default translation.

:generateReleaseSources
:compileReleaseJava/project/src/com/tenforwardconsulting/cordova/bgloc/AbstractLocationService.java:14: error: package android.support.v4.app does not exist
import android.support.v4.app.NotificationCompat;
                             ^
/project/src/com/tenforwardconsulting/cordova/bgloc/AbstractLocationService.java:120: error: package NotificationCompat does not exist
    protected NotificationCompat.Builder setClickEvent (NotificationCompat.Builder builder) {
                                                                          ^
/project/src/com/tenforwardconsulting/cordova/bgloc/AbstractLocationService.java:120: error: package NotificationCompat does not exist
    protected NotificationCompat.Builder setClickEvent (NotificationCompat.Builder builder) {
                                ^
/project/src/com/tenforwardconsulting/cordova/bgloc/AbstractLocationService.java:88: error: package NotificationCompat does not exist
            NotificationCompat.Builder builder = new NotificationCompat.Builder(this);
                              ^
/project/src/com/tenforwardconsulting/cordova/bgloc/AbstractLocationService.java:88: error: package NotificationCompat does not exist
            NotificationCompat.Builder builder = new NotificationCompat.Builder(this);
                                                                       ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /project/src/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.219 secs

/project/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /project/gradlew with args: cdvBuildRelease,-b,/project/build.gradle,-Dorg.gradle.daemon=true,-x,lintVitalRelease

**Comment by mauron85** [comment]
@renevaessen thank you for the steps. Just to clear things out. Your issue is actually bug and slightly different from @ElieSauveterre issue. The problem that you're described is general android problem. Basically it seems that system doesn't call onDestroy method when killing app on low memory. So the background service doesn't know that your app has been killed and continues broadcasting position instead storing them in sqlite db.

I need to find another way, how to detect app has been killed.

**Comment by mauron85** [comment]
Another issue, the -phonegapbuild version of the plugin, does not build with cradle,
    maybe some incompatibility with one of the other plugins?

@renevaessen please create new issue about that. in https://github.com/mauron85/cordova-plugin-mauron85-background-geolocation-phonegapbuild repo

**Comment by renevaessen** [comment]
Hi Mauron,

1) A simple ping/pong pattern to check if it is still alive, would suffice I guess?
 
2) Alright will create a new issue, your right, much better.

**Comment by mauron85** [comment]
@renevaessen. Yeah. Actually I'm thinking about acknowledgements.
1. background service receives positions
2. send intent to main activity (app)
3. main activity respond with ack
4. if background service will not receive ack within couple of seconds, it will switch to sqlite db.

It adds complexity, so I tried to avoid that. But it seems there not better way.

**Comment by srikanthreddyn143** [comment]
Is this issue only for android or iOS as well?

**Comment by renevaessen** [comment]
I don't think this functionality exists for iOS, don't know why, maybe Mauron could enlighten us about that.

**Comment by mauron85** [comment]
@renevaessen can you try version 0.8.0 from next branch? I've tried to fixed your problem using acks.

**Comment by alexander-entin** [comment]
Gents,

If my assumptions are correct, we could possibly improve the plugin.

1. When under memory pressure Android could kill our process hosting both Service and Activity. In case of START_STICKY it then should spawn a new process and start Service only. Check this on how to test START_STICKY: 
https://jira.appcelerator.org/browse/TIMOB-3286?focusedCommentId=183282&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-183282

2. When restarted this way Service receives NULL intent. This can be used to distinguish between normal Service start (via Activity) and re-start (via Android).

3. In case of Service re-start we could start Activity from Service and continue sending it location updates instead of storing them.

Please comment.

**Comment by mauron85** [comment]
@alexander-entin Steps 1. and 2. already in use. What is missing is step 3.

**Comment by mauron85** [comment]
Issue seems to be fixed in upcoming version 0.8.0

How did I test (in android emulator):

Install SampleApp into emulator
```
$ cd example/SampleApp
$ cordova platform add android
$ cordova run --emulator
```

Kill main activity, where pid is process com.transistorsoft.backgroundgeolocation
```
$ adb shell ps
$ adb shell "kill -2 pid"
```

Confirm in adb logcat -s
```
I/ActivityManager( 1219): Process com.transistorsoft.backgroundgeolocation (pid 7348) has died
```

Now send some fake gps data

```
$ telnet localhost 5554

geo fix 1 2
geo fix 2 3
geo fix 49.2 50.3
...
```

Check adb logcat
```
D/DistanceFilterLocationService( 5489): - onLocationChanged: 50.0,49.0, accuracy: 20.0, isMoving: false, speed: 0.0
D/AbstractLocationService( 5489): Final Result Receiver
W/AbstractLocationService( 5489): Main activity seems to be killed
D/AbstractLocationService( 5489): Persisting location. Reason: Main activity was killed.
D/SQLiteLocationDAO( 5489): After insert, rowId = 4
D/AbstractLocationService( 5489): Persisted Location: com.tenforwardconsulting.cordova.bgloc.data.LocationProxy@1aa7e9b6
```

Reopen android app in emulator.
Then open chrome on your computer and enter about:inspect as url
Click inspect on WebView in com.transistorsoft.backgroundgeolocation (39.0.0.0)
Then in chrome developer tools console enter command
```
backgroundGeoLocation.getLocations(function(pos){console.log(JSON.stringify(pos));})
```

You should see positions there were stored while Main Activity was dead.

**Comment by areina** [comment]
Maybe I'm doing something wrong, but trying this new version in my android device, if I kill the Main Activity manually looks like the service is also killed. 

```
D/ConnectivityManager.CallbackHandler(32621): CM callback handler got msg 524290
I/ActivityManager(32392): Killing 20385:com.google.android.gm/u0a75 (adj 15): empty #17
D/BackgroundGeolocationPlugin( 3576): Main Activity destroyed!!!
I/ActivityManager(32392): Killing 3576:com.transistorsoft.backgroundgeolocation/u0a82 (adj 9): remove task
I/WindowState(32392): WIN DEATH: Window{25c35827 u0 com.transistorsoft.backgroundgeolocation/com.transistorsoft.backgroundgeolocation.MainActivity}
W/art     (32392): Long monitor contention event with owner method=boolean com.android.server.am.ActivityManagerService.removeTask(int) from ActivityManagerService.java:8711 waiters=3 for 231ms
W/art     (32392): Long monitor contention event with owner method=boolean com.android.server.am.ActivityManagerService.removeTask(int) from ActivityManagerService.java:8711 waiters=4 for 189ms
I/ActivityManager(32392): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.cyanogenmod.trebuchet/com.android.launcher3.Launcher} from uid 10016 on display 0
W/AbstractLocationService( 3713): Destroyed Location update Service
V/WindowManager(32392): rotationForOrientationLw(orient=5, last=0); user=0 USER_ROTATION_LOCKED
I/ActivityManager(32392): Killing 3713:com.transistorsoft.backgroundgeolocation:remote/u0a82 (adj 16): remove task
```

**Comment by mauron85** [comment]
@areina How exactly are you killing?

**Comment by areina** [comment]
Yes, swiping from app list. I misunderstood your last comments then, I'm sorry for the noise. Do you have plans to implement that case? (maybe we could track that topic in a different issue).

**Comment by mauron85** [comment]
@areina Actually this is right thread for your question :-). The other issues should be separated. Please guys, create separate issues for anything else. I'm sorry that I also contributed to this confusion.

**Comment by mauron85** [comment]
@areina yes, definitely i want to implement that case, but need to find elegant solution. So no estimates, sorry. Help very welcome.

**Comment by mauron85** [comment]
Not sure but android:process=":remote" is maybe the lead.

**Comment by areina** [comment]
In sample application, it's already defined:

```xml
<service android:enabled="true" android:exported="false" android:name="com.tenforwardconsulting.cordova.bgloc.DistanceFilterLocationService" android:process=":remote" android:stopWithTask="false" />
<service android:enabled="true" android:exported="false" android:name="com.tenforwardconsulting.cordova.bgloc.FusedLocationService" android:process=":remote" android:stopWithTask="false" />
```

**Comment by mauron85** [comment]
Ok. Maybe I've got it. Anybody please try 0.8.1 from next branch. Config option ```stopOnTerminate``` must be false .

**Comment by areina** [comment]
I think it's working but few seconds after closing the app, the service crashes. 

```xml
I/DistanceFilterLocationService( 3000): - startMonitoringStationaryRegion (28.4661338,-16.2580186), accuracy:33.0
D/LocationFilter( 3415): Location jumpped by 2.7382578097165924m. Will ignore change=true
E/FastThread(  290): did not receive expected priority boost
V/msm8974_platform(  290): platform_get_output_snd_device: enter: output devices(0x2)
V/msm8974_platform(  290): platform_get_output_snd_device: exit: snd_device(speaker)
D/audio_hw_primary(  290): select_devices: out_snd_device(2: speaker) in_snd_device(0: )
D/hardware_info(  290): hw_info_append_hw_type : device_name = speaker
V/msm8974_platform(  290): platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(14)
D/WifiService( 1090): releaseWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@3fbd293e}
D/SQLiteLocationDAO( 3000): After insert, rowId = 29
D/AbstractLocationService( 3000): Persisted Location: com.tenforwardconsulting.cordova.bgloc.data.LocationProxy@2918dd57
D/AbstractLocationService( 3000): Broadcasting update message: com.tenforwardconsulting.cordova.bgloc.data.LocationProxy@2918dd57
D/Wiper_jni( 1090): wifiRequestEventCb invoked
D/LBSSystemMonitorService( 1090): handleMessage what - 2
I/ActivityManager( 1090): Killing 3000:com.transistorsoft.backgroundgeolocation:remote/u0a119 (adj 0): remove task
W/ContextImpl( 1090): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1480 com.android.server.location.GpsLocationProvider.reportStatus:1916 <bottom of call 
stack> <bottom of call stack> <bottom of call stack> 
W/AudioPolicyManager(  290): unregisterEffect() unknown effect ID 9184
W/BroadcastQueue( 1090): Failure sending broadcast Intent { act=com.tenforwardconsulting.cordova.bgloc.ACTION flg=0x10 (has extras) }
W/BroadcastQueue( 1090): android.os.DeadObjectException
W/BroadcastQueue( 1090):        at android.os.BinderProxy.transactNative(Native Method)
W/BroadcastQueue( 1090):        at android.os.BinderProxy.transact(Binder.java:496)
W/BroadcastQueue( 1090):        at android.app.ApplicationThreadProxy.scheduleRegisteredReceiver(ApplicationThreadNative.java:1103)
W/BroadcastQueue( 1090):        at com.android.server.am.BroadcastQueue.performReceiveLocked(BroadcastQueue.java:431)
W/BroadcastQueue( 1090):        at com.android.server.am.BroadcastQueue.deliverToRegisteredReceiverLocked(BroadcastQueue.java:521)
W/BroadcastQueue( 1090):        at com.android.server.am.BroadcastQueue.processNextBroadcast(BroadcastQueue.java:729)
W/BroadcastQueue( 1090):        at com.android.server.am.BroadcastQueue$BroadcastHandler.handleMessage(BroadcastQueue.java:149)
W/BroadcastQueue( 1090):        at android.os.Handler.dispatchMessage(Handler.java:102)
W/BroadcastQueue( 1090):        at android.os.Looper.loop(Looper.java:135)
W/BroadcastQueue( 1090):        at android.os.HandlerThread.run(HandlerThread.java:61)
W/BroadcastQueue( 1090):        at com.android.server.ServiceThread.run(ServiceThread.java:46)
W/ActivityManager( 1090): Scheduling restart of crashed service com.transistorsoft.backgroundgeolocation/com.tenforwardconsulting.cordova.bgloc.DistanceFilterLocationService in 82750ms
W/BroadcastQueue( 1090): Failure sending broadcast Intent { act=com.tenforwardconsulting.cordova.bgloc.STATIONARY_REGION_ACTION flg=0x10 (has extras) }
W/BroadcastQueue( 1090): android.os.RemoteException: app.thread must not be null
W/BroadcastQueue( 1090):        at com.android.server.am.BroadcastQueue.performReceiveLocked(BroadcastQueue.java:435)
W/BroadcastQueue( 1090):        at com.android.server.am.BroadcastQueue.deliverToRegisteredReceiverLocked(BroadcastQueue.java:521)
W/BroadcastQueue( 1090):        at com.android.server.am.BroadcastQueue.processNextBroadcast(BroadcastQueue.java:569)
W/BroadcastQueue( 1090):        at com.android.server.am.BroadcastQueue$BroadcastHandler.handleMessage(BroadcastQueue.java:149)
W/BroadcastQueue( 1090):        at android.os.Handler.dispatchMessage(Handler.java:102)
W/BroadcastQueue( 1090):        at android.os.Looper.loop(Looper.java:135)
W/BroadcastQueue( 1090):        at android.os.HandlerThread.run(HandlerThread.java:61)
W/BroadcastQueue( 1090):        at com.android.server.ServiceThread.run(ServiceThread.java:46)
W/BroadcastQueue( 1090): Failure [background] sending broadcast result of Intent { act=com.tenforwardconsulting.cordova.bgloc.ACTION flg=0x10 (has extras) }
W/BroadcastQueue( 1090): android.os.RemoteException: app.thread must not be null
W/BroadcastQueue( 1090): android.os.RemoteException: app.thread must not be null
W/BroadcastQueue( 1090):        at com.android.server.am.BroadcastQueue.performReceiveLocked(BroadcastQueue.java:435)
W/BroadcastQueue( 1090):        at com.android.server.am.BroadcastQueue.processNextBroadcast(BroadcastQueue.java:671)
W/BroadcastQueue( 1090):        at com.android.server.am.BroadcastQueue$BroadcastHandler.handleMessage(BroadcastQueue.java:149)
W/BroadcastQueue( 1090):        at android.os.Handler.dispatchMessage(Handler.java:102)
W/BroadcastQueue( 1090):        at android.os.Looper.loop(Looper.java:135)
W/BroadcastQueue( 1090):        at android.os.HandlerThread.run(HandlerThread.java:61)
W/BroadcastQueue( 1090):        at com.android.server.ServiceThread.run(ServiceThread.java:46)
D/hardware_info(  290): hw_info_append_hw_type : device_name = speaker
W/AudioFlinger(  290): session id 9181 not found for pid 3000
W/AudioFlinger(  290): removeEffect_l() 0xb58a1008 cannot promote chain for effect 0xb84fcd00
W/AudioPolicyManager(  290): unregisterEffect() unknown effect ID 9184
E/NetlinkEvent(  285): NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
W/NotificationService( 1090): Object died trying to hide notification android.app.ITransientNotification$Stub$Proxy@1e6e91a3 in package com.transistorsoft.backgroundgeolocation
```
Few minutes later, the mobile restarts the service.

**Comment by mauron85** [comment]
Can confirm that. I can probably fix that one too. Maybe it just unregistering Intent listener when Main Activity is destroyed.

**Comment by Kujbor** [comment]
mauron85, explain please, for the moment, whether geocoding after you close the application, and after restarting your phone? I implemented this functionality, as well as continuous sending location on the server for Android. But I couldn't understand technology Google Play API and geofences, so I implement android.location.LocationListener. It wildly discharge the battery. I would like to use your plugin, but I just do not know whether this functionality is implemented in it. Everything is complicated... Explain, please. Thank you)

**Comment by mauron85** [comment]
@Kujbor current version 0.8.1 will do geolocation in the background when app is closed by the user (option stopOnTerminate must be false). However there is one last bug, which causes background service to be terminated after few seconds, but service will be restarted after couple of minutes and should operate normally, meaning it will store positions to sqlite. Those saved locations can be later (on app reopen) retrieved by backgroundGeoLocation.getLocations. I will fix that issue later.

Same apply in case when app is killed by the system.

After restarting phone you have to open app again. If you're interested in this kind of functionality, open issue for it.

If you're interested in http posting of position directly by plugin, give +1 to #20.

**Comment by Kujbor** [comment]
In what platforms it is implemented?

**Comment by mauron85** [comment]
@Kujbor I was talking about android.

**Comment by mauron85** [comment]
@areina Version 0.8.2 is out. Crash should be fixed now. Hopefully we can close this one ;-)

**Comment by Kujbor** [comment]
Under ios it will not be implemented?

Maybe we can take the code for ios from actual version of the  christocracy app?)) As far as I understand, there's a version of ios, running as a service, without front-end))

I mean, this repository: https://github.com/transistorsoft/cordova-background-geolocation-lt.

**Comment by mauron85** [comment]
@Kujbor Actually, it is implemented under iOS too.

And I cannot take code from christocracy lt repo. First because of license is proprietary (and I'm not layer to decide if we can take code). And second, now plugin consists mostly of binary part.

**Comment by Kujbor** [comment]
That is, at the moment, it continues to write down the location after the user closes his or restart the phone? And it works on ios and android? And both platforms use geofences? And even unnecessary icon in the status bar at Android no longer used?) If true, this is a great work, and thank you very much! I am implementing data storage on the server. But only for Android (can not under ios).

**Comment by Kujbor** [comment]
Where do I place the code of saving on server for Android so that it is guaranteed to be invoked at a location update in the background, and in the foreground?

**Comment by Kujbor** [comment]
And I noticed that the icon in the status bar is still displayed. What for? In red folder such service works fine without it ...

**Comment by mauron85** [comment]
@Kujbor you're asking too many questions not related to this issue. I'll try to answer then, but next time please open new issue, cause this thread is getting polluted and it's too confusing.

> t continues to write down the location after the user closes his or restart the phone? 
yes for user close
phone restarts in upcoming version 1.0.0 see next branch

>And both platforms use geofences? 
Not really. But actually both platforms use APIs that can be considered as geofencing.
iOS Significant Changes API (see README.md)
Android depends on provider. ANDROID_FUSED_LOCATION is using ActivityRecognitionAPI and FusedLocationProviderAPI. ANDROID_DISTANCE_FILTER is using proximity-alerts

>And even unnecessary icon in the status bar at Android no longer used?
icon is necessary. It increases chances that bg service will not be terminated. see #12

>Where do I place the code of saving on server for Android so that it is guaranteed to be invoked at a location update in the background, and in the foreground?

in your app. When your app is running, you're normally receiving location updates (see README.md). When your app is killed, bg service save location into sqlite instead. In this case you want to add deviceready handler to retrieve those saved locations on app start.

```
document.addEventListener('deviceready', onDeviceReady, false);
function onDeviceReady () {
    backgroundGeoLocation.getLocations(function(locations) {
        [].filter.call(locations, function(location) {
            if (location.debug === false) {
                 //do ajax post of location
                 backgroundGeoLocation.deleteLocation(location.locationId);
            };
        });
    });
}

```

>And I noticed that the icon in the status bar is still displayed. What for? In red folder such service works fine without it ...

already answered that

**Comment by Kujbor** [comment]
mauron85, sorry) I answered you in the task #20

**Comment by Kujbor** [comment]
And by the way, I tested for a week the red folder's background service plugin, and there wasn't observed any of unexpected behavior. Yes, the system closes the execution of the service when the battery is low, but it warns that all background processes will be stopped. And when you exit the power-saving mode (manually or when connected to the charger) the service is automatically restored.

So maybe the icon gives some kind of bonus in the prevention of stopping the process, but even without it the service works expectedly and steadily. I highly recommend you look at the source code of the background service project developed by red folder.

They use the source code execution by a timer. But I did not use it. I created LocationManager in onTimerEnabled and it worked extremely stable when I turn on and off application or phone! Please see how they did it. Maybe this will help. They have also implemented a very simple way to start the service when you turn on your phone.

I hope this will help get rid of the hated icon in status bar, or at least make it optional.

**Comment by mauron85** [comment]
@Kujbor ok. in next branch I've added startForeground option to disable notification.

**Comment by renevaessen** [comment]
mauron85, 

I work for a company that increasingly rely on gps positions being logged and analyzed, for tracking and "timesheet management".
 
We need a solution that will work on Android, preferably also iOS but the latter is not a must.
 
Are you, or someone else, interested in making a robust solution, in the form of a background service, that is PhoneGap compatible?

Some features we need:
- GPS positions need to be stored for later retreival by the UI in case the OS closes it
- A very specific Driving / Stopped detection according to our specs
- The UI must be able to set certain event types like 'Stopped for 2 minutes' that should launch the UI in case it is closed, so we can query the driver what he is doing? (timesheet management)
- When the UI get's launched again after the OS has closed it, we need to be able to detect this, by asking the background service what kind of launch it was, cold, or restart.
- Also, could a background service add a sticky notification like google maps do, while navigating, to ask the user to return to the main ui?

Ofcourse we will pay you for developing this. Name a price.
 
Our app now:  https://play.google.com/store/apps/details?id=nl.mendrix.mobile&hl=en

**Comment by mauron85** [comment]
@renevaessen

>GPS positions need to be stored for later retreival by the UI in case the OS closes it

already in 0.9.1 (there is issue after closing the app, the service crashes, but it restart itself later and works ok)

>A very specific Driving / Stopped detection according to our specs

ANDROID_FUSION_PROVIDER can be extended to provide such a thing

>The UI must be able to set certain event types like 'Stopped for 2 minutes' that should launch the UI in case it is closed, so we can query the driver what he is doing? (timesheet management)

This can be implemented in your cordova app. But probably some assistence from bg service might be needed. Or maybe push notifications can be used to trigger such actions from the server.

>When the UI get's launched again after the OS has closed it, we need to be able to detect this, by asking the background service what kind of launch it was, cold, or restart.

This should be possible.

>Also, could a background service add a sticky notification like google maps do, while navigating, to ask the user to return to the main ui?

Not sure if I understand what you mean. But this is already implemented.

**Comment by christocracy** [comment]
@kujboar 

>Maybe we can take the code for ios from actual version of the christocracy app?)) As far as I 
>understand, there's a version of ios, running as a service, without front-end))
>I mean, this repository: https://github.com/transistorsoft/cordova-background-geolocation-lt.

As the author of that project, I wouldn't recommend that, since you don't have access to the source.  The lib is implemented as an iOS framework.

**Comment by mauron85** [comment]
Unfortunately it seems that due android bug, background service is killed and later restarted. It seems nothing can be done to prevent that kill.

More info here:

https://code.google.com/p/android/issues/detail?id=53313

**Comment by mauron85** [comment]
Closing. After app termination (swipe from the list), service is terminated first but eventually restarted and continues to operate.

**Comment by ElieSauveterre** [comment]
@mauron85 If it's restarted that great. In my use case I "just" need to find a way to send the user position to a server. I think you are working on it, no ?
I have done something similar on the Geofence Plugin https://github.com/ElieSauveterre/cordova-plugin-geofence/blob/72848cb3e3bde3af8e0e6a2a5c4c5dbbf9563c6c/src/android/TransitionReceiver.java

**Comment by mauron85** [comment]
@ElieSauveterre I spent too much time fixing this and finally realised this restart is the best what we can have (due android bug). Regarding HTTP posts from bg plugin there is issue #20 for it. But I'm thinking about how it should actually behave. Should it post locations updates only what app was terminated or in all circumstances? What do you think? You can answer directly to #20.

**Comment by sabanad** [comment]
@mauron85 can you please provide the link of next branch which includes the functionality of tracking even when user closes the app from background by swiping it out of recent tasks.

**Comment by mauron85** [comment]
@sabanad there is no special branch. it's already in master/npm. However this functionality is Android only. iOS will be coming soon.

**Comment by sabanad** [comment]
@mauron85 great I need it for Android only. Thanks this plugin helps alot.
