### ISSUE TITLE
running a function in background alongside callbacks

### ISSUE THREAD

**Issue by clement360** [mauron85/cordova-plugin-background-geolocation#98]
I want to verify that the device gps is running by having the device post it's latest gps location to the server every 30 min. if the server has not received a gps location in over an hour I will alert the app through a notification. I originally planned to have the client app call home in the success and failure call backs but if the user is stationary the callbacks are not called. is there a way I could run a set timeout for 30 minutes in the background using this plugin? There are other background plugins... but they will create a second background process notification on android. I can't have two of these notifications running constantly.

Thanks

**Comment by mauron85** [comment]
Yes, it is. Just configure plugin like this:

```
backgroundGeolocation.configure(callbackFn, failureFn, {
    desiredAccuracy: 10,
    locationProvider: backgroundGeolocation.provider.ANDROID_ACTIVITY_PROVIDER,
    interval: 30*10000, // <!-- poll for position every 30 min
    fastestInterval: 30*10000,
    stopOnStillActivity: false // this is important
});
```

**Comment by clement360** [comment]
Thank you for your answer! I have some clarification questions. I was under the impression that the interval was only used on Android devices. I need iOS and Android. 

Secondly, I need the client to run it's location callback more frequently than every thirty minutes because my main goal is to detect if drivers are exceeding a specific speed. I'm only using the 30 minute server call in to make sure that the gps and or the application have not been disabled.

**Comment by clement360** [comment]
If the callback detects an elevated speed it will alert the server. So that needs to be running continuously

**Comment by mauron85** [comment]
We can ignore the 30min interval then, you can implement such a thing using plain js `setInterval` (in foreground). Regarding tracking speed of the vehicle, you'll probably need to set interval in seconds (interval: 5000) on Android. Not sure how this can be done on iOS. Maybe using desiredAccuracy: 10 will suffice. Also add option `options.saveBatteryOnBackground: false' for iOS to stay accurate in background. Also all of this will drain battery as hell, but probably your drivers use car adapter, so may be not an issue.
