### ISSUE TITLE
StartOnBoot doesn't work on certain devices.

### ISSUE THREAD

**Issue by shyamal890** [mauron85/cordova-plugin-background-geolocation#99]
I have set `startOnBoot: true,` in the configuration. It works perfectly on Motorola phone however on Xiaomi phones one has to manually set the app to `autostart` in the `security app` of MI Phones.

**Comment by uzumakinaruto123** [comment]
thats mi issue actually. check this [Mi Link](http://en.miui.com/thread-225827-1-1.html) i even have post there.  Instead try searching how google apps and whatsapp are being able to keep there app enabled in the list.

**Comment by mauron85** [comment]
Oh boy I really hate this Android fragmentation, where anybody can bend Android at will.

**Comment by shyamal890** [comment]
There is another issue with Xiaomi. It kills the geolocation background service too on 2 conditions mentioned below:

1. When user kills the App from drawer.
2. After a long time of inactivity.

**Comment by mauron85** [comment]
I wonder if there is something I can do? Probably not.

**Comment by uzumakinaruto123** [comment]
If anyone gets a auto-startup solution , please do share. It will help alot.  Its getting annoying now . unfortunately , client has a MI device.

**Comment by shyamal890** [comment]
@mauron85 @uzumakinaruto123 I have created this bug report in MIUI thread. 

Here is the link: http://en.miui.com/thread-305663-1-1.html

Do confirm the bug, so that MI developers would pay more attention. 

This is mainly regarding tracking app being killed by MIUI. However, one more bug has to be created about app auto-start too.

**Comment by uzumakinaruto123** [comment]
good ! I will give a +1 there but you should have created a thread for auto-startup instead. by solving that auto-startup issue would solve the above too. since miui will try restarting even if it was killed.

**Comment by shyamal890** [comment]
Do create another thread for autostart, will comment  and +1

**Comment by mauron85** [comment]
Notice: this issue has been closed because it has been reported for branch 2.x or later. It could be already fixed in v3 or is not relevant anymore. You may reopen this issue if it has been closed in error.

**Comment by mauron85** [comment]
As said. There is no way how I can override those settings.
